/* Questions de la classe de 1ère A (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "1A — Polynôme du second degré & discriminant": [
    {q:"Un polynôme du second degré est de la forme…",c:["ax² + bx + c avec a ≠ 0","ax + b","a/x + b","ax³ + bx² + c"],a:0,exp:"Définition"},
    {q:"La forme canonique de x² − 4x + 1 est…",c:["(x − 2)² + 3","(x − 2)² − 3","(x − 4)² − 15","(x + 2)² − 3"],a:1,exp:"(x − 2)² = x² − 4x + 4"},
    {q:"Le discriminant de ax² + bx + c est…",c:["Δ = b² − 4ac","Δ = b − 4ac","Δ = 4ac − b²","Δ = b² + 4ac"],a:0,exp:"Définition"},
    {q:"Si Δ > 0, le polynôme admet…",c:["une infinité de racines","aucune racine réelle","une racine double","deux racines distinctes (−b ± √Δ)/(2a)"],a:3,exp:"Racines d'un polynôme du second degré"},
    {q:"Si Δ = 0, le polynôme admet…",c:["deux racines opposées","une racine double −b/(2a)","aucune racine réelle","deux racines distinctes"],a:1,exp:"Racine double"},
    {q:"Si Δ < 0, le polynôme…",c:["admet une racine double","admet deux racines","n'admet aucune racine réelle","est nul"],a:2,exp:"Pas de racine réelle"},
    {q:"Le discriminant de 3x² − 5x + 2 est…",c:["25","−1","49","1"],a:3,exp:"25 − 24"},
    {q:"Les racines de 3x² − 5x + 2 sont…",c:["1 et 3/2","5 et 2","−1 et −2/3","1 et 2/3"],a:3,exp:"(5 ± 1)/6"},
    {q:"Le discriminant de x² + 2x + 5 est…",c:["−16","24","16","−24"],a:0,exp:"4 − 20 : aucune racine réelle"},
    {q:"Si x₁ et x₂ sont les racines, ax² + bx + c se factorise en…",c:["a(x − x₁)(x − x₂)","a x₁ x₂","(x − x₁)(x − x₂)","a(x + x₁)(x + x₂)"],a:0,exp:"Factorisation à l'aide des racines"},
    {q:"Factoriser 2x² − 2x − 12.",c:["2(x − 3)(x + 2)","2(x − 6)(x + 1)","(x − 3)(x + 2)","2(x + 3)(x − 2)"],a:0,exp:"Racines 3 et −2"},
    {q:"Résoudre x³ − 6x² + 11x − 6 = 0 sachant que 1 est solution évidente.",c:["x = −1, x = −2 ou x = −3","x = 1, x = 2 ou x = 3","x = 1 seulement","x = 1 ou x = 6"],a:1,exp:"(x − 1)(x² − 5x + 6) = 0"},
    {q:"Le sommet de la parabole y = x² − 4x + 3 a pour coordonnées…",c:["(4 ; 3)","(2 ; −1)","(−2 ; 1)","(2 ; 1)"],a:1,exp:"Forme canonique (x − 2)² − 1"},
    {q:"Le polynôme ax² + bx + c avec a > 0 et Δ < 0 est…",c:["strictement négatif pour tout réel x","négatif entre ses racines","strictement positif pour tout réel x","nul en un point"],a:2,exp:"Pas de racine et a > 0"},
  ],
  "1A — Équations du second degré": [
    {q:"Les solutions de x² − 5x + 6 = 0 sont…",c:["2 et 3","−2 et −3","−1 et −6","1 et 6"],a:0,exp:"(x − 2)(x − 3) = 0"},
    {q:"Les solutions de x² − 6x + 9 = 0 sont…",c:["x = 6","x = 3 (double)","aucune","x = 3 et x = −3"],a:1,exp:"Δ = 0"},
    {q:"Les solutions de 2x² + x − 1 = 0 sont…",c:["2 et −1","1/2 et −1","−1/2 et 1","1 et −2"],a:1,exp:"Δ = 9 ; x = (−1 ± 3)/4"},
    {q:"L'équation x² + 4 = 0 dans ℝ…",c:["a une solution −2","a deux solutions ±2","n'a aucune solution","a une solution 2"],a:2,exp:"x² ≥ 0"},
    {q:"Si x₁ et x₂ sont solutions de ax² + bx + c = 0, alors x₁ + x₂ = …",c:["−b/a","−c/a","c/a","b/a"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si x₁ et x₂ sont solutions de ax² + bx + c = 0, alors x₁ x₂ = …",c:["b/a","c/a","−b/a","−c/a"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Deux nombres de somme 5 et de produit 6 sont…",c:["1 et 4","0 et 5","2 et 3","−2 et −3"],a:2,exp:"x² − 5x + 6 = 0"},
    {q:"Deux nombres de somme −3 et de produit −10 sont…",c:["5 et −8","1 et −4","−2 et 5","2 et −5"],a:3,exp:"x² + 3x − 10 = 0"},
    {q:"Une équation bicarrée est une équation de la forme…",c:["ax² + bx + c = 0","a/x² + b = 0","ax³ + bx + c = 0","ax⁴ + bx² + c = 0"],a:3,exp:"On pose X = x²"},
    {q:"Résoudre x⁴ − 5x² + 4 = 0.",c:["x = 1 ou x = 4","x = ±√5","x = ±1 ou x = ±2","x = ±4"],a:2,exp:"X² − 5X + 4 = 0 : X = 1 ou X = 4"},
    {q:"Résoudre x⁴ + x² − 2 = 0.",c:["x = ±1","aucune solution","x = ±2","x = 1 ou x = −2"],a:0,exp:"X² + X − 2 = 0 : X = 1 ou X = −2 (rejeté)"},
    {q:"Dans une équation bicarrée, une valeur négative trouvée pour X = x² est…",c:["remplacée par 0","doublée","conservée","rejetée"],a:3,exp:"x² ne peut pas être négatif"},
    {q:"Un rectangle a un périmètre de 20 cm et une aire de 21 cm². Ses dimensions sont…",c:["5 cm et 5 cm","3 cm et 7 cm","2 cm et 8 cm","4 cm et 6 cm"],a:1,exp:"Somme 10 et produit 21"},
  ],
  "1A — Inéquations du second degré": [
    {q:"Le signe de ax² + bx + c (Δ > 0) est celui de a…",c:["nulle part","entre les racines","à l'extérieur des racines","partout"],a:2,exp:"Signe d'un trinôme"},
    {q:"x² − 3x − 4 ≤ 0 a pour ensemble de solutions…",c:["]−1 ; 4[","[−1 ; 4]","ℝ","]−∞ ; −1] ∪ [4 ; +∞["],a:1,exp:"Racines −1 et 4 ; négatif entre les racines"},
    {q:"x² − 4 > 0 a pour ensemble de solutions…",c:["]−∞ ; −2[ ∪ ]2 ; +∞[","]−2 ; 2[","ℝ","]2 ; +∞["],a:0,exp:"Positif à l'extérieur des racines"},
    {q:"−x² + 4 ≥ 0 a pour ensemble de solutions…",c:["ℝ","]−∞ ; −2] ∪ [2 ; +∞[","[−2 ; 2]","[2 ; +∞["],a:2,exp:"a < 0 : positif entre les racines"},
    {q:"x² + x + 1 > 0 a pour ensemble de solutions…",c:["ℝ","[0 ; +∞[","]−1 ; 0[","∅"],a:0,exp:"Δ < 0 et a > 0"},
    {q:"x² − 2x + 1 ≤ 0 a pour ensemble de solutions…",c:["ℝ","{1}","∅","]−∞ ; 1["],a:1,exp:"(x − 1)² ≤ 0"},
    {q:"Pour résoudre graphiquement une inéquation du second degré, on…",c:["dérive la parabole","trace une droite verticale","calcule une limite","lit sur la parabole les abscisses où elle est au-dessus ou en dessous de l'axe des abscisses"],a:3,exp:"Résolution graphique"},
    {q:"Résoudre x⁴ − 5x² + 4 < 0.",c:["]−2 ; 2[","]−1 ; 1[","]1 ; 4[","]−2 ; −1[ ∪ ]1 ; 2["],a:3,exp:"X = x² ∈ ]1 ; 4["},
    {q:"Un problème conduisant à une inéquation du second degré demande de…",c:["calculer une limite","tracer un histogramme","calculer un discriminant nul","traduire la situation par une inéquation puis étudier le signe d'un trinôme"],a:3,exp:"Méthode"},
    {q:"L'inéquation 2x² − 8 ≥ 0 a pour solutions…",c:["[−2 ; 2]","ℝ","]−∞ ; −2] ∪ [2 ; +∞[","[2 ; +∞["],a:2,exp:"2(x − 2)(x + 2) ≥ 0"},
  ],
  "1A — Systèmes d'équations & d'inéquations linéaires": [
    {q:"Résoudre x + y = 5 ; 2x − y = 1.",c:["x = 3 et y = 2","x = 4 et y = 1","x = 1 et y = 4","x = 2 et y = 3"],a:3,exp:"On additionne : 3x = 6"},
    {q:"Résoudre x + 2y = 7 ; 3x − y = 7 par substitution.",c:["x = 3 et y = 2","x = 2 et y = 3","x = 5 et y = 1","x = 1 et y = 3"],a:0,exp:"y = 3x − 7 puis x + 6x − 14 = 7"},
    {q:"Résoudre 2x + y = 8 ; x − y = 1 par combinaison.",c:["x = 3 et y = 2","x = 1 et y = 6","x = 4 et y = 0","x = 2 et y = 4"],a:0,exp:"On additionne : 3x = 9"},
    {q:"Résoudre 2/x + 3/y = 7 ; 1/x − 1/y = 1 avec X = 1/x et Y = 1/y.",c:["x = 1/2 et y = 1","x = 1/2 et y = 2","x = 1 et y = 1/2","x = 2 et y = 1"],a:0,exp:"2X + 3Y = 7 ; X − Y = 1 : X = 2, Y = 1"},
    {q:"Graphiquement, résoudre un système de deux équations linéaires revient à…",c:["dénombrer des cas","calculer un discriminant","dériver deux fonctions","trouver l'intersection de deux droites"],a:3,exp:"Résolution graphique"},
    {q:"Une droite (D) d'équation ax + by + c = 0 partage le plan en…",c:["la droite et deux demi-plans ouverts","trois demi-plans","un seul demi-plan","deux droites"],a:0,exp:"Propriété du guide"},
    {q:"Les points d'un des demi-plans vérifient…",c:["ax + by + c ≤ 0","ax + by + c > 0","ax + by + c = 0","x + y = 0"],a:1,exp:"L'autre demi-plan : ax + by + c < 0"},
    {q:"Pour savoir quel demi-plan vérifie 2x + y − 4 < 0, on teste…",c:["un point n'appartenant pas à la droite, par exemple O(0 ; 0)","le point (2 ; 0) seulement","aucun point","le milieu de la droite"],a:0,exp:"−4 < 0 : O appartient au demi-plan"},
    {q:"Le point O(0 ; 0) vérifie-t-il 2x + y − 4 < 0 ?",c:["Non","Oui","Seulement s'il est sur la droite","On ne peut pas savoir"],a:1,exp:"−4 < 0"},
    {q:"Résoudre un système d'inéquations linéaires revient à…",c:["déterminer l'intersection de demi-plans","résoudre une équation du second degré","calculer une somme","tracer une parabole"],a:0,exp:"Méthode graphique"},
    {q:"Le système x ≥ 0 ; y ≥ 0 ; x + y ≤ 4 a pour solution…",c:["une droite","un cercle","un triangle de sommets (0 ; 0), (4 ; 0) et (0 ; 4)","un carré"],a:2,exp:"Intersection de trois demi-plans"},
    {q:"Deux systèmes d'équations sont équivalents lorsqu'ils ont…",c:["le même ensemble de solutions","le même nombre d'équations","la même solution particulière","les mêmes coefficients"],a:0,exp:"Définition"},
  ],
  "1A — Suites arithmétiques": [
    {q:"Une suite arithmétique de raison r vérifie…",c:["Uₙ₊₁ = r/n","Uₙ₊₁ = Uₙ + r","Uₙ₊₁ = Uₙ²","Uₙ₊₁ = r Uₙ"],a:1,exp:"Définition"},
    {q:"Pour une suite arithmétique de premier terme U₀ et de raison r, Uₙ = …",c:["U₀ × rⁿ","n U₀","U₀ + r","U₀ + n r"],a:3,exp:"Propriété admise"},
    {q:"Suite arithmétique de raison r : pour tous entiers n et k, Uₙ = …",c:["U_k + r","U_k × rⁿ⁻ᵏ","U_k + (n − k) r","U_k + n k r"],a:2,exp:"Propriété admise"},
    {q:"U₀ = 5 et r = 3 : U₂₀ = …",c:["68","60","75","65"],a:3,exp:"5 + 20 × 3"},
    {q:"La somme de n termes consécutifs d'une suite arithmétique est égale…",c:["à la somme des extrêmes","à n × le premier terme","au produit par n de la demi-somme des termes extrêmes","à n²"],a:2,exp:"Propriété admise"},
    {q:"U₀ = 5 et r = 3 : la somme U₀ + U₁ + … + U₁₉ vaut…",c:["335","670","1 000","1 340"],a:1,exp:"20 × (5 + 62)/2"},
    {q:"Une suite arithmétique de raison r > 0 est…",c:["décroissante","croissante","constante","géométrique"],a:1,exp:"Uₙ₊₁ − Uₙ = r > 0"},
    {q:"U₃ = 11 et U₇ = 23 (suite arithmétique) : la raison est…",c:["12","2","3","4"],a:2,exp:"(23 − 11)/4"},
    {q:"U₃ = 11 et U₇ = 23 (suite arithmétique) : U₀ = …",c:["5","3","2","−1"],a:2,exp:"U₀ = U₃ − 3 × 3 = 11 − 9"},
    {q:"La suite Uₙ = 4n − 1 est…",c:["arithmétique de raison 4","géométrique de raison 4","arithmétique de raison −1","constante"],a:0,exp:"Uₙ₊₁ − Uₙ = 4"},
    {q:"1 + 2 + 3 + … + 100 = …",c:["10 000","5 000","5 050","101"],a:2,exp:"100 × (1 + 100)/2"},
    {q:"Un loyer augmente de 2 000 F chaque année à partir de 30 000 F. Après 5 ans, il vaut…",c:["60 000 F","40 000 F","32 000 F","35 000 F"],a:1,exp:"30 000 + 5 × 2 000"},
  ],
  "1A — Suites géométriques": [
    {q:"Une suite géométrique de raison q vérifie…",c:["Uₙ₊₁ = Uₙ²","Uₙ₊₁ = q Uₙ","Uₙ₊₁ = Uₙ + q","Uₙ₊₁ = q/n"],a:1,exp:"Définition"},
    {q:"Pour une suite géométrique de premier terme U₀ et de raison q, Uₙ = …",c:["U₀ qⁿ⁺¹","U₀ + n q","n U₀ q","U₀ × qⁿ"],a:3,exp:"Propriété admise"},
    {q:"Suite géométrique de raison q : pour tous entiers n et k, Uₙ = …",c:["U_k × qⁿ⁻ᵏ","U_k + (n − k) q","U_k × q","U_k qⁿ k"],a:0,exp:"Propriété admise"},
    {q:"U₀ = 3 et q = 2 : U₅ = …",c:["48","192","30","96"],a:3,exp:"3 × 2⁵"},
    {q:"Si q ≠ 1, la somme de n termes consécutifs de premier terme a est S = …",c:["n a","a(1 − qⁿ)/(1 − q)","a(1 − q)/(1 − qⁿ)","a qⁿ"],a:1,exp:"Propriété admise"},
    {q:"Si q = 1, la somme de n termes vaut…",c:["n a","0","a n²","a"],a:0,exp:"Tous les termes sont égaux à a"},
    {q:"U₀ = 3, q = 2 : la somme des 6 premiers termes vaut…",c:["192","189","93","96"],a:1,exp:"3(1 − 2⁶)/(1 − 2) = 3 × 63"},
    {q:"Une suite géométrique de premier terme positif et de raison q > 1 est…",c:["décroissante","alternée","croissante","constante"],a:2,exp:"Monotonie"},
    {q:"Une suite géométrique de premier terme positif et de raison 0 < q < 1 est…",c:["croissante","alternée","constante","décroissante"],a:3,exp:"Monotonie"},
    {q:"Une suite géométrique de raison q < 0 est…",c:["décroissante","constante","alternée (ni croissante ni décroissante)","croissante"],a:2,exp:"Les termes changent de signe"},
    {q:"U₃ = 12 et U₆ = 96 (suite géométrique) : la raison est…",c:["2","8","4","3"],a:0,exp:"q³ = 96/12 = 8"},
    {q:"Un capital de 100 000 F placé à 10 % à intérêts composés vaut après 2 ans…",c:["111 000 F","110 000 F","121 000 F","120 000 F"],a:2,exp:"100 000 × 1,1²"},
    {q:"La suite 2, 6, 18, 54, … est…",c:["arithmétique de raison 3","géométrique de raison 6","arithmétique de raison 4","géométrique de raison 3"],a:3,exp:"Chaque terme est multiplié par 3"},
  ],
  "1A — Statistique": [
    {q:"Un caractère quantitatif est un caractère dont les modalités sont…",c:["des couleurs","des noms","des mots","des nombres"],a:3,exp:"Vocabulaire"},
    {q:"La couleur des yeux est un caractère…",c:["numérique","continu","quantitatif","qualitatif"],a:3,exp:"Vocabulaire"},
    {q:"Le mode d'une série statistique est…",c:["la plus grande valeur","la valeur centrale","la modalité d'effectif maximal","la moyenne"],a:2,exp:"Caractéristique de position"},
    {q:"La médiane d'une série statistique est…",c:["la valeur d'effectif maximal","l'étendue","la moyenne","la valeur qui partage la série ordonnée en deux groupes de même effectif"],a:3,exp:"Caractéristique de position"},
    {q:"La variance d'une série est…",c:["la médiane des écarts","l'étendue","la moyenne des écarts","la moyenne des carrés des écarts à la moyenne"],a:3,exp:"Caractéristique de dispersion"},
    {q:"L'écart-type d'une série est…",c:["le carré de la variance","la moitié de l'étendue","la moyenne des écarts","la racine carrée de la variance"],a:3,exp:"Caractéristique de dispersion"},
    {q:"L'effectif cumulé croissant d'une classe est…",c:["la somme des effectifs de cette classe et des classes précédentes","l'effectif de la classe","l'effectif total","la fréquence de la classe"],a:0,exp:"Définition"},
    {q:"La fréquence cumulée croissante de la dernière classe est…",c:["0","l'effectif total","1 (100 %)","0,5"],a:2,exp:"Toute la série est comptée"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la moyenne est…",c:["17","20","15","18"],a:3,exp:"(5×4 + 15×6 + 25×10)/20"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la médiane est…",c:["18","20","15","10"],a:1,exp:"L'effectif cumulé atteint 10 = N/2 en x = 20"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la classe modale est…",c:["[10 ; 20[","[0 ; 10[","aucune","[20 ; 30["],a:3,exp:"Effectif maximal"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la variance est…",c:["18","61","1 220","13"],a:1,exp:"(13²×4 + 3²×6 + 7²×10)/20"},
    {q:"Pour représenter une série regroupée en classes, on utilise…",c:["un diagramme en bâtons","un histogramme","un nuage de points","un diagramme circulaire uniquement"],a:1,exp:"Séries à modalités regroupées"},
    {q:"Le polygone des effectifs cumulés sert à déterminer…",c:["la variance exacte","la moyenne exacte","le mode seulement","la médiane"],a:3,exp:"Détermination graphique"},
    {q:"Une série chronologique est une série…",c:["de caractère qualitatif","sans effectifs","à deux caractères","dont les modalités sont ordonnées dans le temps"],a:3,exp:"Exemples du guide"},
  ],
  "1A — Dénombrement": [
    {q:"Le complémentaire de A dans un ensemble fini E vérifie Card(complémentaire de A) = …",c:["Card(A)/Card(E)","Card(E) − Card(A)","Card(A) − Card(E)","Card(E) + Card(A)"],a:1,exp:"Propriété du guide"},
    {q:"Card(A × B) = …",c:["Card(A) − Card(B)","Card(A) × Card(B)","Card(A)ᴮ","Card(A) + Card(B)"],a:1,exp:"Propriété admise"},
    {q:"Le nombre de p-uplets d'un ensemble à n éléments est…",c:["pⁿ","n!","nᵖ","n × p"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Le nombre de codes à 3 chiffres (0 à 9, répétitions permises) est…",c:["30","720","1 000","100"],a:2,exp:"10³"},
    {q:"Le nombre d'arrangements de p éléments parmi n est Aₙᵖ = …",c:["n!","n(n − 1)…(n − p + 1)","n!/p!","nᵖ"],a:1,exp:"Propriété admise"},
    {q:"A₅² = …",c:["120","20","25","10"],a:1,exp:"5 × 4"},
    {q:"Aₙᵖ = …",c:["n!/p!","nᵖ","n!/(p!(n − p)!)","n!/(n − p)!"],a:3,exp:"Propriété admise"},
    {q:"Le nombre de permutations de n éléments est…",c:["nⁿ","n²","2n","n!"],a:3,exp:"Propriété admise"},
    {q:"4! = …",c:["12","16","10","24"],a:3,exp:"4 × 3 × 2 × 1"},
    {q:"Le nombre de façons de ranger 5 livres différents sur une étagère est…",c:["120","60","5","25"],a:0,exp:"5!"},
    {q:"Le nombre de combinaisons de p éléments parmi n est Cₙᵖ = …",c:["nᵖ/p!","n!/(p!(n − p)!)","n!/(n − p)!","n!/p!"],a:1,exp:"Propriété admise"},
    {q:"C₅² = …",c:["5","10","20","25"],a:1,exp:"5!/(2! 3!)"},
    {q:"Le nombre de façons de choisir un comité de 3 personnes parmi 8 est…",c:["512","336","24","56"],a:3,exp:"C₈³"},
    {q:"Le nombre de façons de choisir un président et un secrétaire parmi 6 personnes est…",c:["12","15","30","36"],a:2,exp:"A₆² = 6 × 5 (ordre important)"},
    {q:"Par convention, A⁰ₙ = …",c:["1","0","n","non défini"],a:0,exp:"Convention du guide"},
    {q:"Dans un arrangement, l'ordre des éléments…",c:["ne compte pas","compte","est toujours croissant","est aléatoire"],a:1,exp:"Différence avec une combinaison"},
  ],
  "1A — Fonctions : parité, symétrie, périodicité & fonctions associées": [
    {q:"Une fonction paire a une courbe symétrique par rapport…",c:["à l'axe des ordonnées","à la droite y = x","à l'origine","à l'axe des abscisses"],a:0,exp:"Propriété du guide"},
    {q:"Une fonction impaire a une courbe symétrique par rapport…",c:["à l'axe des ordonnées","à l'axe des abscisses","à la droite y = x","à l'origine"],a:3,exp:"Propriété du guide"},
    {q:"La fonction x ↦ x² + 1 est…",c:["impaire","paire","ni paire ni impaire","périodique"],a:1,exp:"f(−x) = f(x)"},
    {q:"La fonction x ↦ x³ est…",c:["ni paire ni impaire","impaire","constante","paire"],a:1,exp:"f(−x) = −f(x)"},
    {q:"La fonction x ↦ x² + x est…",c:["impaire","paire","constante","ni paire ni impaire"],a:3,exp:"f(−1) = 0 alors que f(1) = 2"},
    {q:"Pour démontrer que la droite x = a est axe de symétrie de (Cf), on vérifie que…",c:["f(a + h) = −f(a − h)","f(a) = 0","f(h) = f(−h)","f(a − h) = f(a + h) pour tout h admissible"],a:3,exp:"Méthode"},
    {q:"Pour démontrer que Ω(a ; b) est centre de symétrie de (Cf), on vérifie que…",c:["(f(a + h) + f(a − h))/2 = b","f(a + h) = f(a − h)","f(a + h) − f(a − h) = b","f(a + h) × f(a − h) = b"],a:0,exp:"Méthode"},
    {q:"Une fonction f est périodique de période T si…",c:["f(T) = 0","f(x) = T","f(x + T) = −f(x)","f(x + T) = f(x) pour tout x du domaine"],a:3,exp:"Définition"},
    {q:"La fonction cos est périodique de période…",c:["1","π/2","π","2π"],a:3,exp:"cos(x + 2π) = cos x"},
    {q:"La courbe de x ↦ −f(x) est symétrique de celle de f par rapport…",c:["à l'axe des abscisses","à l'axe des ordonnées","à la droite y = x","à l'origine"],a:0,exp:"Fonctions associées"},
    {q:"La courbe de x ↦ f(−x) est symétrique de celle de f par rapport…",c:["à l'axe des abscisses","à l'axe des ordonnées","à l'origine","à la droite y = x"],a:1,exp:"Fonctions associées"},
    {q:"La courbe de x ↦ −f(−x) est symétrique de celle de f par rapport…",c:["à l'axe des abscisses","à l'origine","à l'axe des ordonnées","à la droite y = x"],a:1,exp:"Fonctions associées"},
    {q:"La courbe de x ↦ |f(x)| s'obtient en…",c:["symétrisant par rapport à (Oy)","translatant de (0 ; 1)","symétrisant par rapport à (Ox) les parties situées sous l'axe des abscisses","doublant les ordonnées"],a:2,exp:"Fonctions associées"},
  ],
  "1A — Limites & continuité": [
    {q:"Si f est définie en a et admet une limite en a, cette limite est égale à…",c:["+∞","0","f(a)","a"],a:2,exp:"Propriété admise"},
    {q:"Une fonction est continue en a lorsqu'elle est…",c:["croissante en a","seulement dérivable en a","seulement définie en a","définie en a et admet une limite en a"],a:3,exp:"Définition"},
    {q:"Les fonctions polynômes et rationnelles sont continues…",c:["sur ℝ toujours","en tout point de leur ensemble de définition","seulement en 0","sur [0 ; 1] seulement"],a:1,exp:"Somme, produit, quotient de fonctions élémentaires"},
    {q:"La somme de deux fonctions continues en a est…",c:["constante","discontinue en a","continue en a","nulle"],a:2,exp:"Propriété admise"},
    {q:"Si lim f = l et lim g = l' en a, alors lim (f × g) = …",c:["l/l'","l − l'","l + l'","l × l'"],a:3,exp:"Propriété admise"},
    {q:"Si f n'est pas définie en a, f a une limite l en a si et seulement si…",c:["elle est croissante","f(a) = l","sa limite à gauche est l","ses limites à gauche et à droite en a sont égales à l"],a:3,exp:"Propriété admise"},
    {q:"La fonction valeur absolue est continue…",c:["en tout élément de ℝ","nulle part","seulement en 0","sur ]0 ; +∞["],a:0,exp:"Propriété démontrée en classe"},
    {q:"Pour n impair, la limite de 1/(x − a)ⁿ quand x tend vers a par valeurs supérieures est…",c:["1","0","−∞","+∞"],a:3,exp:"Le dénominateur est positif"},
    {q:"Pour n impair, la limite de 1/(x − a)ⁿ quand x tend vers a par valeurs inférieures est…",c:["+∞","−∞","0","1"],a:1,exp:"Le dénominateur est négatif"},
    {q:"Pour n pair, la limite de 1/(x − a)ⁿ en a est…",c:["+∞","−∞","1","0"],a:0,exp:"Le dénominateur est toujours positif"},
    {q:"Lorsque f a une limite infinie en a, la droite x = a est…",c:["une asymptote horizontale","une tangente horizontale","une asymptote verticale","un axe de symétrie"],a:2,exp:"Interprétation"},
    {q:"Si f a pour limite b en +∞, la droite y = b est…",c:["un axe de symétrie","une asymptote verticale","une tangente verticale","une asymptote horizontale"],a:3,exp:"Interprétation"},
    {q:"La limite d'un polynôme à l'infini est celle…",c:["de son monôme de plus haut degré","de son coefficient dominant seulement","de son terme constant","de sa dérivée"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"La limite en +∞ de (2x² + 1)/(x² − 3) est…",c:["−1/3","0","2","+∞"],a:2,exp:"2x²/x²"},
    {q:"La limite en 2 de (x² − 4)/(x − 2) est…",c:["2","+∞","4","0"],a:2,exp:"(x − 2)(x + 2)/(x − 2) = x + 2"},
  ],
  "1A — Dérivation & sens de variation": [
    {q:"Le taux de variation de f entre x₀ et x est…",c:["(f(x) − f(x₀))/(x − x₀)","f(x) − f(x₀)","f(x)/f(x₀)","(x − x₀)/(f(x) − f(x₀))"],a:0,exp:"Définition"},
    {q:"Le nombre dérivé de f en x₀ est…",c:["f(x₀)","la limite du taux de variation en x₀","le taux de variation en 0","f(x₀)²"],a:1,exp:"Définition"},
    {q:"Si f est dérivable en un point, alors f est…",c:["continue en ce point","discontinue en ce point","monotone","constante"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La réciproque de « dérivable ⟹ continue » est…",c:["fausse (la valeur absolue en 0)","vraie","vraie sur ℝ","vraie pour les polynômes seulement"],a:0,exp:"Exemple du guide"},
    {q:"Une équation de la tangente en x₀ est…",c:["y = f'(x₀)(x − x₀) + f(x₀)","y = f'(x₀)","y = x₀ f'(x)","y = f(x₀)(x − x₀) + f'(x₀)"],a:0,exp:"Tangente"},
    {q:"La dérivée de x ↦ x² est… ; celle de x ↦ x³ est…",c:["2x et 3x","x² et x³","2x et 3x²","x et x²"],a:2,exp:"Fonctions élémentaires"},
    {q:"La dérivée de x ↦ 1/x est…",c:["−1/x²","−1/x","1/x²","ln x"],a:0,exp:"Fonction inverse"},
    {q:"La dérivée de x ↦ √x est…",c:["1/√x","2√x","√x/2","1/(2√x)"],a:3,exp:"Fonction racine"},
    {q:"La dérivée d'un produit uv est…",c:["uv","u'v'","u'v + uv'","u'v − uv'"],a:2,exp:"Propriété admise"},
    {q:"La dérivée d'un quotient u/v est…",c:["(u'v + uv')/v²","(u' − v')/v²","(u'v − uv')/v²","u'/v'"],a:2,exp:"Propriété admise"},
    {q:"Si f(x) = g(x + α), alors f'(a) = …",c:["g'(a + α)","g(a + α)","α g'(a)","g'(a)"],a:0,exp:"Propriété admise"},
    {q:"f est croissante sur un intervalle ouvert K si et seulement si…",c:["f' est positive sur K","f' est nulle sur K","f est continue","f' est négative sur K"],a:0,exp:"Propriété admise"},
    {q:"Si f' s'annule et change de signe en x₀, alors f admet en x₀…",c:["aucun comportement particulier","un extremum relatif","un point anguleux","une asymptote"],a:1,exp:"Propriété admise"},
    {q:"La dérivée de x ↦ 3x² − 6x + 1 est…",c:["6x − 6","3x² − 6","6x + 1","3x − 6"],a:0,exp:"Dérivation terme à terme"},
    {q:"Le minimum de f(x) = 3x² − 6x + 1 est atteint en…",c:["x = 2","x = 0","x = −1","x = 1"],a:3,exp:"f'(x) = 6x − 6"},
    {q:"Si la dérivée garde un signe constant sauf en un nombre fini de points où elle s'annule, f est…",c:["constante","strictement monotone","périodique","non dérivable"],a:1,exp:"Remarque du guide"},
  ],
  "1A — Étude de fonctions & représentations graphiques": [
    {q:"La fonction x ↦ 1/x est strictement décroissante…",c:["nulle part","sur ℝ","sur ]0 ; +∞[ seulement","sur chacun des intervalles ]−∞ ; 0[ et ]0 ; +∞["],a:3,exp:"Étude de la fonction inverse"},
    {q:"La courbe représentative de x ↦ 1/x est…",c:["une hyperbole","une droite","un cercle","une parabole"],a:0,exp:"Représentation graphique"},
    {q:"La courbe de x ↦ 1/x admet pour asymptotes…",c:["la droite y = x","aucune droite","les axes du repère","la droite y = 1"],a:2,exp:"x = 0 et y = 0"},
    {q:"Pour a > 0, x ↦ ax² admet…",c:["un maximum en 0","un minimum en 1","aucun extremum","un minimum en 0"],a:3,exp:"Parabole tournée vers le haut"},
    {q:"Pour a < 0, x ↦ ax² admet…",c:["un maximum en 0","un maximum en 1","un minimum en 0","aucun extremum"],a:0,exp:"Parabole tournée vers le bas"},
    {q:"La fonction x ↦ √x est…",c:["paire","strictement croissante sur [0 ; +∞[","définie sur ℝ","strictement décroissante"],a:1,exp:"Étude de la fonction racine"},
    {q:"La fonction f(x) = x² − 4x + 3 est décroissante sur…",c:["ℝ","]−∞ ; 2]","[2 ; +∞[","]−∞ ; −2]"],a:1,exp:"f'(x) = 2x − 4"},
    {q:"L'axe de symétrie de y = ax² + bx + c est la droite…",c:["x = b/(2a)","x = −b/(2a)","y = −b/(2a)","x = c/a"],a:1,exp:"Abscisse du sommet"},
    {q:"Les asymptotes de f(x) = (x + 1)/(x − 1) sont…",c:["x = 1 et y = −1","x = 0 et y = 0","x = −1 et y = 1","x = 1 et y = 1"],a:3,exp:"−d/c = 1 et a/c = 1"},
    {q:"La dérivée de f(x) = (x + 1)/(x − 1) est…",c:["−2/(x − 1)","1/(x − 1)","2/(x − 1)²","−2/(x − 1)²"],a:3,exp:"((x − 1) − (x + 1))/(x − 1)²"},
    {q:"La fonction f(x) = (x + 1)/(x − 1) est…",c:["croissante sur ℝ","croissante sur chacun des intervalles","constante","décroissante sur chacun des intervalles de son domaine"],a:3,exp:"f'(x) < 0"},
    {q:"Le centre de symétrie de la courbe de (ax + b)/(cx + d) est…",c:["(d/c ; a/c)","(−d/c ; b/d)","(−d/c ; a/c)","(0 ; a/c)"],a:2,exp:"Intersection des asymptotes"},
    {q:"Étudier une fonction, c'est notamment déterminer…",c:["seulement son signe","seulement son domaine","son domaine, ses limites, sa dérivée et son tableau de variations","seulement ses zéros"],a:2,exp:"Méthode d'étude"},
  ],
  "1A — Prop. & Déf.": [
    {q:"Définition : Δ = …",c:["b² + 4ac","4ac − b²","b² − 4ac","b − 4ac"],a:2,exp:"Discriminant"},
    {q:"Propriété : si Δ > 0, les racines sont…",c:["±Δ","(−b ± √Δ)/(2a)","−b/(2a)","b/(2a)"],a:1,exp:"Racines"},
    {q:"Propriété : x₁ + x₂ = … ; x₁ x₂ = …",c:["b/a ; −c/a","c/a ; −b/a","−b/a ; c/a","−b ; c"],a:2,exp:"Somme et produit des racines"},
    {q:"Propriété : le signe de ax² + bx + c (Δ > 0) est celui de a…",c:["nulle part","entre les racines","à l'extérieur des racines","partout"],a:2,exp:"Signe du trinôme"},
    {q:"Définition : une équation bicarrée est de la forme…",c:["ax² + bx + c = 0","a/x² + b = 0","ax⁴ + bx² + c = 0","ax³ + bx = 0"],a:2,exp:"Bicarrée"},
    {q:"Propriété : une droite ax + by + c = 0 partage le plan en…",c:["deux droites","un demi-plan","trois demi-plans","la droite et deux demi-plans ouverts"],a:3,exp:"Demi-plans"},
    {q:"Définition : une suite arithmétique de raison r vérifie…",c:["Uₙ₊₁ = Uₙ²","Uₙ₊₁ = r/n","Uₙ₊₁ = r Uₙ","Uₙ₊₁ = Uₙ + r"],a:3,exp:"Suite arithmétique"},
    {q:"Propriété : Uₙ = U₀ + n r pour une suite…",c:["arithmétique","quelconque","constante","géométrique"],a:0,exp:"Terme général"},
    {q:"Définition : une suite géométrique de raison q vérifie…",c:["Uₙ₊₁ = Uₙ²","Uₙ₊₁ = Uₙ + q","Uₙ₊₁ = q/n","Uₙ₊₁ = q Uₙ"],a:3,exp:"Suite géométrique"},
    {q:"Propriété : la somme de n termes d'une suite géométrique de raison q ≠ 1 est…",c:["a qⁿ","a(1 − q)/(1 − qⁿ)","n a","a(1 − qⁿ)/(1 − q)"],a:3,exp:"Somme géométrique"},
    {q:"Définition : la variance est…",c:["la médiane des écarts","l'étendue","la moyenne des carrés des écarts à la moyenne","la moyenne des écarts"],a:2,exp:"Statistique"},
    {q:"Propriété : Card(A × B) = …",c:["(Card A)ᴮ","Card A + Card B","Card A × Card B","Card A − Card B"],a:2,exp:"Dénombrement"},
    {q:"Propriété : le nombre de p-uplets d'un ensemble à n éléments est…",c:["n!","n × p","nᵖ","pⁿ"],a:2,exp:"Dénombrement"},
    {q:"Propriété : Aₙᵖ = …",c:["n!/p!","n!/(n − p)!","n!/(p!(n − p)!)","nᵖ"],a:1,exp:"Arrangements"},
    {q:"Propriété : Cₙᵖ = …",c:["n!/p!","nᵖ/p!","n!/(p!(n − p)!)","n!/(n − p)!"],a:2,exp:"Combinaisons"},
    {q:"Définition : f est paire si…",c:["f(x) = 0","f(−x) = f(x) pour tout x du domaine","f(x) > 0","f(−x) = −f(x)"],a:1,exp:"Parité"},
    {q:"Définition : f est continue en a si…",c:["f est définie en a et admet une limite en a","f est croissante","f est dérivable en a","f(a) = 0"],a:0,exp:"Continuité"},
    {q:"Propriété : si f est dérivable en a, alors f est…",c:["monotone","positive","continue en a","constante"],a:2,exp:"Dérivabilité et continuité"},
    {q:"Propriété : f est croissante sur K ouvert si et seulement si…",c:["f est continue","f' est nulle sur K","f' est négative sur K","f' est positive sur K"],a:3,exp:"Sens de variation"},
    {q:"Propriété : la dérivée de x ↦ 1/x est…",c:["1/x²","1/x","ln x","−1/x²"],a:3,exp:"Dérivée usuelle"},
    {q:"Propriété : la dérivée de x ↦ √x est…",c:["2√x","1/(2√x)","√x/2","1/√x"],a:1,exp:"Dérivée usuelle"},
    {q:"Propriété : la limite d'un polynôme à l'infini est celle…",c:["de son terme constant","de son monôme de plus haut degré","de sa dérivée","de son coefficient dominant seulement"],a:1,exp:"Limites à l'infini"},
    {q:"Propriété : la courbe de x ↦ −f(x) est symétrique de celle de f par rapport…",c:["à la droite y = x","à l'axe des abscisses","à l'origine","à l'axe des ordonnées"],a:1,exp:"Fonctions associées"},
  ],
});
