/* Questions de la classe de 1ère C (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "1C — Orthogonalité dans l'espace": [
    {q:"Deux droites de l'espace sont orthogonales lorsque…",c:["elles ont un point commun","les parallèles à ces droites passant par un point donné sont perpendiculaires","elles sont sécantes","elles sont parallèles"],a:1,exp:"Définition du guide"},
    {q:"Si deux droites sont orthogonales, alors toute droite parallèle à l'une est…",c:["confondue avec l'autre","orthogonale à l'autre","parallèle à l'autre","sécante à l'autre en un point quelconque"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Une droite est orthogonale à un plan lorsqu'elle est orthogonale…",c:["à toute droite de ce plan","à un point de ce plan","à un autre plan","à une seule droite de ce plan"],a:0,exp:"Définition du guide"},
    {q:"Si une droite est orthogonale à deux droites sécantes d'un plan, alors elle est…",c:["parallèle à ce plan","sécante non orthogonale à ce plan","orthogonale à ce plan","contenue dans ce plan"],a:2,exp:"Propriété admise"},
    {q:"Par un point A de l'espace, il passe…",c:["une droite unique perpendiculaire à un plan donné","une infinité de droites perpendiculaires à un plan donné","deux droites perpendiculaires à un plan donné","aucune droite perpendiculaire à un plan donné"],a:0,exp:"Propriété admise"},
    {q:"Par un point de l'espace, il passe…",c:["une infinité de plans orthogonaux à une droite donnée","deux plans orthogonaux à une droite donnée","un plan unique orthogonal à une droite donnée","aucun plan orthogonal à une droite donnée"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si deux plans sont parallèles, toute droite orthogonale à l'un est…",c:["parallèle à l'autre","orthogonale à l'autre","contenue dans l'autre","sécante non orthogonale à l'autre"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si deux plans sont perpendiculaires à une même droite, alors ils sont…",c:["perpendiculaires","parallèles","sécants","confondus obligatoirement"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si deux droites sont parallèles, tout plan orthogonal à l'une est…",c:["orthogonal à l'autre","contenu dans l'autre","parallèle à l'autre","sécant non orthogonal à l'autre"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si deux droites sont orthogonales à un même plan, alors elles sont…",c:["non coplanaires","orthogonales entre elles","parallèles","sécantes"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Deux plans sont perpendiculaires lorsque…",c:["ils sont parallèles","ils sont confondus","l'un contient une droite orthogonale à l'autre","leur intersection est un point"],a:2,exp:"Définition du guide"},
    {q:"Deux droites orthogonales de l'espace sont-elles forcément sécantes ?",c:["Oui si elles sont coplanaires seulement","Non, elles peuvent être non coplanaires","Oui si elles sont parallèles","Oui, toujours"],a:1,exp:"Ex. deux arêtes non coplanaires d'un cube"},
    {q:"Dans un cube ABCDEFGH (E au-dessus de A), la droite (AE) est orthogonale…",c:["au plan (ABFE)","à aucun plan","au plan (AEGC)","au plan (ABCD)"],a:3,exp:"(AE) est orthogonale à (AB) et (AD), deux droites sécantes du plan (ABCD)"},
    {q:"Dans le même cube, les plans (ABCD) et (ABFE) sont…",c:["parallèles","perpendiculaires","confondus","sécants non perpendiculaires"],a:1,exp:"(ABFE) contient (AE) orthogonale à (ABCD)"},
  ],
  "1C — Projections orthogonales": [
    {q:"La projection orthogonale sur un plan (P) associe à M le point M'…",c:["intersection de (P) et de la droite passant par M et orthogonale à (P)","du plan (P) le plus éloigné de M","milieu de M et de son symétrique","situé sur (P) et tel que MM' est parallèle à (P)"],a:0,exp:"Définition du guide"},
    {q:"L'ensemble des points invariants par la projection orthogonale sur (P) est…",c:["une droite","un point","l'espace entier","le plan (P) lui-même"],a:3,exp:"Propriété admise"},
    {q:"L'image d'une droite (D) non orthogonale à (P) par la projection sur (P) est…",c:["un segment","un singleton","une droite","un plan"],a:2,exp:"Propriété démontrée en classe"},
    {q:"L'image d'une droite (D) perpendiculaire à (P) par la projection sur (P) est…",c:["un plan","une droite","un segment","un singleton"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si A' et B' sont les projetés de A et B sur (P) avec (AB) non orthogonale à (P), l'image de [AB] est…",c:["la droite (A'B')","le point B'","le segment [A'B']","le point A'"],a:2,exp:"Propriété du guide"},
    {q:"Si (AB) est parallèle à (P), alors A'B' = …",c:["0","2AB","AB/2","AB"],a:3,exp:"Segments égaux"},
    {q:"Si (AB) et (P) ne sont pas parallèles (et (AB) non orthogonale à (P)), alors A'B' … AB",c:["=","est indépendant de",">","<"],a:3,exp:"A'B' < AB"},
    {q:"L'image du milieu d'un segment (support non orthogonal à (P)) par la projection sur (P) est…",c:["une extrémité du segment image","un point quelconque","le point invariant","le milieu du segment image"],a:3,exp:"Propriété du guide"},
    {q:"La projection orthogonale sur une droite (D) associe à M le point M'…",c:["milieu de [MO]","intersection de (D) et d'un plan parallèle à (D)","de (D) le plus proche de A","intersection de (D) et du plan orthogonal à (D) passant par M"],a:3,exp:"Définition du guide"},
    {q:"L'ensemble des points invariants par la projection orthogonale sur (D) est…",c:["l'espace entier","la droite (D)","un plan","un point"],a:1,exp:"Propriété démontrée en classe"},
    {q:"L'image par la projection sur (D) d'une droite orthogonale à (D) est…",c:["un singleton","la droite (D)","un plan","une droite parallèle"],a:0,exp:"Propriété démontrée en classe"},
    {q:"L'image par la projection sur (D) d'une droite non orthogonale à (D) est…",c:["la droite (D)","une droite parallèle à (D)","un plan","un singleton"],a:0,exp:"Propriété démontrée en classe"},
  ],
  "1C — Vecteurs de l'espace": [
    {q:"Un vecteur non nul de l'espace est caractérisé par…",c:["sa longueur seulement","son sens seulement","son origine seulement","sa direction, son sens et sa longueur"],a:3,exp:"Définition"},
    {q:"Pour tout point O et tout vecteur →u, il existe…",c:["aucun point M","deux points M","une infinité de points M","un unique point M tel que →OM = →u"],a:3,exp:"Propriété admise"},
    {q:"Deux vecteurs sont colinéaires lorsque…",c:["ils sont orthogonaux","l'un d'eux est nul ou lorsqu'ils ont la même direction","ils ont même sens seulement","ils ont la même longueur"],a:1,exp:"Définition du guide"},
    {q:"Trois vecteurs sont coplanaires si…",c:["l'un au moins est une combinaison linéaire des deux autres","ils sont orthogonaux","ils ont la même norme","ils sont deux à deux colinéaires"],a:0,exp:"Définition du guide"},
    {q:"Pour A ≠ B, un point M appartient à la droite (AB) si et seulement si…",c:["AM = AB","→AM = →AB seulement","→AM ⋅ →AB = 0","il existe un réel x tel que →AM = x →AB"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Pour A, B, C non alignés, M appartient au plan (ABC) si et seulement si…",c:["→AM = →AB + →AC","AM = AB + AC","il existe des réels x et y tels que →AM = x →AB + y →AC","→AM ⋅ →AB = 0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Une base de l'ensemble des vecteurs de l'espace est…",c:["un vecteur non nul","un triplet de vecteurs colinéaires","un couple de vecteurs non colinéaires","un triplet de vecteurs non coplanaires"],a:3,exp:"Définition du guide"},
    {q:"Un repère de l'espace est…",c:["un plan muni d'une origine","un quadruplet (O, I, J, K) de points non coplanaires","un couple de points","un triplet de vecteurs quelconques"],a:1,exp:"Définition du guide"},
    {q:"Dans un repère (O, I, J, K), tout point M admet…",c:["plusieurs triplets de coordonnées","un unique triplet de coordonnées (x ; y ; z)","un couple de coordonnées","aucun triplet de coordonnées"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Dans un cube ABCDEFGH (E au-dessus de A), →AB + →AD + →AE = …",c:["→AC","→AF","→AH","→AG"],a:3,exp:"Diagonale du cube"},
    {q:"Dans un parallélogramme ABCD, →AB + →AD = …",c:["→AC","→BD","→CA","→DB"],a:0,exp:"Règle du parallélogramme"},
    {q:"Les vecteurs →u(1 ; 2 ; 3) et →v(2 ; 4 ; 6) sont…",c:["colinéaires","égaux","orthogonaux","non coplanaires"],a:0,exp:"→v = 2 →u"},
    {q:"Les vecteurs →i, →j et →i + →j sont…",c:["orthogonaux deux à deux","non coplanaires","coplanaires","colinéaires"],a:2,exp:"→i + →j est combinaison linéaire de →i et →j"},
    {q:"Les coordonnées de →AB avec A(1 ; 2 ; 3) et B(4 ; 0 ; 5) sont…",c:["(3 ; 2 ; 2)","(−3 ; 2 ; −2)","(3 ; −2 ; 2)","(5 ; 2 ; 8)"],a:2,exp:"(xB − xA ; yB − yA ; zB − zA)"},
    {q:"Le milieu de [AB] pour A(1 ; 2 ; 3) et B(3 ; 4 ; 7) est…",c:["(1 ; 1 ; 2)","(2 ; 3 ; 4)","(4 ; 6 ; 10)","(2 ; 3 ; 5)"],a:3,exp:"Moyennes des coordonnées"},
  ],
  "1C — Produit scalaire dans l'espace": [
    {q:"Le produit scalaire →u ⋅ →v dans l'espace se définit par projection orthogonale comme…",c:["OA × OB × sin θ","OA − OB","OA + OB","→OA ⋅ →OB = OA × OH (mesure algébrique), H projeté de B sur (OA)"],a:3,exp:"Définition du guide"},
    {q:"Dans une base orthonormée, →u(x ; y ; z) ⋅ →v(x' ; y' ; z') = …",c:["xx' + yy' + zz'","xx' − yy' − zz'","xy' + yz' + zx'","x + y + z + x' + y' + z'"],a:0,exp:"Expression analytique"},
    {q:"→u ⋅ →v = 0 (vecteurs non nuls) équivaut à…",c:["→u et →v sont colinéaires","‖→u‖ = ‖→v‖","→u = →v","→u et →v sont orthogonaux"],a:3,exp:"Orthogonalité"},
    {q:"La norme de →u(x ; y ; z) dans une base orthonormée est…",c:["√(x² + y² + z²)","|x| + |y| + |z|","x + y + z","x² + y² + z²"],a:0,exp:"‖→u‖² = →u ⋅ →u"},
    {q:"La norme de →u(1 ; 2 ; 2) est…",c:["5","9","√5","3"],a:3,exp:"√(1 + 4 + 4)"},
    {q:"Le produit scalaire de →u(1 ; 2 ; 3) et →v(4 ; −1 ; 2) est…",c:["5","−8","8","10"],a:2,exp:"4 − 2 + 6"},
    {q:"Les vecteurs →u(1 ; −1 ; 2) et →v(3 ; 1 ; −1) sont-ils orthogonaux ?",c:["Non, car →u ⋅ →v = 4","Non, car →u ⋅ →v = 6","Oui, car →u ⋅ →v = 3 − 1 − 2 = 0","Non, car ils sont colinéaires"],a:2,exp:"3 − 1 − 2 = 0 : ils sont orthogonaux"},
    {q:"Un vecteur unitaire est un vecteur de norme…",c:["0","−1","1","2"],a:2,exp:"Définition"},
    {q:"Une base orthonormée est une base formée de trois vecteurs…",c:["de normes quelconques","colinéaires et unitaires","coplanaires et unitaires","deux à deux orthogonaux et unitaires"],a:3,exp:"Définition"},
    {q:"Le produit scalaire est…",c:["symétrique : →u ⋅ →v = →v ⋅ →u","toujours nul","toujours positif","antisymétrique"],a:0,exp:"Propriété"},
    {q:"‖→u + →v‖² = …",c:["‖→u‖² + ‖→v‖²","‖→u‖² − 2 →u ⋅ →v + ‖→v‖²","(‖→u‖ + ‖→v‖)²","‖→u‖² + 2 →u ⋅ →v + ‖→v‖²"],a:3,exp:"Identité"},
    {q:"Le cosinus de l'angle entre →u et →v non nuls est…",c:["‖→u‖ / ‖→v‖","→u ⋅ →v","→u ⋅ →v / (‖→u‖ ‖→v‖)","→u ⋅ →v × ‖→u‖ ‖→v‖"],a:2,exp:"Expression trigonométrique du produit scalaire"},
    {q:"Si A, B, C sont tels que →AB ⋅ →AC = 0, alors le triangle ABC est…",c:["rectangle en A","équilatéral","plat","isocèle en A"],a:0,exp:"(AB) ⊥ (AC)"},
  ],
  "1C — Géométrie analytique de l'espace": [
    {q:"Une équation cartésienne d'un plan de vecteur normal →n(a ; b ; c) est…",c:["ax² + by² + cz² = d","ax + by + cz + d = 0","ax + by + c = 0","a + b + c + d = 0"],a:1,exp:"Plan"},
    {q:"Le plan passant par A(1 ; 0 ; 2) de vecteur normal →n(2 ; −1 ; 3) a pour équation…",c:["2x + y + 3z − 8 = 0","2x − y + 3z + 8 = 0","2x − y + 3z − 8 = 0","x − 2y + 3z − 8 = 0"],a:2,exp:"2(x − 1) − y + 3(z − 2) = 0"},
    {q:"Un vecteur normal à 3x − y + 2z − 5 = 0 est…",c:["(1 ; −3 ; 2)","(−5 ; 0 ; 0)","(3 ; −1 ; 2)","(3 ; 1 ; 2)"],a:2,exp:"Coefficients de x, y, z"},
    {q:"La distance de M₀(x₀ ; y₀ ; z₀) au plan ax + by + cz + d = 0 est…",c:["|ax₀ + by₀ + cz₀ + d|","|ax₀ + by₀ + cz₀ + d| / √(a² + b² + c²)","√(a² + b² + c²)","(ax₀ + by₀ + cz₀ + d)/3"],a:1,exp:"Distance point-plan"},
    {q:"La distance de l'origine au plan 2x − 2y + z − 9 = 0 est…",c:["9","1","3","√14"],a:2,exp:"9/√9"},
    {q:"Une représentation paramétrique de la droite passant par A(1 ; 2 ; 3) de vecteur directeur →u(2 ; −1 ; 4) est…",c:["x = 1 + 2t ; y = 2 − t ; z = 3 + 4t","x = 1 + 2t ; y = 2 + t ; z = 3 − 4t","x = 2 + t ; y = −1 + 2t ; z = 4 + 3t","x = 2t ; y = −t ; z = 4t"],a:0,exp:"Point + t fois le vecteur directeur"},
    {q:"Deux plans sont parallèles si et seulement si leurs vecteurs normaux sont…",c:["orthogonaux","nuls","égaux en norme seulement","colinéaires"],a:3,exp:"Étude analytique du parallélisme"},
    {q:"Deux plans sont perpendiculaires si et seulement si leurs vecteurs normaux sont…",c:["colinéaires","orthogonaux","de norme 1","égaux"],a:1,exp:"Étude analytique de la perpendicularité"},
    {q:"Les plans x + y + z = 1 et 2x + 2y + 2z = 5 sont…",c:["perpendiculaires","sécants suivant une droite","confondus","parallèles (non confondus)"],a:3,exp:"(2 ; 2 ; 2) = 2 (1 ; 1 ; 1) mais 5 ≠ 2"},
    {q:"Une droite est parallèle à un plan si et seulement si son vecteur directeur est…",c:["égal à un vecteur normal","nul","colinéaire à un vecteur normal","orthogonal à un vecteur normal du plan"],a:3,exp:"Étude analytique"},
    {q:"Caractérisation vectorielle du plan (ABC) : M appartient à (ABC) si et seulement si…",c:["AM = AB + AC","→AM = x →AB + y →AC","→AM ⋅ →AB = 0","→AM = →AB + →AC uniquement"],a:1,exp:"Plan défini par trois points non alignés"},
    {q:"Deux plans non parallèles se coupent suivant…",c:["un point","une droite","un plan","l'ensemble vide"],a:1,exp:"Système de deux équations cartésiennes"},
  ],
  "1C — Équations du second degré": [
    {q:"Le discriminant de ax² + bx + c est Δ = …",c:["4ac − b²","b² + 4ac","b² − 4ac","b − 4ac"],a:2,exp:"Définition"},
    {q:"Si Δ > 0, l'équation ax² + bx + c = 0 admet…",c:["une infinité de solutions","deux solutions réelles distinctes","une solution double","aucune solution réelle"],a:1,exp:"Résolution par le discriminant"},
    {q:"Si Δ = 0, l'équation admet…",c:["deux solutions distinctes","une solution double x = −b/(2a)","aucune solution","deux solutions opposées"],a:1,exp:"Résolution par le discriminant"},
    {q:"Si Δ < 0, l'équation n'admet…",c:["qu'une solution","que deux solutions","que des solutions entières","aucune solution réelle"],a:3,exp:"Résolution par le discriminant"},
    {q:"Les solutions de 2x² − 3x − 2 = 0 sont…",c:["−2 et 1/2","3 et −1","2 et −1/2","1 et −2"],a:2,exp:"Δ = 9 + 16 = 25 ; x = (3 ± 5)/4"},
    {q:"Les solutions de x² − 6x + 9 = 0 sont…",c:["x = 6","x = 3 (solution double)","aucune solution réelle","x = 3 et x = −3"],a:1,exp:"Δ = 0"},
    {q:"Si x₁ et x₂ sont les solutions de ax² + bx + c = 0, alors x₁ + x₂ = … et x₁ x₂ = …",c:["b/a et −c/a","−b et c","c/a et −b/a","−b/a et c/a"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Deux nombres de somme 7 et de produit 12 sont…",c:["−3 et −4","2 et 5","3 et 4","1 et 6"],a:2,exp:"Racines de x² − 7x + 12 = 0"},
    {q:"Les solutions de x² − 5x + 6 = 0 sont de signes…",c:["contraires","impossibles à déterminer","opposés","identiques (produit 6 > 0 et somme 5 > 0 : deux positives)"],a:3,exp:"c/a > 0 et −b/a > 0"},
    {q:"Si c/a < 0, les solutions de ax² + bx + c = 0 sont…",c:["toutes deux nulles","de même signe","de signes contraires","non réelles"],a:2,exp:"Le produit est négatif"},
    {q:"Résoudre x⁴ − 5x² + 4 = 0 avec X = x².",c:["x = 1 ou x = 4","x = ±1 ou x = ±2","x = ±√5","x = ±4"],a:1,exp:"X² − 5X + 4 = 0 donne X = 1 ou X = 4"},
    {q:"Résoudre l'équation irrationnelle √(x + 2) = x.",c:["x = −1","x = 0","x = 2","x = 2 ou x = −1"],a:2,exp:"x + 2 = x² avec x ≥ 0 : on rejette −1"},
    {q:"Pour résoudre une équation irrationnelle, il faut toujours…",c:["vérifier les solutions trouvées dans l'équation de départ","prendre l'inverse","dériver les deux membres","passer au logarithme"],a:0,exp:"Élever au carré peut ajouter de fausses solutions"},
    {q:"Le signe du trinôme ax² + bx + c avec Δ < 0 est celui de…",c:["−a sur ℝ","b sur ℝ","a sur tout ℝ","c seulement"],a:2,exp:"Pas de racine réelle"},
    {q:"Le signe de x² + x + 1 sur ℝ est…",c:["nul en deux points","toujours négatif","positif puis négatif","toujours strictement positif"],a:3,exp:"Δ = −3 < 0 et a = 1 > 0"},
    {q:"La forme canonique de ax² + bx + c est…",c:["a[(x + b/(2a))² − Δ/(4a²)]","a(x + b)² + c","a(x − b/(2a))² + Δ","(x + b/(2a))² + c"],a:0,exp:"Origine du discriminant"},
  ],
  "1C — Inéquations du second degré & systèmes linéaires": [
    {q:"x² − 3x + 2 ≤ 0 a pour ensemble de solutions…",c:["]−∞ ; 1] ∪ [2 ; +∞[","[1 ; 2]","]1 ; 2[","ℝ"],a:1,exp:"Racines 1 et 2 ; trinôme négatif entre les racines"},
    {q:"x² − 4 > 0 a pour ensemble de solutions…",c:["]2 ; +∞[","ℝ","]−∞ ; −2[ ∪ ]2 ; +∞[","]−2 ; 2["],a:2,exp:"Positif à l'extérieur des racines"},
    {q:"Un trinôme ax² + bx + c (a > 0, Δ > 0) est négatif…",c:["nulle part","à l'extérieur de ses racines","partout","entre ses racines"],a:3,exp:"Signe de a à l'extérieur, de −a entre les racines"},
    {q:"Pour un trinôme de racines x₁ < x₂ et a > 0, le nombre α vérifiant α < x₁ < x₂ est tel que…",c:["f(α) = 0","on ne peut pas conclure","f(α) > 0","f(α) < 0"],a:2,exp:"À l'extérieur des racines, le trinôme est du signe de a"},
    {q:"Deux systèmes d'équations sont équivalents si…",c:["ils ont le même nombre d'équations","ils ont la même solution particulière","ils ont le même ensemble de validité et le même ensemble de solutions","ils ont les mêmes coefficients"],a:2,exp:"Définition du guide"},
    {q:"La méthode du pivot de Gauss permet de…",c:["résoudre une équation du second degré","calculer un discriminant","tracer une droite","transformer un système en un système équivalent triangulaire"],a:3,exp:"Système linéaire à trois inconnues"},
    {q:"Résoudre x + y + z = 6 ; y + z = 5 ; z = 3.",c:["(3 ; 2 ; 1)","(1 ; 2 ; 3)","(1 ; 3 ; 2)","(2 ; 1 ; 3)"],a:1,exp:"On remonte : z = 3, y = 2, x = 1"},
    {q:"Résoudre le système x + y + z = 3 ; x − y + z = 1 ; x + y − z = 1.",c:["(1 ; 1 ; 1)","(2 ; 0 ; 1)","(1 ; 2 ; 0)","(0 ; 1 ; 2)"],a:0,exp:"Par différences : y = 1 ; z = 1 ; x = 1"},
    {q:"Pour résoudre un système avec 1/x, 1/y, 1/z, on peut…",c:["poser X = 1/x, Y = 1/y, Z = 1/z","poser x = y = z","élever au carré","supprimer une équation"],a:0,exp:"Changement d'inconnues"},
    {q:"Un problème de programmation linéaire à deux variables se résout…",c:["par un dénombrement","par le pivot de Gauss seulement","en cherchant l'optimum d'une fonction linéaire sur le polygone des contraintes","en calculant un discriminant"],a:2,exp:"Résolution graphique"},
    {q:"L'optimum d'une fonction linéaire sur un polygone convexe est atteint en…",c:["le centre du polygone","un sommet du polygone","un point intérieur quelconque","aucun point"],a:1,exp:"Principe de la programmation linéaire"},
    {q:"Les systèmes linéaires étudiés en 1ère D sont…",c:["seulement à deux inconnues","sans paramètre","toujours avec paramètre","seulement homogènes"],a:1,exp:"N.B. du guide"},
  ],
  "1C — Statistique à deux caractères": [
    {q:"Un nuage de points est…",c:["une droite","l'ensemble des points Mᵢ(xᵢ ; yᵢ) associés aux couples de valeurs observés","un histogramme","un diagramme circulaire"],a:1,exp:"Série double"},
    {q:"Le point moyen G d'un nuage a pour coordonnées…",c:["(mode de X ; mode de Y)","(somme de X ; somme de Y)","(moyenne de X ; moyenne de Y)","(médiane de X ; médiane de Y)"],a:2,exp:"Définition"},
    {q:"La variance de X est V(X) = …",c:["(moyenne de X)²","moyenne des xᵢ","(moyenne des xᵢ²) − (moyenne de X)²","(moyenne de X)² − (moyenne des xᵢ²)"],a:2,exp:"Formule de König"},
    {q:"La covariance de (X, Y) est Cov(X, Y) = …",c:["(moyenne de X)(moyenne de Y)","(moyenne des xᵢ yᵢ) − (moyenne de X)(moyenne de Y)","V(X) V(Y)","moyenne des xᵢ + moyenne des yᵢ"],a:1,exp:"Définition"},
    {q:"La droite de régression de Y en X (moindres carrés) a pour coefficient directeur a = …",c:["Cov(X, Y) × V(X)","Cov(X, Y)/V(X)","V(X)/Cov(X, Y)","Cov(X, Y)/V(Y)"],a:1,exp:"Ajustement linéaire"},
    {q:"Son ordonnée à l'origine est b = …",c:["(moyenne de Y) + a (moyenne de X)","(moyenne de X) − a","(moyenne de Y) − a (moyenne de X)","a × (moyenne de Y)"],a:2,exp:"La droite passe par G"},
    {q:"La droite de régression passe par…",c:["l'origine seulement","le premier point du nuage","le point moyen G du nuage","aucun point particulier"],a:2,exp:"Propriété"},
    {q:"X : 1, 2, 3, 4 et Y : 2, 4, 6, 8. La covariance vaut…",c:["5","15","0","2,5"],a:3,exp:"15 − 2,5 × 5"},
    {q:"X : 1, 2, 3, 4 et Y : 2, 4, 6, 8. V(X) = …",c:["2,5","6,25","1,25","7,5"],a:2,exp:"7,5 − 2,5²"},
    {q:"X : 1, 2, 3, 4 et Y : 2, 4, 6, 8. La droite de régression de Y en X est…",c:["y = 2x + 5","y = 5x","y = 2x","y = x + 2,5"],a:2,exp:"a = 2,5/1,25 = 2 et b = 5 − 2 × 2,5 = 0"},
    {q:"Un ajustement linéaire permet de…",c:["estimer une valeur de Y pour une valeur de X non observée","résoudre une équation du second degré","construire un histogramme","calculer la médiane"],a:0,exp:"Utilisation"},
    {q:"Si tous les points du nuage sont alignés, la droite de régression…",c:["passe par l'origine seulement","est la droite qui les contient","n'existe pas","est horizontale"],a:1,exp:"Ajustement parfait"},
  ],
  "1C — Dénombrement": [
    {q:"card(A ∪ B) = …",c:["card A × card B","card A + card B − card(A ∩ B)","card A − card B","card A + card B + card(A ∩ B)"],a:1,exp:"Propriété démontrée en classe"},
    {q:"card(A × B) = …",c:["card A − card B","(card A)ᵇ","card A × card B","card A + card B"],a:2,exp:"Propriété admise"},
    {q:"Le nombre de p-listes d'un ensemble à n éléments est…",c:["n!/p!","nᵖ","pⁿ","n × p"],a:1,exp:"card Eᵖ = nᵖ"},
    {q:"Le nombre de codes à 4 chiffres (chiffres de 0 à 9, répétitions autorisées) est…",c:["10 000","5 040","40","10 × 4"],a:0,exp:"10⁴"},
    {q:"Le nombre d'applications d'un ensemble à p éléments dans un ensemble à n éléments est…",c:["n × p","nᵖ","n!","pⁿ"],a:1,exp:"Propriété du guide"},
    {q:"Le nombre de p-arrangements de n éléments est Aₙᵖ = …",c:["n(n − 1)…(n − p + 1)","nᵖ","n!/p!","n!"],a:0,exp:"Propriété du guide"},
    {q:"A₅² = …",c:["10","25","20","120"],a:2,exp:"5 × 4"},
    {q:"Le nombre d'injections d'un ensemble de p éléments dans un ensemble de n éléments est…",c:["nᵖ","n!","Aₙᵖ","Cₙᵖ"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Le nombre de permutations de n éléments est…",c:["2n","n!","n²","nⁿ"],a:1,exp:"Propriété démontrée en classe"},
    {q:"5! = …",c:["25","720","120","60"],a:2,exp:"5 × 4 × 3 × 2 × 1"},
    {q:"Par convention, 0! = …",c:["non défini","1","−1","0"],a:1,exp:"Convention du guide"},
    {q:"Le nombre de bijections d'un ensemble à n éléments sur un ensemble de même cardinal est…",c:["2n","n!","nⁿ","n²"],a:1,exp:"Propriété du guide"},
    {q:"Le nombre de p-combinaisons de n éléments est Cₙᵖ = …",c:["n!/(n − p)!","n!/p!","n!/(p!(n − p)!)","nᵖ/p!"],a:2,exp:"Propriété du guide"},
    {q:"C₅² = …",c:["5","10","25","20"],a:1,exp:"5!/(2! 3!)"},
    {q:"C₆³ = …",c:["120","20","18","6"],a:1,exp:"6!/(3! 3!)"},
    {q:"Cₙ⁰ = … et Cₙⁿ = …",c:["1 et 1","1 et n","0 et 1","n et n"],a:0,exp:"Propriétés démontrées en classe"},
    {q:"Cₙᵖ = …",c:["Cₙᵖ⁺¹","Cₙⁿ⁻ᵖ","Cₚⁿ","Aₙᵖ"],a:1,exp:"Symétrie des combinaisons"},
    {q:"Relation de Pascal : Cₙᵖ = …",c:["Cₙ₋₁ᵖ × Cₙ₋₁ᵖ⁻¹","Cₙ₊₁ᵖ − Cₙᵖ","Cₙ₋₁ᵖ⁻¹ + Cₙ₋₁ᵖ","Cₙᵖ⁻¹ + Cₙᵖ⁺¹"],a:2,exp:"Construction du triangle de Pascal"},
    {q:"Le nombre de façons de choisir 3 personnes parmi 8 est…",c:["56","8³","24","336"],a:0,exp:"C₈³ = 56"},
    {q:"Le nombre de façons de placer 4 personnes différentes sur 6 sièges numérotés est…",c:["24","15","1 296","360"],a:3,exp:"A₆⁴ = 6 × 5 × 4 × 3"},
    {q:"Le développement de (a + b)³ selon la formule du binôme est…",c:["a³ + 3a²b + 3ab² + b³","a³ + b³","a³ + 2a²b + 2ab² + b³","a³ + 3ab + b³"],a:0,exp:"Coefficients 1, 3, 3, 1 (ligne du triangle de Pascal)"},
  ],
  "1C — Applications & fonctions numériques": [
    {q:"Toute application est…",c:["une fonction croissante","une fonction (la réciproque est fausse)","une injection","une bijection"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La restriction d'une fonction f à une partie E de son ensemble de définition est…",c:["f définie sur un ensemble plus grand","une fonction constante","la réciproque de f","la fonction g de E dans B définie par g(x) = f(x)"],a:3,exp:"Définition du guide"},
    {q:"Un prolongement de f est…",c:["une fonction qui coïncide avec f sur l'ensemble de définition de f et qui est définie sur un ensemble plus grand","une restriction de f","une primitive de f","la réciproque de f"],a:0,exp:"Définition"},
    {q:"Une fonction f est bornée sur E si…",c:["elle est continue","elle est croissante","elle est positive","elle est à la fois majorée et minorée sur E"],a:3,exp:"Définition du guide"},
    {q:"La composée de deux injections est…",c:["une application constante","une bijection","une injection","une surjection"],a:2,exp:"Propriété admise"},
    {q:"La composée de deux surjections est…",c:["une surjection","une application non définie","une injection","une application constante"],a:0,exp:"Propriété admise"},
    {q:"La composée f∘g de deux bijections f et g est une bijection et (f∘g)⁻¹ = …",c:["g⁻¹ ∘ f⁻¹","f ∘ g","f⁻¹ ∘ g⁻¹","g ∘ f"],a:0,exp:"Propriété admise"},
    {q:"La composition des applications est…",c:["commutative","toujours nulle","toujours bijective","associative"],a:3,exp:"Propriété admise"},
    {q:"f est bijective de A vers B si et seulement si…",c:["f est croissante","pour tout y de B, l'équation f(x) = y admet une solution unique dans A","f est continue","A = B"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est une bijection de A sur B, alors f⁻¹ ∘ f = …",c:["f","Id_A","f⁻¹","Id_B"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Dans un repère orthonormé, les courbes de deux bijections réciproques sont symétriques par rapport à…",c:["l'axe des ordonnées","l'origine","la droite y = x (première bissectrice)","l'axe des abscisses"],a:2,exp:"Propriété démontrée en classe"},
    {q:"L'image directe d'une partie A par f est…",c:["la restriction de f","l'ensemble des images des éléments de A","la réciproque de f","l'ensemble des antécédents d'un ensemble"],a:1,exp:"Définition du guide"},
    {q:"L'image réciproque d'une partie B par f est…",c:["l'ensemble des éléments dont l'image appartient à B","f(B)","l'ensemble des images de B","la réciproque de f"],a:0,exp:"Définition du guide (f n'est pas forcément bijective)"},
    {q:"Un minorant de f sur E est un réel m tel que…",c:["m > f(x) pour un x de E","m ≥ f(x) pour tout x de E","m ≤ f(x) pour tout x de E","m = f(0)"],a:2,exp:"Définition"},
    {q:"Pour deux fonctions f et g, « f < g sur E » signifie que…",c:["f(x) < g(x) pour tout x de E","f(x) = g(x) pour tout x de E","f(E) < g(E)","f(x) < g(x) pour un seul x"],a:0,exp:"Comparaison de fonctions"},
  ],
  "1C — Limites & continuité": [
    {q:"Si f est définie en a et admet une limite en a, alors cette limite est égale à…",c:["f(a)","+∞","a","0"],a:0,exp:"Propriété admise"},
    {q:"Une fonction est continue en a lorsqu'elle est…",c:["seulement définie en a","seulement dérivable en a","définie en a et admet une limite en a","croissante en a"],a:2,exp:"Définition du guide"},
    {q:"Les fonctions polynômes sont continues…",c:["sur [0 ; 1]","sur ]0 ; +∞[","seulement en 0","sur ℝ"],a:3,exp:"Somme et produit de fonctions élémentaires"},
    {q:"Une fonction rationnelle est continue…",c:["seulement en 0","seulement sur [0 ; 1]","en tout point de son ensemble de définition","sur ℝ toujours"],a:2,exp:"Quotient de fonctions élémentaires"},
    {q:"La somme de deux fonctions continues en a est…",c:["nulle","constante","continue en a","discontinue en a"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si lim f = l et lim g = l' en a, alors lim (f × g) = …",c:["l × l'","l/l'","l − l'","l + l'"],a:0,exp:"Propriété admise"},
    {q:"Si f ≤ g sur I, lim f = l et lim g = l' en a, alors…",c:["l ≤ l'","l < l'","l ≥ l'","l = l'"],a:0,exp:"Propriété admise"},
    {q:"Théorème des gendarmes : f ≤ g ≤ h avec f et h de même limite l en a ⟹",c:["g est continue","g est constante","g n'a pas de limite","g admet la limite l en a"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si f n'est pas définie en a, f admet une limite l en a si et seulement si…",c:["elle admet une limite à gauche seulement","elle est croissante","elle admet en a une limite à gauche et une limite à droite égales à l","f(a) = l"],a:2,exp:"Propriété admise"},
    {q:"La fonction valeur absolue est continue…",c:["sur ]0 ; +∞[ seulement","en tout élément de ℝ","nulle part","seulement en 0"],a:1,exp:"Propriété démontrée en distinguant x < 0, x = 0 et x > 0"},
    {q:"La limite de (x² − 1)/(x − 1) en 1 est…",c:["2","0","1","+∞"],a:0,exp:"(x − 1)(x + 1)/(x − 1) = x + 1"},
    {q:"La limite de 1/(x − 1)² en 1 est…",c:["+∞","−∞","0","1"],a:0,exp:"Le dénominateur tend vers 0 par valeurs positives"},
    {q:"La limite de (x + 1)/(x − 1) quand x tend vers 1 par valeurs inférieures est…",c:["2","−∞","+∞","0"],a:1,exp:"Numérateur proche de 2 ; dénominateur tend vers 0 par valeurs négatives"},
    {q:"Lorsque f a une limite infinie en a, la droite x = a est…",c:["un axe de symétrie","une tangente horizontale","une asymptote horizontale","une asymptote verticale à la courbe de f"],a:3,exp:"Interprétation géométrique"},
    {q:"Si f a pour limite b en +∞, la droite y = b est…",c:["une tangente verticale","un axe de symétrie","une asymptote verticale","une asymptote horizontale à la courbe de f"],a:3,exp:"Interprétation géométrique"},
    {q:"La limite d'une fonction polynôme à l'infini est celle…",c:["de sa dérivée","de son coefficient dominant seulement","de son monôme de plus haut degré","de son terme constant"],a:2,exp:"Propriété énoncée dans le guide"},
    {q:"La limite d'une fonction rationnelle à l'infini est celle…",c:["du quotient des monômes de plus haut degré","du quotient des termes constants","de son dénominateur","de son numérateur"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"La notion de prolongement par continuité est en 1ère D…",c:["démontrée","au programme","obligatoire","hors programme"],a:3,exp:"N.B. du guide"},
  ],
  "1C — Dérivation & primitives": [
    {q:"Le taux de variation de f entre x₀ et x est…",c:["(x − x₀)/(f(x) − f(x₀))","f(x) − f(x₀)","(f(x) − f(x₀))/(x − x₀)","f(x)/f(x₀)"],a:2,exp:"Définition"},
    {q:"Le nombre dérivé de f en x₀ est…",c:["la limite du taux de variation en x₀","f(x₀)","f(x₀)²","le taux de variation en 0"],a:0,exp:"Définition"},
    {q:"Si f est dérivable en un point, alors f est…",c:["constante","discontinue en ce point","continue en ce point","monotone"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La réciproque de « dérivable ⟹ continue » est…",c:["vraie","vraie sur ℝ","fausse : la valeur absolue est continue en 0 sans y être dérivable","vraie pour les polynômes seulement"],a:2,exp:"Exemple du guide"},
    {q:"Une équation de la tangente au point d'abscisse x₀ est…",c:["y = f(x₀)(x − x₀) + f'(x₀)","y = f'(x₀)","y = f'(x₀)(x − x₀) + f(x₀)","y = x₀ f'(x)"],a:2,exp:"Formule de la tangente"},
    {q:"La dérivée d'un produit uv est…",c:["u'v − uv'","u'v + uv'","u v","u'v'"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La dérivée d'un quotient u/v est…",c:["(u'v + uv')/v²","u'/v'","(u' − v')/v²","(u'v − uv')/v²"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si f(x) = g(x + α), alors f'(a) = …",c:["g'(a + α)","g(a + α)","α g'(a)","g'(a)"],a:0,exp:"Propriété admise"},
    {q:"f est croissante sur un intervalle ouvert K si et seulement si…",c:["f' est positive sur K","f' est nulle sur K","f est continue","f' est négative sur K"],a:0,exp:"Propriété admise"},
    {q:"Si f' s'annule et change de signe en x₀, alors f admet en x₀…",c:["un extremum relatif","une asymptote","aucun comportement particulier","un point anguleux"],a:0,exp:"Propriété admise"},
    {q:"Toute fonction continue sur un intervalle K admet…",c:["une limite infinie","un minimum strict","une dérivée sur K","une primitive sur K"],a:3,exp:"Propriété admise"},
    {q:"Si F est une primitive de f sur K, les primitives de f sur K sont…",c:["les fonctions F + C, C constante","les fonctions F²","les fonctions C × F","uniquement F"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Il existe une unique primitive de f sur K qui prend la valeur y₀ en x₀ :",c:["faux, il n'en existe aucune","vrai seulement si y₀ = 0","faux, il en existe une infinité","vrai (f continue sur K)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une primitive de x ↦ x² est…",c:["x³","2x","x³/3","x²/2"],a:2,exp:"Primitive usuelle"},
    {q:"La primitive de x ↦ 3x² + 2x qui s'annule en 0 est…",c:["x³ + x²","6x + 2","x³ + x² + 1","3x³ + 2x²"],a:0,exp:"F(x) = x³ + x² + C avec C = 0"},
    {q:"Une primitive de x ↦ cos x est…",c:["cos x","−cos x","sin x","−sin x"],a:2,exp:"(sin x)' = cos x"},
    {q:"Une primitive de x ↦ 1/√x sur ]0 ; +∞[ est…",c:["2√x","1/(2√x)","−1/x","√x/2"],a:0,exp:"(2√x)' = 1/√x"},
    {q:"Si F et G sont des primitives de f et g, alors une primitive de af + bg est…",c:["aG + bF","aF + bG","a + b","F × G"],a:1,exp:"Linéarité des primitives"},
  ],
  "1C — Suites numériques": [
    {q:"Une suite numérique est…",c:["un nombre","une fonction de ℝ vers ℝ","une fonction de ℕ (ou d'une partie de ℕ) vers ℝ","une équation"],a:2,exp:"Définition du guide"},
    {q:"Une suite (uₙ) est majorée si…",c:["il existe M tel que uₙ ≤ M pour tout n","il existe m tel que uₙ ≥ m","uₙ est croissante","uₙ est positive"],a:0,exp:"Définition du guide"},
    {q:"Une suite est bornée si…",c:["elle est croissante","elle est convergente seulement","elle est à la fois majorée et minorée","elle est positive"],a:2,exp:"Définition du guide"},
    {q:"Une suite arithmétique vérifie…",c:["uₙ₊₁ = uₙ + r","uₙ₊₁ = uₙ²","uₙ₊₁ = q uₙ","uₙ₊₁ = uₙ/n"],a:0,exp:"Définition du guide"},
    {q:"Le terme général d'une suite arithmétique de premier terme u_k et de raison r est…",c:["uₙ = u_k + (n − k) r","uₙ = u_k × rⁿ⁻ᵏ","uₙ = u_k + r","uₙ = n r"],a:0,exp:"Formule du guide"},
    {q:"Suite arithmétique avec u₀ = 3 et r = 2 : u₁₀ = …",c:["20","13","23","33"],a:2,exp:"3 + 10 × 2"},
    {q:"Suite arithmétique avec u₀ = 3 et r = 2 : la somme u₀ + u₁ + … + u₉ vaut…",c:["100","120","60","66"],a:1,exp:"10 × (3 + 21)/2"},
    {q:"Une suite géométrique vérifie…",c:["uₙ₊₁ = q uₙ","uₙ₊₁ = uₙ + r","uₙ₊₁ = uₙ/n","uₙ₊₁ = uₙ + q"],a:0,exp:"Définition du guide"},
    {q:"Suite géométrique avec u₀ = 2 et q = 3 : u₄ = …",c:["24","162","486","54"],a:1,exp:"2 × 3⁴"},
    {q:"Pour q ≠ 1, la somme de p termes consécutifs à partir de u_k vaut…",c:["u_k (1 − q)/(1 − qᵖ)","u_k (1 − qᵖ)/(1 − q)","u_k qᵖ","p u_k"],a:1,exp:"Formule du guide"},
    {q:"Suite géométrique avec u₀ = 2 et q = 3 : u₀ + u₁ + u₂ + u₃ + u₄ = …",c:["242","80","486","162"],a:0,exp:"2(1 − 3⁵)/(1 − 3)"},
    {q:"Une suite est croissante si…",c:["uₙ₊₁ ≥ uₙ pour tout n","uₙ = 0","uₙ > 0","uₙ₊₁ ≤ uₙ pour tout n"],a:0,exp:"Définition"},
    {q:"Une suite monotone est…",c:["bornée","croissante ou décroissante","à la fois croissante et décroissante","convergente"],a:1,exp:"Définition du guide"},
    {q:"Une suite est convergente si…",c:["elle est croissante","elle est positive","elle a une limite finie","elle est bornée"],a:2,exp:"Définition du guide"},
    {q:"Toute suite décroissante et minorée est…",c:["nulle","constante","divergente","convergente"],a:3,exp:"Propriété admise"},
    {q:"Toute suite croissante et majorée est…",c:["divergente","nulle","décroissante","convergente"],a:3,exp:"Propriété admise"},
    {q:"Si uₙ = f(n) et si f a pour limite l en +∞, alors (uₙ)…",c:["diverge","est croissante","est constante","converge vers l"],a:3,exp:"Propriété admise"},
    {q:"Si f n'a pas de limite en +∞, peut-on conclure sur la convergence de uₙ = f(n) ?",c:["Non, il faut étudier la suite séparément","Oui, elle est croissante","Oui, elle diverge","Oui, elle converge"],a:0,exp:"Remarque du guide"},
    {q:"La suite uₙ = (3n + 1)/(n + 2) converge vers…",c:["0","1/2","+∞","3"],a:3,exp:"3n/n"},
  ],
  "1C — Angles orientés & fonctions circulaires": [
    {q:"Une mesure d'un angle orienté de mesure principale α est de la forme…",c:["kα","α + 2kπ (k ∈ ℤ)","α/2 + kπ","α + kπ (k ∈ ℤ)"],a:1,exp:"Définition du guide"},
    {q:"Les mesures de l'angle orienté nul sont…",c:["π + 2kπ","π/2 + 2kπ","2kπ","kπ"],a:2,exp:"Propriété admise"},
    {q:"Les mesures de l'angle orienté plat sont…",c:["2kπ","π + 2kπ","π/2 + 2kπ","kπ"],a:1,exp:"Propriété admise"},
    {q:"Les mesures d'un angle orienté droit (de vecteurs orthogonaux) sont de la forme…",c:["π/2 + 2kπ","2kπ","π/2 + kπ","π + 2kπ"],a:2,exp:"Propriété admise"},
    {q:"La mesure principale d'un angle de mesure 7π/3 est…",c:["−π/3","7π/3","π/3","4π/3"],a:2,exp:"7π/3 − 2π"},
    {q:"La mesure principale d'un angle de mesure 13π/4 est…",c:["−3π/4","3π/4","13π/4","π/4"],a:0,exp:"13π/4 − 2π = 5π/4, puis 5π/4 − 2π = −3π/4"},
    {q:"Relation de Chasles : (→u, →w) = …",c:["(→v, →u) + (→w, →v)","(→u, →v) + (→v, →w)","(→u, →v) × (→v, →w)","(→u, →v) − (→v, →w)"],a:1,exp:"À 2π près"},
    {q:"Pour tout réel a, cos²a + sin²a = …",c:["1","0","cos 2a","2"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Pour tout réel a, on a…",c:["−1 ≤ cos a ≤ 1 et −1 ≤ sin a ≤ 1","sin a ≥ 1","cos a ≥ 1","cos a + sin a = 1"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si cos a ≠ 0, tan a = …",c:["cos a / sin a","sin a / cos a","1/sin a","sin a × cos a"],a:1,exp:"Définition"},
    {q:"Si cos a ≠ 0, 1 + tan²a = …",c:["1/cos²a","1/sin²a","tan 2a","cos²a"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La période de cos et de sin est…",c:["π/2","4π","π","2π"],a:3,exp:"cos(a + 2kπ) = cos a"},
    {q:"La période de tan est…",c:["4π","π","2π","π/2"],a:1,exp:"tan(a + kπ) = tan a"},
    {q:"La fonction cos est…",c:["ni paire ni impaire","impaire","constante","paire"],a:3,exp:"cos(−x) = cos x"},
    {q:"La fonction sin est…",c:["paire","impaire","constante","ni paire ni impaire"],a:1,exp:"sin(−x) = −sin x"},
    {q:"La limite de (sin x)/x en 0 est…",c:["1","+∞","0","1/2"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"La limite de (1 − cos x)/x² en 0 est…",c:["2","0","1","1/2"],a:3,exp:"Propriété énoncée dans le guide"},
    {q:"Pour les petites valeurs de |x|, sin x est approximativement égal à…",c:["x","1","x²","1 − x"],a:0,exp:"Limite de sin x / x = 1"},
  ],
  "1C — Formules trigonométriques & équations": [
    {q:"cos(a + b) = …",c:["cos a + cos b","cos a cos b − sin a sin b","cos a cos b + sin a sin b","sin a cos b + cos a sin b"],a:1,exp:"Formule d'addition"},
    {q:"cos(a − b) = …",c:["cos a cos b − sin a sin b","cos a − cos b","sin a cos b − cos a sin b","cos a cos b + sin a sin b"],a:3,exp:"Formule d'addition"},
    {q:"sin(a + b) = …",c:["sin a cos b + cos a sin b","cos a cos b − sin a sin b","sin a cos b − cos a sin b","sin a + sin b"],a:0,exp:"Formule d'addition"},
    {q:"sin(a − b) = …",c:["sin a cos b − cos a sin b","cos a cos b + sin a sin b","sin a − sin b","sin a cos b + cos a sin b"],a:0,exp:"Formule d'addition"},
    {q:"cos 2a = …",c:["2 sin a cos a","1 + 2 sin²a","cos²a − sin²a","cos²a + sin²a"],a:2,exp:"Formule de duplication"},
    {q:"cos 2a s'écrit aussi…",c:["cos²a + 1","1 + 2cos²a","2cos²a − 1","2sin²a − 1"],a:2,exp:"Formule de duplication"},
    {q:"sin 2a = …",c:["sin²a − cos²a","2 sin a cos a","sin a + cos a","2 sin a"],a:1,exp:"Formule de duplication"},
    {q:"Si cos a = 3/5, alors cos 2a = …",c:["7/25","9/25","−7/25","6/5"],a:2,exp:"2 × 9/25 − 1"},
    {q:"Si sin a = 3/5 avec a dans ]0 ; π/2[, alors sin 2a = …",c:["6/5","12/25","9/25","24/25"],a:3,exp:"cos a = 4/5 ; 2 × 3/5 × 4/5"},
    {q:"cos(π/3 + π/6) = …",c:["√3/2","0","1","1/2"],a:1,exp:"cos(π/2)"},
    {q:"Les solutions de cos x = 1/2 sont…",c:["x = π/6 + kπ","x = π/6 + 2kπ ou 5π/6 + 2kπ","x = π/3 + kπ","x = ±π/3 + 2kπ"],a:3,exp:"Résolution de cos x = a"},
    {q:"Les solutions de sin x = 1/2 sont…",c:["x = π/6 + 2kπ ou x = 5π/6 + 2kπ","x = π/3 + 2kπ","x = π/6 + kπ","x = ±π/6 + 2kπ"],a:0,exp:"Résolution de sin x = b"},
    {q:"Les solutions de tan x = 1 sont…",c:["x = π/4 + kπ","x = π/4 + 2kπ","x = ±π/4 + 2kπ","x = π/2 + kπ"],a:0,exp:"tan est π-périodique"},
    {q:"cos x = 0 a pour solutions…",c:["x = 2kπ","x = π/2 + kπ","x = π + 2kπ","x = kπ"],a:1,exp:"Points d'abscisse nulle sur le cercle trigonométrique"},
    {q:"Pour résoudre a cos x + b sin x = c, on écrit a cos x + b sin x sous la forme…",c:["(a + b) cos x","a cos(x) + b cos(x)","√(a² + b²) cos(x − φ)","ab cos x sin x"],a:2,exp:"Méthode du guide"},
    {q:"Résoudre cos x ≥ 0 sur ]−π ; π].",c:["x ∈ [−π/2 ; π/2]","x ∈ [−π ; 0]","x ∈ [π/2 ; π]","x ∈ [0 ; π]"],a:0,exp:"cos est positif sur cet intervalle"},
    {q:"Pour tout t de [−1 ; 1], il existe a dans ]−π ; π] tel que…",c:["tan a = t","a = t","sin a = t","cos a = 0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Pour tout réel t, il existe a dans ]−π/2 ; π/2[ tel que…",c:["cos a = t","tan a = t","a = 2t","sin a = t"],a:1,exp:"Propriété démontrée en classe"},
  ],
  "1C — Barycentre & lignes de niveau": [
    {q:"G est le barycentre de (A ; α) et (B ; β), α + β ≠ 0, si et seulement si…",c:["α + β = 0","α →GA + β →GB = →0","GA = GB","→GA = →GB"],a:1,exp:"Définition"},
    {q:"Pour tout point M, α →MA + β →MB = …",c:["α + β","(α + β) MG","→0","(α + β) →MG"],a:3,exp:"Propriété démontrée en classe"},
    {q:"G est le barycentre de (A ; 2) et (B ; 1). Alors →AG = …",c:["3 →AB","(1/3) →AB","(1/2) →AB","(2/3) →AB"],a:1,exp:"G = (2A + B)/3"},
    {q:"Le barycentre de A(1 ; 2) et B(4 ; 5) affectés des coefficients 2 et 1 est…",c:["(2 ; 3)","(3 ; 4)","(2,5 ; 3,5)","(5 ; 7)"],a:0,exp:"((2 + 4)/3 ; (4 + 5)/3)"},
    {q:"Le barycentre de (A ; 3) et (B ; −1) est…",c:["le milieu de [AB]","le point G tel que →AG = −(1/2) →AB (il existe car 3 + (−1) = 2 ≠ 0)","le point A","il n'existe pas"],a:1,exp:"→AG = (−1/2) →AB"},
    {q:"Le barycentre de (A ; 1) et (B ; −1) n'existe pas car…",c:["les coefficients sont opposés à ceux de G","la somme des coefficients est nulle","aucun point ne convient jamais","A = B"],a:1,exp:"α + β = 0"},
    {q:"L'isobarycentre de trois points non alignés A, B, C est…",c:["le centre du cercle circonscrit","un sommet","l'orthocentre de ABC","le centre de gravité du triangle ABC"],a:3,exp:"Coefficients égaux"},
    {q:"Homogénéité : le barycentre ne change pas lorsqu'on…",c:["ajoute 1 à chaque coefficient","change un coefficient","multiplie tous les coefficients par un même réel non nul","permute les points seulement"],a:2,exp:"Propriété du guide"},
    {q:"Associativité : le barycentre de trois points au moins ne change pas lorsqu'on…",c:["double un coefficient","permute les coefficients","remplace une partie d'entre eux par leur barycentre affecté de la somme de leurs coefficients","supprime un point"],a:2,exp:"Propriété du guide"},
    {q:"Le barycentre permet notamment de démontrer…",c:["des congruences","des limites","l'alignement de points et le concours de droites","des dérivées"],a:2,exp:"Utilisation du barycentre"},
    {q:"Une ligne de niveau k de M ↦ Σ αᵢ MAᵢ² est…",c:["un point","l'ensemble des barycentres","l'ensemble des points M tels que Σ αᵢ MAᵢ² = k","la courbe de sin"],a:2,exp:"Définition du guide"},
    {q:"L'ensemble des points M tels que MA² + MB² = 3 est la ligne de niveau…",c:["1 de M ↦ MA²","0 de M ↦ MA + MB","3 de l'application M ↦ MA² + MB²","3 de M ↦ MA − MB"],a:2,exp:"Exemple du guide"},
    {q:"L'ensemble des points M du plan tels que MA = MB est…",c:["la droite (AB)","le milieu de [AB]","la médiatrice de [AB]","le cercle de diamètre [AB]"],a:2,exp:"Ligne de niveau 0 de MA² − MB²"},
    {q:"L'ensemble des points M tels que MA² + MB² = k (k assez grand) est…",c:["un cercle de centre le milieu de [AB]","une droite","un segment","une parabole"],a:0,exp:"Barycentre de (A ; 1), (B ; 1)"},
  ],
  "1C — Cercle : équation, représentation paramétrique & tangente": [
    {q:"Le cercle de centre Ω(a ; b) et de rayon r a pour équation…",c:["x² + y² = r","(x + a)² + (y + b)² = r²","(x − a)² + (y − b)² = r","(x − a)² + (y − b)² = r²"],a:3,exp:"Équation cartésienne"},
    {q:"Une représentation paramétrique du cercle de centre Ω(a ; b) et de rayon r est…",c:["x = a cos t ; y = b sin t","x = r + a cos t ; y = r + b sin t","x = a + r t ; y = b + r t","x = a + r cos t ; y = b + r sin t"],a:3,exp:"t ∈ ℝ"},
    {q:"Le cercle x² + y² − 4x + 2y − 4 = 0 a pour centre…",c:["(2 ; 1)","(2 ; −1)","(4 ; −2)","(−2 ; 1)"],a:1,exp:"(x − 2)² + (y + 1)² = 9"},
    {q:"Le cercle x² + y² − 4x + 2y − 4 = 0 a pour rayon…",c:["√3","3","4","9"],a:1,exp:"r² = 4 + 1 + 4 = 9"},
    {q:"L'équation x² + y² − 2ax − 2by + c = 0 représente un cercle si…",c:["a = b","a² + b² − c < 0","c > 0","a² + b² − c > 0"],a:3,exp:"r² = a² + b² − c"},
    {q:"La tangente au cercle de centre Ω et de rayon r au point M₀(x₀ ; y₀) a pour équation…",c:["(x − a)² + (y − b)² = 0","x x₀ + y y₀ = 0","(x₀ − a)(x − a) − (y₀ − b)(y − b) = r²","(x₀ − a)(x − a) + (y₀ − b)(y − b) = r²"],a:3,exp:"Équation d'une tangente à un cercle"},
    {q:"La tangente au cercle x² + y² = 25 au point (3 ; 4) a pour équation…",c:["3x + 4y = 25","3x − 4y = 25","x + y = 25","4x + 3y = 25"],a:0,exp:"x₀ x + y₀ y = r²"},
    {q:"La tangente en un point d'un cercle est…",c:["sécante au cercle en deux points","parallèle au rayon","confondue avec le rayon","perpendiculaire au rayon en ce point"],a:3,exp:"Propriété classique"},
    {q:"Le point (0 ; 5) est-il sur le cercle x² + y² = 25 ?",c:["Non","On ne peut pas savoir","Oui","Oui, mais à l'intérieur"],a:2,exp:"0 + 25 = 25"},
    {q:"Représentation paramétrique de x² + y² = 4 :",c:["x = cos t ; y = sin t","x = 2t ; y = 2t","x = 4 cos t ; y = 4 sin t","x = 2 cos t ; y = 2 sin t"],a:3,exp:"Rayon 2 centré à l'origine"},
    {q:"Le cercle de diamètre [AB] avec A(0 ; 0) et B(4 ; 2) a pour équation…",c:["(x − 2)² + (y − 1)² = 5","x² + y² = 5","(x − 4)² + (y − 2)² = 5","(x − 2)² + (y − 1)² = 20"],a:0,exp:"Centre (2 ; 1) ; r² = (16 + 4)/4 = 5"},
  ],
  "1C — Isométries & composition de transformations": [
    {q:"Une isométrie du plan est une transformation qui…",c:["conserve les distances","conserve les angles seulement","conserve les aires seulement","multiplie les distances par k"],a:0,exp:"Définition"},
    {q:"La composée de deux rotations de même centre est…",c:["une rotation de même centre dont l'angle est la somme des angles","l'identité toujours","une homothétie","une translation"],a:0,exp:"Composée au programme"},
    {q:"La composée de deux homothéties de même centre O et de rapports k et k' est…",c:["l'identité toujours","une homothétie de rapport k + k'","une homothétie de centre O et de rapport kk'","une translation"],a:2,exp:"Composée au programme"},
    {q:"La composée d'une homothétie de rapport k (k ≠ 1) et d'une translation est…",c:["une translation","l'identité","une homothétie de rapport k","une rotation"],a:2,exp:"Composée au programme"},
    {q:"La composée d'une rotation et d'une translation est…",c:["une symétrie centrale toujours","une homothétie","une rotation de même angle (ou une translation si l'angle est nul)","une projection"],a:2,exp:"Composée au programme"},
    {q:"La composée de deux translations de vecteurs →u et →v est…",c:["la translation de vecteur →u + →v","l'identité","une rotation","une homothétie"],a:0,exp:"Propriété classique"},
    {q:"La composée de deux rotations de même centre d'angles π/3 et π/6 est…",c:["une translation","la rotation de même centre d'angle π/2","la rotation d'angle π/18","l'identité"],a:1,exp:"π/3 + π/6"},
    {q:"La composée de deux homothéties de même centre de rapports 2 et −3 est…",c:["l'homothétie de rapport −6","une translation","l'homothétie de rapport −1","l'homothétie de rapport 5"],a:0,exp:"2 × (−3)"},
    {q:"Une rotation conserve…",c:["aucune distance","seulement les aires","seulement les alignements","les distances et les angles orientés"],a:3,exp:"Isométrie directe"},
    {q:"Une translation conserve…",c:["seulement les aires","les distances, les angles et le parallélisme","aucune propriété","seulement les distances"],a:1,exp:"Isométrie"},
    {q:"Une homothétie de rapport k (|k| ≠ 1) est-elle une isométrie ?",c:["Oui si k < 0","Oui toujours","Non, elle multiplie les distances par |k|","Oui si k > 0"],a:2,exp:"|k| ≠ 1"},
    {q:"En 1ère D, on ne parle pas…",c:["de rotation","de translation","d'homothétie","de similitude"],a:3,exp:"N.B. du guide"},
  ],
  "1C — Similitudes planes & triangles semblables": [
    {q:"Une similitude de rapport k (k > 0) multiplie les distances par…",c:["k²","1/k","k","2k"],a:2,exp:"Définition"},
    {q:"Une similitude de rapport k multiplie les aires par…",c:["k","k³","2k","k²"],a:3,exp:"Propriété"},
    {q:"Une similitude conserve…",c:["les aires","les longueurs","les périmètres","le rapport de deux distances, l'alignement, le parallélisme et les angles géométriques"],a:3,exp:"Propriétés"},
    {q:"Les similitudes de rapport 1 sont…",c:["les homothéties de rapport 2","les isométries","les projections","les translations seulement"],a:1,exp:"k = 1"},
    {q:"La composée d'une homothétie de rapport k et d'une isométrie est…",c:["une similitude de rapport |k|","une isométrie","une translation","une projection"],a:0,exp:"Composition au programme"},
    {q:"L'image d'un cercle par une similitude de rapport k est…",c:["une ellipse","un cercle de même rayon","une droite","un cercle de rayon k fois plus grand"],a:3,exp:"Effet sur les figures simples"},
    {q:"L'image d'un segment [AB] par une similitude de rapport k est…",c:["une droite","un point","un segment de longueur AB","un segment de longueur k AB"],a:3,exp:"Effet sur les figures simples"},
    {q:"Deux triangles sont semblables si…",c:["leurs aires sont égales","ils ont un sommet commun","leurs angles sont égaux deux à deux (ou leurs côtés sont proportionnels)","leurs périmètres sont égaux"],a:2,exp:"Triangles semblables"},
    {q:"Le rapport de similitude de deux triangles semblables est…",c:["le rapport de leurs périmètres seulement","le rapport des angles","la somme des côtés","le rapport de deux côtés homologues"],a:3,exp:"Rapport des côtés homologues"},
    {q:"Deux triangles semblables de rapport 3 : le rapport de leurs aires est…",c:["9","27","3","6"],a:0,exp:"k²"},
    {q:"Deux triangles ayant les trois côtés respectivement égaux sont…",c:["aplatis","isométriques","rectangles","semblables de rapport 2"],a:1,exp:"Critère d'isométrie"},
    {q:"Deux triangles ayant un angle égal compris entre deux côtés respectivement égaux sont…",c:["semblables de rapport 2","aplatis","isométriques","rectangles"],a:2,exp:"Critère d'isométrie"},
  ],
  "1C — Fonctions associées & transformations de courbes": [
    {q:"La courbe de g(x) = f(x + a) se déduit de celle de f par la translation de vecteur…",c:["(0 ; −a)","(0 ; a)","(−a ; 0)","(a ; 0)"],a:2,exp:"Décalage horizontal opposé au signe de a"},
    {q:"La courbe de g(x) = f(x) + b se déduit de celle de f par la translation de vecteur…",c:["(0 ; −b)","(b ; 0)","(−b ; 0)","(0 ; b)"],a:3,exp:"Décalage vertical"},
    {q:"La courbe de g(x) = f(−x) est symétrique de celle de f par rapport…",c:["à la droite y = x","à l'axe des ordonnées","à l'axe des abscisses","à l'origine"],a:1,exp:"Symétrie orthogonale d'axe (Oy)"},
    {q:"La courbe de g(x) = −f(x) est symétrique de celle de f par rapport…",c:["à l'axe des abscisses","à l'axe des ordonnées","à la droite y = x","à l'origine"],a:0,exp:"Symétrie orthogonale d'axe (Ox)"},
    {q:"La courbe de g(x) = |f(x)| se déduit de celle de f en…",c:["doublant les ordonnées","symétrisant par rapport à (Ox) les parties situées sous l'axe des abscisses","translatant de (0 ; 1)","symétrisant par rapport à (Oy)"],a:1,exp:"Valeur absolue de f"},
    {q:"La courbe de g(x) = (x − 2)² se déduit de celle de x ↦ x² par la translation de vecteur…",c:["(2 ; 0)","(0 ; 2)","(−2 ; 0)","(0 ; −2)"],a:0,exp:"g(x) = f(x − 2)"},
    {q:"La courbe de g(x) = x² + 3 se déduit de celle de x ↦ x² par la translation de vecteur…",c:["(0 ; −3)","(0 ; 3)","(3 ; 0)","(−3 ; 0)"],a:1,exp:"g(x) = f(x) + 3"},
    {q:"La parabole d'équation y = ax² + bx + c admet pour axe de symétrie la droite…",c:["y = −b/(2a)","x = c/a","x = b/(2a)","x = −b/(2a)"],a:3,exp:"Abscisse du sommet"},
    {q:"La courbe d'une fonction homographique x ↦ (ax + b)/(cx + d) admet pour centre de symétrie le point…",c:["(d/c ; a/c)","(0 ; a/c)","(−d/c ; b/d)","(−d/c ; a/c)"],a:3,exp:"Intersection des deux asymptotes"},
    {q:"La courbe de x ↦ 1/(x − 1) + 2 se déduit de celle de x ↦ 1/x par la translation de vecteur…",c:["(2 ; 1)","(1 ; 2)","(−1 ; 2)","(1 ; −2)"],a:1,exp:"Décalage de 1 horizontalement et de 2 verticalement"},
  ],
  "1C — Prop. & Déf.": [
    {q:"Définition : deux droites de l'espace sont orthogonales lorsque…",c:["elles sont parallèles","elles ont un point commun","elles sont sécantes","les parallèles à ces droites passant par un point donné sont perpendiculaires"],a:3,exp:"Droites orthogonales"},
    {q:"Propriété : une droite orthogonale à deux droites sécantes d'un plan est…",c:["orthogonale à ce plan","sécante non orthogonale","parallèle à ce plan","contenue dans ce plan"],a:0,exp:"Droite et plan orthogonaux"},
    {q:"Définition : deux plans sont perpendiculaires lorsque…",c:["leur intersection est un point","ils sont parallèles","l'un contient une droite orthogonale à l'autre","ils sont confondus"],a:2,exp:"Plans perpendiculaires"},
    {q:"Propriété : l'ensemble des points invariants par la projection orthogonale sur un plan (P) est…",c:["un point","l'espace entier","le plan (P)","une droite"],a:2,exp:"Projection orthogonale"},
    {q:"Définition : trois vecteurs sont coplanaires si…",c:["ils ont la même norme","ils sont colinéaires","l'un au moins est combinaison linéaire des deux autres","ils sont orthogonaux"],a:2,exp:"Vecteurs coplanaires"},
    {q:"Définition : une base de l'espace est…",c:["un triplet de vecteurs non coplanaires","un couple de vecteurs non colinéaires","un vecteur non nul","trois points"],a:0,exp:"Base"},
    {q:"Propriété : x₁ + x₂ = … et x₁ x₂ = …",c:["c/a et −b/a","−b et c","−b/a et c/a","b/a et −c/a"],a:2,exp:"Somme et produit des racines"},
    {q:"Définition : deux systèmes sont équivalents si…",c:["même solution particulière","même ensemble de validité et même ensemble de solutions","même nombre d'équations","mêmes coefficients"],a:1,exp:"Systèmes équivalents"},
    {q:"Propriété : card(A ∪ B) = …",c:["card A − card B","card A × card B","card A + card B − card(A ∩ B)","card A + card B + card(A ∩ B)"],a:2,exp:"Dénombrement"},
    {q:"Propriété : Cₙᵖ = …",c:["n!/p!","n!/(p!(n − p)!)","nᵖ/p!","n!/(n − p)!"],a:1,exp:"Combinaisons"},
    {q:"Propriété : Aₙᵖ = …",c:["n!/(p!(n − p)!)","n!","n!/(n − p)!","nᵖ"],a:2,exp:"Arrangements"},
    {q:"Propriété : la composée de deux injections est…",c:["constante","une surjection","une injection","une bijection"],a:2,exp:"Applications"},
    {q:"Propriété : f est bijective si et seulement si…",c:["A = B","f est continue","f est croissante","pour tout y, l'équation f(x) = y a une solution unique"],a:3,exp:"Bijection"},
    {q:"Définition : f est continue en a si…",c:["f(a) = 0","f est définie en a et admet une limite en a","f est croissante en a","f est dérivable en a"],a:1,exp:"Continuité"},
    {q:"Propriété : si f est dérivable en a, alors f est…",c:["constante en a","monotone en a","positive en a","continue en a"],a:3,exp:"Dérivabilité"},
    {q:"Propriété : f est croissante sur un intervalle ouvert K si et seulement si…",c:["f' est négative sur K","f est continue","f' est nulle sur K","f' est positive sur K"],a:3,exp:"Sens de variation"},
    {q:"Propriété : si F est une primitive de f sur K, alors les primitives de f sur K sont…",c:["les fonctions C × F","F seulement","les fonctions F + C","les fonctions F²"],a:2,exp:"Primitives"},
    {q:"Définition : une suite arithmétique de raison r vérifie…",c:["uₙ₊₁ = r uₙ","uₙ₊₁ = r/n","uₙ₊₁ = uₙ²","uₙ₊₁ = uₙ + r"],a:3,exp:"Suites"},
    {q:"Propriété : toute suite croissante et majorée est…",c:["décroissante","nulle","convergente","divergente"],a:2,exp:"Suites"},
    {q:"Propriété : cos²a + sin²a = …",c:["2","0","cos 2a","1"],a:3,exp:"Trigonométrie"},
    {q:"Propriété : cos(a + b) = …",c:["cos a + cos b","sin a cos b + cos a sin b","cos a cos b − sin a sin b","cos a cos b + sin a sin b"],a:2,exp:"Formules d'addition"},
    {q:"Propriété : sin 2a = …",c:["sin a + cos a","2 sin a cos a","sin²a − cos²a","2 sin a"],a:1,exp:"Duplication"},
    {q:"Propriété : G barycentre de (A ; α), (B ; β) ⟹ pour tout M, α →MA + β →MB = …",c:["(α + β) →MG","α + β","→0","(α − β) →MG"],a:0,exp:"Barycentre"},
    {q:"Propriété : l'équation d'un cercle de centre Ω(a ; b) et de rayon r est…",c:["(x − a) + (y − b) = r","x² + y² = r","(x − a)² + (y − b)² = r²","(x + a)² + (y + b)² = r²"],a:2,exp:"Cercle"},
    {q:"Propriété : la composée de deux rotations de même centre est…",c:["l'identité","une translation","une rotation de même centre dont l'angle est la somme des angles","une homothétie"],a:2,exp:"Composées"},
    {q:"Propriété : la composée de deux homothéties de même centre a pour rapport…",c:["la différence des rapports","la somme des rapports","le produit des rapports","le quotient des rapports"],a:2,exp:"Composées"},
    {q:"Propriété : dans une base orthonormée, →u ⋅ →v = …",c:["xy' + yz' + zx'","xx' − yy' − zz'","x + y + z","xx' + yy' + zz'"],a:3,exp:"Produit scalaire"},
    {q:"Propriété : Cov(X, Y) = …",c:["moyenne des xᵢ + moyenne des yᵢ","(moyenne de X)(moyenne de Y)","V(X) V(Y)","(moyenne des xᵢyᵢ) − (moyenne de X)(moyenne de Y)"],a:3,exp:"Covariance"},
    {q:"Propriété : la droite de régression de Y en X a pour pente a = …",c:["Cov(X, Y)/V(X)","V(X)/Cov(X, Y)","σ(X)/σ(Y)","Cov(X, Y)/V(Y)"],a:0,exp:"Ajustement linéaire"},
    {q:"Propriété : une similitude de rapport k multiplie les aires par…",c:["k","k³","k²","2k"],a:2,exp:"Similitude"},
    {q:"Propriété : la distance de M₀ au plan ax + by + cz + d = 0 est…",c:["(ax₀ + by₀ + cz₀ + d)/3","√(a² + b² + c²)","|ax₀ + by₀ + cz₀ + d| / √(a² + b² + c²)","|ax₀ + by₀ + cz₀ + d|"],a:2,exp:"Distance point-plan"},
    {q:"Critère : deux triangles ayant les trois côtés respectivement égaux sont…",c:["rectangles","semblables de rapport 2","aplatis","isométriques"],a:3,exp:"Isométrie de deux triangles"},
  ],
});
