/* Questions de la classe de 1ère D (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "1D — Orthogonalité dans l'espace": [
    {q:"Deux droites de l'espace sont orthogonales lorsque…",c:["elles ont un point commun","les parallèles à ces droites passant par un point donné sont perpendiculaires","elles sont parallèles","elles sont sécantes"],a:1,exp:"Définition du guide"},
    {q:"Si deux droites sont orthogonales, alors toute droite parallèle à l'une est…",c:["sécante à l'autre en un point quelconque","confondue avec l'autre","orthogonale à l'autre","parallèle à l'autre"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Une droite est orthogonale à un plan lorsqu'elle est orthogonale…",c:["à une seule droite de ce plan","à un point de ce plan","à un autre plan","à toute droite de ce plan"],a:3,exp:"Définition du guide"},
    {q:"Si une droite est orthogonale à deux droites sécantes d'un plan, alors elle est…",c:["parallèle à ce plan","contenue dans ce plan","orthogonale à ce plan","sécante non orthogonale à ce plan"],a:2,exp:"Propriété admise"},
    {q:"Par un point A de l'espace, il passe…",c:["aucune droite perpendiculaire à un plan donné","une infinité de droites perpendiculaires à un plan donné","deux droites perpendiculaires à un plan donné","une droite unique perpendiculaire à un plan donné"],a:3,exp:"Propriété admise"},
    {q:"Par un point de l'espace, il passe…",c:["deux plans orthogonaux à une droite donnée","une infinité de plans orthogonaux à une droite donnée","un plan unique orthogonal à une droite donnée","aucun plan orthogonal à une droite donnée"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si deux plans sont parallèles, toute droite orthogonale à l'un est…",c:["parallèle à l'autre","orthogonale à l'autre","contenue dans l'autre","sécante non orthogonale à l'autre"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si deux plans sont perpendiculaires à une même droite, alors ils sont…",c:["perpendiculaires","parallèles","sécants","confondus obligatoirement"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si deux droites sont parallèles, tout plan orthogonal à l'une est…",c:["orthogonal à l'autre","sécant non orthogonal à l'autre","contenu dans l'autre","parallèle à l'autre"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si deux droites sont orthogonales à un même plan, alors elles sont…",c:["non coplanaires","parallèles","orthogonales entre elles","sécantes"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Deux plans sont perpendiculaires lorsque…",c:["ils sont parallèles","ils sont confondus","l'un contient une droite orthogonale à l'autre","leur intersection est un point"],a:2,exp:"Définition du guide"},
    {q:"Deux droites orthogonales de l'espace sont-elles forcément sécantes ?",c:["Non, elles peuvent être non coplanaires","Oui si elles sont parallèles","Oui, toujours","Oui si elles sont coplanaires seulement"],a:0,exp:"Ex. deux arêtes non coplanaires d'un cube"},
    {q:"Dans un cube ABCDEFGH (E au-dessus de A), la droite (AE) est orthogonale…",c:["au plan (ABCD)","au plan (ABFE)","à aucun plan","au plan (AEGC)"],a:0,exp:"(AE) est orthogonale à (AB) et (AD), deux droites sécantes du plan (ABCD)"},
    {q:"Dans le même cube, les plans (ABCD) et (ABFE) sont…",c:["perpendiculaires","confondus","sécants non perpendiculaires","parallèles"],a:0,exp:"(ABFE) contient (AE) orthogonale à (ABCD)"},
  ],
  "1D — Projections orthogonales": [
    {q:"La projection orthogonale sur un plan (P) associe à M le point M'…",c:["du plan (P) le plus éloigné de M","situé sur (P) et tel que MM' est parallèle à (P)","milieu de M et de son symétrique","intersection de (P) et de la droite passant par M et orthogonale à (P)"],a:3,exp:"Définition du guide"},
    {q:"L'ensemble des points invariants par la projection orthogonale sur (P) est…",c:["l'espace entier","le plan (P) lui-même","une droite","un point"],a:1,exp:"Propriété admise"},
    {q:"L'image d'une droite (D) non orthogonale à (P) par la projection sur (P) est…",c:["un segment","un singleton","une droite","un plan"],a:2,exp:"Propriété démontrée en classe"},
    {q:"L'image d'une droite (D) perpendiculaire à (P) par la projection sur (P) est…",c:["un singleton","un plan","une droite","un segment"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si A' et B' sont les projetés de A et B sur (P) avec (AB) non orthogonale à (P), l'image de [AB] est…",c:["le point A'","le point B'","le segment [A'B']","la droite (A'B')"],a:2,exp:"Propriété du guide"},
    {q:"Si (AB) est parallèle à (P), alors A'B' = …",c:["2AB","0","AB/2","AB"],a:3,exp:"Segments égaux"},
    {q:"Si (AB) et (P) ne sont pas parallèles (et (AB) non orthogonale à (P)), alors A'B' … AB",c:["<",">","est indépendant de","="],a:0,exp:"A'B' < AB"},
    {q:"L'image du milieu d'un segment (support non orthogonal à (P)) par la projection sur (P) est…",c:["le point invariant","le milieu du segment image","une extrémité du segment image","un point quelconque"],a:1,exp:"Propriété du guide"},
    {q:"La projection orthogonale sur une droite (D) associe à M le point M'…",c:["milieu de [MO]","de (D) le plus proche de A","intersection de (D) et du plan orthogonal à (D) passant par M","intersection de (D) et d'un plan parallèle à (D)"],a:2,exp:"Définition du guide"},
    {q:"L'ensemble des points invariants par la projection orthogonale sur (D) est…",c:["un point","l'espace entier","la droite (D)","un plan"],a:2,exp:"Propriété démontrée en classe"},
    {q:"L'image par la projection sur (D) d'une droite orthogonale à (D) est…",c:["un plan","la droite (D)","un singleton","une droite parallèle"],a:2,exp:"Propriété démontrée en classe"},
    {q:"L'image par la projection sur (D) d'une droite non orthogonale à (D) est…",c:["un plan","la droite (D)","un singleton","une droite parallèle à (D)"],a:1,exp:"Propriété démontrée en classe"},
  ],
  "1D — Vecteurs de l'espace": [
    {q:"Un vecteur non nul de l'espace est caractérisé par…",c:["sa direction, son sens et sa longueur","son origine seulement","sa longueur seulement","son sens seulement"],a:0,exp:"Définition"},
    {q:"Pour tout point O et tout vecteur →u, il existe…",c:["un unique point M tel que →OM = →u","deux points M","aucun point M","une infinité de points M"],a:0,exp:"Propriété admise"},
    {q:"Deux vecteurs sont colinéaires lorsque…",c:["ils ont même sens seulement","l'un d'eux est nul ou lorsqu'ils ont la même direction","ils sont orthogonaux","ils ont la même longueur"],a:1,exp:"Définition du guide"},
    {q:"Trois vecteurs sont coplanaires si…",c:["l'un au moins est une combinaison linéaire des deux autres","ils sont deux à deux colinéaires","ils sont orthogonaux","ils ont la même norme"],a:0,exp:"Définition du guide"},
    {q:"Pour A ≠ B, un point M appartient à la droite (AB) si et seulement si…",c:["il existe un réel x tel que →AM = x →AB","AM = AB","→AM ⋅ →AB = 0","→AM = →AB seulement"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Pour A, B, C non alignés, M appartient au plan (ABC) si et seulement si…",c:["→AM = →AB + →AC","il existe des réels x et y tels que →AM = x →AB + y →AC","AM = AB + AC","→AM ⋅ →AB = 0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Une base de l'ensemble des vecteurs de l'espace est…",c:["un vecteur non nul","un triplet de vecteurs colinéaires","un triplet de vecteurs non coplanaires","un couple de vecteurs non colinéaires"],a:2,exp:"Définition du guide"},
    {q:"Un repère de l'espace est…",c:["un triplet de vecteurs quelconques","un plan muni d'une origine","un quadruplet (O, I, J, K) de points non coplanaires","un couple de points"],a:2,exp:"Définition du guide"},
    {q:"Dans un repère (O, I, J, K), tout point M admet…",c:["aucun triplet de coordonnées","un unique triplet de coordonnées (x ; y ; z)","plusieurs triplets de coordonnées","un couple de coordonnées"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Dans un cube ABCDEFGH (E au-dessus de A), →AB + →AD + →AE = …",c:["→AC","→AH","→AG","→AF"],a:2,exp:"Diagonale du cube"},
    {q:"Dans un parallélogramme ABCD, →AB + →AD = …",c:["→CA","→BD","→DB","→AC"],a:3,exp:"Règle du parallélogramme"},
    {q:"Les vecteurs →u(1 ; 2 ; 3) et →v(2 ; 4 ; 6) sont…",c:["colinéaires","orthogonaux","non coplanaires","égaux"],a:0,exp:"→v = 2 →u"},
    {q:"Les vecteurs →i, →j et →i + →j sont…",c:["orthogonaux deux à deux","colinéaires","non coplanaires","coplanaires"],a:3,exp:"→i + →j est combinaison linéaire de →i et →j"},
    {q:"Les coordonnées de →AB avec A(1 ; 2 ; 3) et B(4 ; 0 ; 5) sont…",c:["(−3 ; 2 ; −2)","(3 ; 2 ; 2)","(3 ; −2 ; 2)","(5 ; 2 ; 8)"],a:2,exp:"(xB − xA ; yB − yA ; zB − zA)"},
    {q:"Le milieu de [AB] pour A(1 ; 2 ; 3) et B(3 ; 4 ; 7) est…",c:["(2 ; 3 ; 5)","(1 ; 1 ; 2)","(4 ; 6 ; 10)","(2 ; 3 ; 4)"],a:0,exp:"Moyennes des coordonnées"},
  ],
  "1D — Équations du second degré": [
    {q:"Le discriminant de ax² + bx + c est Δ = …",c:["b² − 4ac","b − 4ac","b² + 4ac","4ac − b²"],a:0,exp:"Définition"},
    {q:"Si Δ > 0, l'équation ax² + bx + c = 0 admet…",c:["aucune solution réelle","une solution double","une infinité de solutions","deux solutions réelles distinctes"],a:3,exp:"Résolution par le discriminant"},
    {q:"Si Δ = 0, l'équation admet…",c:["deux solutions distinctes","deux solutions opposées","une solution double x = −b/(2a)","aucune solution"],a:2,exp:"Résolution par le discriminant"},
    {q:"Si Δ < 0, l'équation n'admet…",c:["que des solutions entières","que deux solutions","aucune solution réelle","qu'une solution"],a:2,exp:"Résolution par le discriminant"},
    {q:"Les solutions de 2x² − 3x − 2 = 0 sont…",c:["3 et −1","−2 et 1/2","2 et −1/2","1 et −2"],a:2,exp:"Δ = 9 + 16 = 25 ; x = (3 ± 5)/4"},
    {q:"Les solutions de x² − 6x + 9 = 0 sont…",c:["x = 3 (solution double)","x = 6","x = 3 et x = −3","aucune solution réelle"],a:0,exp:"Δ = 0"},
    {q:"Si x₁ et x₂ sont les solutions de ax² + bx + c = 0, alors x₁ + x₂ = … et x₁ x₂ = …",c:["b/a et −c/a","−b/a et c/a","−b et c","c/a et −b/a"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Deux nombres de somme 7 et de produit 12 sont…",c:["1 et 6","2 et 5","3 et 4","−3 et −4"],a:2,exp:"Racines de x² − 7x + 12 = 0"},
    {q:"Les solutions de x² − 5x + 6 = 0 sont de signes…",c:["impossibles à déterminer","identiques (produit 6 > 0 et somme 5 > 0 : deux positives)","opposés","contraires"],a:1,exp:"c/a > 0 et −b/a > 0"},
    {q:"Si c/a < 0, les solutions de ax² + bx + c = 0 sont…",c:["non réelles","de même signe","de signes contraires","toutes deux nulles"],a:2,exp:"Le produit est négatif"},
    {q:"Résoudre x⁴ − 5x² + 4 = 0 avec X = x².",c:["x = ±4","x = ±1 ou x = ±2","x = 1 ou x = 4","x = ±√5"],a:1,exp:"X² − 5X + 4 = 0 donne X = 1 ou X = 4"},
    {q:"Résoudre l'équation irrationnelle √(x + 2) = x.",c:["x = 0","x = −1","x = 2 ou x = −1","x = 2"],a:3,exp:"x + 2 = x² avec x ≥ 0 : on rejette −1"},
    {q:"Pour résoudre une équation irrationnelle, il faut toujours…",c:["vérifier les solutions trouvées dans l'équation de départ","passer au logarithme","dériver les deux membres","prendre l'inverse"],a:0,exp:"Élever au carré peut ajouter de fausses solutions"},
    {q:"Le signe du trinôme ax² + bx + c avec Δ < 0 est celui de…",c:["c seulement","a sur tout ℝ","b sur ℝ","−a sur ℝ"],a:1,exp:"Pas de racine réelle"},
    {q:"Le signe de x² + x + 1 sur ℝ est…",c:["positif puis négatif","toujours négatif","nul en deux points","toujours strictement positif"],a:3,exp:"Δ = −3 < 0 et a = 1 > 0"},
    {q:"La forme canonique de ax² + bx + c est…",c:["a(x + b)² + c","(x + b/(2a))² + c","a(x − b/(2a))² + Δ","a[(x + b/(2a))² − Δ/(4a²)]"],a:3,exp:"Origine du discriminant"},
  ],
  "1D — Inéquations du second degré & systèmes linéaires": [
    {q:"x² − 3x + 2 ≤ 0 a pour ensemble de solutions…",c:["[1 ; 2]","ℝ","]−∞ ; 1] ∪ [2 ; +∞[","]1 ; 2["],a:0,exp:"Racines 1 et 2 ; trinôme négatif entre les racines"},
    {q:"x² − 4 > 0 a pour ensemble de solutions…",c:["]−2 ; 2[","]2 ; +∞[","ℝ","]−∞ ; −2[ ∪ ]2 ; +∞["],a:3,exp:"Positif à l'extérieur des racines"},
    {q:"Un trinôme ax² + bx + c (a > 0, Δ > 0) est négatif…",c:["nulle part","entre ses racines","partout","à l'extérieur de ses racines"],a:1,exp:"Signe de a à l'extérieur, de −a entre les racines"},
    {q:"Pour un trinôme de racines x₁ < x₂ et a > 0, le nombre α vérifiant α < x₁ < x₂ est tel que…",c:["f(α) > 0","f(α) < 0","on ne peut pas conclure","f(α) = 0"],a:0,exp:"À l'extérieur des racines, le trinôme est du signe de a"},
    {q:"Deux systèmes d'équations sont équivalents si…",c:["ils ont la même solution particulière","ils ont le même ensemble de validité et le même ensemble de solutions","ils ont le même nombre d'équations","ils ont les mêmes coefficients"],a:1,exp:"Définition du guide"},
    {q:"La méthode du pivot de Gauss permet de…",c:["transformer un système en un système équivalent triangulaire","calculer un discriminant","tracer une droite","résoudre une équation du second degré"],a:0,exp:"Système linéaire à trois inconnues"},
    {q:"Résoudre x + y + z = 6 ; y + z = 5 ; z = 3.",c:["(1 ; 3 ; 2)","(2 ; 1 ; 3)","(1 ; 2 ; 3)","(3 ; 2 ; 1)"],a:2,exp:"On remonte : z = 3, y = 2, x = 1"},
    {q:"Résoudre le système x + y + z = 3 ; x − y + z = 1 ; x + y − z = 1.",c:["(2 ; 0 ; 1)","(1 ; 1 ; 1)","(1 ; 2 ; 0)","(0 ; 1 ; 2)"],a:1,exp:"Par différences : y = 1 ; z = 1 ; x = 1"},
    {q:"Pour résoudre un système avec 1/x, 1/y, 1/z, on peut…",c:["poser x = y = z","poser X = 1/x, Y = 1/y, Z = 1/z","élever au carré","supprimer une équation"],a:1,exp:"Changement d'inconnues"},
    {q:"Un problème de programmation linéaire à deux variables se résout…",c:["en cherchant l'optimum d'une fonction linéaire sur le polygone des contraintes","par le pivot de Gauss seulement","en calculant un discriminant","par un dénombrement"],a:0,exp:"Résolution graphique"},
    {q:"L'optimum d'une fonction linéaire sur un polygone convexe est atteint en…",c:["un point intérieur quelconque","un sommet du polygone","aucun point","le centre du polygone"],a:1,exp:"Principe de la programmation linéaire"},
    {q:"Les systèmes linéaires étudiés en 1ère D sont…",c:["toujours avec paramètre","sans paramètre","seulement homogènes","seulement à deux inconnues"],a:1,exp:"N.B. du guide"},
  ],
  "1D — Statistique : séries groupées en classes": [
    {q:"Regrouper en classes, c'est répartir les valeurs en…",c:["classes d'un seul élément","valeurs isolées","intervalles qui se chevauchent","intervalles disjoints deux à deux"],a:3,exp:"Définition du guide"},
    {q:"La densité d'une classe est…",c:["le quotient de l'effectif par l'amplitude de la classe","l'effectif seulement","le produit de l'effectif par l'amplitude","la fréquence seulement"],a:0,exp:"Définition du guide"},
    {q:"La série statistique des centres est…",c:["la série des amplitudes","la série discrète dont les modalités sont les centres des classes","la série des effectifs","la série des bornes"],a:1,exp:"Définition du guide"},
    {q:"L'histogramme est adapté à…",c:["un seul individu","une série double","une série qualitative","une série groupée en classes"],a:3,exp:"Mode de représentation le plus adapté"},
    {q:"Le polygone des effectifs d'une série groupée s'obtient…",c:["en joignant les médianes","en joignant les bornes inférieures","en traçant le polygone des effectifs de la série des centres","en traçant un cercle"],a:2,exp:"Indication du guide"},
    {q:"Les effectifs cumulés croissants s'obtiennent en…",c:["divisant par l'effectif total","soustrayant les effectifs","cumulant les effectifs dans l'ordre croissant des classes","multipliant les effectifs"],a:2,exp:"Définition"},
    {q:"La classe modale est…",c:["la classe centrale","toute classe d'effectif maximal","toute classe de densité maximale","la première classe"],a:1,exp:"Définition du guide"},
    {q:"Le mode d'une série groupée est…",c:["le centre de toute classe de densité maximale","la moyenne","le centre de toute classe d'effectif maximal","la médiane"],a:0,exp:"Définition du guide"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : l'effectif total est…",c:["100","20","3","30"],a:1,exp:"4 + 6 + 10"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la moyenne est…",c:["15","18","17","20"],a:1,exp:"(5×4 + 15×6 + 25×10)/20 = 360/20"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la classe modale est…",c:["[20 ; 30[","[10 ; 20[","il n'y en a pas","[0 ; 10["],a:0,exp:"Effectif maximal : 10"},
    {q:"Classes [0 ; 10[ (4), [10 ; 20[ (6), [20 ; 30[ (10) : la densité de la classe [0 ; 10[ est…",c:["10","0,04","4","0,4"],a:3,exp:"4/10"},
    {q:"La moyenne, la variance et l'écart-type d'une série groupée se calculent à l'aide…",c:["des amplitudes","des bornes inférieures","de la série des centres","de la médiane"],a:2,exp:"N.B. du guide"},
    {q:"L'écart-type est…",c:["la médiane des écarts","la moyenne des écarts","le carré de la variance","la racine carrée de la variance"],a:3,exp:"Paramètre de dispersion"},
  ],
  "1D — Dénombrement": [
    {q:"card(A ∪ B) = …",c:["card A − card B","card A + card B + card(A ∩ B)","card A + card B − card(A ∩ B)","card A × card B"],a:2,exp:"Propriété démontrée en classe"},
    {q:"card(A × B) = …",c:["card A − card B","(card A)ᵇ","card A × card B","card A + card B"],a:2,exp:"Propriété admise"},
    {q:"Le nombre de p-listes d'un ensemble à n éléments est…",c:["nᵖ","pⁿ","n × p","n!/p!"],a:0,exp:"card Eᵖ = nᵖ"},
    {q:"Le nombre de codes à 4 chiffres (chiffres de 0 à 9, répétitions autorisées) est…",c:["40","5 040","10 × 4","10 000"],a:3,exp:"10⁴"},
    {q:"Le nombre d'applications d'un ensemble à p éléments dans un ensemble à n éléments est…",c:["nᵖ","pⁿ","n!","n × p"],a:0,exp:"Propriété du guide"},
    {q:"Le nombre de p-arrangements de n éléments est Aₙᵖ = …",c:["n!/p!","nᵖ","n(n − 1)…(n − p + 1)","n!"],a:2,exp:"Propriété du guide"},
    {q:"A₅² = …",c:["20","10","25","120"],a:0,exp:"5 × 4"},
    {q:"Le nombre d'injections d'un ensemble de p éléments dans un ensemble de n éléments est…",c:["n!","Aₙᵖ","Cₙᵖ","nᵖ"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Le nombre de permutations de n éléments est…",c:["n²","nⁿ","2n","n!"],a:3,exp:"Propriété démontrée en classe"},
    {q:"5! = …",c:["120","720","25","60"],a:0,exp:"5 × 4 × 3 × 2 × 1"},
    {q:"Par convention, 0! = …",c:["non défini","1","−1","0"],a:1,exp:"Convention du guide"},
    {q:"Le nombre de bijections d'un ensemble à n éléments sur un ensemble de même cardinal est…",c:["2n","nⁿ","n²","n!"],a:3,exp:"Propriété du guide"},
    {q:"Le nombre de p-combinaisons de n éléments est Cₙᵖ = …",c:["nᵖ/p!","n!/p!","n!/(n − p)!","n!/(p!(n − p)!)"],a:3,exp:"Propriété du guide"},
    {q:"C₅² = …",c:["20","5","10","25"],a:2,exp:"5!/(2! 3!)"},
    {q:"C₆³ = …",c:["20","120","18","6"],a:0,exp:"6!/(3! 3!)"},
    {q:"Cₙ⁰ = … et Cₙⁿ = …",c:["1 et n","0 et 1","n et n","1 et 1"],a:3,exp:"Propriétés démontrées en classe"},
    {q:"Cₙᵖ = …",c:["Cₚⁿ","Cₙⁿ⁻ᵖ","Cₙᵖ⁺¹","Aₙᵖ"],a:1,exp:"Symétrie des combinaisons"},
    {q:"Relation de Pascal : Cₙᵖ = …",c:["Cₙᵖ⁻¹ + Cₙᵖ⁺¹","Cₙ₊₁ᵖ − Cₙᵖ","Cₙ₋₁ᵖ × Cₙ₋₁ᵖ⁻¹","Cₙ₋₁ᵖ⁻¹ + Cₙ₋₁ᵖ"],a:3,exp:"Construction du triangle de Pascal"},
    {q:"Le nombre de façons de choisir 3 personnes parmi 8 est…",c:["336","24","56","8³"],a:2,exp:"C₈³ = 56"},
    {q:"Le nombre de façons de placer 4 personnes différentes sur 6 sièges numérotés est…",c:["24","15","1 296","360"],a:3,exp:"A₆⁴ = 6 × 5 × 4 × 3"},
    {q:"Le développement de (a + b)³ selon la formule du binôme est…",c:["a³ + b³","a³ + 2a²b + 2ab² + b³","a³ + 3ab + b³","a³ + 3a²b + 3ab² + b³"],a:3,exp:"Coefficients 1, 3, 3, 1 (ligne du triangle de Pascal)"},
  ],
  "1D — Applications & fonctions numériques": [
    {q:"Toute application est…",c:["une injection","une fonction (la réciproque est fausse)","une bijection","une fonction croissante"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La restriction d'une fonction f à une partie E de son ensemble de définition est…",c:["la fonction g de E dans B définie par g(x) = f(x)","une fonction constante","la réciproque de f","f définie sur un ensemble plus grand"],a:0,exp:"Définition du guide"},
    {q:"Un prolongement de f est…",c:["une fonction qui coïncide avec f sur l'ensemble de définition de f et qui est définie sur un ensemble plus grand","une primitive de f","la réciproque de f","une restriction de f"],a:0,exp:"Définition"},
    {q:"Une fonction f est bornée sur E si…",c:["elle est positive","elle est continue","elle est à la fois majorée et minorée sur E","elle est croissante"],a:2,exp:"Définition du guide"},
    {q:"La composée de deux injections est…",c:["une surjection","une application constante","une injection","une bijection"],a:2,exp:"Propriété admise"},
    {q:"La composée de deux surjections est…",c:["une application non définie","une injection","une application constante","une surjection"],a:3,exp:"Propriété admise"},
    {q:"La composée f∘g de deux bijections f et g est une bijection et (f∘g)⁻¹ = …",c:["g ∘ f","f⁻¹ ∘ g⁻¹","g⁻¹ ∘ f⁻¹","f ∘ g"],a:2,exp:"Propriété admise"},
    {q:"La composition des applications est…",c:["toujours bijective","toujours nulle","commutative","associative"],a:3,exp:"Propriété admise"},
    {q:"f est bijective de A vers B si et seulement si…",c:["f est croissante","f est continue","pour tout y de B, l'équation f(x) = y admet une solution unique dans A","A = B"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si f est une bijection de A sur B, alors f⁻¹ ∘ f = …",c:["Id_B","f⁻¹","Id_A","f"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Dans un repère orthonormé, les courbes de deux bijections réciproques sont symétriques par rapport à…",c:["la droite y = x (première bissectrice)","l'axe des abscisses","l'axe des ordonnées","l'origine"],a:0,exp:"Propriété démontrée en classe"},
    {q:"L'image directe d'une partie A par f est…",c:["la restriction de f","l'ensemble des images des éléments de A","la réciproque de f","l'ensemble des antécédents d'un ensemble"],a:1,exp:"Définition du guide"},
    {q:"L'image réciproque d'une partie B par f est…",c:["la réciproque de f","l'ensemble des éléments dont l'image appartient à B","l'ensemble des images de B","f(B)"],a:1,exp:"Définition du guide (f n'est pas forcément bijective)"},
    {q:"Un minorant de f sur E est un réel m tel que…",c:["m ≥ f(x) pour tout x de E","m ≤ f(x) pour tout x de E","m = f(0)","m > f(x) pour un x de E"],a:1,exp:"Définition"},
    {q:"Pour deux fonctions f et g, « f < g sur E » signifie que…",c:["f(x) = g(x) pour tout x de E","f(x) < g(x) pour un seul x","f(x) < g(x) pour tout x de E","f(E) < g(E)"],a:2,exp:"Comparaison de fonctions"},
  ],
  "1D — Limites & continuité": [
    {q:"Si f est définie en a et admet une limite en a, alors cette limite est égale à…",c:["f(a)","a","+∞","0"],a:0,exp:"Propriété admise"},
    {q:"Une fonction est continue en a lorsqu'elle est…",c:["seulement définie en a","seulement dérivable en a","définie en a et admet une limite en a","croissante en a"],a:2,exp:"Définition du guide"},
    {q:"Les fonctions polynômes sont continues…",c:["seulement en 0","sur [0 ; 1]","sur ]0 ; +∞[","sur ℝ"],a:3,exp:"Somme et produit de fonctions élémentaires"},
    {q:"Une fonction rationnelle est continue…",c:["en tout point de son ensemble de définition","sur ℝ toujours","seulement en 0","seulement sur [0 ; 1]"],a:0,exp:"Quotient de fonctions élémentaires"},
    {q:"La somme de deux fonctions continues en a est…",c:["nulle","constante","continue en a","discontinue en a"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si lim f = l et lim g = l' en a, alors lim (f × g) = …",c:["l/l'","l + l'","l − l'","l × l'"],a:3,exp:"Propriété admise"},
    {q:"Si f ≤ g sur I, lim f = l et lim g = l' en a, alors…",c:["l ≥ l'","l = l'","l < l'","l ≤ l'"],a:3,exp:"Propriété admise"},
    {q:"Théorème des gendarmes : f ≤ g ≤ h avec f et h de même limite l en a ⟹",c:["g est continue","g n'a pas de limite","g est constante","g admet la limite l en a"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si f n'est pas définie en a, f admet une limite l en a si et seulement si…",c:["f(a) = l","elle est croissante","elle admet en a une limite à gauche et une limite à droite égales à l","elle admet une limite à gauche seulement"],a:2,exp:"Propriété admise"},
    {q:"La fonction valeur absolue est continue…",c:["en tout élément de ℝ","seulement en 0","sur ]0 ; +∞[ seulement","nulle part"],a:0,exp:"Propriété démontrée en distinguant x < 0, x = 0 et x > 0"},
    {q:"La limite de (x² − 1)/(x − 1) en 1 est…",c:["1","0","+∞","2"],a:3,exp:"(x − 1)(x + 1)/(x − 1) = x + 1"},
    {q:"La limite de 1/(x − 1)² en 1 est…",c:["−∞","+∞","0","1"],a:1,exp:"Le dénominateur tend vers 0 par valeurs positives"},
    {q:"La limite de (x + 1)/(x − 1) quand x tend vers 1 par valeurs inférieures est…",c:["0","+∞","−∞","2"],a:2,exp:"Numérateur proche de 2 ; dénominateur tend vers 0 par valeurs négatives"},
    {q:"Lorsque f a une limite infinie en a, la droite x = a est…",c:["une asymptote verticale à la courbe de f","une tangente horizontale","une asymptote horizontale","un axe de symétrie"],a:0,exp:"Interprétation géométrique"},
    {q:"Si f a pour limite b en +∞, la droite y = b est…",c:["une asymptote horizontale à la courbe de f","une asymptote verticale","un axe de symétrie","une tangente verticale"],a:0,exp:"Interprétation géométrique"},
    {q:"La limite d'une fonction polynôme à l'infini est celle…",c:["de son monôme de plus haut degré","de son terme constant","de son coefficient dominant seulement","de sa dérivée"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"La limite d'une fonction rationnelle à l'infini est celle…",c:["du quotient des monômes de plus haut degré","de son numérateur","du quotient des termes constants","de son dénominateur"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"La notion de prolongement par continuité est en 1ère D…",c:["hors programme","obligatoire","démontrée","au programme"],a:0,exp:"N.B. du guide"},
  ],
  "1D — Dérivation & primitives": [
    {q:"Le taux de variation de f entre x₀ et x est…",c:["f(x) − f(x₀)","(x − x₀)/(f(x) − f(x₀))","(f(x) − f(x₀))/(x − x₀)","f(x)/f(x₀)"],a:2,exp:"Définition"},
    {q:"Le nombre dérivé de f en x₀ est…",c:["le taux de variation en 0","f(x₀)","la limite du taux de variation en x₀","f(x₀)²"],a:2,exp:"Définition"},
    {q:"Si f est dérivable en un point, alors f est…",c:["continue en ce point","constante","monotone","discontinue en ce point"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La réciproque de « dérivable ⟹ continue » est…",c:["vraie pour les polynômes seulement","fausse : la valeur absolue est continue en 0 sans y être dérivable","vraie sur ℝ","vraie"],a:1,exp:"Exemple du guide"},
    {q:"Une équation de la tangente au point d'abscisse x₀ est…",c:["y = x₀ f'(x)","y = f(x₀)(x − x₀) + f'(x₀)","y = f'(x₀)","y = f'(x₀)(x − x₀) + f(x₀)"],a:3,exp:"Formule de la tangente"},
    {q:"La dérivée d'un produit uv est…",c:["u'v − uv'","u'v'","u'v + uv'","u v"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La dérivée d'un quotient u/v est…",c:["(u'v − uv')/v²","(u' − v')/v²","u'/v'","(u'v + uv')/v²"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si f(x) = g(x + α), alors f'(a) = …",c:["α g'(a)","g'(a)","g'(a + α)","g(a + α)"],a:2,exp:"Propriété admise"},
    {q:"f est croissante sur un intervalle ouvert K si et seulement si…",c:["f' est négative sur K","f' est nulle sur K","f est continue","f' est positive sur K"],a:3,exp:"Propriété admise"},
    {q:"Si f' s'annule et change de signe en x₀, alors f admet en x₀…",c:["une asymptote","un point anguleux","aucun comportement particulier","un extremum relatif"],a:3,exp:"Propriété admise"},
    {q:"Toute fonction continue sur un intervalle K admet…",c:["une dérivée sur K","un minimum strict","une primitive sur K","une limite infinie"],a:2,exp:"Propriété admise"},
    {q:"Si F est une primitive de f sur K, les primitives de f sur K sont…",c:["uniquement F","les fonctions F + C, C constante","les fonctions C × F","les fonctions F²"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Il existe une unique primitive de f sur K qui prend la valeur y₀ en x₀ :",c:["vrai seulement si y₀ = 0","faux, il n'en existe aucune","faux, il en existe une infinité","vrai (f continue sur K)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une primitive de x ↦ x² est…",c:["x²/2","x³","x³/3","2x"],a:2,exp:"Primitive usuelle"},
    {q:"La primitive de x ↦ 3x² + 2x qui s'annule en 0 est…",c:["3x³ + 2x²","x³ + x² + 1","6x + 2","x³ + x²"],a:3,exp:"F(x) = x³ + x² + C avec C = 0"},
    {q:"Une primitive de x ↦ cos x est…",c:["sin x","−sin x","−cos x","cos x"],a:0,exp:"(sin x)' = cos x"},
    {q:"Une primitive de x ↦ 1/√x sur ]0 ; +∞[ est…",c:["1/(2√x)","−1/x","√x/2","2√x"],a:3,exp:"(2√x)' = 1/√x"},
    {q:"Si F et G sont des primitives de f et g, alors une primitive de af + bg est…",c:["a + b","aG + bF","F × G","aF + bG"],a:3,exp:"Linéarité des primitives"},
  ],
  "1D — Suites numériques": [
    {q:"Une suite numérique est…",c:["une fonction de ℕ (ou d'une partie de ℕ) vers ℝ","un nombre","une fonction de ℝ vers ℝ","une équation"],a:0,exp:"Définition du guide"},
    {q:"Une suite (uₙ) est majorée si…",c:["uₙ est positive","il existe M tel que uₙ ≤ M pour tout n","il existe m tel que uₙ ≥ m","uₙ est croissante"],a:1,exp:"Définition du guide"},
    {q:"Une suite est bornée si…",c:["elle est positive","elle est à la fois majorée et minorée","elle est convergente seulement","elle est croissante"],a:1,exp:"Définition du guide"},
    {q:"Une suite arithmétique vérifie…",c:["uₙ₊₁ = uₙ/n","uₙ₊₁ = uₙ + r","uₙ₊₁ = q uₙ","uₙ₊₁ = uₙ²"],a:1,exp:"Définition du guide"},
    {q:"Le terme général d'une suite arithmétique de premier terme u_k et de raison r est…",c:["uₙ = u_k × rⁿ⁻ᵏ","uₙ = n r","uₙ = u_k + (n − k) r","uₙ = u_k + r"],a:2,exp:"Formule du guide"},
    {q:"Suite arithmétique avec u₀ = 3 et r = 2 : u₁₀ = …",c:["33","13","20","23"],a:3,exp:"3 + 10 × 2"},
    {q:"Suite arithmétique avec u₀ = 3 et r = 2 : la somme u₀ + u₁ + … + u₉ vaut…",c:["60","66","100","120"],a:3,exp:"10 × (3 + 21)/2"},
    {q:"Une suite géométrique vérifie…",c:["uₙ₊₁ = q uₙ","uₙ₊₁ = uₙ + r","uₙ₊₁ = uₙ/n","uₙ₊₁ = uₙ + q"],a:0,exp:"Définition du guide"},
    {q:"Suite géométrique avec u₀ = 2 et q = 3 : u₄ = …",c:["162","486","54","24"],a:0,exp:"2 × 3⁴"},
    {q:"Pour q ≠ 1, la somme de p termes consécutifs à partir de u_k vaut…",c:["u_k (1 − qᵖ)/(1 − q)","p u_k","u_k qᵖ","u_k (1 − q)/(1 − qᵖ)"],a:0,exp:"Formule du guide"},
    {q:"Suite géométrique avec u₀ = 2 et q = 3 : u₀ + u₁ + u₂ + u₃ + u₄ = …",c:["162","80","486","242"],a:3,exp:"2(1 − 3⁵)/(1 − 3)"},
    {q:"Une suite est croissante si…",c:["uₙ₊₁ ≥ uₙ pour tout n","uₙ > 0","uₙ₊₁ ≤ uₙ pour tout n","uₙ = 0"],a:0,exp:"Définition"},
    {q:"Une suite monotone est…",c:["croissante ou décroissante","à la fois croissante et décroissante","bornée","convergente"],a:0,exp:"Définition du guide"},
    {q:"Une suite est convergente si…",c:["elle est positive","elle est bornée","elle a une limite finie","elle est croissante"],a:2,exp:"Définition du guide"},
    {q:"Toute suite décroissante et minorée est…",c:["convergente","divergente","constante","nulle"],a:0,exp:"Propriété admise"},
    {q:"Toute suite croissante et majorée est…",c:["divergente","décroissante","nulle","convergente"],a:3,exp:"Propriété admise"},
    {q:"Si uₙ = f(n) et si f a pour limite l en +∞, alors (uₙ)…",c:["est constante","converge vers l","diverge","est croissante"],a:1,exp:"Propriété admise"},
    {q:"Si f n'a pas de limite en +∞, peut-on conclure sur la convergence de uₙ = f(n) ?",c:["Oui, elle diverge","Oui, elle est croissante","Non, il faut étudier la suite séparément","Oui, elle converge"],a:2,exp:"Remarque du guide"},
    {q:"La suite uₙ = (3n + 1)/(n + 2) converge vers…",c:["3","+∞","0","1/2"],a:0,exp:"3n/n"},
  ],
  "1D — Angles orientés & fonctions circulaires": [
    {q:"Une mesure d'un angle orienté de mesure principale α est de la forme…",c:["kα","α/2 + kπ","α + 2kπ (k ∈ ℤ)","α + kπ (k ∈ ℤ)"],a:2,exp:"Définition du guide"},
    {q:"Les mesures de l'angle orienté nul sont…",c:["2kπ","π/2 + 2kπ","π + 2kπ","kπ"],a:0,exp:"Propriété admise"},
    {q:"Les mesures de l'angle orienté plat sont…",c:["2kπ","kπ","π/2 + 2kπ","π + 2kπ"],a:3,exp:"Propriété admise"},
    {q:"Les mesures d'un angle orienté droit (de vecteurs orthogonaux) sont de la forme…",c:["π/2 + 2kπ","2kπ","π/2 + kπ","π + 2kπ"],a:2,exp:"Propriété admise"},
    {q:"La mesure principale d'un angle de mesure 7π/3 est…",c:["4π/3","−π/3","7π/3","π/3"],a:3,exp:"7π/3 − 2π"},
    {q:"La mesure principale d'un angle de mesure 13π/4 est…",c:["13π/4","3π/4","−3π/4","π/4"],a:2,exp:"13π/4 − 2π = 5π/4, puis 5π/4 − 2π = −3π/4"},
    {q:"Relation de Chasles : (→u, →w) = …",c:["(→u, →v) − (→v, →w)","(→v, →u) + (→w, →v)","(→u, →v) + (→v, →w)","(→u, →v) × (→v, →w)"],a:2,exp:"À 2π près"},
    {q:"Pour tout réel a, cos²a + sin²a = …",c:["cos 2a","1","2","0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Pour tout réel a, on a…",c:["sin a ≥ 1","cos a + sin a = 1","cos a ≥ 1","−1 ≤ cos a ≤ 1 et −1 ≤ sin a ≤ 1"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si cos a ≠ 0, tan a = …",c:["1/sin a","sin a × cos a","sin a / cos a","cos a / sin a"],a:2,exp:"Définition"},
    {q:"Si cos a ≠ 0, 1 + tan²a = …",c:["tan 2a","cos²a","1/sin²a","1/cos²a"],a:3,exp:"Propriété démontrée en classe"},
    {q:"La période de cos et de sin est…",c:["4π","π/2","π","2π"],a:3,exp:"cos(a + 2kπ) = cos a"},
    {q:"La période de tan est…",c:["2π","π","4π","π/2"],a:1,exp:"tan(a + kπ) = tan a"},
    {q:"La fonction cos est…",c:["impaire","paire","ni paire ni impaire","constante"],a:1,exp:"cos(−x) = cos x"},
    {q:"La fonction sin est…",c:["impaire","paire","ni paire ni impaire","constante"],a:0,exp:"sin(−x) = −sin x"},
    {q:"La limite de (sin x)/x en 0 est…",c:["1","1/2","+∞","0"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"La limite de (1 − cos x)/x² en 0 est…",c:["1/2","2","1","0"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"Pour les petites valeurs de |x|, sin x est approximativement égal à…",c:["1 − x","1","x","x²"],a:2,exp:"Limite de sin x / x = 1"},
  ],
  "1D — Formules trigonométriques & équations": [
    {q:"cos(a + b) = …",c:["sin a cos b + cos a sin b","cos a cos b − sin a sin b","cos a cos b + sin a sin b","cos a + cos b"],a:1,exp:"Formule d'addition"},
    {q:"cos(a − b) = …",c:["cos a − cos b","cos a cos b − sin a sin b","sin a cos b − cos a sin b","cos a cos b + sin a sin b"],a:3,exp:"Formule d'addition"},
    {q:"sin(a + b) = …",c:["sin a + sin b","cos a cos b − sin a sin b","sin a cos b − cos a sin b","sin a cos b + cos a sin b"],a:3,exp:"Formule d'addition"},
    {q:"sin(a − b) = …",c:["sin a − sin b","cos a cos b + sin a sin b","sin a cos b + cos a sin b","sin a cos b − cos a sin b"],a:3,exp:"Formule d'addition"},
    {q:"cos 2a = …",c:["2 sin a cos a","cos²a + sin²a","cos²a − sin²a","1 + 2 sin²a"],a:2,exp:"Formule de duplication"},
    {q:"cos 2a s'écrit aussi…",c:["2cos²a − 1","cos²a + 1","1 + 2cos²a","2sin²a − 1"],a:0,exp:"Formule de duplication"},
    {q:"sin 2a = …",c:["2 sin a cos a","2 sin a","sin a + cos a","sin²a − cos²a"],a:0,exp:"Formule de duplication"},
    {q:"Si cos a = 3/5, alors cos 2a = …",c:["−7/25","9/25","7/25","6/5"],a:0,exp:"2 × 9/25 − 1"},
    {q:"Si sin a = 3/5 avec a dans ]0 ; π/2[, alors sin 2a = …",c:["24/25","6/5","9/25","12/25"],a:0,exp:"cos a = 4/5 ; 2 × 3/5 × 4/5"},
    {q:"cos(π/3 + π/6) = …",c:["1","0","√3/2","1/2"],a:1,exp:"cos(π/2)"},
    {q:"Les solutions de cos x = 1/2 sont…",c:["x = π/6 + 2kπ ou 5π/6 + 2kπ","x = ±π/3 + 2kπ","x = π/3 + kπ","x = π/6 + kπ"],a:1,exp:"Résolution de cos x = a"},
    {q:"Les solutions de sin x = 1/2 sont…",c:["x = ±π/6 + 2kπ","x = π/3 + 2kπ","x = π/6 + kπ","x = π/6 + 2kπ ou x = 5π/6 + 2kπ"],a:3,exp:"Résolution de sin x = b"},
    {q:"Les solutions de tan x = 1 sont…",c:["x = ±π/4 + 2kπ","x = π/4 + kπ","x = π/2 + kπ","x = π/4 + 2kπ"],a:1,exp:"tan est π-périodique"},
    {q:"cos x = 0 a pour solutions…",c:["x = kπ","x = π/2 + kπ","x = π + 2kπ","x = 2kπ"],a:1,exp:"Points d'abscisse nulle sur le cercle trigonométrique"},
    {q:"Pour résoudre a cos x + b sin x = c, on écrit a cos x + b sin x sous la forme…",c:["(a + b) cos x","√(a² + b²) cos(x − φ)","a cos(x) + b cos(x)","ab cos x sin x"],a:1,exp:"Méthode du guide"},
    {q:"Résoudre cos x ≥ 0 sur ]−π ; π].",c:["x ∈ [0 ; π]","x ∈ [−π ; 0]","x ∈ [−π/2 ; π/2]","x ∈ [π/2 ; π]"],a:2,exp:"cos est positif sur cet intervalle"},
    {q:"Pour tout t de [−1 ; 1], il existe a dans ]−π ; π] tel que…",c:["cos a = 0","sin a = t","tan a = t","a = t"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Pour tout réel t, il existe a dans ]−π/2 ; π/2[ tel que…",c:["a = 2t","cos a = t","tan a = t","sin a = t"],a:2,exp:"Propriété démontrée en classe"},
  ],
  "1D — Barycentre & lignes de niveau": [
    {q:"G est le barycentre de (A ; α) et (B ; β), α + β ≠ 0, si et seulement si…",c:["α →GA + β →GB = →0","GA = GB","α + β = 0","→GA = →GB"],a:0,exp:"Définition"},
    {q:"Pour tout point M, α →MA + β →MB = …",c:["(α + β) MG","(α + β) →MG","→0","α + β"],a:1,exp:"Propriété démontrée en classe"},
    {q:"G est le barycentre de (A ; 2) et (B ; 1). Alors →AG = …",c:["(1/3) →AB","(1/2) →AB","3 →AB","(2/3) →AB"],a:0,exp:"G = (2A + B)/3"},
    {q:"Le barycentre de A(1 ; 2) et B(4 ; 5) affectés des coefficients 2 et 1 est…",c:["(5 ; 7)","(2 ; 3)","(3 ; 4)","(2,5 ; 3,5)"],a:1,exp:"((2 + 4)/3 ; (4 + 5)/3)"},
    {q:"Le barycentre de (A ; 3) et (B ; −1) est…",c:["le point G tel que →AG = −(1/2) →AB (il existe car 3 + (−1) = 2 ≠ 0)","il n'existe pas","le point A","le milieu de [AB]"],a:0,exp:"→AG = (−1/2) →AB"},
    {q:"Le barycentre de (A ; 1) et (B ; −1) n'existe pas car…",c:["aucun point ne convient jamais","les coefficients sont opposés à ceux de G","A = B","la somme des coefficients est nulle"],a:3,exp:"α + β = 0"},
    {q:"L'isobarycentre de trois points non alignés A, B, C est…",c:["le centre de gravité du triangle ABC","le centre du cercle circonscrit","un sommet","l'orthocentre de ABC"],a:0,exp:"Coefficients égaux"},
    {q:"Homogénéité : le barycentre ne change pas lorsqu'on…",c:["multiplie tous les coefficients par un même réel non nul","permute les points seulement","ajoute 1 à chaque coefficient","change un coefficient"],a:0,exp:"Propriété du guide"},
    {q:"Associativité : le barycentre de trois points au moins ne change pas lorsqu'on…",c:["double un coefficient","permute les coefficients","remplace une partie d'entre eux par leur barycentre affecté de la somme de leurs coefficients","supprime un point"],a:2,exp:"Propriété du guide"},
    {q:"Le barycentre permet notamment de démontrer…",c:["des dérivées","des limites","des congruences","l'alignement de points et le concours de droites"],a:3,exp:"Utilisation du barycentre"},
    {q:"Une ligne de niveau k de M ↦ Σ αᵢ MAᵢ² est…",c:["la courbe de sin","l'ensemble des barycentres","un point","l'ensemble des points M tels que Σ αᵢ MAᵢ² = k"],a:3,exp:"Définition du guide"},
    {q:"L'ensemble des points M tels que MA² + MB² = 3 est la ligne de niveau…",c:["3 de M ↦ MA − MB","0 de M ↦ MA + MB","1 de M ↦ MA²","3 de l'application M ↦ MA² + MB²"],a:3,exp:"Exemple du guide"},
    {q:"L'ensemble des points M du plan tels que MA = MB est…",c:["la droite (AB)","la médiatrice de [AB]","le cercle de diamètre [AB]","le milieu de [AB]"],a:1,exp:"Ligne de niveau 0 de MA² − MB²"},
    {q:"L'ensemble des points M tels que MA² + MB² = k (k assez grand) est…",c:["une parabole","un cercle de centre le milieu de [AB]","une droite","un segment"],a:1,exp:"Barycentre de (A ; 1), (B ; 1)"},
  ],
  "1D — Cercle : équation, représentation paramétrique & tangente": [
    {q:"Le cercle de centre Ω(a ; b) et de rayon r a pour équation…",c:["(x − a)² + (y − b)² = r","x² + y² = r","(x + a)² + (y + b)² = r²","(x − a)² + (y − b)² = r²"],a:3,exp:"Équation cartésienne"},
    {q:"Une représentation paramétrique du cercle de centre Ω(a ; b) et de rayon r est…",c:["x = a + r t ; y = b + r t","x = a + r cos t ; y = b + r sin t","x = r + a cos t ; y = r + b sin t","x = a cos t ; y = b sin t"],a:1,exp:"t ∈ ℝ"},
    {q:"Le cercle x² + y² − 4x + 2y − 4 = 0 a pour centre…",c:["(−2 ; 1)","(2 ; −1)","(2 ; 1)","(4 ; −2)"],a:1,exp:"(x − 2)² + (y + 1)² = 9"},
    {q:"Le cercle x² + y² − 4x + 2y − 4 = 0 a pour rayon…",c:["9","4","3","√3"],a:2,exp:"r² = 4 + 1 + 4 = 9"},
    {q:"L'équation x² + y² − 2ax − 2by + c = 0 représente un cercle si…",c:["a = b","a² + b² − c > 0","c > 0","a² + b² − c < 0"],a:1,exp:"r² = a² + b² − c"},
    {q:"La tangente au cercle de centre Ω et de rayon r au point M₀(x₀ ; y₀) a pour équation…",c:["x x₀ + y y₀ = 0","(x₀ − a)(x − a) + (y₀ − b)(y − b) = r²","(x − a)² + (y − b)² = 0","(x₀ − a)(x − a) − (y₀ − b)(y − b) = r²"],a:1,exp:"Équation d'une tangente à un cercle"},
    {q:"La tangente au cercle x² + y² = 25 au point (3 ; 4) a pour équation…",c:["4x + 3y = 25","3x + 4y = 25","3x − 4y = 25","x + y = 25"],a:1,exp:"x₀ x + y₀ y = r²"},
    {q:"La tangente en un point d'un cercle est…",c:["sécante au cercle en deux points","parallèle au rayon","confondue avec le rayon","perpendiculaire au rayon en ce point"],a:3,exp:"Propriété classique"},
    {q:"Le point (0 ; 5) est-il sur le cercle x² + y² = 25 ?",c:["Oui","On ne peut pas savoir","Non","Oui, mais à l'intérieur"],a:0,exp:"0 + 25 = 25"},
    {q:"Représentation paramétrique de x² + y² = 4 :",c:["x = 2t ; y = 2t","x = 4 cos t ; y = 4 sin t","x = 2 cos t ; y = 2 sin t","x = cos t ; y = sin t"],a:2,exp:"Rayon 2 centré à l'origine"},
    {q:"Le cercle de diamètre [AB] avec A(0 ; 0) et B(4 ; 2) a pour équation…",c:["x² + y² = 5","(x − 2)² + (y − 1)² = 5","(x − 4)² + (y − 2)² = 5","(x − 2)² + (y − 1)² = 20"],a:1,exp:"Centre (2 ; 1) ; r² = (16 + 4)/4 = 5"},
  ],
  "1D — Isométries & composition de transformations": [
    {q:"Une isométrie du plan est une transformation qui…",c:["conserve les distances","conserve les angles seulement","conserve les aires seulement","multiplie les distances par k"],a:0,exp:"Définition"},
    {q:"La composée de deux rotations de même centre est…",c:["l'identité toujours","une translation","une rotation de même centre dont l'angle est la somme des angles","une homothétie"],a:2,exp:"Composée au programme"},
    {q:"La composée de deux homothéties de même centre O et de rapports k et k' est…",c:["une translation","une homothétie de rapport k + k'","une homothétie de centre O et de rapport kk'","l'identité toujours"],a:2,exp:"Composée au programme"},
    {q:"La composée d'une homothétie de rapport k (k ≠ 1) et d'une translation est…",c:["une translation","une rotation","une homothétie de rapport k","l'identité"],a:2,exp:"Composée au programme"},
    {q:"La composée d'une rotation et d'une translation est…",c:["une symétrie centrale toujours","une homothétie","une rotation de même angle (ou une translation si l'angle est nul)","une projection"],a:2,exp:"Composée au programme"},
    {q:"La composée de deux translations de vecteurs →u et →v est…",c:["l'identité","la translation de vecteur →u + →v","une rotation","une homothétie"],a:1,exp:"Propriété classique"},
    {q:"La composée de deux rotations de même centre d'angles π/3 et π/6 est…",c:["l'identité","la rotation d'angle π/18","la rotation de même centre d'angle π/2","une translation"],a:2,exp:"π/3 + π/6"},
    {q:"La composée de deux homothéties de même centre de rapports 2 et −3 est…",c:["l'homothétie de rapport 5","une translation","l'homothétie de rapport −1","l'homothétie de rapport −6"],a:3,exp:"2 × (−3)"},
    {q:"Une rotation conserve…",c:["aucune distance","seulement les alignements","seulement les aires","les distances et les angles orientés"],a:3,exp:"Isométrie directe"},
    {q:"Une translation conserve…",c:["seulement les aires","les distances, les angles et le parallélisme","seulement les distances","aucune propriété"],a:1,exp:"Isométrie"},
    {q:"Une homothétie de rapport k (|k| ≠ 1) est-elle une isométrie ?",c:["Oui toujours","Oui si k < 0","Oui si k > 0","Non, elle multiplie les distances par |k|"],a:3,exp:"|k| ≠ 1"},
    {q:"En 1ère D, on ne parle pas…",c:["d'homothétie","de similitude","de translation","de rotation"],a:1,exp:"N.B. du guide"},
  ],
  "1D — Fonctions associées & transformations de courbes": [
    {q:"La courbe de g(x) = f(x + a) se déduit de celle de f par la translation de vecteur…",c:["(0 ; a)","(−a ; 0)","(a ; 0)","(0 ; −a)"],a:1,exp:"Décalage horizontal opposé au signe de a"},
    {q:"La courbe de g(x) = f(x) + b se déduit de celle de f par la translation de vecteur…",c:["(−b ; 0)","(b ; 0)","(0 ; −b)","(0 ; b)"],a:3,exp:"Décalage vertical"},
    {q:"La courbe de g(x) = f(−x) est symétrique de celle de f par rapport…",c:["à l'axe des abscisses","à l'origine","à la droite y = x","à l'axe des ordonnées"],a:3,exp:"Symétrie orthogonale d'axe (Oy)"},
    {q:"La courbe de g(x) = −f(x) est symétrique de celle de f par rapport…",c:["à l'axe des ordonnées","à l'origine","à la droite y = x","à l'axe des abscisses"],a:3,exp:"Symétrie orthogonale d'axe (Ox)"},
    {q:"La courbe de g(x) = |f(x)| se déduit de celle de f en…",c:["translatant de (0 ; 1)","symétrisant par rapport à (Oy)","doublant les ordonnées","symétrisant par rapport à (Ox) les parties situées sous l'axe des abscisses"],a:3,exp:"Valeur absolue de f"},
    {q:"La courbe de g(x) = (x − 2)² se déduit de celle de x ↦ x² par la translation de vecteur…",c:["(0 ; −2)","(−2 ; 0)","(0 ; 2)","(2 ; 0)"],a:3,exp:"g(x) = f(x − 2)"},
    {q:"La courbe de g(x) = x² + 3 se déduit de celle de x ↦ x² par la translation de vecteur…",c:["(−3 ; 0)","(0 ; −3)","(0 ; 3)","(3 ; 0)"],a:2,exp:"g(x) = f(x) + 3"},
    {q:"La parabole d'équation y = ax² + bx + c admet pour axe de symétrie la droite…",c:["x = c/a","x = b/(2a)","y = −b/(2a)","x = −b/(2a)"],a:3,exp:"Abscisse du sommet"},
    {q:"La courbe d'une fonction homographique x ↦ (ax + b)/(cx + d) admet pour centre de symétrie le point…",c:["(0 ; a/c)","(−d/c ; a/c)","(−d/c ; b/d)","(d/c ; a/c)"],a:1,exp:"Intersection des deux asymptotes"},
    {q:"La courbe de x ↦ 1/(x − 1) + 2 se déduit de celle de x ↦ 1/x par la translation de vecteur…",c:["(1 ; −2)","(1 ; 2)","(2 ; 1)","(−1 ; 2)"],a:1,exp:"Décalage de 1 horizontalement et de 2 verticalement"},
  ],
  "1D — Prop. & Déf.": [
    {q:"Définition : deux droites de l'espace sont orthogonales lorsque…",c:["elles sont parallèles","elles sont sécantes","elles ont un point commun","les parallèles à ces droites passant par un point donné sont perpendiculaires"],a:3,exp:"Droites orthogonales"},
    {q:"Propriété : une droite orthogonale à deux droites sécantes d'un plan est…",c:["sécante non orthogonale","contenue dans ce plan","parallèle à ce plan","orthogonale à ce plan"],a:3,exp:"Droite et plan orthogonaux"},
    {q:"Définition : deux plans sont perpendiculaires lorsque…",c:["l'un contient une droite orthogonale à l'autre","ils sont parallèles","ils sont confondus","leur intersection est un point"],a:0,exp:"Plans perpendiculaires"},
    {q:"Propriété : l'ensemble des points invariants par la projection orthogonale sur un plan (P) est…",c:["un point","le plan (P)","une droite","l'espace entier"],a:1,exp:"Projection orthogonale"},
    {q:"Définition : trois vecteurs sont coplanaires si…",c:["ils sont colinéaires","l'un au moins est combinaison linéaire des deux autres","ils sont orthogonaux","ils ont la même norme"],a:1,exp:"Vecteurs coplanaires"},
    {q:"Définition : une base de l'espace est…",c:["trois points","un triplet de vecteurs non coplanaires","un couple de vecteurs non colinéaires","un vecteur non nul"],a:1,exp:"Base"},
    {q:"Propriété : x₁ + x₂ = … et x₁ x₂ = …",c:["c/a et −b/a","−b/a et c/a","b/a et −c/a","−b et c"],a:1,exp:"Somme et produit des racines"},
    {q:"Définition : deux systèmes sont équivalents si…",c:["même ensemble de validité et même ensemble de solutions","même solution particulière","mêmes coefficients","même nombre d'équations"],a:0,exp:"Systèmes équivalents"},
    {q:"Définition : la densité d'une classe est…",c:["le quotient de l'effectif par l'amplitude","la fréquence","l'effectif","le produit de l'effectif par l'amplitude"],a:0,exp:"Statistique"},
    {q:"Définition : le mode d'une série groupée est…",c:["la moyenne","le centre de toute classe de densité maximale","le centre de toute classe d'effectif maximal","la médiane"],a:1,exp:"Statistique"},
    {q:"Propriété : card(A ∪ B) = …",c:["card A + card B − card(A ∩ B)","card A − card B","card A × card B","card A + card B + card(A ∩ B)"],a:0,exp:"Dénombrement"},
    {q:"Propriété : Cₙᵖ = …",c:["n!/(n − p)!","nᵖ/p!","n!/p!","n!/(p!(n − p)!)"],a:3,exp:"Combinaisons"},
    {q:"Propriété : Aₙᵖ = …",c:["nᵖ","n!/(n − p)!","n!/(p!(n − p)!)","n!"],a:1,exp:"Arrangements"},
    {q:"Propriété : la composée de deux injections est…",c:["une bijection","constante","une injection","une surjection"],a:2,exp:"Applications"},
    {q:"Propriété : f est bijective si et seulement si…",c:["pour tout y, l'équation f(x) = y a une solution unique","A = B","f est continue","f est croissante"],a:0,exp:"Bijection"},
    {q:"Définition : f est continue en a si…",c:["f est définie en a et admet une limite en a","f est dérivable en a","f est croissante en a","f(a) = 0"],a:0,exp:"Continuité"},
    {q:"Propriété : si f est dérivable en a, alors f est…",c:["constante en a","continue en a","monotone en a","positive en a"],a:1,exp:"Dérivabilité"},
    {q:"Propriété : f est croissante sur un intervalle ouvert K si et seulement si…",c:["f est continue","f' est nulle sur K","f' est positive sur K","f' est négative sur K"],a:2,exp:"Sens de variation"},
    {q:"Propriété : si F est une primitive de f sur K, alors les primitives de f sur K sont…",c:["les fonctions F²","les fonctions C × F","F seulement","les fonctions F + C"],a:3,exp:"Primitives"},
    {q:"Définition : une suite arithmétique de raison r vérifie…",c:["uₙ₊₁ = uₙ + r","uₙ₊₁ = r uₙ","uₙ₊₁ = uₙ²","uₙ₊₁ = r/n"],a:0,exp:"Suites"},
    {q:"Propriété : toute suite croissante et majorée est…",c:["décroissante","divergente","convergente","nulle"],a:2,exp:"Suites"},
    {q:"Propriété : cos²a + sin²a = …",c:["2","cos 2a","0","1"],a:3,exp:"Trigonométrie"},
    {q:"Propriété : cos(a + b) = …",c:["sin a cos b + cos a sin b","cos a cos b − sin a sin b","cos a cos b + sin a sin b","cos a + cos b"],a:1,exp:"Formules d'addition"},
    {q:"Propriété : sin 2a = …",c:["2 sin a cos a","sin²a − cos²a","sin a + cos a","2 sin a"],a:0,exp:"Duplication"},
    {q:"Propriété : G barycentre de (A ; α), (B ; β) ⟹ pour tout M, α →MA + β →MB = …",c:["(α + β) →MG","→0","(α − β) →MG","α + β"],a:0,exp:"Barycentre"},
    {q:"Propriété : l'équation d'un cercle de centre Ω(a ; b) et de rayon r est…",c:["x² + y² = r","(x − a) + (y − b) = r","(x − a)² + (y − b)² = r²","(x + a)² + (y + b)² = r²"],a:2,exp:"Cercle"},
    {q:"Propriété : la composée de deux rotations de même centre est…",c:["l'identité","une homothétie","une rotation de même centre dont l'angle est la somme des angles","une translation"],a:2,exp:"Composées"},
    {q:"Propriété : la composée de deux homothéties de même centre a pour rapport…",c:["la différence des rapports","la somme des rapports","le produit des rapports","le quotient des rapports"],a:2,exp:"Composées"},
  ],
});
