/* Questions de la classe de 2nde A (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "2A — Proportionnalité & pourcentages": [
    {q:"Deux grandeurs sont proportionnelles lorsque…",c:["leur différence est constante","leur somme est constante","elles sont égales","on passe des valeurs de l'une à celles de l'autre en multipliant par un même nombre non nul"],a:3,exp:"Définition"},
    {q:"Dans le tableau (2 ; 6) et (5 ; 15), le coefficient de proportionnalité est…",c:["30","2","3","4"],a:2,exp:"6 ÷ 2 = 15 ÷ 5"},
    {q:"5 kg de riz coûtent 3 500 F. Le prix de 8 kg est…",c:["4 500 F","2 800 F","28 000 F","5 600 F"],a:3,exp:"1 kg coûte 700 F"},
    {q:"20 % de 150 est égal à…",c:["300","20","30","7,5"],a:2,exp:"150 × 20/100"},
    {q:"Une remise de 10 % sur un article de 8 000 F représente…",c:["8 000 F","80 F","10 F","800 F"],a:3,exp:"10 % de 8 000"},
    {q:"Après une remise de 10 % sur 8 000 F, le prix à payer est…",c:["800 F","8 800 F","7 900 F","7 200 F"],a:3,exp:"8 000 − 800"},
    {q:"Sur 40 élèves, 10 sont absents : le pourcentage d'absents est…",c:["4 %","10 %","25 %","40 %"],a:2,exp:"10/40 = 0,25"},
    {q:"Sur une carte à l'échelle 1/50 000, 4 cm représentent en réalité…",c:["0,2 km","20 km","200 m","2 km"],a:3,exp:"4 × 50 000 cm = 200 000 cm"},
    {q:"Zoé a 7 notes de moyenne 13,5. La somme de ses notes est…",c:["7","20,5","94,5","13,5"],a:2,exp:"7 × 13,5"},
    {q:"Zoé a 7 notes de moyenne 13,5 ; avec une 8e note de 18, sa nouvelle moyenne est…",c:["15,75","14","14,0625","13,5"],a:2,exp:"(94,5 + 18)/8"},
    {q:"On partage 1 200 F proportionnellement à 2, 3 et 7. La plus grande part est…",c:["700 F","840 F","300 F","200 F"],a:0,exp:"1 200 ÷ 12 = 100 F par part ; 7 parts"},
    {q:"Le tableau (3 ; 5 ; 7) et (9 ; 15 ; 22) est-il de proportionnalité ?",c:["Non, car 22 ≠ 7 × 3","Oui, avec le coefficient 3","Oui, avec le coefficient 22/7","On ne peut pas savoir"],a:0,exp:"9/3 = 15/5 = 3 mais 22/7 ≠ 3"},
  ],
  "2A — Fonctions numériques : généralités": [
    {q:"Une fonction numérique associe à chaque réel x de son ensemble de définition…",c:["au plus un réel f(x)","aucun réel","deux réels","un intervalle"],a:0,exp:"Définition"},
    {q:"L'ensemble de définition de f(x) = 1/(x − 2) est…",c:["ℝ","ℝ privé de 2","]2 ; +∞[","ℝ privé de −2"],a:1,exp:"Le dénominateur ne doit pas s'annuler"},
    {q:"L'ensemble de définition de f(x) = √(x − 1) est…",c:["[1 ; +∞[","ℝ","]−∞ ; 1]","]1 ; +∞["],a:0,exp:"x − 1 ≥ 0"},
    {q:"La représentation graphique de f est l'ensemble des points…",c:["M(x ; f(x)) avec x dans l'ensemble de définition","M(f(x) ; x)","M(0 ; f(x))","M(x ; x)"],a:0,exp:"Définition"},
    {q:"Deux fonctions f et g sont égales si…",c:["elles ont le même ensemble de définition seulement","elles ont le même ensemble de définition et f(x) = g(x) pour tout x de cet ensemble","elles ont la même valeur en un point","f(0) = g(0)"],a:1,exp:"Égalité de deux fonctions"},
    {q:"L'image de 3 par f(x) = 2x − 1 est…",c:["5","7","6","1"],a:0,exp:"2 × 3 − 1"},
    {q:"Un antécédent de 7 par f(x) = 2x − 1 est…",c:["13","3","4","6"],a:2,exp:"2x − 1 = 7"},
    {q:"Le point A(2 ; 5) appartient à la courbe de f(x) = 3x − 1 car…",c:["f(5) = 2","f(0) = 5","f(2) = 0","f(2) = 5"],a:3,exp:"3 × 2 − 1 = 5"},
    {q:"Une valeur de x pour laquelle f(x) = 0 est appelée…",c:["une image de f","un antécédent de 1","un zéro de f","un extremum de f"],a:2,exp:"Vocabulaire"},
    {q:"Sur le graphique d'une fonction, l'image de a se lit…",c:["en ordonnée du point d'abscisse a","en abscisse du point d'ordonnée a","comme la pente","sur la bissectrice"],a:0,exp:"Lecture graphique"},
  ],
  "2A — Notion de suite numérique": [
    {q:"Une suite numérique est…",c:["une équation","une liste de nombres indexés par les entiers naturels","un ensemble de points","une fonction affine seulement"],a:1,exp:"Définition"},
    {q:"Une suite définie par une formule explicite s'écrit…",c:["Uₙ₊₁ = f(Uₙ)","Uₙ = f(n)","Uₙ = n","Uₙ = Uₙ₊₁"],a:1,exp:"Formule explicite"},
    {q:"Une suite définie par récurrence est donnée par…",c:["son dernier terme","une formule en n seulement","son premier terme et une relation Uₙ₊₁ = f(Uₙ)","sa somme"],a:2,exp:"Formule de récurrence"},
    {q:"Si Uₙ = 2n + 3, alors U₄ = …",c:["11","9","14","8"],a:0,exp:"2 × 4 + 3"},
    {q:"Si U₀ = 1 et Uₙ₊₁ = 2Uₙ + 1, alors U₂ = …",c:["5","7","3","4"],a:1,exp:"U₁ = 3 ; U₂ = 2 × 3 + 1"},
    {q:"Si Uₙ = n², alors U₅ = …",c:["10","25","5","32"],a:1,exp:"5²"},
    {q:"Si Uₙ = (−1)ⁿ, alors U₃ = …",c:["−3","3","1","−1"],a:3,exp:"(−1)³"},
    {q:"Les premiers termes de Uₙ = 3n sont…",c:["3, 6, 9, 12, …","0, 3, 6, 9, …","1, 3, 9, 27, …","0, 3, 9, 27, …"],a:1,exp:"n = 0, 1, 2, 3"},
    {q:"Pour calculer U₁₀ avec une formule de récurrence, il faut…",c:["calculer tous les termes précédents","utiliser directement n = 10","connaître seulement U₉","connaître la somme"],a:0,exp:"Un terme dépend du précédent"},
  ],
  "2A — Dénombrement élémentaire": [
    {q:"Si A ∩ B = ∅, alors Card(A ∪ B) = …",c:["Card A × Card B","Card A − Card B","Card A","Card A + Card B"],a:3,exp:"Parties disjointes"},
    {q:"En général, Card(A ∪ B) = …",c:["Card A × Card B","Card A − Card B","Card A + Card B − Card(A ∩ B)","Card A + Card B + Card(A ∩ B)"],a:2,exp:"Propriété du guide"},
    {q:"Dans une classe de 38 élèves, 20 aiment les maths et 15 le sport, dont 7 les deux. Le nombre d'élèves qui aiment au moins l'un des deux est…",c:["13","35","38","28"],a:3,exp:"20 + 15 − 7"},
    {q:"Dans une classe de 38 élèves, 20 aiment les maths et 15 le sport, dont 7 les deux. Le nombre d'élèves n'aimant aucun des deux est…",c:["28","0","3","10"],a:3,exp:"38 − 28"},
    {q:"Un arbre de choix sert à…",c:["résoudre une équation","calculer une moyenne","dénombrer les issues d'une succession de choix","tracer une droite"],a:2,exp:"Méthode"},
    {q:"On choisit un maillot (3 couleurs) et un short (2 couleurs). Le nombre de tenues est…",c:["6","5","3","2"],a:0,exp:"3 × 2"},
    {q:"Le nombre de nombres à 2 chiffres distincts formés avec {1, 2, 3} est…",c:["6","9","8","3"],a:0,exp:"3 × 2"},
    {q:"Un tableau à double entrée sert à…",c:["résoudre une inéquation","calculer une limite","tracer une parabole","dénombrer les cas en croisant deux critères"],a:3,exp:"Méthode"},
    {q:"On lance deux pièces. Le nombre d'issues possibles est…",c:["3","4","2","6"],a:1,exp:"2 × 2"},
    {q:"Un diagramme permet de trouver…",c:["la moyenne exacte","la dérivée d'une fonction","l'effectif d'une classe ou d'une partie","une racine carrée"],a:2,exp:"Utilisation d'un diagramme"},
  ],
  "2A — Nombres réels": [
    {q:"Un entier naturel est un nombre…",c:["négatif seulement","à virgule seulement","entier positif ou nul : 0, 1, 2, …","irrationnel"],a:2,exp:"Ensemble ℕ"},
    {q:"Les entiers relatifs forment l'ensemble…",c:["ℤ","ℚ","𝔻","ℕ"],a:0,exp:"…, −2, −1, 0, 1, 2, …"},
    {q:"Un nombre rationnel est un nombre qui peut s'écrire…",c:["a + b√2","a/b avec a entier relatif et b entier non nul","√a","sous forme décimale illimitée non périodique"],a:1,exp:"Ensemble ℚ"},
    {q:"Lequel de ces nombres est irrationnel ?",c:["−4","1/3","√2","0,75"],a:2,exp:"√2 n'est pas une fraction"},
    {q:"Lequel de ces nombres est un nombre décimal ?",c:["π","√3","1/3","0,125"],a:3,exp:"0,125 = 125/1 000"},
    {q:"L'ensemble ℝ contient…",c:["seulement les décimaux","les rationnels et les irrationnels","seulement les entiers","seulement les rationnels"],a:1,exp:"ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ"},
    {q:"Quelle inclusion est correcte ?",c:["ℚ ⊂ ℤ ⊂ ℕ","ℝ ⊂ ℚ","ℕ ⊂ ℤ ⊂ ℚ ⊂ ℝ","ℤ ⊂ ℕ"],a:2,exp:"Chaînes d'ensembles"},
    {q:"Le nombre π est…",c:["irrationnel","rationnel","entier","décimal"],a:0,exp:"Développement décimal illimité non périodique"},
    {q:"L'opposé de −7 est… ; l'inverse de 4 est…",c:["7 et −4","−7 et 4","1/7 et 4","7 et 1/4"],a:3,exp:"Opposé : a + (−a) = 0 ; inverse : a × (1/a) = 1"},
    {q:"Le nombre 0,333… est égal à…",c:["0,3","3/10","33/100","1/3"],a:3,exp:"Nombre rationnel"},
  ],
  "2A — Calculs dans ℝ : fractions, puissances, notation scientifique": [
    {q:"a/b + c/d = … (b, d non nuls)",c:["ac/bd","(ad + bc)/(bd)","(a + c)/bd","(a + c)/(b + d)"],a:1,exp:"Propriété du guide"},
    {q:"a/b × c/d = …",c:["ac/bd","(ac)/(b + d)","(a + c)/(b + d)","ad/bc"],a:0,exp:"Propriété du guide"},
    {q:"2/3 + 1/4 = …",c:["3/7","2/12","3/12","11/12"],a:3,exp:"8/12 + 3/12"},
    {q:"(3/4) ÷ (9/8) = …",c:["3/8","2/3","27/32","3/2"],a:1,exp:"3/4 × 8/9"},
    {q:"an × ap = …",c:["(2a)^(n + p)","a^(n × p)","a^(n + p)","a^(n − p)"],a:2,exp:"Propriété des puissances"},
    {q:"(aⁿ)ᵖ = …",c:["a^(np)","a^(n + p)","a^(n/p)","aⁿ + aᵖ"],a:0,exp:"Propriété des puissances"},
    {q:"aⁿ × bⁿ = …",c:["(ab)ⁿ","aⁿ⁺ⁿ","abⁿ","(a + b)ⁿ"],a:0,exp:"Propriété des puissances"},
    {q:"2³ × 2⁻² = …",c:["2⁵","2⁻⁶","1/2","2"],a:3,exp:"2^(3 − 2)"},
    {q:"(3²)³ = …",c:["243","27","81","729"],a:3,exp:"3⁶ = 729"},
    {q:"La notation scientifique de 45 000 est…",c:["0,45 × 10⁵","4,5 × 10³","45 × 10³","4,5 × 10⁴"],a:3,exp:"Écriture normalisée a × 10ⁿ avec 1 ≤ a < 10"},
    {q:"La notation scientifique de 0,00032 est…",c:["0,32 × 10⁻³","3,2 × 10⁻⁴","32 × 10⁻⁵","3,2 × 10⁻³"],a:1,exp:"0,00032 = 3,2/10 000"},
    {q:"(2 × 10³) × (3 × 10⁻¹) = …",c:["5 × 10²","6 × 10⁴","6 × 10²","6 × 10⁻³"],a:2,exp:"2 × 3 = 6 et 10^(3 − 1)"},
  ],
  "2A — Racine carrée": [
    {q:"La racine carrée d'un réel positif a est…",c:["l'inverse de a","le carré de a","le réel positif dont le carré est a","le double de a"],a:2,exp:"Définition"},
    {q:"√49 = …",c:["−7","7","24,5","49"],a:1,exp:"7² = 49"},
    {q:"(√5)² = …",c:["5","10","√5","25"],a:0,exp:"Par définition"},
    {q:"√(a × b) = … (a, b positifs)",c:["√a × √b","√a / √b","√a + √b","a√b"],a:0,exp:"Propriété du guide"},
    {q:"√(a/b) = … (a ≥ 0, b > 0)",c:["a/b","√a × √b","√a − √b","√a / √b"],a:3,exp:"Propriété du guide"},
    {q:"√2 × √8 = …",c:["4","2√10","16","√10"],a:0,exp:"√16"},
    {q:"√12 = …",c:["4√3","3√2","2√3","6"],a:2,exp:"√(4 × 3)"},
    {q:"√75 = …",c:["3√5","25√3","5√3","15"],a:2,exp:"√(25 × 3)"},
    {q:"√9 + √16 = …",c:["√25","25","7","5"],a:2,exp:"3 + 4"},
    {q:"Peut-on écrire √(a + b) = √a + √b ?",c:["Oui toujours","Non, en général c'est faux","Oui si a > b","Oui si a = b"],a:1,exp:"Ex. √(9 + 16) = 5 ≠ 3 + 4"},
    {q:"1/√2 = …",c:["2/√2","√2/2","1/2","√2"],a:1,exp:"On multiplie haut et bas par √2"},
  ],
  "2A — Équations du premier degré": [
    {q:"Une équation du premier degré est de la forme…",c:["ax + by = c","a/x + b = 0","ax + b = 0 avec a ≠ 0","ax² + b = 0"],a:2,exp:"Définition du guide"},
    {q:"Ajouter un même nombre à chaque membre d'une équation donne…",c:["une équation équivalente","une équation sans solution","une équation avec des solutions différentes","une inéquation"],a:0,exp:"Propriété du guide"},
    {q:"Multiplier chaque membre d'une équation par un même réel non nul donne…",c:["une équation sans solution","une inéquation","une équation avec des solutions différentes","une équation équivalente"],a:3,exp:"Propriété du guide"},
    {q:"Résoudre 3x − 5 = 10.",c:["x = 5","x = 5/3","x = 15","x = −5"],a:0,exp:"3x = 15"},
    {q:"Résoudre 2(x − 1) = x + 3.",c:["x = −5","x = 3","x = 5","x = 1"],a:2,exp:"2x − 2 = x + 3"},
    {q:"Un produit de facteurs est nul si et seulement si…",c:["l'un des facteurs est nul","la somme des facteurs est nulle","leur produit vaut 1","tous les facteurs sont nuls"],a:0,exp:"Propriété du guide"},
    {q:"Résoudre (2x + 4)(x − 3) = 0.",c:["x = −2 et x = 3 seulement","x = −2 ou x = 3","x = 2 ou x = −3","x = 4 ou x = 3"],a:1,exp:"2x + 4 = 0 ou x − 3 = 0"},
    {q:"Résoudre x² − 9 = 0.",c:["x = 9","x = 3 ou x = −3","x = ±√3","x = 3"],a:1,exp:"(x − 3)(x + 3) = 0"},
    {q:"Un quotient est nul si et seulement si…",c:["ses deux termes sont nuls","son numérateur vaut 1","son numérateur est nul (et son dénominateur non nul)","son dénominateur est nul"],a:2,exp:"Propriété du guide"},
    {q:"Résoudre (x − 2)/(x + 1) = 0.",c:["x = −1","x = 2 ou x = −1","x = 2","aucune solution"],a:2,exp:"Numérateur nul, dénominateur non nul"},
    {q:"Un champ rectangulaire de périmètre 60 m a une largeur de 12 m. Sa longueur est…",c:["30 m","24 m","18 m","48 m"],a:2,exp:"2(L + 12) = 60"},
  ],
  "2A — Inéquations du premier degré": [
    {q:"Une inéquation du premier degré est de la forme…",c:["ax + b ≥ 0 (ou ≤, >, <) avec a ≠ 0","a/x ≥ 0","ax² + b ≥ 0","ax + by ≥ 0"],a:0,exp:"Définition du guide"},
    {q:"Multiplier chaque membre d'une inéquation par un réel strictement négatif…",c:["annule l'inéquation","conserve le sens","donne une égalité","change le sens de l'inégalité"],a:3,exp:"Propriété du guide"},
    {q:"Multiplier chaque membre par un réel strictement positif…",c:["annule l'inéquation","donne une égalité","change le sens","conserve le sens de l'inégalité"],a:3,exp:"Propriété du guide"},
    {q:"Résoudre 3x − 6 < 0.",c:["x < 2","x < −2","x > 2","x > −2"],a:0,exp:"3x < 6"},
    {q:"Résoudre −2x + 4 ≥ 0.",c:["x ≤ 2","x ≤ −2","x ≥ 2","x ≥ −2"],a:0,exp:"−2x ≥ −4 : le sens change"},
    {q:"Résoudre 5 − x > 1.",c:["x > 4","x > −4","x < −4","x < 4"],a:3,exp:"−x > −4"},
    {q:"Le signe de ax + b (a > 0) est négatif pour…",c:["x > −b/a","x > b/a","x < −b/a","x < b/a"],a:2,exp:"Tableau de signes"},
    {q:"Le signe de −3x + 6 est positif pour…",c:["x < −2","x > −2","x > 2","x < 2"],a:3,exp:"−3x + 6 > 0 ⟺ x < 2"},
    {q:"Résoudre (x − 1)(x + 2) ≥ 0 à l'aide d'un tableau de signes.",c:["]−2 ; 1[","[−2 ; 1]","]−∞ ; −2] ∪ [1 ; +∞[","[1 ; +∞["],a:2,exp:"Positif à l'extérieur des racines"},
    {q:"Résoudre (x − 3)/(x + 1) < 0.",c:["[−1 ; 3]","]3 ; +∞[","]−1 ; 3[","]−∞ ; −1[ ∪ ]3 ; +∞["],a:2,exp:"Signes contraires"},
  ],
  "2A — Équations linéaires & systèmes dans ℝ × ℝ": [
    {q:"Une équation linéaire à deux inconnues est de la forme…",c:["ax + by = c","a/x + by = c","ax² + by = c","ax = b"],a:0,exp:"Définition"},
    {q:"Le couple (2 ; 1) est solution de x + 2y = 4 car…",c:["2 + 1 = 4","2 + 2 = 4","2 − 1 = 4","2 × 1 = 4"],a:1,exp:"2 + 2 × 1 = 4"},
    {q:"Résoudre x + y = 5 ; x − y = 1.",c:["x = 4 et y = 1","x = 2 et y = 3","x = 1 et y = 4","x = 3 et y = 2"],a:3,exp:"On additionne : 2x = 6"},
    {q:"Résoudre 2x + y = 7 ; x − y = −1.",c:["x = 2 et y = 1","x = 1 et y = 5","x = 3 et y = 2","x = 2 et y = 3"],a:3,exp:"On additionne : 3x = 6"},
    {q:"Résoudre x + 2y = 7 ; 3x − y = 7 par substitution.",c:["x = 3 et y = 2","x = 2 et y = 3","x = 1 et y = 3","x = 5 et y = 1"],a:0,exp:"y = 3x − 7"},
    {q:"Les méthodes de résolution d'un système au programme sont…",c:["substitution, addition (combinaison) et graphique","seulement le discriminant","seulement la dérivation","seulement les probabilités"],a:0,exp:"Guide de 2nde A"},
    {q:"Graphiquement, la solution d'un système de deux équations linéaires est…",c:["le point d'intersection des deux droites","l'origine","un cercle","le milieu des deux droites"],a:0,exp:"Méthode graphique"},
    {q:"Le système x + y = 2 ; x + y = 5 a…",c:["aucune solution","deux solutions","une solution","une infinité de solutions"],a:0,exp:"Droites parallèles distinctes"},
    {q:"Un système de trois équations linéaires à trois inconnues au programme est…",c:["toujours avec paramètre","impossible à résoudre","limité à deux inconnues","sans paramètre"],a:3,exp:"Guide de 2nde A"},
    {q:"Deux nombres ont pour somme 30 et pour différence 8. Ces nombres sont…",c:["20 et 10","19 et 11","22 et 8","15 et 15"],a:1,exp:"x + y = 30 ; x − y = 8"},
  ],
  "2A — Fonctions affines & affines par intervalles": [
    {q:"Une fonction affine est de la forme…",c:["f(x) = a/x","f(x) = ax² + b","f(x) = ax + b","f(x) = |x|"],a:2,exp:"Définition"},
    {q:"La représentation graphique d'une fonction affine est…",c:["une droite","une parabole","une hyperbole","un cercle"],a:0,exp:"Propriété"},
    {q:"Si a > 0, la fonction affine f(x) = ax + b est…",c:["croissante","constante","paire","décroissante"],a:0,exp:"Sens de variation"},
    {q:"Si a < 0, la fonction affine f(x) = ax + b est…",c:["décroissante","croissante","impaire","constante"],a:0,exp:"Sens de variation"},
    {q:"Si a = 0, la fonction f(x) = ax + b est…",c:["nulle","constante","croissante","décroissante"],a:1,exp:"f(x) = b"},
    {q:"La droite y = −2x + 4 coupe l'axe des ordonnées en…",c:["(4 ; 0)","(0 ; 4)","(0 ; −2)","(2 ; 0)"],a:1,exp:"f(0) = 4"},
    {q:"La droite y = −2x + 4 coupe l'axe des abscisses en…",c:["(4 ; 0)","(2 ; 0)","(0 ; 2)","(−2 ; 0)"],a:1,exp:"−2x + 4 = 0"},
    {q:"Une fonction affine f vérifie f(0) = 3 et f(1) = 5. Alors f(x) = …",c:["2x + 3","3x + 5","x + 3","5x + 3"],a:0,exp:"b = 3 et a = 5 − 3"},
    {q:"Une fonction affine par intervalles est…",c:["une fonction du second degré","une fonction dont l'expression est affine sur chacun de plusieurs intervalles","une fonction affine sur ℝ","une fonction constante"],a:1,exp:"Définition du guide"},
    {q:"Une fonction linéaire est une fonction affine…",c:["dont le terme constant est nul","dont le coefficient est nul","de coefficient 1","de terme constant 1"],a:0,exp:"f(x) = ax"},
    {q:"Les droites y = 2x + 1 et y = 2x − 3 sont…",c:["perpendiculaires","sécantes en un point","parallèles","confondues"],a:2,exp:"Même coefficient a"},
  ],
  "2A — Valeur absolue & fonction en escalier": [
    {q:"|x| est égale à…",c:["1/x","−x toujours","x²","x si x ≥ 0 ; −x si x < 0"],a:3,exp:"Définition"},
    {q:"|−5| = …",c:["1/5","0","−5","5"],a:3,exp:"Distance à zéro"},
    {q:"|3 − 7| = …",c:["4","−4","−10","10"],a:0,exp:"|−4|"},
    {q:"La courbe de x ↦ |x| est…",c:["formée de deux demi-droites de sommet O","une parabole","une hyperbole","une droite"],a:0,exp:"Fonction affine par intervalles"},
    {q:"La fonction x ↦ |x| est…",c:["paire","impaire","constante","ni paire ni impaire"],a:0,exp:"|−x| = |x|"},
    {q:"Résoudre |x| = 3.",c:["x = −3","x = 3 ou x = −3","x = 9","x = 3"],a:1,exp:"Deux nombres à distance 3 de 0"},
    {q:"Résoudre |x| = −2.",c:["x = 2","x = −2","aucune solution","x = ±2"],a:2,exp:"Une valeur absolue est positive ou nulle"},
    {q:"Une fonction en escalier est…",c:["une fonction affine","une fonction continue","une fonction constante sur chacun de plusieurs intervalles","une fonction du second degré"],a:2,exp:"Définition"},
    {q:"La partie entière E(x) est un exemple de fonction…",c:["affine","homographique","quadratique","en escalier"],a:3,exp:"E est constante sur chaque intervalle [n ; n + 1["},
    {q:"Les tarifs postaux par tranche de poids sont un exemple de…",c:["fonction en escalier","fonction carrée","valeur absolue","fonction affine"],a:0,exp:"Constantes par intervalles"},
  ],
  "2A — Fonctions élémentaires & résolutions graphiques": [
    {q:"Une fonction est croissante sur un intervalle I si, pour a < b dans I,…",c:["f(a) ≤ f(b)","f(a) ≥ f(b)","f(a) < 0","f(a) = f(b) toujours"],a:0,exp:"Définition"},
    {q:"Une fonction est décroissante sur I si, pour a < b dans I,…",c:["f(a) > 0","f(a) ≤ f(b)","f(a) ≥ f(b)","f(a) = 0"],a:2,exp:"Définition"},
    {q:"Une fonction est constante sur I si…",c:["f(a) = f(b) pour tous a, b de I","f(a) = 0","f n'est pas définie sur I","f est croissante"],a:0,exp:"Définition"},
    {q:"La fonction carrée x ↦ x² est décroissante sur…",c:["[−1 ; 1]","ℝ","[0 ; +∞[","]−∞ ; 0]"],a:3,exp:"Elle décroît puis croît"},
    {q:"La fonction carrée admet en 0…",c:["aucun extremum","un minimum égal à 1","un maximum égal à 0","un minimum égal à 0"],a:3,exp:"x² ≥ 0"},
    {q:"La représentation graphique de x ↦ ax² (a ≠ 0) est…",c:["un cercle","une droite","une parabole de sommet O et d'axe (OJ)","une hyperbole"],a:2,exp:"Propriété du guide"},
    {q:"Si a > 0, la parabole y = ax² est tournée…",c:["vers la gauche","vers le haut","vers le bas","vers la droite"],a:1,exp:"Propriété du guide"},
    {q:"Si a < 0, la parabole y = ax² est tournée…",c:["vers le haut","vers la gauche","vers le bas","vers la droite"],a:2,exp:"Propriété du guide"},
    {q:"Graphiquement, les solutions de x² = 4 sont les abscisses des points de la parabole d'ordonnée…",c:["4, soit x = −2 et x = 2","2","0","−4"],a:0,exp:"Intersection de y = x² et y = 4"},
    {q:"Graphiquement, x² = −1 n'a…",c:["aucune solution","une infinité de solutions","deux solutions","qu'une solution"],a:0,exp:"La parabole est au-dessus de l'axe des abscisses"},
    {q:"Un extremum d'une fonction est…",c:["un maximum ou un minimum","une asymptote","un point d'inflexion","un zéro"],a:0,exp:"Définition"},
    {q:"Pour résoudre graphiquement f(x) = k, on cherche…",c:["les zéros de f'","l'aire sous la courbe","les abscisses des points d'intersection de la courbe avec la droite y = k","les ordonnées du point d'abscisse k"],a:2,exp:"Résolution graphique"},
  ],
  "2A — Prop. & Déf.": [
    {q:"Définition : deux grandeurs sont proportionnelles si…",c:["on passe de l'une à l'autre en multipliant par un même nombre non nul","elles sont égales","leur différence est constante","leur somme est constante"],a:0,exp:"Proportionnalité"},
    {q:"Propriété : Card(A ∪ B) = …",c:["Card A + Card B − Card(A ∩ B)","Card A − Card B","Card A + Card B + Card(A ∩ B)","Card A × Card B"],a:0,exp:"Dénombrement"},
    {q:"Définition : une suite numérique est…",c:["une liste de nombres indexés par les entiers naturels","une équation","un ensemble de points","une fonction affine"],a:0,exp:"Suites"},
    {q:"Définition : un nombre rationnel est un nombre qui s'écrit…",c:["seulement décimal","√a","a/b avec a entier relatif et b entier non nul","décimal illimité non périodique"],a:2,exp:"Nombres réels"},
    {q:"Propriété : aⁿ × aᵖ = …",c:["a^(n − p)","a^(n × p)","a^(n + p)","(2a)^(n + p)"],a:2,exp:"Puissances"},
    {q:"Propriété : (aⁿ)ᵖ = …",c:["a^(n + p)","aⁿ + aᵖ","a^(np)","a^(n/p)"],a:2,exp:"Puissances"},
    {q:"Définition : la racine carrée de a ≥ 0 est…",c:["l'inverse de a","le réel positif dont le carré est a","le double de a","le carré de a"],a:1,exp:"Racine carrée"},
    {q:"Propriété : √(ab) = …",c:["√a / √b","a√b","√a + √b","√a × √b"],a:3,exp:"Racine carrée"},
    {q:"Propriété : un produit de facteurs est nul si et seulement si…",c:["leur produit vaut 1","leur somme est nulle","tous les facteurs sont nuls","l'un des facteurs est nul"],a:3,exp:"Équations"},
    {q:"Propriété : un quotient est nul si et seulement si…",c:["son numérateur est nul (dénominateur non nul)","son numérateur vaut 1","son dénominateur est nul","ses deux termes sont nuls"],a:0,exp:"Équations"},
    {q:"Propriété : multiplier une inéquation par un réel strictement négatif…",c:["annule l'inéquation","change le sens de l'inégalité","conserve le sens","donne une égalité"],a:1,exp:"Inéquations"},
    {q:"Définition : une équation linéaire à deux inconnues est de la forme…",c:["a/x + by = c","ax = b","ax² + by = c","ax + by = c"],a:3,exp:"Systèmes"},
    {q:"Définition : une fonction affine est de la forme…",c:["f(x) = ax² + b","f(x) = a/x","f(x) = ax + b","f(x) = |x|"],a:2,exp:"Fonctions affines"},
    {q:"Propriété : la représentation graphique d'une fonction affine est…",c:["une hyperbole","une droite","un cercle","une parabole"],a:1,exp:"Fonctions affines"},
    {q:"Définition : |x| = …",c:["x si x ≥ 0 ; −x si x < 0","−x","1/x","x²"],a:0,exp:"Valeur absolue"},
    {q:"Définition : une fonction en escalier est…",c:["affine sur ℝ","constante sur chacun de plusieurs intervalles","du second degré","toujours continue"],a:1,exp:"Fonction en escalier"},
    {q:"Propriété : la courbe de x ↦ ax² (a ≠ 0) est…",c:["une parabole de sommet O et d'axe (OJ)","un cercle","une hyperbole","une droite"],a:0,exp:"Fonction carrée"},
    {q:"Définition : une fonction croissante sur I vérifie, pour a < b,…",c:["f(a) > 0","f(a) ≥ f(b)","f(a) ≤ f(b)","f(a) = f(b)"],a:2,exp:"Sens de variation"},
  ],
});
