/* Questions de la classe de Tle A (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "TleA — Parité & éléments de symétrie": [
    {q:"Une fonction f est paire si, pour tout x de son ensemble de définition,…",c:["f(−x) = 1/f(x)","f(x) = 0","f(−x) = −f(x)","−x appartient à l'ensemble de définition et f(−x) = f(x)"],a:3,exp:"Définition de la parité"},
    {q:"La courbe d'une fonction paire est symétrique par rapport…",c:["à l'origine","à l'axe des abscisses","à l'axe des ordonnées","à la droite y = x"],a:2,exp:"Propriété de la parité"},
    {q:"La courbe d'une fonction impaire est symétrique par rapport…",c:["à l'axe des abscisses","à l'origine du repère","à l'axe des ordonnées","à la droite y = 1"],a:1,exp:"f(−x) = −f(x)"},
    {q:"La fonction f(x) = x² − 3 est…",c:["paire","impaire","ni paire ni impaire","constante"],a:0,exp:"f(−x) = f(x)"},
    {q:"La fonction f(x) = x³ + x est…",c:["périodique","paire","ni paire ni impaire","impaire"],a:3,exp:"f(−x) = −f(x)"},
    {q:"Pour montrer que la droite x = a est un axe de symétrie de (Cf), on vérifie que pour tout h tel que a + h ∈ Df,…",c:["f(a + h) = −f(a − h)","f(a − h) = 0","a − h ∈ Df et f(a − h) = f(a + h)","f(h) = f(−h)"],a:2,exp:"Méthode du guide"},
    {q:"Pour montrer que le point Ω(a ; b) est un centre de symétrie de (Cf), on vérifie que pour tout h tel que a + h ∈ Df,…",c:["f(a + h) × f(a − h) = b","f(a + h) − f(a − h) = b","a − h ∈ Df et f(a + h) = f(a − h)","a − h ∈ Df et (f(a + h) + f(a − h))/2 = b"],a:3,exp:"Méthode du guide"},
    {q:"La courbe de f(x) = (x − 2)² admet pour axe de symétrie la droite…",c:["x = 0","y = 2","x = −2","x = 2"],a:3,exp:"f(2 − h) = f(2 + h) = h²"},
    {q:"Le point Ω(1 ; 0) est un centre de symétrie de la courbe de f(x) = (x − 1)³ car…",c:["f(1 + h) = f(1 − h)","f(h) = f(−h)","f(1 + h) = 0","(f(1 + h) + f(1 − h))/2 = (h³ − h³)/2 = 0"],a:3,exp:"f(1 + h) = h³ et f(1 − h) = −h³"},
    {q:"Le domaine de définition d'une fonction paire est…",c:["toujours ℝ","toujours [0 ; +∞[","toujours ]0 ; +∞[","symétrique par rapport à 0"],a:3,exp:"Si x est dans le domaine, −x aussi"},
  ],
  "TleA — Limites & continuité": [
    {q:"Quand x tend vers +∞, la limite de 1/x est…",c:["+∞","−∞","0","1"],a:2,exp:"Résultat admis"},
    {q:"La limite de x² en −∞ est…",c:["0","−∞","1","+∞"],a:3,exp:"Résultat admis"},
    {q:"La limite de x³ en −∞ est…",c:["+∞","0","−∞","1"],a:2,exp:"Résultat admis"},
    {q:"La limite de √x en +∞ est…",c:["−∞","0","+∞","1"],a:2,exp:"Résultat admis"},
    {q:"Lorsqu'une fonction admet une limite en +∞ (ou en −∞), cette limite est…",c:["toujours nulle","toujours infinie","double","unique"],a:3,exp:"Propriété admise"},
    {q:"La limite de 2x² − 3x + 1 en +∞ est…",c:["0","2","+∞","−∞"],a:2,exp:"Un polynôme a même limite que son monôme de plus haut degré : 2x²"},
    {q:"La limite de x³ − x en −∞ est…",c:["0","−∞","−1","+∞"],a:1,exp:"Monôme de plus haut degré : x³"},
    {q:"La limite de (3x² + 1)/(x² − 5) en +∞ est…",c:["+∞","3","0","−5"],a:1,exp:"Quotient des monômes de plus haut degré : 3x²/x²"},
    {q:"La limite de (x + 1)/(x² + 2) en +∞ est…",c:["0","1/2","1","+∞"],a:0,exp:"x/x² = 1/x"},
    {q:"La limite de (2x + 1)/(x − 3) en +∞ est…",c:["2","+∞","0","−3"],a:0,exp:"2x/x"},
    {q:"La limite de (x² − 1)/(x − 1) en 1 est…",c:["+∞","0","2","1"],a:2,exp:"On simplifie : (x − 1)(x + 1)/(x − 1) = x + 1"},
    {q:"La limite de 1/(x − 2) quand x tend vers 2 par valeurs supérieures est…",c:["−∞","0","2","+∞"],a:3,exp:"x − 2 tend vers 0 par valeurs positives"},
    {q:"La limite de 1/(x − 2) quand x tend vers 2 par valeurs inférieures est…",c:["2","+∞","−∞","0"],a:2,exp:"x − 2 tend vers 0 par valeurs négatives"},
    {q:"(+∞) + (−∞) est…",c:["égal à 0","une forme indéterminée","égal à −∞","égal à +∞"],a:1,exp:"Il faut lever l'indétermination"},
    {q:"(+∞) × 0 est…",c:["une forme indéterminée","égal à 0","égal à +∞","égal à 1"],a:0,exp:"Forme indéterminée"},
    {q:"Si f admet pour limite +∞ et g pour limite +∞ en x₀, alors f + g a pour limite…",c:["−∞","une forme indéterminée","0","+∞"],a:3,exp:"Tableau des limites d'une somme"},
    {q:"Une fonction est continue sur un intervalle lorsque sa courbe…",c:["est symétrique","se trace sans lever le crayon","est croissante","passe par l'origine"],a:1,exp:"Reconnaissance graphique"},
    {q:"Une fonction dérivable sur un intervalle K est…",c:["toujours positive","toujours croissante","continue sur K","constante"],a:2,exp:"Propriété admise"},
  ],
  "TleA — Dérivation & sens de variation": [
    {q:"La dérivée de x ↦ xⁿ (n ≥ 2) est…",c:["xⁿ/n","xⁿ⁻¹","n x","n xⁿ⁻¹"],a:3,exp:"Formule de dérivation"},
    {q:"La dérivée de x ↦ √x est…",c:["2√x","1/√x","1/(2√x)","√x/2"],a:2,exp:"Formule de dérivation"},
    {q:"La dérivée de x ↦ 1/x est…",c:["ln x","−1/x","1/x²","−1/x²"],a:3,exp:"Formule de dérivation"},
    {q:"La dérivée de x ↦ u(ax + b) est…",c:["a u(ax + b)","u'(x)","u'(ax + b)","a u'(ax + b)"],a:3,exp:"Propriété admise"},
    {q:"La dérivée de x ↦ (3x + 1)⁵ est…",c:["(3x + 1)⁴","3(3x + 1)⁵","5(3x + 1)⁴","15(3x + 1)⁴"],a:3,exp:"a = 3 et u(t) = t⁵"},
    {q:"Une équation de la tangente à (C) au point d'abscisse x₀ est…",c:["y = f(x₀)(x − x₀) + f'(x₀)","y = f'(x) + x₀","y = f'(x₀)(x − x₀) + f(x₀)","y = f'(x₀) x"],a:2,exp:"Formule du guide"},
    {q:"La tangente à la courbe de f(x) = x² au point d'abscisse 1 a pour équation…",c:["y = 2x − 1","y = x² − 1","y = x","y = 2x + 1"],a:0,exp:"f'(1) = 2 et f(1) = 1"},
    {q:"Si f' est positive sur un intervalle ouvert K, alors f est…",c:["constante sur K","nulle sur K","décroissante sur K","croissante sur K"],a:3,exp:"Propriété du guide"},
    {q:"Si f' est nulle sur K, alors f est…",c:["croissante sur K","non dérivable","décroissante sur K","constante sur K"],a:3,exp:"Propriété du guide"},
    {q:"Si f' s'annule et change de signe en x₀, alors f admet en x₀…",c:["une asymptote verticale","un extremum relatif","un point anguleux","aucun comportement particulier"],a:1,exp:"Propriété du guide"},
    {q:"Le minimum de f(x) = x² − 4x + 3 est atteint en…",c:["x = 2, et vaut −1","x = 2, et vaut 1","x = 4, et vaut 3","x = 1, et vaut 0"],a:0,exp:"f'(x) = 2x − 4 et f(2) = 4 − 8 + 3"},
    {q:"f(x) = x³ − 3x admet en x = −1…",c:["un minimum relatif égal à 2","un maximum relatif égal à 2","un maximum relatif égal à −2","aucun extremum"],a:1,exp:"f'(x) = 3x² − 3 change de signe de + à − en −1 ; f(−1) = 2"},
    {q:"f(x) = x³ − 3x admet en x = 1…",c:["un minimum relatif égal à −2","un minimum relatif égal à 2","aucun extremum","un maximum relatif égal à −2"],a:0,exp:"f'(x) change de signe de − à + ; f(1) = −2"},
    {q:"Le tableau de variations d'un polynôme de degré 2 (a > 0) montre…",c:["f constante","f décroissante puis croissante, avec un minimum","f croissante puis décroissante","f toujours croissante"],a:1,exp:"Parabole tournée vers le haut"},
  ],
  "TleA — Fonctions polynômes, homographiques & asymptotes": [
    {q:"La droite d'équation y = l est asymptote à (Cf) lorsque…",c:["f est constante","f a pour limite finie l en +∞ ou en −∞","f a une limite infinie en x₀","f(x) = l pour tout x"],a:1,exp:"Asymptote parallèle à l'axe des abscisses"},
    {q:"La droite d'équation x = x₀ est asymptote à (Cf) lorsque…",c:["f a une limite infinie à droite ou à gauche en x₀","f est paire","f a pour limite l en +∞","f(x₀) = 0"],a:0,exp:"Asymptote verticale"},
    {q:"La droite y = ax + b est asymptote oblique lorsque…",c:["f(x) − (ax + b) a pour limite 0 en +∞ ou −∞","f(x) = ax + b pour tout x","f'(x) = a","f a une limite finie en x₀"],a:0,exp:"Définition du guide"},
    {q:"f(x) = (2x + 1)/(x − 3) a pour asymptote horizontale la droite…",c:["y = 1/3","y = 2","y = −3","y = 3"],a:1,exp:"La limite en ±∞ est 2"},
    {q:"f(x) = (2x + 1)/(x − 3) a pour asymptote verticale la droite…",c:["x = 1/2","x = 2","x = −3","x = 3"],a:3,exp:"Le dénominateur s'annule en 3"},
    {q:"La dérivée de f(x) = (2x + 1)/(x − 3) est…",c:["(4x − 5)/(x − 3)²","7/(x − 3)²","−7/(x − 3)²","2/(x − 3)"],a:2,exp:"(2(x − 3) − (2x + 1))/(x − 3)²"},
    {q:"f(x) = (2x + 1)/(x − 3) est…",c:["constante","strictement croissante sur ℝ","strictement décroissante sur chacun des intervalles ]−∞ ; 3[ et ]3 ; +∞[","strictement croissante sur chacun des intervalles de son domaine"],a:2,exp:"f'(x) < 0"},
    {q:"Le centre de symétrie de la courbe de f(x) = (ax + b)/(cx + d) est le point…",c:["(0 ; a/c)","(d/c ; a/c)","(−d/c ; b/d)","(−d/c ; a/c)"],a:3,exp:"Intersection des deux asymptotes"},
    {q:"Pour étudier la position relative de (Cf) et (Cg), on étudie le signe de…",c:["f(x) × g(x)","f(x) − g(x)","f'(x) − g'(x)","f(x) + g(x)"],a:1,exp:"Méthode du guide"},
    {q:"Si f(x) − g(x) < 0, alors (Cf) est…",c:["sécante à (Cg)","en dessous de (Cg)","confondue avec (Cg)","au-dessus de (Cg)"],a:1,exp:"Méthode du guide"},
    {q:"Si f(x) − g(x) = 0, alors…",c:["(Cf) et (Cg) se coupent","(Cf) est au-dessus de (Cg)","(Cf) est en dessous de (Cg)","les deux courbes sont parallèles"],a:0,exp:"Méthode du guide"},
    {q:"Une fonction homographique est de la forme…",c:["x ↦ (ax + b)/(cx + d)","x ↦ ax² + bx + c","x ↦ a eˣ","x ↦ a ln x"],a:0,exp:"Quotient de deux fonctions affines"},
    {q:"Le polynôme f(x) = x³ − 3x² + 2 a pour dérivée…",c:["x² − 6x","3x² − 6x","3x² − 6x + 2","3x² − 3x"],a:1,exp:"Dérivation terme à terme"},
    {q:"Étudier une fonction polynôme de degré 3 comprend…",c:["le calcul d'une intégrale","seulement le tracé","domaine, limites, dérivée, tableau de variations, tracé","seulement les limites"],a:2,exp:"Méthode d'étude"},
  ],
  "TleA — Fonction logarithme népérien": [
    {q:"La fonction ln est définie sur…",c:["]0 ; +∞[","[0 ; +∞[","ℝ*","ℝ"],a:0,exp:"Propriété démontrée en classe"},
    {q:"ln 1 = …",c:["e","−1","1","0"],a:3,exp:"ln s'annule en 1"},
    {q:"La dérivée de ln est…",c:["x ↦ 1/x","x ↦ e^x","x ↦ ln x/x","x ↦ x"],a:0,exp:"(ln)'(x) = 1/x"},
    {q:"Pour a, b > 0, ln(a × b) = …",c:["ln(a + b)","ln a − ln b","ln a + ln b","ln a × ln b"],a:2,exp:"Propriété fondamentale"},
    {q:"ln(1/a) = …",c:["ln a","1/ln a","a","−ln a"],a:3,exp:"Pour a > 0"},
    {q:"ln(a/b) = …",c:["ln a − ln b","ln(a − b)","ln a + ln b","ln a / ln b"],a:0,exp:"Pour a, b > 0"},
    {q:"ln(aʳ) = …",c:["ln a + r","r ln a","(ln a)ʳ","a ln r"],a:1,exp:"Pour a > 0 et r rationnel"},
    {q:"ln(√a) = …",c:["ln a − 2","(1/2) ln a","√(ln a)","2 ln a"],a:1,exp:"√a = a^(1/2)"},
    {q:"La limite de ln x en +∞ est…",c:["+∞","0","−∞","1"],a:0,exp:"Propriété admise"},
    {q:"La limite de ln x en 0 (par valeurs positives) est…",c:["+∞","1","−∞","0"],a:2,exp:"Propriété admise"},
    {q:"La limite de x ln x en 0 (par valeurs positives) est…",c:["−∞","0","1","+∞"],a:1,exp:"Propriété admise"},
    {q:"La limite de (ln x)/x en +∞ est…",c:["+∞","1","−∞","0"],a:3,exp:"Propriété admise"},
    {q:"La fonction ln réalise une bijection de…",c:["ℝ sur ]0 ; +∞[","]0 ; +∞[ sur ]0 ; +∞[","]0 ; +∞[ sur ℝ","ℝ sur ℝ"],a:2,exp:"Propriété admise"},
    {q:"Le nombre e est l'unique nombre tel que…",c:["e = 1","ln e = e","ln e = 0","ln e = 1"],a:3,exp:"Définition de la base du logarithme népérien"},
    {q:"Pour a, b > 0, ln a = ln b équivaut à…",c:["a = e","a = 1","a = b","a + b = 1"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Pour a, b > 0, ln a < ln b équivaut à…",c:["a = b","a < b","a > b","a + b < 0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Résoudre ln(x − 2) = 0.",c:["x = 1","x = e","x = 3","x = 2"],a:2,exp:"Domaine x > 2 ; x − 2 = 1"},
    {q:"Résoudre ln x < 0.",c:["x < 1","x > 1","x < 0","0 < x < 1"],a:3,exp:"ln x < ln 1"},
    {q:"Le domaine de définition de x ↦ ln(3 − x) est…",c:["]3 ; +∞[","]−∞ ; 3[","]0 ; 3[","ℝ"],a:1,exp:"3 − x > 0"},
    {q:"La dérivée de x ↦ ln(ax + b) est…",c:["1/(ax + b)","a ln(ax + b)","(ax + b)/a","a/(ax + b)"],a:3,exp:"Propriété admise"},
    {q:"La dérivée de x ↦ ln(2x + 1) est…",c:["2 ln(2x + 1)","(2x + 1)/2","1/(2x + 1)","2/(2x + 1)"],a:3,exp:"a = 2 ; b = 1"},
  ],
  "TleA — Fonction exponentielle népérienne": [
    {q:"La fonction exponentielle népérienne est…",c:["l'inverse de ln","la dérivée de ln","la réciproque de la fonction ln","la primitive de ln"],a:2,exp:"Définition du guide"},
    {q:"b = exp(a) équivaut à…",c:["a = b","a = ln b (b > 0)","b = ln a","ab = 1"],a:1,exp:"Réciprocité"},
    {q:"Pour tout réel a, eᵃ est…",c:["strictement positif","négatif","entier","nul"],a:0,exp:"Propriété admise"},
    {q:"Pour tout réel a, ln(eᵃ) = …",c:["a","eᵃ","1","0"],a:0,exp:"Propriété admise"},
    {q:"Pour tout réel a > 0, e^(ln a) = …",c:["1","a","ln a","0"],a:1,exp:"Propriété admise"},
    {q:"e^(a + b) = …",c:["eᵃ × eᵇ","(eᵃ)ᵇ","eᵃᵇ","eᵃ + eᵇ"],a:0,exp:"Propriété démontrée en classe"},
    {q:"e^(−a) = …",c:["1/eᵃ","eᵃ","1 − eᵃ","−eᵃ"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La limite de eˣ en −∞ est…",c:["0","−∞","+∞","1"],a:0,exp:"Propriété admise"},
    {q:"La limite de eˣ en +∞ est…",c:["−∞","1","0","+∞"],a:3,exp:"Propriété admise"},
    {q:"La dérivée de eˣ est…",c:["1/eˣ","eˣ","−eˣ","x eˣ⁻¹"],a:1,exp:"Propriété admise"},
    {q:"La dérivée de x ↦ e^(ax + b) est…",c:["e^(ax + b)","(ax + b) e^(ax + b)","a e^(ax + b)","a e^a"],a:2,exp:"Propriété admise"},
    {q:"La dérivée de x ↦ e^(2x − 1) est…",c:["e^(2x − 1)","e^(2x)","2x e^(2x − 1)","2 e^(2x − 1)"],a:3,exp:"a = 2 ; b = −1"},
    {q:"eᵃ = eᵇ équivaut à…",c:["a = b","a = e","a = 1","a + b = 0"],a:0,exp:"Propriété démontrée en classe"},
    {q:"eᵃ < eᵇ équivaut à…",c:["a = b","a < b","a + b < 0","a > b"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Résoudre e^(2x) = 5.",c:["x = ln 5","x = (ln 5)/2","x = e⁵/2","x = 5/2"],a:1,exp:"2x = ln 5"},
    {q:"Résoudre eˣ > 1.",c:["x < 1","x < 0","x > 0","x > 1"],a:2,exp:"eˣ > e⁰"},
    {q:"Résoudre e^(x − 1) = 1.",c:["x = 0","x = e","x = −1","x = 1"],a:3,exp:"x − 1 = 0"},
    {q:"Résoudre ln x = 2.",c:["x = ln 2","x = 2e","x = e²","x = 2"],a:2,exp:"x = e^(ln x) = e²"},
    {q:"Le graphe de eˣ admet pour asymptote horizontale…",c:["l'axe des ordonnées","la droite y = 1","l'axe des abscisses en −∞","la droite y = x"],a:2,exp:"lim eˣ = 0 en −∞"},
  ],
  "TleA — Équations, inéquations & systèmes": [
    {q:"Les solutions de x² − 5x + 6 = 0 sont…",c:["−2 et −3","−1 et 6","2 et 3","1 et 6"],a:2,exp:"(x − 2)(x − 3) = 0"},
    {q:"Résoudre x² − 4 < 0.",c:["x > −2","−2 < x < 2","x < −2 ou x > 2","x < 2"],a:1,exp:"Un polynôme de degré 2 est négatif entre ses racines"},
    {q:"Résoudre x² − 1 ≥ 0.",c:["x ≥ 1","x ≤ −1 ou x ≥ 1","−1 ≤ x ≤ 1","x ≤ −1"],a:1,exp:"Positif à l'extérieur des racines"},
    {q:"Résoudre 2x − 6 > 0.",c:["x > −3","x > 3","x < 3","x < −3"],a:1,exp:"2x > 6"},
    {q:"Résoudre le système x + y = 10 ; x − y = 2.",c:["x = 5 et y = 5","x = 4 et y = 6","x = 6 et y = 4","x = 8 et y = 2"],a:2,exp:"x = 6 puis y = 4"},
    {q:"Résoudre le système 2x + y = 7 ; x − y = −1.",c:["x = 3 et y = 2","x = 1 et y = 5","x = 2 et y = 1","x = 2 et y = 3"],a:3,exp:"On additionne : 3x = 6"},
    {q:"Un problème de programmation linéaire consiste à…",c:["résoudre une équation du second degré","calculer une dérivée","résoudre un système à une seule inconnue","optimiser une fonction linéaire de deux variables sous des contraintes d'inéquations"],a:3,exp:"Résolution graphique"},
    {q:"Résoudre un système à l'aide d'un changement d'inconnues, c'est poser…",c:["par exemple X = 1/x et Y = 1/y pour se ramener à un système linéaire","x = 0","X = x² seulement","x = y"],a:0,exp:"Méthode du guide"},
    {q:"Pour résoudre une équation comportant ln, on commence par…",c:["multiplier par ln","poser x = 0","déterminer l'ensemble de définition D","dériver les deux membres"],a:2,exp:"Méthode du guide"},
    {q:"Après avoir trouvé les solutions d'une équation comportant ln, on ne retient que…",c:["toutes les solutions trouvées","celles appartenant à l'ensemble D","les solutions négatives","les solutions entières"],a:1,exp:"Méthode du guide"},
    {q:"Résoudre ln(x + 1) = ln 3.",c:["x = 2","x = 3","x = 0","x = 1"],a:0,exp:"x + 1 = 3 avec x > −1"},
    {q:"Résoudre ln(x − 1) + ln(x + 1) = ln 8 (x > 1).",c:["x = −3","x = 2","x = 9","x = 3"],a:3,exp:"x² − 1 = 8 ; on garde x = 3"},
    {q:"Résoudre e^(2x) − 3eˣ + 2 = 0.",c:["x = 0 ou x = ln 2","x = 0 ou x = 2","x = ln 1 ou x = ln 3","x = 1 ou x = 2"],a:0,exp:"X = eˣ : X² − 3X + 2 = 0"},
    {q:"Résoudre eˣ < 5.",c:["x > ln 5","x < 5","x < ln 5","x < e⁵"],a:2,exp:"exp est croissante"},
    {q:"Résoudre l'inéquation qⁿ ≥ k avec q > 1 :",c:["n ≥ k − q","n = k/q","on passe par le logarithme : n ≥ (ln k)/(ln q)","n ≤ k/q"],a:2,exp:"Méthode du guide"},
    {q:"Une inéquation du second degré se résout à l'aide de…",c:["d'un changement de base","d'une dérivée seulement","l'étude du signe du trinôme","d'une limite"],a:2,exp:"Signe d'un polynôme du second degré"},
  ],
  "TleA — Entiers naturels, numération & récurrence": [
    {q:"Tout entier naturel non nul s'écrit en base b (b ≥ 2)…",c:["de plusieurs façons","seulement si b est premier","de façon unique comme somme de multiples de puissances de b","seulement en base 10"],a:2,exp:"Propriété admise"},
    {q:"1101001 en base 2 vaut, en base 10…",c:["97","121","209","105"],a:3,exp:"64 + 32 + 8 + 1"},
    {q:"105 s'écrit en base 8…",c:["1 015","511","105","151"],a:3,exp:"105 = 1×64 + 5×8 + 1"},
    {q:"37 s'écrit en base 2…",c:["100101","110001","101001","100111"],a:0,exp:"32 + 4 + 1"},
    {q:"Pour écrire un entier en base b, on effectue…",c:["des divisions euclidiennes successives par b","des additions de b","des multiplications par b","des soustractions de b²"],a:0,exp:"Les restes successifs donnent les chiffres"},
    {q:"Les bases au programme incluent…",c:["1 et 2","3, 5 et 7 uniquement","2, 8, 10 et 60","100 et 1000"],a:2,exp:"Guide de Terminale A"},
    {q:"3 725 secondes s'écrivent en base 60 (heures ; minutes ; secondes)…",c:["2 ; 1 ; 5","3 ; 7 ; 25","1 ; 5 ; 2","1 ; 2 ; 5"],a:3,exp:"3 725 = 1 × 3 600 + 2 × 60 + 5"},
    {q:"Un entier est divisible par 2 si et seulement si son dernier chiffre est…",c:["0, 2, 4, 6 ou 8","0 ou 5","un multiple de 3","1, 3, 5, 7 ou 9"],a:0,exp:"Critère de divisibilité par 2"},
    {q:"Un entier est divisible par 5 si et seulement si son dernier chiffre est…",c:["0 ou 5","0 seulement","5 seulement","2 ou 7"],a:0,exp:"Critère de divisibilité par 5"},
    {q:"Un entier est divisible par 3 si et seulement si…",c:["son dernier chiffre est divisible par 3","la somme de ses chiffres est divisible par 3","il est impair","il se termine par 3"],a:1,exp:"Critère de divisibilité par 3"},
    {q:"Un entier est divisible par 9 si et seulement si…",c:["il se termine par 9","son dernier chiffre est 9","la somme de ses chiffres est divisible par 9","il est divisible par 3"],a:2,exp:"Critère de divisibilité par 9"},
    {q:"Le nombre 7 236 est divisible par…",c:["5","7","2 et 5","9"],a:3,exp:"7 + 2 + 3 + 6 = 18"},
    {q:"Pour démontrer par récurrence que P(n) est vraie pour tout n ≥ n₀, il faut démontrer que…",c:["P(n₀) est vraie, puis que P(k) ⟹ P(k + 1) pour tout k ≥ n₀","P(k + 1) est vraie seulement","P(n₀) est vraie seulement","P est vraie pour n₀ et n₀ + 1 seulement"],a:0,exp:"Point de logique du guide"},
    {q:"Dans un raisonnement par récurrence, l'étape « P(k) ⟹ P(k + 1) » s'appelle…",c:["la conclusion","l'initialisation","l'hérédité","le contre-exemple"],a:2,exp:"Vocabulaire"},
    {q:"La propriété « 1 + 2 + … + n = n(n + 1)/2 » s'initialise pour n = 1 car…",c:["1 = 2","n(n + 1) = 0","1 = 1 × 2 / 2","1 + 2 = 3"],a:2,exp:"P(1) est vraie"},
  ],
  "TleA — Suites numériques": [
    {q:"Une suite arithmétique de premier terme U₀ et de raison r vérifie Uₙ = …",c:["U₀ + r","U₀ × rⁿ","n U₀ r","U₀ + n r"],a:3,exp:"Formule du terme général"},
    {q:"Une suite géométrique de premier terme U₀ et de raison q vérifie Uₙ = …",c:["n U₀ q","U₀ qⁿ⁻¹ seulement","U₀ × qⁿ","U₀ + n q"],a:2,exp:"Formule du terme général"},
    {q:"Un capital C placé à intérêts simples au taux t pendant n ans devient…",c:["C(1 + t)ⁿ","C n t","C + t","C(1 + n t)"],a:3,exp:"Suite arithmétique"},
    {q:"Un capital C placé à intérêts composés au taux t pendant n ans devient…",c:["C t ⁿ","C(1 + t)ⁿ","C(1 + n t)","C + n t"],a:1,exp:"Suite géométrique"},
    {q:"100 000 F placés à 5 % à intérêts composés pendant 2 ans deviennent…",c:["110 250 F","110 000 F","100 250 F","105 000 F"],a:0,exp:"100 000 × 1,05²"},
    {q:"100 000 F placés à 5 % à intérêts simples pendant 2 ans deviennent…",c:["110 250 F","110 000 F","105 000 F","102 500 F"],a:1,exp:"100 000 × (1 + 2 × 0,05)"},
    {q:"Si Uₙ₊₁ − Uₙ ≥ 0 pour tout n, alors la suite (Uₙ) est…",c:["constante","divergente","croissante","décroissante"],a:2,exp:"Méthode algébrique"},
    {q:"Si Uₙ = f(n) et f est croissante sur [n₀ ; +∞[, alors (Uₙ) est…",c:["croissante à partir du rang n₀","non monotone","constante","décroissante à partir du rang n₀"],a:0,exp:"Méthode fonctionnelle"},
    {q:"Une suite arithmétique de raison r > 0 est…",c:["constante","décroissante","géométrique","croissante"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une suite arithmétique de raison r < 0 est…",c:["croissante","décroissante","constante","convergente vers 0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Une suite géométrique à termes positifs de raison q > 1 est…",c:["croissante","alternée","décroissante","constante"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Une suite géométrique à termes positifs de raison 0 < q < 1 est…",c:["constante","décroissante","alternée","croissante"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Une suite est convergente lorsque…",c:["elle est croissante","elle est positive","elle est bornée uniquement","elle a une limite finie"],a:3,exp:"Définition du guide"},
    {q:"Une suite est divergente lorsque…",c:["elle n'est pas convergente","elle est décroissante","elle est négative","elle est arithmétique"],a:0,exp:"Définition du guide"},
    {q:"Si q > 1, la limite de qⁿ est…",c:["+∞","1","0","−∞"],a:0,exp:"Propriété admise"},
    {q:"Si −1 < q < 1, la limite de qⁿ est…",c:["1","−1","0","+∞"],a:2,exp:"Propriété admise"},
    {q:"Si q ≤ −1, la suite (qⁿ)…",c:["tend vers 0","n'a pas de limite","tend vers +∞","tend vers 1"],a:1,exp:"Propriété admise"},
    {q:"Si q = 1, la suite (qⁿ) est…",c:["constante égale à 1","croissante","divergente","nulle"],a:0,exp:"qⁿ = 1"},
    {q:"La limite de Uₙ = (2n + 1)/(n + 3) est…",c:["0","+∞","1/3","2"],a:3,exp:"On applique la limite de la fonction f(x) = (2x + 1)/(x + 3) en +∞"},
    {q:"La suite Uₙ = 3n + 2 est…",c:["convergente","constante","décroissante","croissante"],a:3,exp:"Suite arithmétique de raison 3"},
    {q:"La suite Uₙ = 1/(n + 1) est…",c:["divergente","croissante","décroissante et convergente vers 0","constante"],a:2,exp:"Uₙ₊₁ − Uₙ < 0 ; limite 0"},
  ],
  "TleA — Statistique à un caractère": [
    {q:"Pour représenter une série statistique, on peut utiliser…",c:["seulement une courbe","seulement un diagramme circulaire","seulement un tableau","un diagramme circulaire, en bâtons, à bandes ou un histogramme"],a:3,exp:"Représentations du guide"},
    {q:"Le mode d'une série statistique est…",c:["la valeur centrale","toute modalité d'effectif maximal","la moyenne","l'écart entre extrêmes"],a:1,exp:"Définition du guide"},
    {q:"La classe modale d'une série regroupée en classes est…",c:["la première classe","toute classe d'effectif maximal","la dernière classe","la classe centrale"],a:1,exp:"Définition du guide"},
    {q:"Le centre de la classe modale est appelé…",c:["la moyenne","la médiane","le mode de la série","l'étendue"],a:2,exp:"Convention du guide"},
    {q:"La moyenne d'une série à caractère discret s'obtient en…",c:["divisant la somme des modalités par 2","additionnant les effectifs","divisant la somme des produits (modalité × effectif) par l'effectif total","prenant la modalité centrale"],a:2,exp:"Méthode du guide"},
    {q:"Pour une série continue, on utilise pour la moyenne…",c:["les bornes inférieures","les amplitudes","les effectifs seulement","les centres des classes"],a:3,exp:"Méthode du guide"},
    {q:"Série : 2, 4, 6, 8 avec les effectifs 1, 2, 3, 4. La moyenne est…",c:["5","6","60","4,5"],a:1,exp:"(2 + 8 + 18 + 32)/10"},
    {q:"Série : 2, 4, 6, 8 avec les effectifs 1, 2, 3, 4. L'effectif total est…",c:["4","8","20","10"],a:3,exp:"1 + 2 + 3 + 4"},
    {q:"Série : 2, 4, 6, 8 avec les effectifs 1, 2, 3, 4. La médiane est…",c:["4","7","5","6"],a:3,exp:"Effectifs cumulés croissants 1, 3, 6, 10 ; N = 10 est pair : la médiane est la moyenne des 5ᵉ et 6ᵉ valeurs, toutes deux égales à 6"},
    {q:"Série : 2, 4, 6, 8 avec les effectifs 1, 2, 3, 4. Le mode est…",c:["6","5","2","8"],a:3,exp:"Effectif maximal : 4"},
    {q:"La variance d'une série est…",c:["la moyenne des écarts","la moyenne des carrés des écarts à la moyenne","la différence max − min","la médiane des écarts"],a:1,exp:"Définition du guide"},
    {q:"L'écart-type est…",c:["la racine carrée de la variance","la moyenne des écarts","la moitié de la variance","le carré de la variance"],a:0,exp:"Définition du guide"},
    {q:"Série : 2, 4, 6, 8 avec les effectifs 1, 2, 3, 4 (moyenne 6). La variance est…",c:["4","40","2","16"],a:0,exp:"(16 + 8 + 0 + 16)/10"},
    {q:"Série : 2, 4, 6, 8 avec les effectifs 1, 2, 3, 4. L'écart-type est…",c:["√2","√40","2","4"],a:2,exp:"√4"},
    {q:"Pour une série continue, la médiane peut se lire graphiquement comme l'abscisse du point du polygone des fréquences cumulées croissantes d'ordonnée…",c:["100 %","0 %","25 %","50 % (0,5)"],a:3,exp:"1re méthode du guide"},
    {q:"Le polygone des fréquences cumulées croissantes est utilisé pour déterminer…",c:["le mode seulement","la moyenne exacte","la médiane","l'étendue"],a:2,exp:"Méthode graphique"},
  ],
  "TleA — Statistique à deux caractères": [
    {q:"Un nuage de points est…",c:["un diagramme en bâtons","l'ensemble des points (xᵢ ; yᵢ) d'une série double","un histogramme","une droite"],a:1,exp:"Série statistique double"},
    {q:"Le point moyen G d'un nuage a pour coordonnées…",c:["(moyenne des x ; moyenne des y)","(somme des x ; somme des y)","(médiane des x ; médiane des y)","(mode des x ; mode des y)"],a:0,exp:"Définition"},
    {q:"Pour la méthode de Mayer, on partage le nuage en…",c:["deux sous-nuages d'effectifs quelconques","deux sous-nuages de même effectif","trois sous-nuages","un seul sous-nuage"],a:1,exp:"Méthode du guide"},
    {q:"On détermine ensuite…",c:["les modes","les écarts-types","les points moyens G₁ et G₂ des deux sous-nuages","les médianes"],a:2,exp:"Méthode du guide"},
    {q:"La droite de Mayer est…",c:["la droite horizontale passant par G","la droite (G₁G₂)","la droite passant par l'origine","la médiatrice de [G₁G₂]"],a:1,exp:"Méthode du guide"},
    {q:"Points (1 ; 2), (2 ; 4), (3 ; 6), (4 ; 8) : le point moyen G₁ des deux premiers points est…",c:["(1 ; 2)","(3 ; 6)","(2 ; 4)","(1,5 ; 3)"],a:3,exp:"Moyennes (1 + 2)/2 et (2 + 4)/2"},
    {q:"Points (1 ; 2), (2 ; 4), (3 ; 6), (4 ; 8) : le point moyen G₂ des deux derniers points est…",c:["(3,5 ; 7)","(3 ; 6)","(7 ; 14)","(4 ; 8)"],a:0,exp:"Moyennes (3 + 4)/2 et (6 + 8)/2"},
    {q:"Points (1 ; 2), (2 ; 4), (3 ; 6), (4 ; 8) : la droite de Mayer est…",c:["y = x + 1","y = 3x − 1","y = 2x + 1","y = 2x"],a:3,exp:"Pente (7 − 3)/(3,5 − 1,5) = 2 ; elle passe par (1,5 ; 3)"},
    {q:"Une droite d'ajustement permet de…",c:["construire un histogramme","calculer la médiane","déterminer le mode","estimer y pour une valeur de x non observée"],a:3,exp:"Utilisation de l'ajustement"},
    {q:"Si les deux sous-nuages ont le même effectif, le point moyen G du nuage est…",c:["toujours à l'origine","le milieu de [G₁G₂], donc il appartient à la droite de Mayer","à l'extérieur de la droite (G₁G₂)","confondu avec G₁"],a:1,exp:"G est le milieu de [G₁G₂] car les deux groupes ont même effectif"},
  ],
  "TleA — Probabilités": [
    {q:"Une expérience dont on ne peut pas prévoir le résultat est une…",c:["expérience aléatoire","expérience impossible","expérience certaine","expérience déterministe"],a:0,exp:"Définition du guide"},
    {q:"L'ensemble de toutes les éventualités est…",c:["le complémentaire","l'événement certain","l'événement impossible","l'univers"],a:3,exp:"Vocabulaire"},
    {q:"Un événement élémentaire est…",c:["l'ensemble de tous les résultats","un événement contraire","un événement de probabilité 1","un ensemble formé d'un seul résultat"],a:3,exp:"Vocabulaire du guide"},
    {q:"L'événement « A ou B » est formé…",c:["des résultats favorables à l'un au moins des événements A ou B","d'un seul résultat","des résultats favorables aux deux événements","des résultats non favorables à A"],a:0,exp:"A ∪ B"},
    {q:"L'événement « A et B » est formé…",c:["des résultats favorables à A ou B","de tous les résultats","des résultats favorables à la fois à A et à B","des résultats contraires à A"],a:2,exp:"A ∩ B"},
    {q:"Deux événements sont incompatibles lorsque…",c:["leur réunion est certaine","ils n'ont aucun résultat favorable en commun","leurs probabilités sont égales","ils sont contraires"],a:1,exp:"A ∩ B = ∅"},
    {q:"L'événement contraire de A est formé…",c:["de tous les résultats non favorables à A","d'un seul résultat","du seul résultat impossible","de tous les résultats favorables à A"],a:0,exp:"Vocabulaire du guide"},
    {q:"En situation d'équiprobabilité avec n éventualités, la probabilité d'un événement élémentaire est…",c:["1/2","n","n − 1","1/n"],a:3,exp:"Propriété admise"},
    {q:"La probabilité d'un événement est toujours…",c:["supérieure à 1","égale à 1/2","négative","comprise entre 0 et 1"],a:3,exp:"Propriété admise"},
    {q:"La probabilité de l'événement certain est… et celle de l'événement impossible est…",c:["0 et 1","1 et 0","1 et 1/2","1/2 et 0"],a:1,exp:"Propriété admise"},
    {q:"En situation d'équiprobabilité, p(A) = …",c:["nombre de cas possibles / nombre de cas favorables","nombre de cas favorables / nombre de cas possibles","1/2","p(A) + 1"],a:1,exp:"Propriété admise"},
    {q:"La somme des probabilités de deux événements contraires est…",c:["2","0","1/2","1"],a:3,exp:"Propriété admise"},
    {q:"p(A ∪ B) = …",c:["p(A) − p(B)","p(A) + p(B) − p(A ∩ B)","p(A) × p(B)","p(A) + p(B) + p(A ∩ B)"],a:1,exp:"Propriété admise"},
    {q:"On lance un dé équilibré. La probabilité d'obtenir un nombre pair est…",c:["1/6","1/3","1/2","2/3"],a:2,exp:"3 résultats sur 6"},
    {q:"On lance deux dés équilibrés. Le nombre d'issues possibles est…",c:["24","12","6","36"],a:3,exp:"6 × 6"},
    {q:"On lance deux dés. La probabilité d'obtenir au moins un 6 est…",c:["11/36","1/6","2/6","1/3"],a:0,exp:"1 − (5/6)² = 11/36"},
    {q:"Pour calculer la probabilité d'un événement défini par « au moins un », il est souvent plus simple de calculer…",c:["la probabilité de l'événement contraire","la moyenne","la probabilité de l'intersection","la probabilité de l'union"],a:0,exp:"Méthode du guide"},
    {q:"On tire une carte dans un jeu de 32 cartes. La probabilité d'obtenir un as est…",c:["4/8","1/32","1/8","1/4"],a:2,exp:"4 as sur 32"},
    {q:"p(A) = 0,3 et p(B) = 0,5 avec A et B incompatibles : p(A ∪ B) = …",c:["0,5","0,2","0,8","0,15"],a:2,exp:"p(A) + p(B)"},
    {q:"Si p(A) = 0,35, alors la probabilité de l'événement contraire est…",c:["0,7","0,65","0,35","1,35"],a:1,exp:"1 − 0,35"},
  ],
  "TleA — Prop. & Déf.": [
    {q:"Définition : une fonction est paire si…",c:["f(−x) = −f(x)","f(−x) = f(x) pour tout x du domaine (domaine symétrique)","f(x) = 0","f(x) > 0"],a:1,exp:"Parité"},
    {q:"Propriété : la droite x = a est axe de symétrie de (Cf) si…",c:["f(a − h) = f(a + h)","f(a) = 0","f(h) = f(−h)","f(a + h) = −f(a − h)"],a:0,exp:"Symétrie"},
    {q:"Propriété : lorsqu'une fonction admet une limite en +∞, cette limite est…",c:["toujours nulle","toujours infinie","unique","double"],a:2,exp:"Unicité de la limite"},
    {q:"Propriété : à l'infini, un polynôme a même limite que…",c:["sa dérivée","son terme constant","son coefficient dominant seulement","son monôme de plus haut degré"],a:3,exp:"Limite d'un polynôme"},
    {q:"Propriété : à l'infini, une fraction rationnelle a même limite que…",c:["son numérateur","son dénominateur","le quotient des termes constants","le quotient des monômes de plus haut degré"],a:3,exp:"Limite d'une fraction rationnelle"},
    {q:"Propriété : une fonction dérivable sur un intervalle est…",c:["positive","continue sur cet intervalle","monotone","constante"],a:1,exp:"Dérivabilité et continuité"},
    {q:"Propriété : une équation de la tangente en x₀ est…",c:["y = f'(x₀)(x − x₀) + f(x₀)","y = f'(x₀)","y = x₀ f(x)","y = f(x₀)(x − x₀) + f'(x₀)"],a:0,exp:"Tangente"},
    {q:"Propriété : si f' est positive sur un intervalle ouvert K, alors f est…",c:["nulle","croissante sur K","décroissante sur K","constante"],a:1,exp:"Sens de variation"},
    {q:"Définition : une asymptote y = l existe si…",c:["f est croissante","f a pour limite l en +∞ ou −∞","f(x₀) = l","f est constante"],a:1,exp:"Asymptote horizontale"},
    {q:"Définition : ln est la fonction définie sur ]0 ; +∞[ qui s'annule en 1 et a pour dérivée…",c:["x ↦ 1/x","x ↦ ln x","x ↦ eˣ","x ↦ x"],a:0,exp:"Définition de ln"},
    {q:"Propriété : ln(ab) = …",c:["ln a + ln b","ln a − ln b","ln(a + b)","ln a × ln b"],a:0,exp:"Propriété fondamentale"},
    {q:"Définition : e est l'unique nombre tel que…",c:["ln e = 0","e = ln e","ln e = 1","e = 1"],a:2,exp:"Base du logarithme népérien"},
    {q:"Définition : la fonction exponentielle est…",c:["la dérivée de ln","la primitive de ln","la réciproque de la fonction ln","l'inverse de ln"],a:2,exp:"Exponentielle"},
    {q:"Propriété : la dérivée de eˣ est…",c:["eˣ","x eˣ","1/eˣ","−eˣ"],a:0,exp:"Exponentielle"},
    {q:"Propriété : eᵃ = eᵇ équivaut à…",c:["a = 1","a = b","a = e","a + b = 0"],a:1,exp:"Exponentielle"},
    {q:"Propriété : un entier est divisible par 9 si et seulement si…",c:["son dernier chiffre est 9","il est pair","la somme de ses chiffres est divisible par 9","il se termine par 5"],a:2,exp:"Divisibilité"},
    {q:"Méthode : pour démontrer P(n) pour tout n ≥ n₀, on démontre…",c:["P(n₀) seulement","P(n₀) et P(n₀ + 1) seulement","P(n₀) puis P(k) ⟹ P(k + 1)","P(k + 1) seulement"],a:2,exp:"Récurrence"},
    {q:"Propriété : une suite arithmétique de raison r > 0 est…",c:["décroissante","géométrique","croissante","constante"],a:2,exp:"Suites"},
    {q:"Propriété : si q > 1, la limite de qⁿ est…",c:["+∞","0","1","−∞"],a:0,exp:"Suites géométriques"},
    {q:"Définition : une suite est convergente si…",c:["elle est croissante","elle est bornée","elle a une limite finie","elle est positive"],a:2,exp:"Suites convergentes"},
    {q:"Définition : la variance d'une série est…",c:["la moyenne des écarts","la moyenne des carrés des écarts à la moyenne","la médiane des écarts","la différence max − min"],a:1,exp:"Statistique"},
    {q:"Définition : le mode d'une série statistique est…",c:["la plus grande valeur","la valeur centrale","la moyenne","toute modalité d'effectif maximal"],a:3,exp:"Statistique"},
    {q:"Méthode : la droite de Mayer est…",c:["la droite passant par les points moyens G₁ et G₂ des deux sous-nuages","la droite passant par l'origine et G","la médiatrice de [G₁G₂]","la droite horizontale passant par G"],a:0,exp:"Ajustement"},
    {q:"Propriété : p(A) + p(contraire de A) = …",c:["1/2","1","2","0"],a:1,exp:"Probabilités"},
    {q:"Propriété : p(A ∪ B) = …",c:["p(A) + p(B) − p(A ∩ B)","p(A) × p(B)","p(A) + p(B) + p(A ∩ B)","p(A) − p(B)"],a:0,exp:"Probabilités"},
    {q:"Propriété : en équiprobabilité, p(A) = …",c:["p(A)²","cas favorables / cas possibles","cas possibles / cas favorables","1/2"],a:1,exp:"Probabilités"},
  ],
});
