/* Questions de la classe de Tle D (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "TleD — Vecteurs de l'espace & barycentre": [
    {q:"Dans un cube ABCDEFGH (E au-dessus de A, F au-dessus de B), les vecteurs →AB et →EF sont…",c:["opposés","orthogonaux","égaux","non coplanaires"],a:2,exp:"Ils ont même direction, même sens et même longueur"},
    {q:"Trois vecteurs de l'espace sont coplanaires lorsque…",c:["ils sont deux à deux colinéaires","leurs représentants de même origine sont dans un même plan","ils ont la même norme","ils sont orthogonaux deux à deux"],a:1,exp:"Définition de la coplanarité"},
    {q:"Dans le cube ABCDEFGH, les vecteurs →AB, →AD et →AE sont…",c:["coplanaires","colinéaires","non coplanaires","égaux"],a:2,exp:"Ils dirigent trois arêtes issues de A"},
    {q:"Dans le cube ABCDEFGH, les vecteurs →AB et →AD sont…",c:["colinéaires","orthogonaux","opposés","égaux"],a:1,exp:"Deux arêtes perpendiculaires"},
    {q:"Le barycentre G de (A, α) et (B, β) avec α + β ≠ 0 est défini par…",c:["α→GA + β→GB = →0","α + β = 0","α→AG + β→BG = →AB","→GA = →GB"],a:0,exp:"Définition du barycentre de deux points pondérés"},
    {q:"G est le barycentre de (A, 1) et (B, 3). Alors →AG = …",c:["(1/4) →AB","(3/4) →AB","(1/3) →AB","3 →AB"],a:1,exp:"G = (A + 3B)/4"},
    {q:"Le barycentre de (A, 2) et (B, 2) est…",c:["un point extérieur à (AB)","le point B","le milieu de [AB]","le point A"],a:2,exp:"Coefficients égaux : isobarycentre"},
    {q:"Le barycentre de (A, 1) et (B, −1)…",c:["n'existe pas, car la somme des coefficients est nulle","est le milieu de [AB]","est le point A","est à l'infini seulement"],a:0,exp:"Il faut α + β ≠ 0"},
    {q:"Propriété d'homogénéité : le barycentre de (Aᵢ, αᵢ) ne change pas si on…",c:["ajoute 1 à chaque coefficient","multiplie un seul coefficient par 2","multiplie tous les coefficients par un même réel non nul","change l'ordre des points seulement"],a:2,exp:"Homogénéité du barycentre"},
    {q:"Pour G barycentre de (Aᵢ, αᵢ) avec Σαᵢ ≠ 0 et tout point M : Σ αᵢ →MAᵢ = …",c:["→0","(Σ αᵢ)² →MG","Σ αᵢ × MG","(Σ αᵢ) →MG"],a:3,exp:"Réduction de la somme vectorielle"},
    {q:"Le barycentre de (A, 1), (B, 1) et (C, 1) est…",c:["le centre de gravité du triangle ABC","l'orthocentre de ABC","le centre du cercle circonscrit","le milieu de [AB]"],a:0,exp:"Isobarycentre de trois points"},
    {q:"Les barycentres partiels permettent de…",c:["supprimer un des points","remplacer certains points pondérés par leur barycentre affecté de la somme de leurs coefficients","annuler un coefficient","ajouter un point quelconque"],a:1,exp:"Associativité du barycentre"},
    {q:"Les coordonnées du barycentre de A(1 ; 2 ; 3) de coefficient 1 et B(5 ; 6 ; 7) de coefficient 3 sont…",c:["(2 ; 3 ; 4)","(6 ; 8 ; 10)","(3 ; 4 ; 5)","(4 ; 5 ; 6)"],a:3,exp:"G = (A + 3B)/4"},
  ],
  "TleD — Produit scalaire & orthogonalité dans l'espace": [
    {q:"Deux droites sont orthogonales si et seulement si un vecteur directeur de l'une est… à un vecteur directeur de l'autre.",c:["opposé","égal","colinéaire","orthogonal"],a:3,exp:"Propriété du guide"},
    {q:"Deux droites sont parallèles si et seulement si un vecteur directeur de l'une est… à un vecteur directeur de l'autre.",c:["égal en norme seulement","de norme 1","colinéaire","orthogonal"],a:2,exp:"Propriété du guide"},
    {q:"Un vecteur normal à un plan est tout vecteur directeur…",c:["d'une droite quelconque","d'une droite parallèle à ce plan","d'une droite contenue dans ce plan","d'une droite perpendiculaire à ce plan"],a:3,exp:"Définition du guide"},
    {q:"Une droite est perpendiculaire à un plan si et seulement si un de ses vecteurs directeurs est…",c:["nul","un vecteur normal à ce plan","de norme 1","orthogonal à un vecteur normal du plan"],a:1,exp:"Propriété du guide"},
    {q:"Une droite est parallèle à un plan si et seulement si un de ses vecteurs directeurs est… à un vecteur normal du plan.",c:["orthogonal","égal","opposé","colinéaire"],a:0,exp:"Propriété du guide"},
    {q:"Deux plans sont perpendiculaires si et seulement si un vecteur normal à l'un est… à un vecteur normal à l'autre.",c:["égal","colinéaire","de même norme","orthogonal"],a:3,exp:"Propriété du guide"},
    {q:"Deux plans sont parallèles si et seulement si un vecteur normal à l'un est… à un vecteur normal à l'autre.",c:["orthogonal","de norme différente","colinéaire","nul"],a:2,exp:"Propriété du guide"},
    {q:"Dans une base orthonormée, →u(x ; y ; z) ⋅ →v(x' ; y' ; z') = …",c:["x + y + z + x' + y' + z'","xx' − yy' − zz'","xy' + yz' + zx'","xx' + yy' + zz'"],a:3,exp:"Expression analytique du produit scalaire"},
    {q:"Les vecteurs →u(1 ; 2 ; 3) et →v(2 ; −1 ; 0) sont…",c:["orthogonaux","opposés","colinéaires","égaux"],a:0,exp:"→u ⋅ →v = 2 − 2 + 0 = 0"},
    {q:"La norme du vecteur →u(2 ; 3 ; 6) est…",c:["7","11","√11","5"],a:0,exp:"√(4 + 9 + 36) = √49"},
    {q:"‖→u + →v‖² = …",c:["‖→u‖² − 2 →u ⋅ →v + ‖→v‖²","(‖→u‖ + ‖→v‖)²","‖→u‖² + ‖→v‖²","‖→u‖² + 2 →u ⋅ →v + ‖→v‖²"],a:3,exp:"Identité du produit scalaire"},
    {q:"L'angle entre →u(1 ; 0 ; 1) et →v(0 ; 0 ; 2) mesure…",c:["45°","60°","30°","90°"],a:0,exp:"cos θ = 2/(√2 × 2) = √2/2"},
  ],
  "TleD — Plans, droites & distances dans l'espace": [
    {q:"Un plan de vecteur normal →n(a ; b ; c) a une équation de la forme…",c:["ax² + by² + cz² = d","ax + by + c = 0","ax + by + cz + d = 0","a + b + c + d = 0"],a:2,exp:"Équation cartésienne d'un plan"},
    {q:"Le plan passant par A(1 ; 0 ; 2) et de vecteur normal →n(2 ; −1 ; 3) a pour équation…",c:["2x − y + 3z + 8 = 0","2x + y + 3z − 8 = 0","2x − y + 3z − 8 = 0","x − 2y + 3z − 8 = 0"],a:2,exp:"2(x − 1) − y + 3(z − 2) = 0"},
    {q:"Un vecteur normal au plan 3x − y + 2z − 5 = 0 est…",c:["(−5 ; 0 ; 0)","(3 ; −1 ; 2)","(3 ; 1 ; 2)","(1 ; −3 ; 2)"],a:1,exp:"Les coefficients de x, y, z"},
    {q:"Le point A(1 ; 1 ; 1) appartient au plan x + y + z − 3 = 0 car…",c:["1 − 1 − 1 = 3","1 × 1 × 1 = 3","A est l'origine","1 + 1 + 1 − 3 = 0"],a:3,exp:"Ses coordonnées vérifient l'équation"},
    {q:"La distance du point M₀(x₀ ; y₀ ; z₀) au plan ax + by + cz + d = 0 est…",c:["(ax₀ + by₀ + cz₀ + d)/(a + b + c)","|ax₀ + by₀ + cz₀ + d| / √(a² + b² + c²)","|ax₀ + by₀ + cz₀ + d|","√(a² + b² + c²)"],a:1,exp:"Formule de la distance point-plan"},
    {q:"La distance de l'origine au plan 2x − 2y + z − 9 = 0 est…",c:["√14","1","9","3"],a:3,exp:"9/√(4 + 4 + 1) = 9/3"},
    {q:"La distance du point A(1 ; 2 ; 2) au plan x + 2y + 2z + 3 = 0 est…",c:["3","2","4","12"],a:2,exp:"|1 + 4 + 4 + 3|/3 = 12/3"},
    {q:"La distance de A(2 ; 1 ; 3) au plan x − 2y + 2z − 6 = 0 est…",c:["0","2","1","6"],a:0,exp:"2 − 2 + 6 − 6 = 0 : A appartient au plan"},
    {q:"Une représentation paramétrique d'un plan passant par A de vecteurs directeurs →u et →v non colinéaires traduit que…",c:["→AM = →u + →v","→AM = →u ∧ →v","→AM = s →u + t →v (s et t réels)","AM = ‖→u‖ + ‖→v‖"],a:2,exp:"Combinaison linéaire de deux vecteurs directeurs"},
    {q:"Une représentation paramétrique de la droite passant par A(1 ; 2 ; 3) de vecteur directeur →u(2 ; −1 ; 4) est…",c:["x = 2t ; y = −t ; z = 4t","x = 1 + 2t ; y = 2 + t ; z = 3 − 4t","x = 1 + 2t ; y = 2 − t ; z = 3 + 4t","x = 2 + t ; y = −1 + 2t ; z = 4 + 3t"],a:2,exp:"Point + t fois le vecteur directeur"},
    {q:"Un système d'équations cartésiennes d'une droite de l'espace exprime que la droite est…",c:["perpendiculaire à un plan","contenue dans un seul plan","parallèle à un plan","l'intersection de deux plans sécants"],a:3,exp:"Deux équations de plans"},
    {q:"Deux plans non parallèles se coupent suivant…",c:["un point","une droite","un plan","l'ensemble vide"],a:1,exp:"Intersection de deux plans sécants"},
    {q:"Le plan x + y + z = 3 et la droite x = t ; y = 1 ; z = 2 − t : la droite est…",c:["parallèle au plan sans y être contenue","perpendiculaire au plan","contenue dans le plan","sécante au plan en un point"],a:2,exp:"t + 1 + 2 − t = 3 pour tout t"},
    {q:"Un vecteur normal au plan de vecteurs directeurs →u(1 ; 0 ; 0) et →v(0 ; 1 ; 0) est…",c:["(0 ; 0 ; 1)","(1 ; 1 ; 0)","(1 ; 0 ; 1)","(0 ; 1 ; 1)"],a:0,exp:"→u ∧ →v = →k"},
  ],
  "TleD — Systèmes d'équations linéaires (pivot de Gauss)": [
    {q:"La méthode du pivot de Gauss consiste à…",c:["supprimer une inconnue au hasard","résoudre chaque équation séparément","tracer les plans","transformer le système en un système équivalent triangulaire"],a:3,exp:"Échelonnement du système"},
    {q:"Quelle opération n'est pas permise dans la méthode de Gauss ?",c:["multiplier une équation par un réel non nul","ajouter à une équation un multiple d'une autre","permuter deux équations","multiplier une équation par 0"],a:3,exp:"Multiplier par 0 ne conserve pas l'équivalence"},
    {q:"Résoudre x + y + z = 6 ; x − y + z = 2 ; x + y − z = 0.",c:["(1 ; 3 ; 2)","(3 ; 2 ; 1)","(2 ; 1 ; 3)","(1 ; 2 ; 3)"],a:3,exp:"Eq1 + Eq3 : x + y = 3 puis z = 3 ; Eq2 donne x − y = −1"},
    {q:"Résoudre x + y + z = 3 ; y + z = 2 ; z = 1.",c:["(2 ; 1 ; 0)","(1 ; 1 ; 1)","(0 ; 1 ; 2)","(1 ; 2 ; 0)"],a:1,exp:"Système triangulaire : on remonte"},
    {q:"Un système linéaire peut avoir…",c:["aucune solution, une seule solution ou une infinité de solutions","exactement deux solutions","seulement une infinité de solutions","toujours une seule solution"],a:0,exp:"Trois cas possibles"},
    {q:"Le système x + y = 2 ; 2x + 2y = 5 a…",c:["deux solutions","une infinité de solutions","une seule solution","aucune solution"],a:3,exp:"Droites parallèles distinctes"},
    {q:"Le système x + y − z = 1 ; 2x + 2y − 2z = 2 ; x − y = 0 a…",c:["aucune solution","exactement deux solutions","une seule solution","une infinité de solutions"],a:3,exp:"Deux équations identiques : z = 2x − 1 avec x = y"},
    {q:"Pour espérer une solution unique dans un système à 3 inconnues, il faut…",c:["un second membre nul","au moins trois équations indépendantes","deux équations dépendantes","une seule équation"],a:1,exp:"Autant d'équations indépendantes que d'inconnues"},
  ],
  "TleD — Produit vectoriel": [
    {q:"Dans une base orthonormée directe (→i, →j, →k), →i ∧ →j = …",c:["→k","→0","−→k","→j"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Dans une base orthonormée directe, →j ∧ →k = …",c:["→k","→i","−→i","→0"],a:1,exp:"Permutation circulaire"},
    {q:"Dans une base orthonormée directe, →k ∧ →i = …",c:["−→j","→0","→j","→i"],a:2,exp:"Permutation circulaire"},
    {q:"Pour tous vecteurs →u et →v, →u ∧ →v = …",c:["→u ⋅ →v","→v ∧ →u","→0","−(→v ∧ →u)"],a:3,exp:"Le produit vectoriel est antisymétrique"},
    {q:"→u ∧ →v = →0 si et seulement si…",c:["→u et →v sont orthogonaux","‖→u‖ = ‖→v‖","→u = →v seulement","→u et →v sont colinéaires"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Les coordonnées de →u(x ; y ; z) ∧ →v(x' ; y' ; z') sont…",c:["(x + x' ; y + y' ; z + z')","(xx' ; yy' ; zz')","(xy' − yx' ; yz' − zy' ; zx' − xz')","(yz' − zy' ; zx' − xz' ; xy' − yx')"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Calculer →u(1 ; 2 ; 3) ∧ →v(0 ; 1 ; 0).",c:["(2 ; 3 ; 1)","(3 ; 0 ; −1)","(−3 ; 0 ; 1)","(0 ; 0 ; 0)"],a:2,exp:"(2×0 − 3×1 ; 3×0 − 1×0 ; 1×1 − 2×0)"},
    {q:"Pour A, B, C non alignés, →AB ∧ →AC est…",c:["un vecteur normal au plan (ABC)","le vecteur nul","un vecteur de norme 1","un vecteur du plan (ABC)"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Les points A, B, C sont alignés si et seulement si…",c:["→AB ∧ →AC = →0","→AB ⋅ →AC = 0","AB = AC","→AB = →AC"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Les points A, B, C, D sont coplanaires si et seulement si…",c:["→AB + →AC + →AD = →0","→AB ⋅ →AC = →AD","→AB ∧ →AC = →AD","→AB ⋅ (→AC ∧ →AD) = 0"],a:3,exp:"Produit mixte nul"},
    {q:"L'aire du triangle ABC est égale à…",c:["(1/2) ‖→AB ∧ →AC‖","‖→AB ∧ →AC‖","(1/2) →AB ⋅ →AC","AB × AC"],a:0,exp:"Application du produit vectoriel"},
    {q:"A(0 ; 0 ; 0), B(1 ; 0 ; 0), C(0 ; 2 ; 0) : l'aire du triangle ABC est…",c:["2","1","1/2","√5/2"],a:1,exp:"→AB ∧ →AC = (0 ; 0 ; 2), norme 2, donc aire 1"},
    {q:"Le volume du tétraèdre ABCD est égal à…",c:["(1/6) |→AB ⋅ (→AC ∧ →AD)|","|→AB ⋅ (→AC ∧ →AD)|","(1/2) ‖→AB ∧ →AC‖","(1/3) AB × AC × AD"],a:0,exp:"Produit mixte divisé par 6"},
    {q:"La distance d'un point M à la droite (AB) est égale à…",c:["‖→AM ∧ →AB‖ / AB","‖→AM ∧ →AB‖ × AB","‖→AM ⋅ →AB‖ / AB","AM × AB"],a:0,exp:"Application du produit vectoriel"},
    {q:"Le volume du tétraèdre OIJK avec O(0 ; 0 ; 0), I(1 ; 0 ; 0), J(0 ; 1 ; 0), K(0 ; 0 ; 1) est…",c:["1/6","1","1/2","1/3"],a:0,exp:"|1|/6"},
  ],
  "TleD — Nombres complexes : forme algébrique": [
    {q:"Dans ℂ, le nombre i vérifie…",c:["i² = 1","i² = −1","i² = 0","i = −1"],a:1,exp:"Définition de i"},
    {q:"Pour z = 3 − 2i, on a…",c:["Re(z) = −2 et Im(z) = 3","Re(z) = 3 et Im(z) = −2i","Re(z) = 1 et Im(z) = 1","Re(z) = 3 et Im(z) = −2"],a:3,exp:"Partie réelle 3, partie imaginaire −2"},
    {q:"Le nombre z = 5i est…",c:["de partie réelle non nulle","imaginaire pur","égal à 5","réel"],a:1,exp:"a = 0 et b ≠ 0"},
    {q:"z = z' si et seulement si…",c:["z − z' est imaginaire pur","Re(z) = Re(z') et Im(z) = Im(z')","Re(z) = Im(z')","|z| = |z'|"],a:1,exp:"Propriété admise"},
    {q:"z = 0 si et seulement si…",c:["Re(z) = 0 et Im(z) = 0","|z| = 1","Re(z) = Im(z)","Re(z) = 0 ou Im(z) = 0"],a:0,exp:"Propriété démontrée en classe"},
    {q:"(2 + 3i) + (1 − 5i) = …",c:["3 − 2i","1 − 2i","3 + 8i","3 − 8i"],a:0,exp:"Somme des parties réelles et imaginaires"},
    {q:"(2 + 3i)(1 − i) = …",c:["5 + i","−1 + 5i","5 − i","2 − 3i"],a:0,exp:"2 − 2i + 3i − 3i² = 2 + i + 3"},
    {q:"i³ = …",c:["i","1","−i","−1"],a:2,exp:"i² × i"},
    {q:"i²⁰²⁶ = …",c:["1","−1","i","−i"],a:1,exp:"2026 = 4 × 506 + 2"},
    {q:"L'inverse de 1 + i est…",c:["1/2","(1 + i)/2","1 − i","(1 − i)/2"],a:3,exp:"1/(1 + i) = (1 − i)/((1 + i)(1 − i))"},
    {q:"1/(2 − i) = …",c:["2 + i","(2 + i)/3","(2 − i)/5","(2 + i)/5"],a:3,exp:"On multiplie par 2 + i"},
    {q:"zz' = 0 si et seulement si…",c:["z + z' = 0","z = 0 et z' = 0","z = z'","z = 0 ou z' = 0"],a:3,exp:"Propriété démontrée en classe"},
    {q:"(2 + i)(2 − i) = …",c:["5","3","4","1"],a:0,exp:"4 − i² = 5"},
    {q:"L'ensemble des imaginaires purs est noté…",c:["ℤ","iℝ","ℂ*","ℝ"],a:1,exp:"Notation du guide"},
  ],
  "TleD — Conjugué & module": [
    {q:"Le conjugué de 3 − 4i est…",c:["−3 + 4i","3 + 4i","−3 − 4i","4 − 3i"],a:1,exp:"On change le signe de la partie imaginaire"},
    {q:"Pour z = a + ib, z × conj(z) = …",c:["2a","a² + b²","a² − b²","2ib"],a:1,exp:"Propriété démontrée en classe"},
    {q:"z + conj(z) = …",c:["2i Im(z)","|z|²","2 Re(z)","0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"z − conj(z) = …",c:["2i Im(z)","0","2 Re(z)","|z|"],a:0,exp:"Propriété démontrée en classe"},
    {q:"z est réel si et seulement si…",c:["|z| = 1","Im(z) = 1","conj(z) = −z","conj(z) = z"],a:3,exp:"Propriété démontrée en classe"},
    {q:"z est imaginaire pur (z ≠ 0) si et seulement si…",c:["conj(z) = −z","conj(z) = z","Re(z) ≠ 0","z = 1"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Le module de 3 − 4i est…",c:["5","7","√7","1"],a:0,exp:"√(9 + 16)"},
    {q:"Pour M d'affixe z, OM = …",c:["Re(z)","z²","Im(z)","|z|"],a:3,exp:"Interprétation géométrique du module"},
    {q:"Pour M et M' d'affixes z et z', MM' = …",c:["|z'| + |z|","z' − z","|z' − z|","|z' + z|"],a:2,exp:"Distance entre deux points"},
    {q:"|zz'| = …",c:["|z + z'|","|z| + |z'|","|z|²","|z| × |z'|"],a:3,exp:"Propriété démontrée en classe"},
    {q:"|zⁿ| = … (n entier relatif)",c:["|z|ⁿ","n|z|","|z|/n","|z| + n"],a:0,exp:"Propriété démontrée en classe"},
    {q:"L'inégalité triangulaire s'écrit…",c:["|z + z'| ≥ |z| + |z'|","|z + z'| ≤ |z| + |z'|","|z + z'| < |z| − |z'|","|z + z'| = |z| + |z'|"],a:1,exp:"Propriété démontrée en classe"},
    {q:"|z| = 0 si et seulement si…",c:["Re(z) = 0","Im(z) = 0","z = 1","z = 0"],a:3,exp:"Propriété démontrée en classe"},
    {q:"La distance entre A(1 + i) et B(4 + 5i) est…",c:["7","3","√7","5"],a:3,exp:"|3 + 4i| = 5"},
    {q:"Le conjugué d'un produit est…",c:["la somme des conjugués","égal au produit","l'opposé du produit","le produit des conjugués"],a:3,exp:"conj(zz') = conj(z) conj(z')"},
  ],
  "TleD — Forme trigonométrique & exponentielle": [
    {q:"La forme trigonométrique d'un nombre complexe non nul z est…",c:["z = r + iθ","z = r(cos θ + i sin θ) avec r = |z| et θ = arg z","z = cos r + i sin r","z = r(cos θ − i sin θ)"],a:1,exp:"Définition du guide"},
    {q:"Le module et un argument de 1 + i sont…",c:["2 et π/4","√2 et π/2","√2 et π/4","1 et π/4"],a:2,exp:"|1 + i| = √2 ; cos θ = sin θ = √2/2"},
    {q:"Un argument de −1 est…",c:["−π/2","0","π/2","π"],a:3,exp:"−1 = cos π + i sin π"},
    {q:"Un argument de i est…",c:["π","0","π/2","−π/2"],a:2,exp:"i = cos(π/2) + i sin(π/2)"},
    {q:"arg(zz') = … (à 2π près)",c:["arg z × arg z'","arg z − arg z'","arg z + arg z'","2 arg z"],a:2,exp:"Propriété démontrée en classe"},
    {q:"arg(z/z') = … (à 2π près)",c:["arg z − arg z'","−arg z","arg z / arg z'","arg z + arg z'"],a:0,exp:"Propriété démontrée en classe"},
    {q:"arg(−z) = … (à 2π près)",c:["π/2 + arg z","−arg z","π + arg z","arg z"],a:2,exp:"Propriété démontrée en classe"},
    {q:"arg(zⁿ) = … (à 2π près)",c:["n arg z","(arg z)ⁿ","arg z / n","arg z + n"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La formule de Moivre s'écrit (cos θ + i sin θ)ⁿ = …",c:["cosⁿθ + i sinⁿθ","cos θ + i sin nθ","n cos θ + i n sin θ","cos nθ + i sin nθ"],a:3,exp:"Formule de Moivre"},
    {q:"e^(iθ) = …",c:["cos θ + i sin θ","cos θ × sin θ","cos θ − i sin θ","θ + i"],a:0,exp:"Forme exponentielle"},
    {q:"Formule d'Euler : cos θ = …",c:["e^(iθ) e^(−iθ)","(e^(iθ) + e^(−iθ))/2","(e^(iθ) − e^(−iθ))/2","(e^(iθ) + e^(−iθ))/(2i)"],a:1,exp:"Formules d'Euler"},
    {q:"Formule d'Euler : sin θ = …",c:["(e^(iθ) + e^(−iθ))/2","(e^(iθ) + e^(−iθ))/(2i)","(e^(iθ) − e^(−iθ))/2","(e^(iθ) − e^(−iθ))/(2i)"],a:3,exp:"Formules d'Euler"},
    {q:"Si z = 2e^(iπ/3), alors z² = …",c:["4e^(iπ/9)","2e^(2iπ/3)","4e^(iπ/3)","4e^(2iπ/3)"],a:3,exp:"Module 2² = 4 ; argument 2 × π/3"},
    {q:"(1 + i)⁸ = …",c:["16","16i","256","−16"],a:0,exp:"(√2 e^(iπ/4))⁸ = 16 e^(2iπ)"},
    {q:"La forme exponentielle de 1 − i est…",c:["e^(−iπ/4)","√2 e^(iπ/4)","2e^(−iπ/4)","√2 e^(−iπ/4)"],a:3,exp:"Module √2 ; argument −π/4"},
    {q:"e^(iπ) = …",c:["i","−1","1","−i"],a:1,exp:"cos π + i sin π"},
    {q:"Deux complexes non nuls sont égaux si et seulement s'ils ont…",c:["même module et arguments égaux à 2kπ près","même argument seulement","même module seulement","même partie réelle seulement"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Linéariser cos²θ donne…",c:["cos 2θ","(1 − cos 2θ)/2","(1 + cos 2θ)/2","2 cos θ"],a:2,exp:"Avec les formules d'Euler"},
    {q:"|e^(iθ)| = …",c:["1","θ","2","0"],a:0,exp:"cos²θ + sin²θ = 1"},
  ],
  "TleD — Équations dans ℂ & racines n-ièmes": [
    {q:"Les racines carrées de −9 dans ℂ sont…",c:["9i et −9i","3 et −3","aucune","3i et −3i"],a:3,exp:"(3i)² = −9"},
    {q:"Les solutions de z² + 4 = 0 sont…",c:["2i et −2i","aucune solution","4i et −4i","2 et −2"],a:0,exp:"z² = −4"},
    {q:"Les solutions de z² − 2z + 5 = 0 sont…",c:["−1 + 2i et −1 − 2i","1 + 2i et 1 − 2i","2 + i et 2 − i","1 + 4i et 1 − 4i"],a:1,exp:"z = (2 ± √(−16))/2 = 1 ± 2i"},
    {q:"Si Δ < 0 et si a, b, c sont réels, les solutions de az² + bz + c = 0 sont…",c:["deux nombres complexes conjugués","deux réels distincts","deux imaginaires purs toujours","un réel double"],a:0,exp:"Racines conjuguées"},
    {q:"Pour az² + bz + c = 0 de solutions z₁ et z₂ : z₁ + z₂ = … et z₁ z₂ = …",c:["−b et c","b/a et −c/a","−b/a et c/a","c/a et −b/a"],a:2,exp:"Relations coefficients-racines"},
    {q:"Les racines n-ièmes de re^(iα) sont zₖ = …",c:["r/n e^(iα)","ⁿ√r e^(iα n)","r e^(i(α + 2kπ)), k entier","ⁿ√r e^(i(α + 2kπ)/n), k = 0, …, n − 1"],a:3,exp:"Propriété admise"},
    {q:"Un nombre complexe non nul admet combien de racines n-ièmes ?",c:["1","n","une infinité","2"],a:1,exp:"Racines zₖ pour k = 0, …, n − 1"},
    {q:"Pour n ≥ 3, les images des racines n-ièmes d'un complexe non nul sont…",c:["sur une même droite verticale","confondues","les sommets d'un polygone régulier à n côtés inscrit dans un cercle de centre O","alignées"],a:2,exp:"Propriété du guide"},
    {q:"Les racines cubiques de 1 sont…",c:["1 ; −1 ; i","1 ; e^(2iπ/3) ; e^(4iπ/3)","1 ; e^(iπ/3) ; e^(2iπ/3)","1 ; 1/2 + i ; 1/2 − i"],a:1,exp:"e^(2ikπ/3), k = 0, 1, 2"},
    {q:"Les racines quatrièmes de 1 sont…",c:["1 ; 2 ; 3 ; 4","1 ; i ; −1 ; −i","1 ; −1","1 ; i"],a:1,exp:"i⁴ = 1"},
    {q:"Si z₀ est racine d'un polynôme P de degré n ≥ 3, alors…",c:["P(z) = (z − z₀) Q(z) avec Q de degré n − 1","P(z) = z − z₀","P(z) = z₀ Q(z)","Q est de degré n"],a:0,exp:"Propriété du guide"},
    {q:"Si P est à coefficients réels et admet une racine non réelle z₀, alors…",c:["conj(z₀) est aussi racine de P","1/z₀ est racine de P","P n'a pas d'autre racine","−z₀ est racine de P"],a:0,exp:"Racines conjuguées"},
    {q:"Les racines carrées de 3 + 4i sont…",c:["2 + i et −2 − i","1 + 2i et −1 − 2i","2 − i et −2 + i","3 + 4i et −3 − 4i"],a:0,exp:"(2 + i)² = 4 + 4i − 1"},
    {q:"Les racines carrées de i sont…",c:["1 + i et −1 − i","i et −i","(√2/2)(1 + i) et −(√2/2)(1 + i)","(1/2)(1 + i) et −(1/2)(1 + i)"],a:2,exp:"e^(iπ/4) et e^(i5π/4)"},
  ],
  "TleD — Nombres complexes & géométrie plane": [
    {q:"mes(→OI, →AB) = … (à 2π près)",c:["arg(z_A − z_B)","|z_B − z_A|","arg(z_B − z_A)","arg(z_B + z_A)"],a:2,exp:"Propriété du guide"},
    {q:"mes(→AB, →CD) = … (à 2π près)",c:["arg((z_D − z_C)/(z_B − z_A))","arg(z_D − z_B)","arg((z_B − z_A)/(z_D − z_C))","|z_D − z_C|/|z_B − z_A|"],a:0,exp:"Propriété du guide"},
    {q:"A, B, C sont alignés si et seulement si…",c:["|z_C − z_A| = |z_B − z_A|","z_A + z_B + z_C = 0","(z_C − z_A)/(z_B − z_A) ∈ ℝ","(z_C − z_A)/(z_B − z_A) ∈ iℝ"],a:2,exp:"Propriété du guide"},
    {q:"(AB) et (CD) sont perpendiculaires si et seulement si…",c:["(z_D − z_C)/(z_B − z_A) ∈ ℝ","|z_D − z_C| = |z_B − z_A|","z_D − z_C = z_B − z_A","(z_D − z_C)/(z_B − z_A) ∈ iℝ"],a:3,exp:"Propriété du guide"},
    {q:"AB = …",c:["|z_A − z_B|²","|z_B − z_A|","z_B − z_A","|z_A| + |z_B|"],a:1,exp:"Distance entre deux points"},
    {q:"L'ensemble des points M d'affixe z tels que |z − (1 − i)| = 2 est…",c:["la médiatrice de [OA]","le cercle de centre d'affixe 1 + i et de rayon 2","la droite d'équation x = 2","le cercle de centre d'affixe 1 − i et de rayon 2"],a:3,exp:"Lieu géométrique"},
    {q:"L'ensemble des points M tels que |z − a| = |z − b| est…",c:["la médiatrice de [AB]","le cercle de diamètre [AB]","la droite (AB)","le milieu de [AB]"],a:0,exp:"MA = MB"},
    {q:"Si (z_C − z_A)/(z_B − z_A) = i, alors le triangle ABC est…",c:["rectangle en B","équilatéral","rectangle isocèle en A","isocèle en B"],a:2,exp:"AC = AB et angle de 90°"},
    {q:"Si (z_C − z_A)/(z_B − z_A) = e^(iπ/3), alors le triangle ABC est…",c:["aplati","isocèle rectangle","équilatéral","rectangle en A"],a:2,exp:"AC = AB et angle de 60°"},
    {q:"ABCD est un parallélogramme si et seulement si…",c:["z_A + z_C = 0","|z_A| = |z_C|","z_B − z_A = z_C − z_D","z_B − z_A = z_D − z_C"],a:2,exp:"→AB = →DC"},
    {q:"Le milieu de [AB] a pour affixe…",c:["|z_A + z_B|/2","(z_A + z_B)/2","z_A z_B","(z_B − z_A)/2"],a:1,exp:"Affixe du milieu"},
  ],
  "TleD — Limites & continuité": [
    {q:"Si lim f = b en a et lim g = l en b, alors lim (g∘f) en a vaut…",c:["a","l + b","l","b"],a:2,exp:"Limite de la composée (propriété admise)"},
    {q:"La somme d'une fonction majorée et d'une fonction de limite −∞ a pour limite…",c:["−∞","+∞","0","une limite finie"],a:0,exp:"Propriété du guide"},
    {q:"La somme d'une fonction minorée et d'une fonction de limite +∞ a pour limite…",c:["+∞","−∞","0","une limite finie"],a:0,exp:"Propriété du guide"},
    {q:"Une fonction croissante et majorée sur [a ; b[ admet en b…",c:["aucune limite","une limite finie à gauche","la limite −∞","la limite +∞"],a:1,exp:"Propriété admise"},
    {q:"Une fonction croissante et non majorée sur [a ; b[ a pour limite en b à gauche…",c:["+∞","−∞","une valeur finie","0"],a:0,exp:"Propriété admise"},
    {q:"Le prolongement par continuité de f en a existe lorsque…",c:["f est paire","f est croissante","f admet une limite finie en a","f est définie en a"],a:2,exp:"Définition"},
    {q:"La composée de deux fonctions continues est…",c:["monotone","continue","toujours dérivable","bornée"],a:1,exp:"Propriété admise"},
    {q:"L'image d'un intervalle par une fonction continue est…",c:["un point","un intervalle","un ensemble fini","une réunion de deux intervalles"],a:1,exp:"Propriété admise"},
    {q:"Si f est continue sur [a ; b], alors f([a ; b]) = …",c:["ℝ","[f(a) ; f(b)]","[m ; M], où m et M sont le minimum et le maximum de f","]f(a) ; f(b)["],a:2,exp:"Propriété admise"},
    {q:"Théorème des valeurs intermédiaires : f continue sur [a ; b] et k compris entre f(a) et f(b) ⟹",c:["f est monotone","l'équation f(x) = k admet une solution unique","f(x) = 0 n'a pas de solution","l'équation f(x) = k admet au moins une solution dans [a ; b]"],a:3,exp:"TVI"},
    {q:"Si f est continue sur K et f(a) f(b) < 0 avec a < b dans K, alors…",c:["f est strictement croissante","f(x) = 0 admet au moins une solution entre a et b","f(x) = 0 n'admet aucune solution","f(x) > 0 sur [a ; b]"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est continue et strictement monotone sur [a ; b] avec f(a) f(b) < 0, alors f(x) = 0 a…",c:["deux solutions","une infinité de solutions","aucune solution","une unique solution dans [a ; b]"],a:3,exp:"Propriété admise"},
    {q:"Si f est continue et strictement croissante sur [a ; b], alors f([a ; b]) = …",c:["[f(a) ; f(b)]","]f(a) ; f(b)[","[a ; b]","[f(b) ; f(a)]"],a:0,exp:"Propriété admise"},
    {q:"Si f est continue et strictement décroissante sur [a ; b], alors f([a ; b]) = …",c:["]f(b) ; f(a)[","[f(b) ; f(a)]","[a ; b]","[f(a) ; f(b)]"],a:1,exp:"Propriété admise"},
    {q:"Si f est continue et strictement monotone sur K, alors f réalise…",c:["une fonction périodique","une bijection de K sur ℝ","une bijection de K sur f(K), de réciproque continue et de même sens de variation","une fonction constante"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La fonction racine n-ième (n ≥ 2) est…",c:["la fonction x ↦ x/n","la fonction x ↦ nx","la dérivée de xⁿ","la bijection réciproque de x ↦ xⁿ sur ℝ⁺"],a:3,exp:"Définition du guide"},
    {q:"8^(2/3) = …",c:["16/3","64","2","4"],a:3,exp:"(∛8)² = 2²"},
    {q:"f est continue en a si et seulement si…",c:["f est définie en a","la limite de f en a est égale à f(a)","f est croissante en a","f est dérivable en a"],a:1,exp:"Définition"},
  ],
  "TleD — Dérivation & étude de fonctions": [
    {q:"f est dérivable en x₀ si et seulement si f(x₀ + h) = f(x₀) + l h + h φ(h) avec…",c:["φ(h) = h","φ constante non nulle","φ(h) de limite 0 quand h tend vers 0","φ(h) de limite +∞"],a:2,exp:"Propriété admise (développement limité d'ordre 1)"},
    {q:"f est dérivable en x₀ si et seulement si…",c:["f est définie en x₀","f est dérivable à gauche et à droite en x₀ avec f'g(x₀) = f'd(x₀)","f' est positive en x₀","f est continue en x₀"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Un point anguleux est un point où la courbe admet…",c:["deux demi-tangentes de supports distincts","une tangente verticale","aucune tangente","une tangente horizontale"],a:0,exp:"Définition du guide"},
    {q:"La fonction valeur absolue x ↦ |x| en 0…",c:["est dérivable de dérivée 0","est dérivable de dérivée 1","n'est pas dérivable : la courbe a un point anguleux","n'est pas continue"],a:2,exp:"f'g(0) = −1 et f'd(0) = 1"},
    {q:"Un point d'inflexion est un point où la tangente…",c:["est verticale","est parallèle à l'axe (Ox)","est horizontale","traverse la courbe"],a:3,exp:"Définition du guide"},
    {q:"Si f'' s'annule en x₀ en changeant de signe, alors…",c:["f n'est pas dérivable en x₀","le point d'abscisse x₀ est un point d'inflexion","f a un extremum en x₀","f est constante"],a:1,exp:"Utilisation de la dérivée seconde"},
    {q:"Si le taux d'accroissement (f(x₀ + h) − f(x₀))/h a une limite infinie en 0, la courbe admet…",c:["une tangente horizontale","une demi-tangente verticale","un point d'inflexion","une asymptote oblique"],a:1,exp:"Propriété admise"},
    {q:"La dérivée seconde de f est…",c:["f' divisée par f","l'inverse de f'","la dérivée de la fonction dérivée f'","le carré de f'"],a:2,exp:"Notée f''"},
    {q:"La dérivée de g∘f est…",c:["g' × (f'∘g)","f' + g'","(f'∘g) × g'","f' × (g'∘f)"],a:3,exp:"Dérivée de la composée"},
    {q:"La dérivée de x ↦ (3x + 1)⁴ est…",c:["4(3x + 1)³","(3x + 1)⁴","12(3x + 1)³","12(3x + 1)⁴"],a:2,exp:"4 × 3 × (3x + 1)³"},
    {q:"La dérivée de x ↦ √(x² + 1) est…",c:["2x/√(x² + 1)","√(x² + 1)","1/(2√(x² + 1))","x/√(x² + 1)"],a:3,exp:"2x/(2√(x² + 1))"},
    {q:"La dérivée de x ↦ sin(2x) est…",c:["cos(2x)","2 sin(2x)","−2 cos(2x)","2 cos(2x)"],a:3,exp:"Composée : 2 × cos(2x)"},
    {q:"La dérivée de x ↦ cos²x est…",c:["−2 cos x","−2 sin x cos x","2 cos x","2 sin x cos x"],a:1,exp:"2 cos x × (−sin x)"},
    {q:"La dérivée de x ↦ tan x est…",c:["1 + tan²x","tan x","−1/cos²x","1/sin²x"],a:0,exp:"1/cos²x = 1 + tan²x"},
    {q:"Si φ est la bijection réciproque de f (f dérivable, f' ≠ 0), alors φ'(y) = …",c:["1 / f'(φ(y))","−f'(φ(y))","f'(φ(y))","1 / f'(y)"],a:0,exp:"Dérivée de la réciproque"},
    {q:"Inégalité des accroissements finis : si m ≤ f' ≤ M sur [a ; b], alors…",c:["f(b) − f(a) ≤ m","m(b − a) ≤ f(b) − f(a) ≤ M(b − a)","f(b) ≥ M","f(b) − f(a) = m + M"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si |f'| ≤ M sur [a ; b], alors…",c:["|f(b)| ≤ M","|f(b) − f(a)| ≤ M |b − a|","f(b) = f(a)","|f(b) − f(a)| ≥ M |b − a|"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La dérivée de x ↦ x^(1/n) (x > 0) est…",c:["x^(1/n)","(1/n) x^((1/n) − 1)","1/(n x)","n x^(n − 1)"],a:1,exp:"Dérivée d'une fonction puissance"},
  ],
  "TleD — Compléments sur les primitives": [
    {q:"Une primitive de f' × fⁿ (n entier, n ≠ −1) est…",c:["fⁿ/n","f^(n+1)","f^(n+1)/(n + 1)","n fⁿ⁻¹"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si f ne s'annule pas, une primitive de f'/f² est…",c:["−1/f","ln|f|","1/f","f²"],a:0,exp:"Cas n = −2"},
    {q:"Si f est strictement positive, une primitive de f'/√f est…",c:["√f","2√f","1/√f","f√f"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Une primitive de f' × (g'∘f) est…",c:["g∘f","g' ∘ f","f∘g","f' × g"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Une primitive de 2x(x² + 1)³ est…",c:["2(x² + 1)⁴","(x² + 1)⁴","(x² + 1)³/3","(x² + 1)⁴/4"],a:3,exp:"u'u³ avec u = x² + 1"},
    {q:"Une primitive de x/√(x² + 1) est…",c:["ln(x² + 1)","2√(x² + 1)","1/√(x² + 1)","√(x² + 1)"],a:3,exp:"u'/(2√u) avec u = x² + 1"},
    {q:"Une primitive de cos x sin³x est…",c:["sin³x","cos⁴x/4","−sin⁴x/4","sin⁴x/4"],a:3,exp:"u'u³ avec u = sin x"},
    {q:"Une primitive de 1/cos²x sur un intervalle où cos x ≠ 0 est…",c:["sin x/cos x²","−tan x","tan x","1/sin x"],a:2,exp:"(tan x)' = 1/cos²x"},
    {q:"Deux primitives d'une même fonction sur un intervalle diffèrent d'…",c:["une constante","un facteur","une fonction affine","une fonction paire"],a:0,exp:"Propriété fondamentale des primitives"},
  ],
  "TleD — Fonction logarithme népérien": [
    {q:"Le logarithme népérien est la primitive de x ↦ 1/x sur ]0 ; +∞[ qui…",c:["vaut e en 1","s'annule en e","s'annule en 1","vaut 1 en 0"],a:2,exp:"Définition du guide"},
    {q:"ln(xy) = … (x, y > 0)",c:["ln x × ln y","ln x + ln y","ln x / ln y","ln x − ln y"],a:1,exp:"Propriété fondamentale"},
    {q:"ln(1/x) = …",c:["ln x","−ln x","1/ln x","x"],a:1,exp:"Conséquence de ln(xy)"},
    {q:"ln(x/y) = …",c:["ln(x − y)","ln x + ln y","ln x / ln y","ln x − ln y"],a:3,exp:"Propriété démontrée en classe"},
    {q:"ln(xʳ) = … (r rationnel)",c:["ln r × x","r + ln x","(ln x)ʳ","r ln x"],a:3,exp:"Propriété démontrée en classe"},
    {q:"ln 1 = … et ln e = …",c:["1 et e","1 et 0","0 et 1","0 et e"],a:2,exp:"L'antécédent de 1 par ln est e"},
    {q:"La limite de ln x en +∞ est…",c:["1","+∞","−∞","0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La limite de ln x en 0 (x > 0) est…",c:["−∞","0","1","+∞"],a:0,exp:"Propriété admise"},
    {q:"La limite de (ln x)/x en +∞ est…",c:["1","0","+∞","−∞"],a:1,exp:"Croissances comparées"},
    {q:"La limite de x ln x en 0 (x > 0) est…",c:["1","−∞","0","+∞"],a:2,exp:"Croissances comparées"},
    {q:"La limite de ln(1 + x)/x en 0 est…",c:["0","1","+∞","e"],a:1,exp:"Nombre dérivé de ln en 1"},
    {q:"La fonction ln est…",c:["strictement décroissante sur ]0 ; +∞[","strictement croissante et bijective de ]0 ; +∞[ sur ℝ","paire","périodique"],a:1,exp:"Étude de la fonction ln"},
    {q:"Pour a, b > 0 : ln a = ln b équivaut à…",c:["a + b = 1","a = e","a = 1","a = b"],a:3,exp:"ln est bijective"},
    {q:"La dérivée de ln∘u est…",c:["u'","1/u","u' ln u","u'/u"],a:3,exp:"u strictement positive et dérivable"},
    {q:"Une primitive de u'/u sur un intervalle où u ne s'annule pas est…",c:["1/u","u²","ln|u|","ln u"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Résoudre ln(x − 1) = 0.",c:["x = 2","x = 0","x = e","x = 1"],a:0,exp:"x − 1 = 1"},
    {q:"Résoudre ln x < 1 (x > 0).",c:["0 < x < e","x < e","0 < x < 1","x > e"],a:0,exp:"ln est croissante"},
    {q:"Le domaine de définition de x ↦ ln(x − 3) est…",c:["ℝ","]3 ; +∞[","]0 ; +∞[","[3 ; +∞["],a:1,exp:"x − 3 > 0"},
    {q:"ln 8 = …",c:["ln 2 + 8","2 ln 3","8 ln 2","3 ln 2"],a:3,exp:"8 = 2³"},
    {q:"La dérivée de x ↦ ln(x² + 1) est…",c:["ln(2x)","2x","1/(x² + 1)","2x/(x² + 1)"],a:3,exp:"u'/u"},
    {q:"Le logarithme décimal est défini par log x = …",c:["x ln 10","ln x × ln 10","ln x / ln 10","ln 10 / ln x"],a:2,exp:"Changement de base"},
  ],
  "TleD — Fonction exponentielle népérienne": [
    {q:"Pour tout réel x, exp(x) est…",c:["strictement positif","égal à 1","entier","négatif ou nul"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Pour x > 0, exp(ln x) = … et pour tout réel x, ln(exp x) = …",c:["x et x","1 et 1","ln x et exp x","x et 1"],a:0,exp:"exp et ln sont réciproques"},
    {q:"La fonction exp est une bijection de…",c:["ℝ sur ]0 ; +∞[","]0 ; +∞[ sur ℝ","ℝ⁺ sur ℝ⁻","ℝ sur ℝ"],a:0,exp:"Propriété démontrée en classe"},
    {q:"e^(a + b) = …",c:["(eᵃ)ᵇ","eᵃ × eᵇ","eᵃ + eᵇ","e^(ab)"],a:1,exp:"Propriété fondamentale"},
    {q:"e^(−a) = …",c:["−eᵃ","1/eᵃ","eᵃ","1 − eᵃ"],a:1,exp:"Propriété démontrée en classe"},
    {q:"(eᵃ)ʳ = …",c:["e^(ar)","eᵃ + r","aʳ","e^(a + r)"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La dérivée de exp est…",c:["x exp","1/exp","exp","−exp"],a:2,exp:"exp est égale à sa dérivée"},
    {q:"La dérivée de e^u est…",c:["u' e^u","u' e^(u')","u e^u","e^u"],a:0,exp:"Dérivée de la composée"},
    {q:"La limite de eˣ en +∞ est … et en −∞ est …",c:["0 et +∞","+∞ et −∞","+∞ et 0","1 et 0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La limite de eˣ/x en +∞ est…",c:["1","0","+∞","e"],a:2,exp:"Croissances comparées"},
    {q:"La limite de x eˣ en −∞ est…",c:["−∞","0","1","+∞"],a:1,exp:"Croissances comparées"},
    {q:"La limite de (eˣ − 1)/x en 0 est…",c:["0","+∞","1","e"],a:2,exp:"Nombre dérivé de exp en 0"},
    {q:"Résoudre eˣ = 3.",c:["x = e³","x = ln 3","x = 3","x = 1/3"],a:1,exp:"On applique ln aux deux membres"},
    {q:"Résoudre e^(2x) − 3eˣ + 2 = 0.",c:["{1 ; 2}","{0 ; ln 2}","{0 ; 2}","{ln 1 ; ln 3}"],a:1,exp:"X = eˣ : X² − 3X + 2 = 0, donc X = 1 ou X = 2"},
    {q:"Résoudre eˣ ≥ 1.",c:["x ≥ 0","x ≥ 1","x ≤ 0","x ≤ 1"],a:0,exp:"exp est croissante et e⁰ = 1"},
    {q:"Une primitive de u' e^u est…",c:["u e^u","e^u","u' e^(u²)","e^(u')"],a:1,exp:"Propriété démontrée en classe"},
    {q:"eᵃ < eᵇ équivaut à…",c:["a > b","a = b","a + b < 0","a < b"],a:3,exp:"exp est strictement croissante"},
    {q:"La dérivée de x ↦ x eˣ est…",c:["(x + 1) eˣ","x eˣ","eˣ","(x − 1) eˣ"],a:0,exp:"Dérivée d'un produit"},
    {q:"La dérivée de x ↦ e^(x²) est…",c:["2 e^(x²)","2x e^(x²)","x² e^(x²)","e^(x²)"],a:1,exp:"u' e^u"},
  ],
  "TleD — Exponentielles de base a & fonctions puissances": [
    {q:"Pour a > 0 et α réel, aᵅ = …",c:["e^(a ln α)","α ln a","e^(α ln a)","a ln α"],a:2,exp:"Définition du guide"},
    {q:"Si a > 1, la fonction x ↦ aˣ est…",c:["périodique","strictement décroissante sur ℝ","strictement croissante sur ℝ","constante"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si 0 < a < 1, la fonction x ↦ aˣ est…",c:["strictement croissante sur ℝ","paire","strictement décroissante sur ℝ","constante"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La dérivée de x ↦ aˣ (a > 0) est…",c:["aˣ","ln a × aˣ","aˣ / ln a","x aˣ⁻¹"],a:1,exp:"aˣ = e^(x ln a)"},
    {q:"La dérivée de x ↦ xᵅ sur ]0 ; +∞[ est…",c:["x^(α − 1)","xᵅ/α","α x^(α − 1)","α xᵅ"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si α > 0, la limite de xᵅ en +∞ est…",c:["1","−∞","+∞","0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si α < 0, la limite de xᵅ en +∞ est…",c:["0","+∞","1","−∞"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si α > 0, la limite de (ln x)/xᵅ en +∞ est…",c:["1","+∞","α","0"],a:3,exp:"Croissances comparées"},
    {q:"Pour n entier naturel, la limite de xⁿ eˣ en −∞ est…",c:["1","0","+∞","−∞"],a:1,exp:"Croissances comparées"},
    {q:"Une primitive de x ↦ xᵅ (α ≠ −1) sur ]0 ; +∞[ est…",c:["xᵅ/α","ln x","α x^(α − 1)","x^(α + 1)/(α + 1)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Résoudre 2ˣ = 8.",c:["x = 8","x = 3","x = 2","x = 4"],a:1,exp:"2³ = 8"},
    {q:"3^(x + 1) = …",c:["3ˣ⁺¹ + 3","3ˣ + 1","3 × 3ˣ","3ˣ / 3"],a:2,exp:"aˣ⁺¹ = a × aˣ"},
    {q:"La dérivée de g^α (g > 0 dérivable) est…",c:["α g'","α g' g^(α − 1)","g' g^α","α g^(α − 1)"],a:1,exp:"Propriété démontrée en classe"},
  ],
  "TleD — Calcul intégral": [
    {q:"∫ de a à b de f(x) dx = …",c:["F(b) − F(a), où F est une primitive de f","F(a) + F(b)","F(a) − F(b)","f(b) − f(a)"],a:0,exp:"Définition du guide"},
    {q:"∫ de a à a de f(x) dx = …",c:["F(a)","1","0","f(a)"],a:2,exp:"Propriété démontrée en classe"},
    {q:"∫ de b à a de f = …",c:["− ∫ de a à b de f","∫ de a à b de |f|","∫ de a à b de f","0"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Relation de Chasles : ∫ de a à c de f + ∫ de c à b de f = …",c:["0","∫ de a à b de f","∫ de b à a de f","∫ de a à c de f"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est positive sur [a ; b] (a ≤ b), alors ∫ de a à b de f est…",c:["toujours égale à b − a","négative","positive : c'est l'aire du domaine sous la courbe","nulle"],a:2,exp:"Interprétation en unités d'aire"},
    {q:"Si f ≥ g sur [a ; b], alors…",c:["∫ de a à b de f ≤ ∫ de a à b de g","∫ de a à b de f ≥ ∫ de a à b de g","f = g","∫ de a à b de f = ∫ de a à b de g"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Inégalité de la moyenne : si m ≤ f ≤ M sur [a ; b], alors…",c:["∫ de a à b de f ≤ m","∫ de a à b de f ≥ M","∫ de a à b de f = m + M","m(b − a) ≤ ∫ de a à b de f ≤ M(b − a)"],a:3,exp:"Propriété énoncée dans le guide"},
    {q:"La valeur moyenne de f sur [a ; b] est…",c:["(f(a) + f(b))/2 toujours","∫ de a à b de f","f((a + b)/2) toujours","(1/(b − a)) ∫ de a à b de f"],a:3,exp:"Définition du guide"},
    {q:"∫ de 0 à 1 de x² dx = …",c:["1/3","1/2","2/3","1"],a:0,exp:"[x³/3] de 0 à 1"},
    {q:"∫ de 1 à e de (1/x) dx = …",c:["1","e − 1","e","0"],a:0,exp:"ln e − ln 1"},
    {q:"∫ de 0 à π de sin x dx = …",c:["2","0","π","1"],a:0,exp:"[−cos x] de 0 à π = 1 + 1"},
    {q:"∫ de 0 à 2 de (3x² + 1) dx = …",c:["6","8","10","14"],a:2,exp:"[x³ + x] de 0 à 2"},
    {q:"Si f est paire et continue, ∫ de −a à a de f = …",c:["∫ de 0 à a de f","2 ∫ de 0 à a de f","0","−2 ∫ de 0 à a de f"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est impaire et continue, ∫ de −a à a de f = …",c:["0","−a","2 ∫ de 0 à a de f","a"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si f est continue et T-périodique, ∫ de a à a + T de f…",c:["vaut T","dépend de a","ne dépend pas de a","est nulle"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Intégration par parties : ∫ de a à b de f g' = …",c:["f g' − f' g","∫ f' g − [f g]","[f g] de a à b − ∫ de a à b de f' g","[f g] de a à b + ∫ de a à b de f' g"],a:2,exp:"Formule d'intégration par parties"},
    {q:"∫ de 0 à 1 de x eˣ dx = …",c:["1","0","e","e − 1"],a:0,exp:"[x eˣ − eˣ] de 0 à 1 = 0 − (−1)"},
    {q:"Si f ≥ g sur [a ; b], l'aire entre les courbes Cf et Cg est…",c:["∫ de a à b de (f + g)","∫ de a à b de (f − g)","∫ de a à b de f × g","∫ de a à b de (g − f)"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Le volume d'un solide compris entre les plans z = a et z = b est V = …",c:["S(a) × (b − a)","∫ de a à b de S(t) dt, où S(t) est l'aire de la section","S(b) − S(a)","(S(a) + S(b))/2"],a:1,exp:"Propriété admise"},
    {q:"Le volume de révolution engendré par un domaine sous la courbe d'une fonction positive f entre a et b, autour de (Ox), est…",c:["π ∫ de a à b de f(x) dx","π ∫ de a à b de f(x)² dx","∫ de a à b de f(x)² dx","2π ∫ de a à b de f(x) dx"],a:1,exp:"Solides de révolution"},
    {q:"Le volume d'une boule de rayon R est…",c:["π R³","(4/3) π R³","4 π R²","(1/3) π R³"],a:1,exp:"Solide de révolution : π ∫ de −R à R de (R² − x²) dx"},
    {q:"La fonction F(x) = ∫ de a à x de f(t) dt est…",c:["la dérivée de f","une primitive de f valant 1 en a","une constante","l'unique primitive de f qui s'annule en a"],a:3,exp:"Propriété démontrée en classe"},
    {q:"La méthode des trapèzes permet de déterminer…",c:["la valeur exacte de toute intégrale","une valeur approchée d'une intégrale","un extremum","une primitive"],a:1,exp:"Méthode du guide"},
  ],
  "TleD — Équations différentielles": [
    {q:"Les solutions de y' = f(x) sont…",c:["les dérivées de f","les primitives de f","f²","les fonctions constantes"],a:1,exp:"Équation du type y' = f(x)"},
    {q:"Pour résoudre y'' = g(x), on…",c:["primitive deux fois g","résout une équation du second degré","dérive deux fois g","multiplie g par x²"],a:0,exp:"Deux primitivations successives"},
    {q:"Les solutions de a y' + b y = 0 (a ≠ 0) sont…",c:["y = C e^(−bx/a)","y = C x e^(−b/a)","y = C e^(bx/a)","y = −b/a"],a:0,exp:"Propriété du guide"},
    {q:"La solution de y' + 2y = 0 avec y(0) = 3 est…",c:["y = 3e^(2x)","y = −6x + 3","y = 3e^(−2x)","y = e^(−2x)"],a:2,exp:"y = C e^(−2x) avec C = 3"},
    {q:"Les solutions de y' = 3y sont…",c:["y = 3x","y = C e^(3x)","y = C + 3x","y = C e^(−3x)"],a:1,exp:"a = 1, b = −3"},
    {q:"L'équation caractéristique de a y'' + b y' + c y = 0 est…",c:["a + b r + c r² = 0 avec r = 0","r² = a + b + c","a r² + b r + c = 0","a r + b = 0"],a:2,exp:"Définition du guide"},
    {q:"Les solutions de y'' − 3y' + 2y = 0 sont…",c:["y = C₁ e^(−x) + C₂ e^(−2x)","y = (C₁ x + C₂) eˣ","y = C₁ eˣ + C₂ e^(2x)","y = C₁ cos x + C₂ sin x"],a:2,exp:"r² − 3r + 2 = 0 : r = 1 ou r = 2"},
    {q:"Les solutions de y'' + y = 0 sont…",c:["y = C e^x","y = (C₁ x + C₂) e^(−x)","y = C₁ cos x + C₂ sin x","y = C₁ eˣ + C₂ e^(−x)"],a:2,exp:"r² + 1 = 0 : r = ± i"},
    {q:"Les solutions de y'' + 2y' + y = 0 sont…",c:["y = (C₁ x + C₂) e^(−x)","y = C₁ e^(−x) + C₂ e^(x)","y = C₁ cos x + C₂ sin x","y = C e^(−2x)"],a:0,exp:"Racine double r = −1"},
    {q:"Si l'équation caractéristique a des racines α ± iβ, les solutions sont…",c:["y = C₁ e^(αx) + C₂ e^(βx)","y = e^(αx)(C₁ cos βx + C₂ sin βx)","y = C e^(iβx) seulement","y = (C₁ x + C₂) e^(αx)"],a:1,exp:"Cas Δ < 0"},
    {q:"Les solutions de y'' = 6x sont…",c:["y = x³ + C","y = x³ + C₁ x + C₂","y = 3x² + C","y = 6"],a:1,exp:"Deux primitivations"},
    {q:"Les solutions de y' + y = 1 sont…",c:["y = C e^x + 1","y = C e^(−x)","y = 1 − x","y = 1 + C e^(−x)"],a:3,exp:"y = 1 est solution particulière"},
    {q:"La solution de y' − y = 0 avec y(0) = 1 est…",c:["y = e^(−x)","y = x + 1","y = 1","y = eˣ"],a:3,exp:"C = 1"},
    {q:"La solution générale de a y' + b y = f(x) est la somme…",c:["d'une solution particulière et de la solution générale de a y' + b y = 0","de f et de sa primitive","de deux solutions particulières","de y' et de y"],a:0,exp:"Structure des solutions"},
  ],
  "TleD — Probabilités : événements & probabilité conditionnelle": [
    {q:"Une probabilité p sur un univers Ω vérifie p(Ω) = …",c:["1","0","1/2","le nombre d'éléments de Ω"],a:0,exp:"Définition du guide"},
    {q:"Si A et B sont incompatibles, p(A ∪ B) = …",c:["p(A) + p(B)","p(A) − p(B)","1","p(A) × p(B)"],a:0,exp:"Définition d'une probabilité"},
    {q:"p(A) + p(non A) = …",c:["2","p(Ω) − 1","1","0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"p(A ∪ B) = …",c:["p(A) + p(B) − p(A ∩ B)","p(A) + p(B) + p(A ∩ B)","p(A) − p(B)","p(A) × p(B)"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si A ⊂ B, alors…",c:["p(A) ≤ p(B)","p(A) ≥ p(B)","p(A) + p(B) = 1","p(A) = p(B)"],a:0,exp:"Propriété démontrée en classe"},
    {q:"En situation d'équiprobabilité, p(A) = …",c:["nombre de cas favorables / nombre de cas possibles","1/2","nombre de cas possibles / nombre de cas favorables","p(non A)"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La probabilité conditionnelle de A sachant B (p(B) ≠ 0) est p_B(A) = …",c:["p(A ∩ B)/p(A)","p(A) × p(B)","p(A ∩ B)/p(B)","p(A ∪ B)/p(B)"],a:2,exp:"Définition du guide"},
    {q:"p(A ∩ B) = …",c:["p(A) + p(B)","p_A(B) + p(A)","p_A(B) × p(A)","p(A)/p_A(B)"],a:2,exp:"Formule des probabilités composées"},
    {q:"Si (B₁, …, Bₙ) est un système complet d'événements, alors p(A) = …",c:["p(B₁) + … + p(Bₙ)","p(A ∩ B₁) + p(A ∩ B₂) + … + p(A ∩ Bₙ)","p(A ∩ B₁) × … × p(A ∩ Bₙ)","1"],a:1,exp:"Formule des probabilités totales"},
    {q:"Un système complet d'événements est formé d'événements…",c:["tous contraires les uns des autres","deux à deux incompatibles dont la réunion est Ω","de même probabilité","tous de probabilité 1/2"],a:1,exp:"Définition"},
    {q:"A et B sont indépendants si et seulement si…",c:["p(A ∩ B) = p(A) × p(B)","p(A) = p(B)","p(A ∪ B) = 1","p(A ∩ B) = 0"],a:0,exp:"Définition du guide"},
    {q:"Si A et B sont indépendants (p(B) ≠ 0), alors p_B(A) = …",c:["0","p(A)","1","p(B)"],a:1,exp:"Propriété démontrée en classe"},
    {q:"A et B sont indépendants si et seulement si A et non B sont…",c:["confondus","contraires","incompatibles","indépendants"],a:3,exp:"Propriété démontrée en classe"},
    {q:"p(A) = 0,4 ; p(B) = 0,5 ; p(A ∩ B) = 0,2. Les événements A et B sont…",c:["indépendants","contraires","impossibles","incompatibles"],a:0,exp:"0,4 × 0,5 = 0,2"},
    {q:"p(A) = 0,3 ; p(B) = 0,6 ; p(A ∩ B) = 0,18. Alors p_B(A) = …",c:["0,6","0,5","0,3","0,18"],a:2,exp:"0,18/0,6"},
    {q:"On tire deux boules sans remise dans une urne de 3 rouges et 2 bleues. La probabilité de tirer deux rouges est…",c:["9/25","3/5","6/25","3/10"],a:3,exp:"3/5 × 2/4"},
    {q:"On lance deux dés équilibrés. La probabilité d'obtenir une somme égale à 7 est…",c:["7/36","1/6","1/12","1/7"],a:1,exp:"6 couples sur 36"},
    {q:"Deux événements sont incompatibles lorsque…",c:["p(A) = p(B)","A ∩ B = ∅","p(A ∩ B) = p(A) p(B)","A ∪ B = Ω"],a:1,exp:"Définition"},
  ],
  "TleD — Variables aléatoires & loi binomiale": [
    {q:"Une variable aléatoire réelle est…",c:["un nombre fixé à l'avance","une application de l'univers Ω dans ℝ","un événement","une probabilité"],a:1,exp:"Définition du guide"},
    {q:"L'espérance de X prenant les valeurs xᵢ avec les probabilités pᵢ est E(X) = …",c:["Σ xᵢ² / n","Σ xᵢ","Σ pᵢ","Σ pᵢ xᵢ"],a:3,exp:"Définition"},
    {q:"La variance de X est V(X) = …",c:["Σ pᵢ (xᵢ − E(X))","Σ pᵢ xᵢ","Σ pᵢ (xᵢ − E(X))²","E(X)²"],a:2,exp:"Définition"},
    {q:"L'écart-type de X est…",c:["la moitié de V(X)","E(X)/V(X)","la racine carrée de V(X)","le carré de V(X)"],a:2,exp:"σ(X) = √V(X)"},
    {q:"La fonction de répartition de X est définie par F(t) = …",c:["p(X < t)","p(X ≥ t)","p(X = t)","p(X ≤ t)"],a:3,exp:"Définition du guide"},
    {q:"X prend les valeurs 0, 1, 2 avec les probabilités 0,2 ; 0,5 ; 0,3. Alors E(X) = …",c:["1,1","1,3","1","0,5"],a:0,exp:"0 + 0,5 + 0,6"},
    {q:"X prend les valeurs 0, 1, 2 avec les probabilités 0,2 ; 0,5 ; 0,3. La variance de X vaut…",c:["1,7","0,49","0,7","1,21"],a:1,exp:"E(X²) = 0,5 + 1,2 = 1,7 ; V = 1,7 − 1,1²"},
    {q:"La fonction de répartition est…",c:["décroissante","croissante, à valeurs dans [0 ; 1]","à valeurs dans [1 ; +∞[","constante"],a:1,exp:"Propriété de F"},
    {q:"La somme des probabilités de la loi d'une variable aléatoire est…",c:["0","le nombre de valeurs","E(X)","1"],a:3,exp:"p(Ω) = 1"},
    {q:"Une épreuve de Bernoulli est…",c:["une expérience à deux issues : succès de probabilité p et échec","une expérience à trois issues","une expérience de probabilité 1/2 obligatoire","une expérience sans hasard"],a:0,exp:"Définition du guide"},
    {q:"Un schéma de Bernoulli est…",c:["un arbre à trois branches","la répétition de n épreuves de Bernoulli identiques et indépendantes","une seule épreuve","une suite d'épreuves dépendantes"],a:1,exp:"Définition du guide"},
    {q:"Si X suit la loi binomiale B(n ; p), alors p(X = k) = …",c:["C(n, k) pᵏ (1 − p)^(n − k)","n pᵏ","C(n, k) pⁿ","pᵏ (1 − p)ᵏ"],a:0,exp:"Propriété admise"},
    {q:"Si X suit la loi binomiale B(n ; p), alors E(X) = …",c:["n p","n(1 − p)","p/n","n p (1 − p)"],a:0,exp:"Propriété du guide"},
    {q:"Si X suit la loi binomiale B(n ; p), alors V(X) = …",c:["p (1 − p)","n p (1 − p)","n (1 − p)","n p"],a:1,exp:"Propriété du guide"},
    {q:"Si X suit B(3 ; 1/3), alors p(X = 1) = …",c:["2/9","1/3","4/9","8/27"],a:2,exp:"3 × (1/3) × (2/3)²"},
    {q:"Si X suit B(10 ; 0,3), alors V(X) = …",c:["7","2,1","3","0,21"],a:1,exp:"10 × 0,3 × 0,7"},
    {q:"Si X suit B(4 ; 1/2), alors p(X = 2) = …",c:["6/16 + 1","1/4","1/2","3/8"],a:3,exp:"6 × (1/2)⁴ = 6/16"},
  ],
  "TleD — Suites numériques": [
    {q:"Un raisonnement par récurrence comporte…",c:["une initialisation seulement","une initialisation puis une hérédité (P(n) ⟹ P(n + 1))","une hérédité seulement","deux initialisations"],a:1,exp:"Structure du raisonnement"},
    {q:"Toute suite croissante et majorée est…",c:["constante","négative","convergente","divergente"],a:2,exp:"Propriété admise"},
    {q:"Toute suite décroissante et minorée est…",c:["nulle","croissante","convergente","divergente"],a:2,exp:"Propriété admise"},
    {q:"Toute suite croissante et non majorée est…",c:["convergente","bornée","divergente","constante"],a:2,exp:"Propriété admise"},
    {q:"Théorème des gendarmes : Vₙ ≤ Uₙ ≤ Wₙ avec lim Vₙ = lim Wₙ = l ⟹",c:["(Uₙ) diverge","lim Uₙ = l","lim Uₙ = 0","(Uₙ) est croissante"],a:1,exp:"Propriété admise"},
    {q:"Si Uₙ ≥ Vₙ à partir d'un certain rang et lim Vₙ = +∞, alors…",c:["lim Uₙ = 0","(Uₙ) est bornée","lim Uₙ = +∞","lim Uₙ = −∞"],a:2,exp:"Propriété admise"},
    {q:"Si Uₙ ≤ Vₙ à partir d'un rang, lim Uₙ = l et lim Vₙ = l', alors…",c:["l = l'","l ≤ l'","l < l'","l ≥ l'"],a:1,exp:"Passage à la limite dans une inégalité large"},
    {q:"Si |Uₙ − l| ≤ Vₙ et lim Vₙ = 0, alors…",c:["lim Uₙ = +∞","(Uₙ) diverge","lim Uₙ = 0","lim Uₙ = l"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Pour a > 1, la limite de aⁿ est… ; pour 0 < a < 1, elle est…",c:["0 et +∞","+∞ et 0","1 et 1","+∞ et +∞"],a:1,exp:"Propriété admise"},
    {q:"Si Uₙ₊₁ = g(Uₙ) converge vers l (g continue), alors…",c:["g(l) = 0","g'(l) = 1","l = 0","g(l) = l"],a:3,exp:"Propriété admise"},
    {q:"Si (Uₙ) converge vers a et si f a pour limite b en a (f continue), alors la limite de f(Uₙ) est…",c:["a","0","f(a) + b","b"],a:3,exp:"Propriété admise"},
    {q:"La limite de n²/2ⁿ est…",c:["2","+∞","0","1"],a:2,exp:"Croissances comparées"},
    {q:"La limite de Uₙ = (2n + 1)/(n + 3) est…",c:["3","+∞","1","2"],a:3,exp:"2 + 1/n sur 1 + 3/n"},
    {q:"U₀ = 1 et Uₙ₊₁ = Uₙ/2 + 1. Si (Uₙ) converge, sa limite l vérifie…",c:["l = 1/2","l = 1","l = l/2 + 1, donc l = 2","l = 0"],a:2,exp:"Passage à la limite dans la relation de récurrence"},
    {q:"La suite Uₙ = (−1)ⁿ…",c:["converge vers 0","converge vers −1","converge vers 1","diverge (elle n'a pas de limite)"],a:3,exp:"Elle alterne entre 1 et −1"},
    {q:"La suite Uₙ = n² − 3n…",c:["est décroissante","converge vers 0","diverge vers +∞","converge vers −3"],a:2,exp:"n²(1 − 3/n) tend vers +∞"},
    {q:"Toute suite convergente est…",c:["monotone","positive","croissante","bornée"],a:3,exp:"Propriété vue en 1ère"},
    {q:"La limite de sin n / n est…",c:["+∞","1","0","n'existe pas"],a:2,exp:"|Uₙ| ≤ 1/n : théorème des gendarmes"},
    {q:"Une suite géométrique de raison q avec |q| < 1 converge vers…",c:["q","1","+∞","0"],a:3,exp:"qⁿ tend vers 0"},
  ],
  "TleD — Statistiques à deux variables": [
    {q:"Un nuage de points est…",c:["une droite","un histogramme","un diagramme en bâtons","l'ensemble des points Mᵢ(xᵢ ; yᵢ) associés aux couples de valeurs"],a:3,exp:"Représentation d'une série double"},
    {q:"Le point moyen G d'un nuage a pour coordonnées…",c:["(mode de X ; mode de Y)","(médiane de X ; médiane de Y)","(somme des xᵢ ; somme des yᵢ)","(moyenne de X ; moyenne de Y)"],a:3,exp:"Définition"},
    {q:"La méthode de Mayer consiste à…",c:["partager les observations en deux groupes de même effectif et tracer la droite passant par leurs points moyens","minimiser la somme des carrés des écarts","tracer la droite au jugé","utiliser la médiane seulement"],a:0,exp:"Méthode des moyennes discontinues"},
    {q:"La droite de régression de Y en X est y = ax + b avec a = …",c:["σ(X)/σ(Y)","Cov(X, Y)/V(X)","V(X)/Cov(X, Y)","Cov(X, Y)/V(Y)"],a:1,exp:"Méthode des moindres carrés"},
    {q:"Dans la droite de régression y = ax + b, b = …",c:["(moyenne de Y) − a × (moyenne de X)","(moyenne de Y) + a × (moyenne de X)","(moyenne de X) − a","a × (moyenne de Y)"],a:0,exp:"Le point moyen G appartient à la droite"},
    {q:"La droite de régression de Y en X passe par…",c:["le point moyen G du nuage","aucun point particulier","le point de plus grande abscisse","l'origine du repère seulement"],a:0,exp:"Propriété du guide"},
    {q:"La covariance de (X, Y) est…",c:["V(X) × V(Y)","Σ xᵢ yᵢ","(1/N) Σ xᵢ yᵢ − (moyenne de X) × (moyenne de Y)","(1/N) Σ (xᵢ + yᵢ)"],a:2,exp:"Définition"},
    {q:"Le coefficient de corrélation linéaire est r = …",c:["Cov(X, Y) × σ(X) σ(Y)","Cov(X, Y) / (σ(X) σ(Y))","σ(X) σ(Y)/Cov(X, Y)","Cov(X, Y)/V(X)"],a:1,exp:"Définition du guide"},
    {q:"Le coefficient de corrélation linéaire r vérifie toujours…",c:["0 ≤ r ≤ 2","−1 ≤ r ≤ 1","r ≤ 0","r ≥ 1"],a:1,exp:"Propriété du guide"},
    {q:"Si |r| = 1, alors…",c:["la droite est horizontale","les variables sont indépendantes","tous les points du nuage sont alignés (ajustement parfait)","le nuage est un cercle"],a:2,exp:"Ajustement linéaire parfait"},
    {q:"Si 0,87 ≤ |r| < 1, on dit qu'il y a…",c:["une forte corrélation linéaire : résultats fiables","une liaison lâche","un ajustement impossible","une indépendance linéaire"],a:0,exp:"Interprétation du guide"},
    {q:"Si |r| < 0,87, la liaison est dite…",c:["nulle","lâche : résultats peu fiables","forte : résultats fiables","parfaite"],a:1,exp:"Interprétation du guide"},
    {q:"Si r est voisin de 0, on parle…",c:["de forte corrélation","de corrélation parfaite","d'indépendance linéaire statistique","d'ajustement parfait"],a:2,exp:"Interprétation du guide"},
    {q:"La droite de régression de Y en X pour les points (1 ; 2), (2 ; 4), (3 ; 6) est…",c:["y = 3x − 1","y = x + 1","y = 2x + 1","y = 2x"],a:3,exp:"Les points sont alignés sur y = 2x"},
    {q:"Dans un tableau à double entrée, l'effectif total se retrouve en…",c:["prenant l'effectif maximum","multipliant les effectifs marginaux","additionnant les effectifs marginaux d'une ligne ou d'une colonne","prenant la moyenne des effectifs"],a:2,exp:"Effectifs marginaux"},
  ],
  "TleD — Complexes & transformations du plan": [
    {q:"L'écriture complexe de la translation de vecteur d'affixe b est…",c:["z' = z/b","z' = bz","z' = z − b²","z' = z + b"],a:3,exp:"Translation"},
    {q:"L'écriture complexe de la rotation de centre O et d'angle θ est…",c:["z' = e^(iθ) z","z' = z + e^(iθ)","z' = e^(θ) z","z' = θ z"],a:0,exp:"Rotation de centre O"},
    {q:"L'écriture complexe de la rotation de centre Ω (affixe ω) et d'angle θ est…",c:["z' + ω = e^(iθ)(z + ω)","z' − ω = e^(iθ)(z − ω)","z' − ω = θ(z − ω)","z' = e^(iθ) z + ω"],a:1,exp:"Rotation de centre Ω"},
    {q:"L'écriture complexe de l'homothétie de centre Ω et de rapport k est…",c:["z' = z + k","z' − ω = k(z − ω)","z' = k z + ω","z' − ω = (z − ω)/k"],a:1,exp:"Homothétie"},
    {q:"Une similitude plane de rapport k est une transformation telle que M'N' = …",c:["k MN","k² MN","MN/k","MN + k"],a:0,exp:"Définition du guide"},
    {q:"Une similitude plane directe est une similitude qui…",c:["conserve l'orientation des angles","fixe tous les points","conserve les longueurs","inverse l'orientation des angles"],a:0,exp:"Définition du guide"},
    {q:"Toute similitude plane directe a une écriture complexe de la forme…",c:["z' = az² + b","z' = a/z + b","z' = a conj(z) + b","z' = az + b avec a ≠ 0"],a:3,exp:"Propriété admise"},
    {q:"Le rapport de la similitude z' = az + b est…",c:["|b|","a","|a|","1"],a:2,exp:"Propriété admise"},
    {q:"Si a = 1, la similitude z' = az + b est…",c:["une symétrie","la translation de vecteur d'affixe b","une rotation de centre O","une homothétie de rapport 1 et de centre b"],a:1,exp:"Propriété admise"},
    {q:"Si a ∈ ℝ − {1}, la similitude z' = az + b est…",c:["une translation","une homothétie de rapport a et de centre d'affixe b/(1 − a)","une rotation d'angle a","une symétrie centrale de rapport a"],a:1,exp:"Propriété admise"},
    {q:"Si |a| = 1 et a ≠ 1, la similitude z' = az + b est…",c:["une translation","une homothétie de rapport |a|","une rotation de centre d'affixe b/(1 − a) et d'angle arg(a)","l'identité"],a:2,exp:"Propriété admise"},
    {q:"La transformation z' = iz est…",c:["la translation de vecteur i","l'homothétie de rapport i","la symétrie de centre O","le quart de tour direct de centre O"],a:3,exp:"a = i : |a| = 1 et arg a = π/2"},
    {q:"La transformation z' = 2z + 3 − i est…",c:["la translation de vecteur 2 + 3 − i","l'homothétie de rapport 2 et de centre d'affixe −3 + i","la rotation de centre O et d'angle 2","l'homothétie de rapport 2 et de centre d'affixe 3 − i"],a:1,exp:"Centre : b/(1 − a) = (3 − i)/(−1)"},
    {q:"La transformation z' = (1 + i) z a pour rapport… et pour angle…",c:["1 et π/4","√2 et π/4","√2 et π/2","2 et π/4"],a:1,exp:"|1 + i| = √2 ; arg(1 + i) = π/4"},
    {q:"La transformation z' = −z + 2i est…",c:["la symétrie d'axe (Oy)","la translation de vecteur 2i","la symétrie centrale de centre d'affixe i","l'identité"],a:2,exp:"a = −1 : centre b/(1 − a) = i"},
    {q:"Une similitude z' = az + b avec a ≠ 1 admet…",c:["un unique point invariant d'affixe b/(1 − a)","exactement deux points invariants","une infinité de points invariants","aucun point invariant"],a:0,exp:"Résolution de z = az + b"},
    {q:"Si a ∈ ℂ − ℝ et |a| ≠ 1, la similitude est…",c:["une symétrie axiale","l'identité","la composée d'une rotation et d'une homothétie de même centre","une translation"],a:2,exp:"Éléments caractéristiques : centre, angle arg(a) et rapport |a|"},
  ],
  "TleD — Prop. & Déf.": [
    {q:"Définition : un vecteur normal à un plan est tout vecteur…",c:["directeur d'une droite perpendiculaire à ce plan","de ce plan","de norme 1","colinéaire à un vecteur du plan"],a:0,exp:"Vecteur normal"},
    {q:"Propriété : →u ∧ →v = →0 si et seulement si…",c:["→u = →v","‖→u‖ = ‖→v‖","→u et →v sont colinéaires","→u et →v sont orthogonaux"],a:2,exp:"Produit vectoriel"},
    {q:"Propriété : pour A, B, C non alignés, →AB ∧ →AC est…",c:["un vecteur du plan (ABC)","un vecteur normal au plan (ABC)","un vecteur unitaire","le vecteur nul"],a:1,exp:"Produit vectoriel"},
    {q:"Propriété : la distance de M₀ au plan ax + by + cz + d = 0 est…",c:["|ax₀ + by₀ + cz₀ + d| / √(a² + b² + c²)","(ax₀ + by₀ + cz₀ + d)/3","√(a² + b² + c²)","|ax₀ + by₀ + cz₀ + d|"],a:0,exp:"Distance point-plan"},
    {q:"Définition : le barycentre de (A, α) et (B, β), α + β ≠ 0, est le point G tel que…",c:["α + β = 0","AG = GB","→GA = →GB","α→GA + β→GB = →0"],a:3,exp:"Barycentre"},
    {q:"Définition : i est le nombre complexe tel que…",c:["i = −1","i² = −1","i² = 1","i = 1"],a:1,exp:"Nombres complexes"},
    {q:"Propriété : z × conj(z) = …",c:["2 Re(z)","|z|","z²","|z|²"],a:3,exp:"Conjugué et module"},
    {q:"Propriété : |zz'| = …",c:["|z + z'|","|z|²","|z| |z'|","|z| + |z'|"],a:2,exp:"Module d'un produit"},
    {q:"Propriété : arg(zz') = …",c:["2 arg z","arg z − arg z'","arg z × arg z'","arg z + arg z'"],a:3,exp:"Argument d'un produit"},
    {q:"Formule de Moivre : (cos θ + i sin θ)ⁿ = …",c:["n cos θ + i n sin θ","cos θ + i sin nθ","cos nθ + i sin nθ","cosⁿθ + i sinⁿθ"],a:2,exp:"Moivre"},
    {q:"Propriété : les racines n-ièmes d'un complexe non nul sont au nombre de…",c:["1","n","une infinité","2"],a:1,exp:"Racines n-ièmes"},
    {q:"Théorème des valeurs intermédiaires : f continue sur [a ; b], k entre f(a) et f(b) ⟹",c:["f(x) = k admet une solution unique","f est dérivable","f(x) = k admet au moins une solution dans [a ; b]","f est monotone"],a:2,exp:"TVI"},
    {q:"Propriété : si f est continue et strictement monotone sur K, alors…",c:["f' s'annule sur K","f réalise une bijection de K sur f(K) dont la réciproque est continue","f est paire","f est constante"],a:1,exp:"Bijection réciproque"},
    {q:"Propriété : (g∘f)' = …",c:["f' + g'","g'∘f'","g' × f'∘g","f' × (g'∘f)"],a:3,exp:"Dérivée de la composée"},
    {q:"Théorème des inégalités des accroissements finis : m ≤ f' ≤ M sur [a ; b] ⟹",c:["m(b − a) ≤ f(b) − f(a) ≤ M(b − a)","f(b) ≥ M","f(b) − f(a) = m + M","f(a) ≤ m"],a:0,exp:"Inégalité des accroissements finis"},
    {q:"Définition : ln est la primitive de x ↦ 1/x sur ]0 ; +∞[ qui…",c:["vaut e en 0","vaut 0 en e","vaut 1 en 1","s'annule en 1"],a:3,exp:"Logarithme népérien"},
    {q:"Propriété fondamentale : ln(xy) = …",c:["ln x − ln y","ln(x + y)","ln x × ln y","ln x + ln y"],a:3,exp:"Logarithme"},
    {q:"Propriété : pour tout réel x, ln(exp x) = … et exp(ln x) = … (x > 0)",c:["ln x et exp x","0 et 0","x et x","1 et 1"],a:2,exp:"Réciprocité"},
    {q:"Propriété : e^(a + b) = …",c:["eᵃ + eᵇ","e^(ab)","eᵃ × eᵇ","(eᵃ)ᵇ"],a:2,exp:"Exponentielle"},
    {q:"Définition : aᵅ (a > 0) = …",c:["e^(α ln a)","e^(a α)","α ln a","a ln α"],a:0,exp:"Puissance d'exposant réel"},
    {q:"Définition : ∫ de a à b de f(x) dx = …",c:["F(b) − F(a) avec F une primitive de f","F(a) + F(b)","F(a) − F(b)","f(b) − f(a)"],a:0,exp:"Intégrale"},
    {q:"Formule d'intégration par parties : ∫ de a à b de f g' = …",c:["[f g] de a à b + ∫ de a à b de f' g","[f g] de a à b − ∫ de a à b de f' g","∫ f' g","f g' − f' g"],a:1,exp:"IPP"},
    {q:"Définition : la solution de a y' + b y = 0 est…",c:["y = −b/a","y = C x","y = C e^(−bx/a)","y = C e^(bx/a)"],a:2,exp:"Équation différentielle"},
    {q:"Définition : p_B(A) = …",c:["p(A) p(B)","p(A ∪ B)","p(A ∩ B)/p(B)","p(A ∩ B)/p(A)"],a:2,exp:"Probabilité conditionnelle"},
    {q:"Définition : A et B sont indépendants si…",c:["p(A) = p(B)","p(A ∪ B) = 1","p(A ∩ B) = 0","p(A ∩ B) = p(A) p(B)"],a:3,exp:"Indépendance"},
    {q:"Propriété : si X suit B(n ; p), alors E(X) = … et V(X) = …",c:["n et p","p/n et p(1 − p)","n p (1 − p) et n p","n p et n p (1 − p)"],a:3,exp:"Loi binomiale"},
    {q:"Propriété : p(X = k) pour X de loi B(n ; p) est…",c:["C(n, k) pᵏ (1 − p)^(n − k)","pᵏ (1 − p)ᵏ","C(n, k) pⁿ","k pⁿ"],a:0,exp:"Loi binomiale"},
    {q:"Propriété : toute suite croissante et majorée est…",c:["décroissante","constante","convergente","divergente"],a:2,exp:"Suites monotones"},
    {q:"Théorème des gendarmes : Vₙ ≤ Uₙ ≤ Wₙ, lim Vₙ = lim Wₙ = l ⟹",c:["(Uₙ) est monotone","lim Uₙ = l","(Uₙ) diverge","lim Uₙ = 0"],a:1,exp:"Gendarmes"},
    {q:"Définition : r = …",c:["σ(X) σ(Y)","Cov(X, Y) / (σ(X) σ(Y))","Cov(X, Y)/V(X)","V(X)/V(Y)"],a:1,exp:"Coefficient de corrélation linéaire"},
    {q:"Définition : la droite de régression de Y en X est y = ax + b avec a = …",c:["Cov(X, Y)/V(X)","σ(Y)/σ(X)","Cov(X, Y)/V(Y)","V(X)/Cov(X, Y)"],a:0,exp:"Moindres carrés"},
    {q:"Propriété : l'écriture complexe d'une similitude plane directe est…",c:["z' = a conj(z) + b","z' = az²","z' = az + b avec a ≠ 0","z' = a/z"],a:2,exp:"Similitude directe"},
    {q:"Propriété : la similitude z' = az + b (a ≠ 1) a pour point invariant…",c:["l'origine","aucun point","le point d'affixe b","le point d'affixe b/(1 − a)"],a:3,exp:"Point invariant"},
    {q:"Définition : la rotation de centre Ω et d'angle θ s'écrit…",c:["z' − ω = θ(z − ω)","z' = e^(iθ) z + ω","z' − ω = e^(iθ)(z − ω)","z' = z + ω"],a:2,exp:"Rotation"},
  ],
});
