/* Questions de la classe de Tle C (2nd cycle) — un thème = une liste de questions. */
Object.assign(THEMES_C2, {
  "TleC — Barycentre de n points, fonctions de Leibniz & lignes de niveau": [
    {q:"La fonction vectorielle de Leibniz associée aux points pondérés (Aᵢ, αᵢ) est l'application…",c:["M ↦ Σ αᵢ →MAᵢ","M ↦ Σ αᵢ MAᵢ²","M ↦ Σ →MAᵢ seulement","M ↦ →OM"],a:0,exp:"Définition du guide"},
    {q:"Si Σ αᵢ ≠ 0, la fonction vectorielle de Leibniz est…",c:["bijective","constante","nulle","non définie"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si Σ αᵢ = 0, la fonction vectorielle de Leibniz est…",c:["bijective","non définie","constante","nulle en un seul point"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si Σ αᵢ ≠ 0, le barycentre G des (Aᵢ, αᵢ) est…",c:["le milieu de [A₁A₂]","l'unique antécédent du vecteur nul par la fonction vectorielle de Leibniz","un point quelconque","le point O"],a:1,exp:"Définition du guide"},
    {q:"Pour tout point O, →OG = …",c:["→0","Σ αᵢ →OAᵢ","(Σ αᵢ →OAᵢ) / (Σ αᵢ)","(Σ →OAᵢ) × (Σ αᵢ)"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La fonction scalaire de Leibniz associée aux (Aᵢ, αᵢ) est l'application…",c:["M ↦ Σ MAᵢ","M ↦ Σ αᵢ →MAᵢ","M ↦ Σ αᵢ MAᵢ","M ↦ Σ αᵢ MAᵢ²"],a:3,exp:"Définition du guide"},
    {q:"Si Σ αᵢ ≠ 0, φ(M) = …",c:["Σ αᵢ MG","(Σ αᵢ) MG² + φ(G)","φ(G) − MG²","(Σ αᵢ) MG + φ(G)"],a:1,exp:"Propriété du guide"},
    {q:"Dans un plan, une ligne de niveau d'une fonction scalaire de Leibniz peut être…",c:["seulement une droite","seulement un cercle","une ellipse","vide, une droite, un cercle, un singleton ou le plan entier"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Dans l'espace, une ligne de niveau peut être…",c:["seulement un plan","vide, un plan, une sphère, un singleton ou l'espace entier","un cylindre","une ellipse"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Sur une droite, une ligne de niveau peut être…",c:["un cercle","une demi-droite","un segment","vide, un singleton, une paire de points ou la droite entière"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Avec Σ αᵢ ≠ 0, l'ensemble des points M tels que φ(M) = k est en général…",c:["une droite passant par G","une parabole","un cercle (dans le plan) ou une sphère (dans l'espace) de centre G","un segment"],a:2,exp:"φ(M) = k équivaut à MG² = (k − φ(G))/Σ αᵢ"},
    {q:"L'ensemble des points M du plan tels que MA² − MB² = k est…",c:["une parabole","une droite perpendiculaire à (AB)","un cercle de diamètre [AB]","un cercle de centre A"],a:1,exp:"Coefficients 1 et −1 : Σ αᵢ = 0"},
    {q:"L'ensemble des points M tels que MA² + MB² = k (k assez grand) est…",c:["un cercle de centre le milieu de [AB]","une droite","une parabole","un segment"],a:0,exp:"Barycentre du système (A, 1), (B, 1)"},
    {q:"L'ensemble des points M de l'espace équidistants de A et B est…",c:["la sphère de diamètre [AB]","la droite (AB)","la médiatrice de [AB]","le plan médiateur de [AB]"],a:3,exp:"Propriété admise"},
  ],
  "TleC — Translations & homothéties de l'espace": [
    {q:"Une application f de l'espace dans lui-même est une translation si et seulement si, pour tous points M et N d'images M' et N',…",c:["→M'N' = →MN","M'N' = 0","→M'N' = −→MN","→M'N' = 2 →MN"],a:0,exp:"Propriété admise"},
    {q:"La composée tᵥ ∘ tᵤ de deux translations de vecteurs →u et →v est…",c:["l'identité","une homothétie","la translation de vecteur →u + →v","une rotation"],a:2,exp:"Propriété admise"},
    {q:"Une application f est une homothétie de rapport k (k ≠ 0 et k ≠ 1) si et seulement si →M'N' = …",c:["k² →MN","→MN","k →MN","−→MN"],a:2,exp:"Propriété admise"},
    {q:"Toute homothétie de l'espace est…",c:["une rotation","une translation","une isométrie","une application affine"],a:3,exp:"Propriété admise"},
    {q:"L'application vectorielle associée à une homothétie de rapport k est…",c:["u ↦ k u","u ↦ k + u","u ↦ u","u ↦ u/k²"],a:0,exp:"Homothétie vectorielle de rapport k"},
    {q:"Une homothétie de rapport k multiplie les distances par…",c:["|k|","k³","k²","1/k"],a:0,exp:"Propriété admise"},
    {q:"Une homothétie de rapport k multiplie les aires par…",c:["k","k²","|k|³","2k"],a:1,exp:"Propriété admise"},
    {q:"Une homothétie de rapport k multiplie les volumes par…",c:["k²","k","|k|³","3k"],a:2,exp:"Propriété admise"},
    {q:"La composée de deux homothéties de même centre O et de rapports k et k' est…",c:["une homothétie de rapport k + k'","l'identité","une homothétie de centre O et de rapport kk'","une translation"],a:2,exp:"Propriété admise"},
    {q:"Les homothéties h et h' de même centre vérifient…",c:["h' ∘ h ≠ h ∘ h'","h' ∘ h = Id toujours","h' ∘ h = h","h' ∘ h = h ∘ h'"],a:3,exp:"Composée commutative"},
    {q:"La composée d'une homothétie de rapport k (k ≠ 1) et d'une translation est…",c:["une homothétie de rapport k","l'identité","une translation","une rotation"],a:0,exp:"Propriété admise"},
    {q:"Le volume d'un solide est multiplié par 8 par une homothétie de rapport…",c:["2 ou −2","8","√8","4"],a:0,exp:"|k|³ = 8"},
    {q:"Expression analytique de la translation de vecteur (1 ; 2 ; 3) :",c:["x' = x + y + z","x' = x ; y' = y ; z' = z + 6","x' = x + 1 ; y' = y + 2 ; z' = z + 3","x' = x − 1 ; y' = y − 2 ; z' = z − 3"],a:2,exp:"On ajoute les coordonnées du vecteur"},
  ],
  "TleC — Réflexions, demi-tours & compositions dans l'espace": [
    {q:"Le plan médiateur d'un segment [AB] est le plan…",c:["contenant A et B","parallèle à (AB)","passant par le milieu de [AB] et perpendiculaire à (AB)","passant par A et perpendiculaire à (AB)"],a:2,exp:"Définition du guide"},
    {q:"L'ensemble des points invariants d'une réflexion de plan (P) est…",c:["le plan (P)","une droite","un point","l'espace entier"],a:0,exp:"Propriété admise"},
    {q:"Pour M' = S_P(M) et H le projeté orthogonal de M sur (P), on a…",c:["→MM' = 2 →MH","M' = H","→MM' = 3 →MH","→MM' = →MH"],a:0,exp:"Propriété admise"},
    {q:"Une réflexion est involutive : S_P ∘ S_P = …",c:["une homothétie","une translation","Id","S_P"],a:2,exp:"S_P est sa propre réciproque"},
    {q:"La composée de deux réflexions de plans parallèles est…",c:["un demi-tour","une rotation","l'identité","une translation de vecteur normal à ces plans"],a:3,exp:"Propriété admise"},
    {q:"La composée de deux réflexions de plans perpendiculaires suivant une droite (Δ) est…",c:["le demi-tour d'axe (Δ)","une homothétie","l'identité","une translation"],a:0,exp:"Propriété admise"},
    {q:"L'ensemble des points invariants d'un demi-tour d'axe (Δ) est…",c:["la droite (Δ)","l'espace","un plan","un point"],a:0,exp:"Propriété admise"},
    {q:"Un demi-tour d'axe (Δ) est aussi appelé…",c:["symétrie centrale","symétrie orthogonale par rapport à (Δ)","réflexion de plan","translation"],a:1,exp:"Remarque du guide"},
    {q:"Un demi-tour S_Δ vérifie…",c:["S_Δ ∘ S_Δ = Id","S_Δ ∘ S_Δ = S_Δ","S_Δ = Id","S_Δ est une translation"],a:0,exp:"Le demi-tour est une involution"},
    {q:"La composée de deux demi-tours d'axes parallèles est…",c:["une rotation d'angle quelconque","un demi-tour","l'identité seulement","une translation"],a:3,exp:"Propriété admise"},
    {q:"La composée de deux demi-tours d'axes perpendiculaires en A est…",c:["la symétrie centrale de centre A","une translation","le demi-tour d'axe la perpendiculaire commune en A","l'identité"],a:2,exp:"Propriété admise"},
    {q:"La composée d'un demi-tour d'axe (Δ) et d'une réflexion de plan (P), (Δ) orthogonale à (P) en A, est…",c:["une translation","un demi-tour","l'identité","la symétrie centrale de centre A"],a:3,exp:"Propriété admise"},
    {q:"Une réflexion conserve…",c:["seulement le parallélisme","le parallélisme et l'orthogonalité","aucune propriété","seulement les aires"],a:1,exp:"Propriété admise"},
    {q:"Toute translation de vecteur non nul est la composée de…",c:["un demi-tour et une translation","deux homothéties de même centre","deux réflexions de plans parallèles","deux réflexions de plans sécants"],a:2,exp:"Propriété admise"},
  ],
  "TleC — Produit vectoriel": [
    {q:"Dans une base orthonormée directe (→i, →j, →k), →i ∧ →j = …",c:["−→k","→k","→j","→0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Dans une base orthonormée directe, →j ∧ →k = …",c:["→0","−→i","→i","→k"],a:2,exp:"Permutation circulaire"},
    {q:"Dans une base orthonormée directe, →k ∧ →i = …",c:["→j","−→j","→0","→i"],a:0,exp:"Permutation circulaire"},
    {q:"Pour tous vecteurs →u et →v, →u ∧ →v = …",c:["→v ∧ →u","→u ⋅ →v","→0","−(→v ∧ →u)"],a:3,exp:"Le produit vectoriel est antisymétrique"},
    {q:"→u ∧ →v = →0 si et seulement si…",c:["‖→u‖ = ‖→v‖","→u et →v sont colinéaires","→u = →v seulement","→u et →v sont orthogonaux"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Les coordonnées de →u(x ; y ; z) ∧ →v(x' ; y' ; z') sont…",c:["(xx' ; yy' ; zz')","(xy' − yx' ; yz' − zy' ; zx' − xz')","(x + x' ; y + y' ; z + z')","(yz' − zy' ; zx' − xz' ; xy' − yx')"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Calculer →u(1 ; 2 ; 3) ∧ →v(0 ; 1 ; 0).",c:["(−3 ; 0 ; 1)","(0 ; 0 ; 0)","(3 ; 0 ; −1)","(2 ; 3 ; 1)"],a:0,exp:"(2×0 − 3×1 ; 3×0 − 1×0 ; 1×1 − 2×0)"},
    {q:"Pour A, B, C non alignés, →AB ∧ →AC est…",c:["un vecteur normal au plan (ABC)","un vecteur du plan (ABC)","un vecteur de norme 1","le vecteur nul"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Les points A, B, C sont alignés si et seulement si…",c:["→AB = →AC","AB = AC","→AB ⋅ →AC = 0","→AB ∧ →AC = →0"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Les points A, B, C, D sont coplanaires si et seulement si…",c:["→AB + →AC + →AD = →0","→AB ⋅ (→AC ∧ →AD) = 0","→AB ∧ →AC = →AD","→AB ⋅ →AC = →AD"],a:1,exp:"Produit mixte nul"},
    {q:"L'aire du triangle ABC est égale à…",c:["‖→AB ∧ →AC‖","(1/2) ‖→AB ∧ →AC‖","AB × AC","(1/2) →AB ⋅ →AC"],a:1,exp:"Application du produit vectoriel"},
    {q:"A(0 ; 0 ; 0), B(1 ; 0 ; 0), C(0 ; 2 ; 0) : l'aire du triangle ABC est…",c:["2","1/2","1","√5/2"],a:2,exp:"→AB ∧ →AC = (0 ; 0 ; 2), norme 2, donc aire 1"},
    {q:"Le volume du tétraèdre ABCD est égal à…",c:["|→AB ⋅ (→AC ∧ →AD)|","(1/3) AB × AC × AD","(1/2) ‖→AB ∧ →AC‖","(1/6) |→AB ⋅ (→AC ∧ →AD)|"],a:3,exp:"Produit mixte divisé par 6"},
    {q:"La distance d'un point M à la droite (AB) est égale à…",c:["‖→AM ∧ →AB‖ × AB","AM × AB","‖→AM ⋅ →AB‖ / AB","‖→AM ∧ →AB‖ / AB"],a:3,exp:"Application du produit vectoriel"},
    {q:"Le volume du tétraèdre OIJK avec O(0 ; 0 ; 0), I(1 ; 0 ; 0), J(0 ; 1 ; 0), K(0 ; 0 ; 1) est…",c:["1","1/2","1/6","1/3"],a:2,exp:"|1|/6"},
  ],
  "TleC — Systèmes d'équations linéaires (pivot de Gauss)": [
    {q:"La méthode du pivot de Gauss consiste à…",c:["résoudre chaque équation séparément","supprimer une inconnue au hasard","tracer les plans","transformer le système en un système équivalent triangulaire"],a:3,exp:"Échelonnement du système"},
    {q:"Quelle opération n'est pas permise dans la méthode de Gauss ?",c:["multiplier une équation par 0","permuter deux équations","ajouter à une équation un multiple d'une autre","multiplier une équation par un réel non nul"],a:0,exp:"Multiplier par 0 ne conserve pas l'équivalence"},
    {q:"Résoudre x + y + z = 6 ; x − y + z = 2 ; x + y − z = 0.",c:["(3 ; 2 ; 1)","(1 ; 3 ; 2)","(2 ; 1 ; 3)","(1 ; 2 ; 3)"],a:3,exp:"Eq1 + Eq3 : x + y = 3 puis z = 3 ; Eq2 donne x − y = −1"},
    {q:"Résoudre x + y + z = 3 ; y + z = 2 ; z = 1.",c:["(0 ; 1 ; 2)","(2 ; 1 ; 0)","(1 ; 2 ; 0)","(1 ; 1 ; 1)"],a:3,exp:"Système triangulaire : on remonte"},
    {q:"Un système linéaire peut avoir…",c:["seulement une infinité de solutions","toujours une seule solution","aucune solution, une seule solution ou une infinité de solutions","exactement deux solutions"],a:2,exp:"Trois cas possibles"},
    {q:"Le système x + y = 2 ; 2x + 2y = 5 a…",c:["une seule solution","deux solutions","une infinité de solutions","aucune solution"],a:3,exp:"Droites parallèles distinctes"},
    {q:"Le système x + y − z = 1 ; 2x + 2y − 2z = 2 ; x − y = 0 a…",c:["aucune solution","une seule solution","exactement deux solutions","une infinité de solutions"],a:3,exp:"Deux équations identiques : z = 2x − 1 avec x = y"},
    {q:"Pour espérer une solution unique dans un système à 3 inconnues, il faut…",c:["un second membre nul","deux équations dépendantes","une seule équation","au moins trois équations indépendantes"],a:3,exp:"Autant d'équations indépendantes que d'inconnues"},
  ],
  "TleC — Arithmétique : ℤ, division euclidienne & numération": [
    {q:"(ℤ, +, ×) est…",c:["un anneau commutatif unitaire","un groupe multiplicatif","un corps","un espace vectoriel"],a:0,exp:"Structure de ℤ"},
    {q:"Dans ℤ, pour tous a, b, c : a × 0 = …",c:["1","a","a + 0","0"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Toute partie non vide de ℕ admet…",c:["un plus petit élément","un plus grand élément","un élément négatif","une infinité d'éléments"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"Toute partie non vide et majorée de ℤ admet…",c:["un plus grand élément","aucun élément","un plus petit élément","une infinité d'éléments"],a:0,exp:"Propriété admise"},
    {q:"Pour c < 0, a ≤ b équivaut à…",c:["a + c ≥ b + c","a × c ≥ b × c","a × c = b × c","a × c ≤ b × c"],a:1,exp:"On change le sens de l'inégalité"},
    {q:"Division euclidienne de a par b (b ≠ 0) dans ℤ : il existe un unique couple (q, r) avec…",c:["a = bq + r et 0 ≤ r < |b|","a = b + qr","a = bq et r = 0","a = bq + r et r < 0"],a:0,exp:"Propriété admise"},
    {q:"Division euclidienne de −17 par 5 :",c:["−17 = 5 × (−4) + 3","−17 = 5 × (−3) − 2","−17 = 5 × (−4) − 3","−17 = 5 × (−3) + 2"],a:0,exp:"Le reste doit vérifier 0 ≤ r < 5"},
    {q:"Division euclidienne de 100 par 7 :",c:["q = 13 et r = 9","q = 14 et r = 2","q = 14 et r = 9","q = 15 et r = −5"],a:1,exp:"100 = 7 × 14 + 2"},
    {q:"101101 en base 2 vaut, en base 10…",c:["61","43","45","37"],a:2,exp:"32 + 8 + 4 + 1"},
    {q:"37 s'écrit en base 2…",c:["100101","101001","100111","110001"],a:0,exp:"37 = 32 + 4 + 1"},
    {q:"Le nombre FF en base 16 vaut en base 10…",c:["256","240","255","15"],a:2,exp:"15 × 16 + 15"},
    {q:"Le système hexadécimal utilise…",c:["10 chiffres","16 chiffres : 0 à 9 puis A à F","8 chiffres","2 chiffres"],a:1,exp:"Base 16"},
    {q:"Le système octal est de base…",c:["2","10","16","8"],a:3,exp:"Système de numération de base 8"},
    {q:"Pour écrire un entier naturel en base b (b ≥ 2), on effectue…",c:["des additions successives de b","des multiplications par b","des soustractions de b²","des divisions euclidiennes successives par b"],a:3,exp:"Les restes donnent les chiffres"},
  ],
  "TleC — Divisibilité & congruences": [
    {q:"Si b divise a (a ≠ 0), alors…",c:["|b| ≥ |a|","b = 1","b = a","|b| ≤ |a|"],a:3,exp:"Propriété énoncée dans le guide"},
    {q:"Si a divise b et b divise a, alors…",c:["a = 1","a = 2b","a = b ou a = −b","a = 0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si a divise b et b divise c, alors…",c:["a = c","c divise a","a divise c","b = 1"],a:2,exp:"Transitivité"},
    {q:"Si a divise b et a divise c, alors pour tous entiers p et q, a divise…",c:["pb × qc seulement","p + q","b + c seulement","pb + qc"],a:3,exp:"Propriété démontrée en classe"},
    {q:"L'ensemble des multiples de n, noté nℤ, est…",c:["un sous-groupe de (ℤ, +)","un corps","fini","un anneau sans élément neutre"],a:0,exp:"Remarque du guide"},
    {q:"x ≡ y [n] signifie que…",c:["x + y ∈ nℤ","x × y ∈ nℤ","x = y","x − y ∈ nℤ"],a:3,exp:"Définition du guide"},
    {q:"La congruence modulo n est une relation…",c:["non symétrique","d'ordre","non transitive","d'équivalence (réflexive, symétrique, transitive)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"a ≡ a' [n] si et seulement si…",c:["a et a' sont de même signe","a et a' ont le même reste dans la division euclidienne par n","a − a' = 1","a = a'"],a:1,exp:"Propriété du guide"},
    {q:"Si a ≡ a' [n] et b ≡ b' [n], alors…",c:["a + b ≡ a' + b' [n] et ab ≡ a'b' [n]","ab ≡ a' + b' [n]","a + b ≡ a'b' [n]","a = a'"],a:0,exp:"Compatibilité avec + et ×"},
    {q:"Le reste de la division de 2026 par 7 est…",c:["4","2","3","6"],a:2,exp:"2026 = 7 × 289 + 3"},
    {q:"7²⁰²⁶ est congru à… modulo 5",c:["4","2","3","1"],a:0,exp:"7 ≡ 2 [5] ; 2⁴ ≡ 1 ; 2026 = 4 × 506 + 2 : 2² = 4"},
    {q:"3¹⁰⁰ est congru à… modulo 4",c:["1","0","2","3"],a:0,exp:"3² = 9 ≡ 1 [4]"},
    {q:"Le critère de divisibilité par 3 se justifie par…",c:["100 ≡ 0 [3]","10 ≡ 2 [3]","10 ≡ 1 [3] : n est congru à la somme de ses chiffres","10 ≡ 0 [3]"],a:2,exp:"Congruences"},
    {q:"Le critère de divisibilité par 11 utilise…",c:["10 ≡ 1 [11]","100 ≡ 0 [11]","la somme des chiffres","10 ≡ −1 [11] : somme alternée des chiffres"],a:3,exp:"Congruences"},
    {q:"Le critère de divisibilité par 4 se justifie par…",c:["10 ≡ 1 [4]","100 ≡ 0 [4] : les deux derniers chiffres suffisent","1000 ≡ 1 [4]","10 ≡ 0 [4]"],a:1,exp:"Congruences"},
    {q:"Si n divise a − b, alors…",c:["a ≡ b [n]","a + b ≡ 0 [n]","n = 1","a = b"],a:0,exp:"Définition de la congruence"},
  ],
  "TleC — PGCD, PPCM, Bézout & Gauss": [
    {q:"PPCM(ka, kb) = …",c:["PPCM(a, b)/k","k PPCM(a, b)","PPCM(a, b)","k² PPCM(a, b)"],a:1,exp:"Propriété énoncée dans le guide"},
    {q:"PGCD(ka, kb) = …",c:["PGCD(a, b)","k PGCD(a, b)","PGCD(a, b)/k","k² PGCD(a, b)"],a:1,exp:"Propriété énoncée dans le guide"},
    {q:"L'ensemble des diviseurs communs de a et b est l'ensemble des diviseurs de…",c:["leur PPCM","leur PGCD","leur somme","leur produit"],a:1,exp:"D(a) ∩ D(b) = D(δ)"},
    {q:"aℤ ∩ bℤ = …",c:["ℤ","δℤ, où δ = PGCD(a, b)","abℤ toujours","μℤ, où μ = PPCM(a, b)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Un entier m est multiple du PGCD δ de a et b si et seulement s'il existe u et v tels que…",c:["m = uv","m = au + bv","m = a + b","m = au × bv"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si r est le reste de la division de a par b (r ≠ 0), alors PGCD(a, b) = …",c:["r","PGCD(a, r)","PGCD(b, r)","b + r"],a:2,exp:"Algorithme d'Euclide"},
    {q:"Pour a ≠ b entiers non nuls, PGCD(a, b) = …",c:["PGCD(a × b, b)","PGCD(a − b, b)","PGCD(a², b²)","a − b"],a:1,exp:"Propriété admise dans le guide"},
    {q:"PGCD(84 ; 126) = …",c:["42","14","252","21"],a:0,exp:"84 = 2² × 3 × 7 ; 126 = 2 × 3² × 7"},
    {q:"PPCM(84 ; 126) = …",c:["252","10 584","42","168"],a:0,exp:"84 × 126 / 42"},
    {q:"PGCD(252 ; 198) = …",c:["6","18","36","9"],a:1,exp:"252 = 198 + 54 ; 198 = 3 × 54 + 36 ; 54 = 36 + 18 ; 36 = 2 × 18"},
    {q:"Pour a et b naturels non nuls, δ μ = …",c:["a/b","a − b","a + b","a × b"],a:3,exp:"PGCD × PPCM = produit"},
    {q:"a et b sont premiers entre eux si et seulement si (Bézout)…",c:["a et b sont premiers","il existe u et v tels que au + bv = 1","PGCD(a, b) = a","a divise b"],a:1,exp:"Théorème de Bézout"},
    {q:"Une solution de 13u + 8v = 1 est…",c:["u = 8, v = −13","u = 1, v = −1","u = 5, v = −8","u = 2, v = −3"],a:2,exp:"65 − 64 = 1"},
    {q:"Théorème de Gauss : si a divise bc et si a et b sont premiers entre eux, alors…",c:["a divise c","a = c","a divise b","b divise c"],a:0,exp:"Théorème de Gauss"},
    {q:"Si a et b sont premiers entre eux et divisent tous deux c, alors…",c:["c = ab","a = b","a + b divise c","ab divise c"],a:3,exp:"Propriété énoncée dans le guide"},
    {q:"Si a et b sont premiers entre eux, PPCM(a, b) = …",c:["|a × b|","a + b","PGCD(a, b)","1"],a:0,exp:"Propriété énoncée dans le guide"},
    {q:"Si a est premier avec n et si ab ≡ ac [n], alors…",c:["n = 1","b = c","a ≡ 0 [n]","b ≡ c [n]"],a:3,exp:"Simplification dans une congruence"},
    {q:"L'équation ax + by = c a des solutions entières si et seulement si…",c:["a divise c","c = 0","PGCD(a, b) divise c","a et b sont premiers"],a:2,exp:"Équation diophantienne"},
    {q:"L'équation 6x + 9y = 5 dans ℤ² a…",c:["une unique solution","une infinité de solutions","aucune solution","exactement deux solutions"],a:2,exp:"PGCD(6, 9) = 3 ne divise pas 5"},
    {q:"Les solutions de 5x + 3y = 1 dans ℤ² sont…",c:["(2 ; −3) uniquement","(2 + 5k ; −3 + 3k)","(2 + 3k ; −3 − 5k), k ∈ ℤ","(1 + 3k ; 1 − 5k)"],a:2,exp:"Solution particulière (2 ; −3)"},
  ],
  "TleC — Nombres premiers & ℤ/nℤ": [
    {q:"Tout entier naturel différent de 0 et de 1 admet…",c:["au moins un diviseur premier","aucun diviseur premier","un nombre pair de diviseurs","exactement un diviseur premier"],a:0,exp:"Propriété démontrée en classe"},
    {q:"L'ensemble des nombres premiers est…",c:["vide","borné par 100","infini","fini"],a:2,exp:"Propriété admise"},
    {q:"Un entier n non premier (n ≥ 2) admet un diviseur premier d tel que…",c:["d > n","d² > n","1 < d² ≤ n","d = n"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Pour savoir si 251 est premier, on teste la divisibilité par les nombres premiers d tels que…",c:["d ≤ 125","d ≤ 251","d² ≤ 251, soit jusqu'à 13","d ≤ 25 seulement"],a:2,exp:"√251 ≈ 15,8"},
    {q:"251 est-il premier ?",c:["Oui","Non, il est divisible par 3","Non, il est divisible par 7","Non, il est divisible par 11"],a:0,exp:"Aucun premier ≤ 13 ne le divise"},
    {q:"Tout entier n ≥ 2 s'écrit comme produit de facteurs premiers, décomposition…",c:["non unique","impossible pour les premiers","possible pour les pairs seulement","unique (à l'ordre près)"],a:3,exp:"Théorème du guide"},
    {q:"La décomposition de 360 est…",c:["2 × 3 × 60","2² × 3² × 10","2³ × 3 × 15","2³ × 3² × 5"],a:3,exp:"360 = 8 × 9 × 5"},
    {q:"ℤ/nℤ est…",c:["infini","un anneau commutatif","un corps pour tout n","un groupe non commutatif"],a:1,exp:"Propriété admise"},
    {q:"ℤ/nℤ possède…",c:["n éléments (n classes)","2n éléments","n² éléments","une infinité d'éléments"],a:0,exp:"Classes des restes 0, 1, …, n − 1"},
    {q:"ℤ/pℤ est un corps si et seulement si…",c:["p est pair","p est premier","p = 2","p est impair"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Dans ℤ/6ℤ, la classe de 2 × 3 est…",c:["la classe de 5","la classe de 1","la classe de 6","la classe de 0 (ℤ/6ℤ n'est pas un corps)"],a:3,exp:"2 × 3 = 6 ≡ 0 [6]"},
    {q:"Dans ℤ/5ℤ, l'inverse de la classe de 2 est…",c:["la classe de 2","la classe de 1","la classe de 4","la classe de 3"],a:3,exp:"2 × 3 = 6 ≡ 1 [5]"},
    {q:"Dans ℤ/7ℤ, la classe de 3 × 5 est…",c:["la classe de 3","la classe de 0","la classe de 1","la classe de 15"],a:2,exp:"15 ≡ 1 [7]"},
    {q:"Pour n = 12, le nombre de classes de ℤ/12ℤ est…",c:["24","6","12","11"],a:2,exp:"Une classe par reste possible"},
  ],
  "TleC — Nombres complexes : forme algébrique": [
    {q:"Dans ℂ, le nombre i vérifie…",c:["i² = 0","i² = 1","i = −1","i² = −1"],a:3,exp:"Définition de i"},
    {q:"Pour z = 3 − 2i, on a…",c:["Re(z) = 3 et Im(z) = −2","Re(z) = −2 et Im(z) = 3","Re(z) = 3 et Im(z) = −2i","Re(z) = 1 et Im(z) = 1"],a:0,exp:"Partie réelle 3, partie imaginaire −2"},
    {q:"Le nombre z = 5i est…",c:["imaginaire pur","réel","de partie réelle non nulle","égal à 5"],a:0,exp:"a = 0 et b ≠ 0"},
    {q:"z = z' si et seulement si…",c:["z − z' est imaginaire pur","Re(z) = Re(z') et Im(z) = Im(z')","Re(z) = Im(z')","|z| = |z'|"],a:1,exp:"Propriété admise"},
    {q:"z = 0 si et seulement si…",c:["Re(z) = Im(z)","|z| = 1","Re(z) = 0 et Im(z) = 0","Re(z) = 0 ou Im(z) = 0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"(2 + 3i) + (1 − 5i) = …",c:["3 − 8i","1 − 2i","3 + 8i","3 − 2i"],a:3,exp:"Somme des parties réelles et imaginaires"},
    {q:"(2 + 3i)(1 − i) = …",c:["2 − 3i","−1 + 5i","5 − i","5 + i"],a:3,exp:"2 − 2i + 3i − 3i² = 2 + i + 3"},
    {q:"i³ = …",c:["−1","i","1","−i"],a:3,exp:"i² × i"},
    {q:"i²⁰²⁶ = …",c:["1","−1","−i","i"],a:1,exp:"2026 = 4 × 506 + 2"},
    {q:"L'inverse de 1 + i est…",c:["(1 + i)/2","1/2","(1 − i)/2","1 − i"],a:2,exp:"1/(1 + i) = (1 − i)/((1 + i)(1 − i))"},
    {q:"1/(2 − i) = …",c:["(2 + i)/5","(2 − i)/5","(2 + i)/3","2 + i"],a:0,exp:"On multiplie par 2 + i"},
    {q:"zz' = 0 si et seulement si…",c:["z + z' = 0","z = 0 ou z' = 0","z = z'","z = 0 et z' = 0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"(2 + i)(2 − i) = …",c:["5","4","1","3"],a:0,exp:"4 − i² = 5"},
    {q:"L'ensemble des imaginaires purs est noté…",c:["ℝ","ℤ","ℂ*","iℝ"],a:3,exp:"Notation du guide"},
  ],
  "TleC — Conjugué & module": [
    {q:"Le conjugué de 3 − 4i est…",c:["−3 − 4i","−3 + 4i","3 + 4i","4 − 3i"],a:2,exp:"On change le signe de la partie imaginaire"},
    {q:"Pour z = a + ib, z × conj(z) = …",c:["a² + b²","2a","2ib","a² − b²"],a:0,exp:"Propriété démontrée en classe"},
    {q:"z + conj(z) = …",c:["|z|²","0","2 Re(z)","2i Im(z)"],a:2,exp:"Propriété démontrée en classe"},
    {q:"z − conj(z) = …",c:["2 Re(z)","|z|","0","2i Im(z)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"z est réel si et seulement si…",c:["conj(z) = −z","Im(z) = 1","conj(z) = z","|z| = 1"],a:2,exp:"Propriété démontrée en classe"},
    {q:"z est imaginaire pur (z ≠ 0) si et seulement si…",c:["conj(z) = −z","z = 1","conj(z) = z","Re(z) ≠ 0"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Le module de 3 − 4i est…",c:["1","√7","5","7"],a:2,exp:"√(9 + 16)"},
    {q:"Pour M d'affixe z, OM = …",c:["|z|","Re(z)","Im(z)","z²"],a:0,exp:"Interprétation géométrique du module"},
    {q:"Pour M et M' d'affixes z et z', MM' = …",c:["|z'| + |z|","|z' + z|","z' − z","|z' − z|"],a:3,exp:"Distance entre deux points"},
    {q:"|zz'| = …",c:["|z + z'|","|z| + |z'|","|z| × |z'|","|z|²"],a:2,exp:"Propriété démontrée en classe"},
    {q:"|zⁿ| = … (n entier relatif)",c:["|z|/n","|z|ⁿ","|z| + n","n|z|"],a:1,exp:"Propriété démontrée en classe"},
    {q:"L'inégalité triangulaire s'écrit…",c:["|z + z'| = |z| + |z'|","|z + z'| ≥ |z| + |z'|","|z + z'| ≤ |z| + |z'|","|z + z'| < |z| − |z'|"],a:2,exp:"Propriété démontrée en classe"},
    {q:"|z| = 0 si et seulement si…",c:["Re(z) = 0","z = 0","Im(z) = 0","z = 1"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La distance entre A(1 + i) et B(4 + 5i) est…",c:["7","√7","3","5"],a:3,exp:"|3 + 4i| = 5"},
    {q:"Le conjugué d'un produit est…",c:["la somme des conjugués","le produit des conjugués","égal au produit","l'opposé du produit"],a:1,exp:"conj(zz') = conj(z) conj(z')"},
  ],
  "TleC — Forme trigonométrique & exponentielle": [
    {q:"La forme trigonométrique d'un nombre complexe non nul z est…",c:["z = r + iθ","z = r(cos θ + i sin θ) avec r = |z| et θ = arg z","z = cos r + i sin r","z = r(cos θ − i sin θ)"],a:1,exp:"Définition du guide"},
    {q:"Le module et un argument de 1 + i sont…",c:["1 et π/4","2 et π/4","√2 et π/4","√2 et π/2"],a:2,exp:"|1 + i| = √2 ; cos θ = sin θ = √2/2"},
    {q:"Un argument de −1 est…",c:["π/2","−π/2","π","0"],a:2,exp:"−1 = cos π + i sin π"},
    {q:"Un argument de i est…",c:["−π/2","π","π/2","0"],a:2,exp:"i = cos(π/2) + i sin(π/2)"},
    {q:"arg(zz') = … (à 2π près)",c:["arg z × arg z'","arg z − arg z'","arg z + arg z'","2 arg z"],a:2,exp:"Propriété démontrée en classe"},
    {q:"arg(z/z') = … (à 2π près)",c:["arg z + arg z'","arg z − arg z'","arg z / arg z'","−arg z"],a:1,exp:"Propriété démontrée en classe"},
    {q:"arg(−z) = … (à 2π près)",c:["arg z","−arg z","π/2 + arg z","π + arg z"],a:3,exp:"Propriété démontrée en classe"},
    {q:"arg(zⁿ) = … (à 2π près)",c:["arg z / n","arg z + n","(arg z)ⁿ","n arg z"],a:3,exp:"Propriété démontrée en classe"},
    {q:"La formule de Moivre s'écrit (cos θ + i sin θ)ⁿ = …",c:["n cos θ + i n sin θ","cos nθ + i sin nθ","cos θ + i sin nθ","cosⁿθ + i sinⁿθ"],a:1,exp:"Formule de Moivre"},
    {q:"e^(iθ) = …",c:["cos θ − i sin θ","cos θ × sin θ","θ + i","cos θ + i sin θ"],a:3,exp:"Forme exponentielle"},
    {q:"Formule d'Euler : cos θ = …",c:["(e^(iθ) − e^(−iθ))/2","(e^(iθ) + e^(−iθ))/2","e^(iθ) e^(−iθ)","(e^(iθ) + e^(−iθ))/(2i)"],a:1,exp:"Formules d'Euler"},
    {q:"Formule d'Euler : sin θ = …",c:["(e^(iθ) + e^(−iθ))/(2i)","(e^(iθ) − e^(−iθ))/2","(e^(iθ) − e^(−iθ))/(2i)","(e^(iθ) + e^(−iθ))/2"],a:2,exp:"Formules d'Euler"},
    {q:"Si z = 2e^(iπ/3), alors z² = …",c:["4e^(iπ/9)","4e^(2iπ/3)","2e^(2iπ/3)","4e^(iπ/3)"],a:1,exp:"Module 2² = 4 ; argument 2 × π/3"},
    {q:"(1 + i)⁸ = …",c:["16","16i","256","−16"],a:0,exp:"(√2 e^(iπ/4))⁸ = 16 e^(2iπ)"},
    {q:"La forme exponentielle de 1 − i est…",c:["e^(−iπ/4)","√2 e^(iπ/4)","2e^(−iπ/4)","√2 e^(−iπ/4)"],a:3,exp:"Module √2 ; argument −π/4"},
    {q:"e^(iπ) = …",c:["i","−1","1","−i"],a:1,exp:"cos π + i sin π"},
    {q:"Deux complexes non nuls sont égaux si et seulement s'ils ont…",c:["même module et arguments égaux à 2kπ près","même module seulement","même partie réelle seulement","même argument seulement"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Linéariser cos²θ donne…",c:["(1 − cos 2θ)/2","cos 2θ","2 cos θ","(1 + cos 2θ)/2"],a:3,exp:"Avec les formules d'Euler"},
    {q:"|e^(iθ)| = …",c:["0","1","θ","2"],a:1,exp:"cos²θ + sin²θ = 1"},
  ],
  "TleC — Équations dans ℂ & racines n-ièmes": [
    {q:"Les racines carrées de −9 dans ℂ sont…",c:["3i et −3i","9i et −9i","3 et −3","aucune"],a:0,exp:"(3i)² = −9"},
    {q:"Les solutions de z² + 4 = 0 sont…",c:["2i et −2i","2 et −2","aucune solution","4i et −4i"],a:0,exp:"z² = −4"},
    {q:"Les solutions de z² − 2z + 5 = 0 sont…",c:["2 + i et 2 − i","1 + 2i et 1 − 2i","−1 + 2i et −1 − 2i","1 + 4i et 1 − 4i"],a:1,exp:"z = (2 ± √(−16))/2 = 1 ± 2i"},
    {q:"Si Δ < 0 et si a, b, c sont réels, les solutions de az² + bz + c = 0 sont…",c:["un réel double","deux nombres complexes conjugués","deux imaginaires purs toujours","deux réels distincts"],a:1,exp:"Racines conjuguées"},
    {q:"Pour az² + bz + c = 0 de solutions z₁ et z₂ : z₁ + z₂ = … et z₁ z₂ = …",c:["c/a et −b/a","b/a et −c/a","−b/a et c/a","−b et c"],a:2,exp:"Relations coefficients-racines"},
    {q:"Les racines n-ièmes de re^(iα) sont zₖ = …",c:["ⁿ√r e^(i(α + 2kπ)/n), k = 0, …, n − 1","r e^(i(α + 2kπ)), k entier","r/n e^(iα)","ⁿ√r e^(iα n)"],a:0,exp:"Propriété admise"},
    {q:"Un nombre complexe non nul admet combien de racines n-ièmes ?",c:["1","une infinité","n","2"],a:2,exp:"Racines zₖ pour k = 0, …, n − 1"},
    {q:"Pour n ≥ 3, les images des racines n-ièmes d'un complexe non nul sont…",c:["alignées","confondues","sur une même droite verticale","les sommets d'un polygone régulier à n côtés inscrit dans un cercle de centre O"],a:3,exp:"Propriété du guide"},
    {q:"Les racines cubiques de 1 sont…",c:["1 ; e^(iπ/3) ; e^(2iπ/3)","1 ; e^(2iπ/3) ; e^(4iπ/3)","1 ; 1/2 + i ; 1/2 − i","1 ; −1 ; i"],a:1,exp:"e^(2ikπ/3), k = 0, 1, 2"},
    {q:"Les racines quatrièmes de 1 sont…",c:["1 ; i","1 ; 2 ; 3 ; 4","1 ; i ; −1 ; −i","1 ; −1"],a:2,exp:"i⁴ = 1"},
    {q:"Si z₀ est racine d'un polynôme P de degré n ≥ 3, alors…",c:["Q est de degré n","P(z) = (z − z₀) Q(z) avec Q de degré n − 1","P(z) = z₀ Q(z)","P(z) = z − z₀"],a:1,exp:"Propriété du guide"},
    {q:"Si P est à coefficients réels et admet une racine non réelle z₀, alors…",c:["P n'a pas d'autre racine","1/z₀ est racine de P","−z₀ est racine de P","conj(z₀) est aussi racine de P"],a:3,exp:"Racines conjuguées"},
    {q:"Les racines carrées de 3 + 4i sont…",c:["1 + 2i et −1 − 2i","2 − i et −2 + i","3 + 4i et −3 − 4i","2 + i et −2 − i"],a:3,exp:"(2 + i)² = 4 + 4i − 1"},
    {q:"Les racines carrées de i sont…",c:["(1/2)(1 + i) et −(1/2)(1 + i)","1 + i et −1 − i","(√2/2)(1 + i) et −(√2/2)(1 + i)","i et −i"],a:2,exp:"e^(iπ/4) et e^(i5π/4)"},
  ],
  "TleC — Nombres complexes & géométrie plane": [
    {q:"mes(→OI, →AB) = … (à 2π près)",c:["arg(z_A − z_B)","|z_B − z_A|","arg(z_B + z_A)","arg(z_B − z_A)"],a:3,exp:"Propriété du guide"},
    {q:"mes(→AB, →CD) = … (à 2π près)",c:["arg((z_B − z_A)/(z_D − z_C))","arg((z_D − z_C)/(z_B − z_A))","|z_D − z_C|/|z_B − z_A|","arg(z_D − z_B)"],a:1,exp:"Propriété du guide"},
    {q:"A, B, C sont alignés si et seulement si…",c:["|z_C − z_A| = |z_B − z_A|","(z_C − z_A)/(z_B − z_A) ∈ ℝ","z_A + z_B + z_C = 0","(z_C − z_A)/(z_B − z_A) ∈ iℝ"],a:1,exp:"Propriété du guide"},
    {q:"(AB) et (CD) sont perpendiculaires si et seulement si…",c:["(z_D − z_C)/(z_B − z_A) ∈ iℝ","(z_D − z_C)/(z_B − z_A) ∈ ℝ","z_D − z_C = z_B − z_A","|z_D − z_C| = |z_B − z_A|"],a:0,exp:"Propriété du guide"},
    {q:"AB = …",c:["|z_A| + |z_B|","|z_B − z_A|","z_B − z_A","|z_A − z_B|²"],a:1,exp:"Distance entre deux points"},
    {q:"L'ensemble des points M d'affixe z tels que |z − (1 − i)| = 2 est…",c:["le cercle de centre d'affixe 1 + i et de rayon 2","la droite d'équation x = 2","le cercle de centre d'affixe 1 − i et de rayon 2","la médiatrice de [OA]"],a:2,exp:"Lieu géométrique"},
    {q:"L'ensemble des points M tels que |z − a| = |z − b| est…",c:["la droite (AB)","la médiatrice de [AB]","le cercle de diamètre [AB]","le milieu de [AB]"],a:1,exp:"MA = MB"},
    {q:"Si (z_C − z_A)/(z_B − z_A) = i, alors le triangle ABC est…",c:["rectangle en B","équilatéral","isocèle en B","rectangle isocèle en A"],a:3,exp:"AC = AB et angle de 90°"},
    {q:"Si (z_C − z_A)/(z_B − z_A) = e^(iπ/3), alors le triangle ABC est…",c:["aplati","rectangle en A","équilatéral","isocèle rectangle"],a:2,exp:"AC = AB et angle de 60°"},
    {q:"ABCD est un parallélogramme si et seulement si…",c:["z_B − z_A = z_C − z_D","z_B − z_A = z_D − z_C","|z_A| = |z_C|","z_A + z_C = 0"],a:0,exp:"→AB = →DC"},
    {q:"Le milieu de [AB] a pour affixe…",c:["(z_B − z_A)/2","|z_A + z_B|/2","(z_A + z_B)/2","z_A z_B"],a:2,exp:"Affixe du milieu"},
  ],
  "TleC — Limites & continuité": [
    {q:"Si lim f = b en a et lim g = l en b, alors lim (g∘f) en a vaut…",c:["l","b","a","l + b"],a:0,exp:"Limite de la composée (propriété admise)"},
    {q:"La somme d'une fonction majorée et d'une fonction de limite −∞ a pour limite…",c:["−∞","+∞","une limite finie","0"],a:0,exp:"Propriété du guide"},
    {q:"La somme d'une fonction minorée et d'une fonction de limite +∞ a pour limite…",c:["+∞","une limite finie","0","−∞"],a:0,exp:"Propriété du guide"},
    {q:"Une fonction croissante et majorée sur [a ; b[ admet en b…",c:["aucune limite","une limite finie à gauche","la limite +∞","la limite −∞"],a:1,exp:"Propriété admise"},
    {q:"Une fonction croissante et non majorée sur [a ; b[ a pour limite en b à gauche…",c:["une valeur finie","0","+∞","−∞"],a:2,exp:"Propriété admise"},
    {q:"Le prolongement par continuité de f en a existe lorsque…",c:["f est définie en a","f est paire","f est croissante","f admet une limite finie en a"],a:3,exp:"Définition"},
    {q:"La composée de deux fonctions continues est…",c:["toujours dérivable","monotone","bornée","continue"],a:3,exp:"Propriété admise"},
    {q:"L'image d'un intervalle par une fonction continue est…",c:["un point","un ensemble fini","un intervalle","une réunion de deux intervalles"],a:2,exp:"Propriété admise"},
    {q:"Si f est continue sur [a ; b], alors f([a ; b]) = …",c:["]f(a) ; f(b)[","[f(a) ; f(b)]","[m ; M], où m et M sont le minimum et le maximum de f","ℝ"],a:2,exp:"Propriété admise"},
    {q:"Théorème des valeurs intermédiaires : f continue sur [a ; b] et k compris entre f(a) et f(b) ⟹",c:["f est monotone","l'équation f(x) = k admet au moins une solution dans [a ; b]","l'équation f(x) = k admet une solution unique","f(x) = 0 n'a pas de solution"],a:1,exp:"TVI"},
    {q:"Si f est continue sur K et f(a) f(b) < 0 avec a < b dans K, alors…",c:["f est strictement croissante","f(x) > 0 sur [a ; b]","f(x) = 0 n'admet aucune solution","f(x) = 0 admet au moins une solution entre a et b"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si f est continue et strictement monotone sur [a ; b] avec f(a) f(b) < 0, alors f(x) = 0 a…",c:["deux solutions","aucune solution","une infinité de solutions","une unique solution dans [a ; b]"],a:3,exp:"Propriété admise"},
    {q:"Si f est continue et strictement croissante sur [a ; b], alors f([a ; b]) = …",c:["]f(a) ; f(b)[","[f(b) ; f(a)]","[f(a) ; f(b)]","[a ; b]"],a:2,exp:"Propriété admise"},
    {q:"Si f est continue et strictement décroissante sur [a ; b], alors f([a ; b]) = …",c:["[a ; b]","]f(b) ; f(a)[","[f(b) ; f(a)]","[f(a) ; f(b)]"],a:2,exp:"Propriété admise"},
    {q:"Si f est continue et strictement monotone sur K, alors f réalise…",c:["une bijection de K sur ℝ","une fonction périodique","une bijection de K sur f(K), de réciproque continue et de même sens de variation","une fonction constante"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La fonction racine n-ième (n ≥ 2) est…",c:["la bijection réciproque de x ↦ xⁿ sur ℝ⁺","la dérivée de xⁿ","la fonction x ↦ nx","la fonction x ↦ x/n"],a:0,exp:"Définition du guide"},
    {q:"8^(2/3) = …",c:["64","2","16/3","4"],a:3,exp:"(∛8)² = 2²"},
    {q:"f est continue en a si et seulement si…",c:["la limite de f en a est égale à f(a)","f est dérivable en a","f est croissante en a","f est définie en a"],a:0,exp:"Définition"},
  ],
  "TleC — Dérivation & étude de fonctions": [
    {q:"f est dérivable en x₀ si et seulement si f(x₀ + h) = f(x₀) + l h + h φ(h) avec…",c:["φ(h) de limite 0 quand h tend vers 0","φ(h) de limite +∞","φ constante non nulle","φ(h) = h"],a:0,exp:"Propriété admise (développement limité d'ordre 1)"},
    {q:"f est dérivable en x₀ si et seulement si…",c:["f est continue en x₀","f est définie en x₀","f' est positive en x₀","f est dérivable à gauche et à droite en x₀ avec f'g(x₀) = f'd(x₀)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Un point anguleux est un point où la courbe admet…",c:["deux demi-tangentes de supports distincts","une tangente verticale","aucune tangente","une tangente horizontale"],a:0,exp:"Définition du guide"},
    {q:"La fonction valeur absolue x ↦ |x| en 0…",c:["n'est pas continue","n'est pas dérivable : la courbe a un point anguleux","est dérivable de dérivée 1","est dérivable de dérivée 0"],a:1,exp:"f'g(0) = −1 et f'd(0) = 1"},
    {q:"Un point d'inflexion est un point où la tangente…",c:["est horizontale","est parallèle à l'axe (Ox)","traverse la courbe","est verticale"],a:2,exp:"Définition du guide"},
    {q:"Si f'' s'annule en x₀ en changeant de signe, alors…",c:["f a un extremum en x₀","le point d'abscisse x₀ est un point d'inflexion","f n'est pas dérivable en x₀","f est constante"],a:1,exp:"Utilisation de la dérivée seconde"},
    {q:"Si le taux d'accroissement (f(x₀ + h) − f(x₀))/h a une limite infinie en 0, la courbe admet…",c:["une asymptote oblique","une tangente horizontale","un point d'inflexion","une demi-tangente verticale"],a:3,exp:"Propriété admise"},
    {q:"La dérivée seconde de f est…",c:["l'inverse de f'","le carré de f'","la dérivée de la fonction dérivée f'","f' divisée par f"],a:2,exp:"Notée f''"},
    {q:"La dérivée de g∘f est…",c:["(f'∘g) × g'","f' + g'","f' × (g'∘f)","g' × (f'∘g)"],a:2,exp:"Dérivée de la composée"},
    {q:"La dérivée de x ↦ (3x + 1)⁴ est…",c:["4(3x + 1)³","12(3x + 1)⁴","12(3x + 1)³","(3x + 1)⁴"],a:2,exp:"4 × 3 × (3x + 1)³"},
    {q:"La dérivée de x ↦ √(x² + 1) est…",c:["2x/√(x² + 1)","x/√(x² + 1)","√(x² + 1)","1/(2√(x² + 1))"],a:1,exp:"2x/(2√(x² + 1))"},
    {q:"La dérivée de x ↦ sin(2x) est…",c:["2 cos(2x)","−2 cos(2x)","cos(2x)","2 sin(2x)"],a:0,exp:"Composée : 2 × cos(2x)"},
    {q:"La dérivée de x ↦ cos²x est…",c:["−2 cos x","2 cos x","−2 sin x cos x","2 sin x cos x"],a:2,exp:"2 cos x × (−sin x)"},
    {q:"La dérivée de x ↦ tan x est…",c:["1 + tan²x","1/sin²x","−1/cos²x","tan x"],a:0,exp:"1/cos²x = 1 + tan²x"},
    {q:"Si φ est la bijection réciproque de f (f dérivable, f' ≠ 0), alors φ'(y) = …",c:["1 / f'(φ(y))","−f'(φ(y))","1 / f'(y)","f'(φ(y))"],a:0,exp:"Dérivée de la réciproque"},
    {q:"Inégalité des accroissements finis : si m ≤ f' ≤ M sur [a ; b], alors…",c:["f(b) − f(a) ≤ m","f(b) ≥ M","m(b − a) ≤ f(b) − f(a) ≤ M(b − a)","f(b) − f(a) = m + M"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si |f'| ≤ M sur [a ; b], alors…",c:["|f(b) − f(a)| ≤ M |b − a|","f(b) = f(a)","|f(b)| ≤ M","|f(b) − f(a)| ≥ M |b − a|"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La dérivée de x ↦ x^(1/n) (x > 0) est…",c:["n x^(n − 1)","x^(1/n)","1/(n x)","(1/n) x^((1/n) − 1)"],a:3,exp:"Dérivée d'une fonction puissance"},
  ],
  "TleC — Compléments sur les primitives": [
    {q:"Une primitive de f' × fⁿ (n entier, n ≠ −1) est…",c:["fⁿ/n","f^(n+1)/(n + 1)","f^(n+1)","n fⁿ⁻¹"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f ne s'annule pas, une primitive de f'/f² est…",c:["f²","1/f","−1/f","ln|f|"],a:2,exp:"Cas n = −2"},
    {q:"Si f est strictement positive, une primitive de f'/√f est…",c:["√f","f√f","2√f","1/√f"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Une primitive de f' × (g'∘f) est…",c:["g' ∘ f","f' × g","f∘g","g∘f"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une primitive de 2x(x² + 1)³ est…",c:["(x² + 1)⁴/4","2(x² + 1)⁴","(x² + 1)³/3","(x² + 1)⁴"],a:0,exp:"u'u³ avec u = x² + 1"},
    {q:"Une primitive de x/√(x² + 1) est…",c:["2√(x² + 1)","ln(x² + 1)","√(x² + 1)","1/√(x² + 1)"],a:2,exp:"u'/(2√u) avec u = x² + 1"},
    {q:"Une primitive de cos x sin³x est…",c:["cos⁴x/4","sin⁴x/4","sin³x","−sin⁴x/4"],a:1,exp:"u'u³ avec u = sin x"},
    {q:"Une primitive de 1/cos²x sur un intervalle où cos x ≠ 0 est…",c:["1/sin x","tan x","sin x/cos x²","−tan x"],a:1,exp:"(tan x)' = 1/cos²x"},
    {q:"Deux primitives d'une même fonction sur un intervalle diffèrent d'…",c:["un facteur","une fonction affine","une fonction paire","une constante"],a:3,exp:"Propriété fondamentale des primitives"},
  ],
  "TleC — Fonction logarithme népérien": [
    {q:"Le logarithme népérien est la primitive de x ↦ 1/x sur ]0 ; +∞[ qui…",c:["s'annule en 1","vaut e en 1","s'annule en e","vaut 1 en 0"],a:0,exp:"Définition du guide"},
    {q:"ln(xy) = … (x, y > 0)",c:["ln x / ln y","ln x + ln y","ln x × ln y","ln x − ln y"],a:1,exp:"Propriété fondamentale"},
    {q:"ln(1/x) = …",c:["ln x","−ln x","1/ln x","x"],a:1,exp:"Conséquence de ln(xy)"},
    {q:"ln(x/y) = …",c:["ln x − ln y","ln x / ln y","ln x + ln y","ln(x − y)"],a:0,exp:"Propriété démontrée en classe"},
    {q:"ln(xʳ) = … (r rationnel)",c:["(ln x)ʳ","ln r × x","r ln x","r + ln x"],a:2,exp:"Propriété démontrée en classe"},
    {q:"ln 1 = … et ln e = …",c:["0 et e","0 et 1","1 et 0","1 et e"],a:1,exp:"L'antécédent de 1 par ln est e"},
    {q:"La limite de ln x en +∞ est…",c:["−∞","0","+∞","1"],a:2,exp:"Propriété démontrée en classe"},
    {q:"La limite de ln x en 0 (x > 0) est…",c:["+∞","1","0","−∞"],a:3,exp:"Propriété admise"},
    {q:"La limite de (ln x)/x en +∞ est…",c:["0","−∞","+∞","1"],a:0,exp:"Croissances comparées"},
    {q:"La limite de x ln x en 0 (x > 0) est…",c:["−∞","0","+∞","1"],a:1,exp:"Croissances comparées"},
    {q:"La limite de ln(1 + x)/x en 0 est…",c:["1","+∞","0","e"],a:0,exp:"Nombre dérivé de ln en 1"},
    {q:"La fonction ln est…",c:["strictement croissante et bijective de ]0 ; +∞[ sur ℝ","paire","périodique","strictement décroissante sur ]0 ; +∞["],a:0,exp:"Étude de la fonction ln"},
    {q:"Pour a, b > 0 : ln a = ln b équivaut à…",c:["a = b","a = 1","a = e","a + b = 1"],a:0,exp:"ln est bijective"},
    {q:"La dérivée de ln∘u est…",c:["1/u","u'","u' ln u","u'/u"],a:3,exp:"u strictement positive et dérivable"},
    {q:"Une primitive de u'/u sur un intervalle où u ne s'annule pas est…",c:["u²","ln u","1/u","ln|u|"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Résoudre ln(x − 1) = 0.",c:["x = 2","x = 1","x = 0","x = e"],a:0,exp:"x − 1 = 1"},
    {q:"Résoudre ln x < 1 (x > 0).",c:["0 < x < e","0 < x < 1","x > e","x < e"],a:0,exp:"ln est croissante"},
    {q:"Le domaine de définition de x ↦ ln(x − 3) est…",c:["]0 ; +∞[","[3 ; +∞[","ℝ","]3 ; +∞["],a:3,exp:"x − 3 > 0"},
    {q:"ln 8 = …",c:["8 ln 2","2 ln 3","3 ln 2","ln 2 + 8"],a:2,exp:"8 = 2³"},
    {q:"La dérivée de x ↦ ln(x² + 1) est…",c:["2x","ln(2x)","1/(x² + 1)","2x/(x² + 1)"],a:3,exp:"u'/u"},
    {q:"Le logarithme décimal est défini par log x = …",c:["ln 10 / ln x","ln x / ln 10","x ln 10","ln x × ln 10"],a:1,exp:"Changement de base"},
  ],
  "TleC — Fonction exponentielle népérienne": [
    {q:"Pour tout réel x, exp(x) est…",c:["strictement positif","entier","négatif ou nul","égal à 1"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Pour x > 0, exp(ln x) = … et pour tout réel x, ln(exp x) = …",c:["ln x et exp x","x et 1","x et x","1 et 1"],a:2,exp:"exp et ln sont réciproques"},
    {q:"La fonction exp est une bijection de…",c:["ℝ sur ℝ","ℝ⁺ sur ℝ⁻","ℝ sur ]0 ; +∞[","]0 ; +∞[ sur ℝ"],a:2,exp:"Propriété démontrée en classe"},
    {q:"e^(a + b) = …",c:["(eᵃ)ᵇ","e^(ab)","eᵃ × eᵇ","eᵃ + eᵇ"],a:2,exp:"Propriété fondamentale"},
    {q:"e^(−a) = …",c:["−eᵃ","1/eᵃ","eᵃ","1 − eᵃ"],a:1,exp:"Propriété démontrée en classe"},
    {q:"(eᵃ)ʳ = …",c:["e^(a + r)","e^(ar)","aʳ","eᵃ + r"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La dérivée de exp est…",c:["exp","x exp","1/exp","−exp"],a:0,exp:"exp est égale à sa dérivée"},
    {q:"La dérivée de e^u est…",c:["u' e^(u')","u' e^u","e^u","u e^u"],a:1,exp:"Dérivée de la composée"},
    {q:"La limite de eˣ en +∞ est … et en −∞ est …",c:["0 et +∞","+∞ et 0","1 et 0","+∞ et −∞"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La limite de eˣ/x en +∞ est…",c:["1","e","+∞","0"],a:2,exp:"Croissances comparées"},
    {q:"La limite de x eˣ en −∞ est…",c:["0","+∞","−∞","1"],a:0,exp:"Croissances comparées"},
    {q:"La limite de (eˣ − 1)/x en 0 est…",c:["0","e","+∞","1"],a:3,exp:"Nombre dérivé de exp en 0"},
    {q:"Résoudre eˣ = 3.",c:["x = 3","x = ln 3","x = e³","x = 1/3"],a:1,exp:"On applique ln aux deux membres"},
    {q:"Résoudre e^(2x) − 3eˣ + 2 = 0.",c:["{1 ; 2}","{0 ; ln 2}","{ln 1 ; ln 3}","{0 ; 2}"],a:1,exp:"X = eˣ : X² − 3X + 2 = 0, donc X = 1 ou X = 2"},
    {q:"Résoudre eˣ ≥ 1.",c:["x ≥ 0","x ≤ 0","x ≥ 1","x ≤ 1"],a:0,exp:"exp est croissante et e⁰ = 1"},
    {q:"Une primitive de u' e^u est…",c:["u e^u","e^u","e^(u')","u' e^(u²)"],a:1,exp:"Propriété démontrée en classe"},
    {q:"eᵃ < eᵇ équivaut à…",c:["a > b","a + b < 0","a = b","a < b"],a:3,exp:"exp est strictement croissante"},
    {q:"La dérivée de x ↦ x eˣ est…",c:["eˣ","x eˣ","(x + 1) eˣ","(x − 1) eˣ"],a:2,exp:"Dérivée d'un produit"},
    {q:"La dérivée de x ↦ e^(x²) est…",c:["2 e^(x²)","e^(x²)","x² e^(x²)","2x e^(x²)"],a:3,exp:"u' e^u"},
  ],
  "TleC — Exponentielles de base a & fonctions puissances": [
    {q:"Pour a > 0 et α réel, aᵅ = …",c:["e^(α ln a)","a ln α","e^(a ln α)","α ln a"],a:0,exp:"Définition du guide"},
    {q:"Si a > 1, la fonction x ↦ aˣ est…",c:["constante","périodique","strictement décroissante sur ℝ","strictement croissante sur ℝ"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si 0 < a < 1, la fonction x ↦ aˣ est…",c:["constante","strictement décroissante sur ℝ","strictement croissante sur ℝ","paire"],a:1,exp:"Propriété démontrée en classe"},
    {q:"La dérivée de x ↦ aˣ (a > 0) est…",c:["ln a × aˣ","aˣ","x aˣ⁻¹","aˣ / ln a"],a:0,exp:"aˣ = e^(x ln a)"},
    {q:"La dérivée de x ↦ xᵅ sur ]0 ; +∞[ est…",c:["x^(α − 1)","α xᵅ","α x^(α − 1)","xᵅ/α"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si α > 0, la limite de xᵅ en +∞ est…",c:["−∞","0","+∞","1"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si α < 0, la limite de xᵅ en +∞ est…",c:["0","+∞","1","−∞"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si α > 0, la limite de (ln x)/xᵅ en +∞ est…",c:["+∞","1","0","α"],a:2,exp:"Croissances comparées"},
    {q:"Pour n entier naturel, la limite de xⁿ eˣ en −∞ est…",c:["+∞","−∞","0","1"],a:2,exp:"Croissances comparées"},
    {q:"Une primitive de x ↦ xᵅ (α ≠ −1) sur ]0 ; +∞[ est…",c:["ln x","α x^(α − 1)","xᵅ/α","x^(α + 1)/(α + 1)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Résoudre 2ˣ = 8.",c:["x = 3","x = 2","x = 4","x = 8"],a:0,exp:"2³ = 8"},
    {q:"3^(x + 1) = …",c:["3ˣ + 1","3ˣ / 3","3ˣ⁺¹ + 3","3 × 3ˣ"],a:3,exp:"aˣ⁺¹ = a × aˣ"},
    {q:"La dérivée de g^α (g > 0 dérivable) est…",c:["g' g^α","α g'","α g' g^(α − 1)","α g^(α − 1)"],a:2,exp:"Propriété démontrée en classe"},
  ],
  "TleC — Calcul intégral": [
    {q:"∫ de a à b de f(x) dx = …",c:["f(b) − f(a)","F(a) + F(b)","F(a) − F(b)","F(b) − F(a), où F est une primitive de f"],a:3,exp:"Définition du guide"},
    {q:"∫ de a à a de f(x) dx = …",c:["f(a)","F(a)","0","1"],a:2,exp:"Propriété démontrée en classe"},
    {q:"∫ de b à a de f = …",c:["∫ de a à b de f","∫ de a à b de |f|","− ∫ de a à b de f","0"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Relation de Chasles : ∫ de a à c de f + ∫ de c à b de f = …",c:["0","∫ de b à a de f","∫ de a à b de f","∫ de a à c de f"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si f est positive sur [a ; b] (a ≤ b), alors ∫ de a à b de f est…",c:["positive : c'est l'aire du domaine sous la courbe","toujours égale à b − a","négative","nulle"],a:0,exp:"Interprétation en unités d'aire"},
    {q:"Si f ≥ g sur [a ; b], alors…",c:["∫ de a à b de f ≤ ∫ de a à b de g","∫ de a à b de f = ∫ de a à b de g","∫ de a à b de f ≥ ∫ de a à b de g","f = g"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Inégalité de la moyenne : si m ≤ f ≤ M sur [a ; b], alors…",c:["∫ de a à b de f = m + M","∫ de a à b de f ≥ M","∫ de a à b de f ≤ m","m(b − a) ≤ ∫ de a à b de f ≤ M(b − a)"],a:3,exp:"Propriété énoncée dans le guide"},
    {q:"La valeur moyenne de f sur [a ; b] est…",c:["(1/(b − a)) ∫ de a à b de f","(f(a) + f(b))/2 toujours","f((a + b)/2) toujours","∫ de a à b de f"],a:0,exp:"Définition du guide"},
    {q:"∫ de 0 à 1 de x² dx = …",c:["1/3","2/3","1","1/2"],a:0,exp:"[x³/3] de 0 à 1"},
    {q:"∫ de 1 à e de (1/x) dx = …",c:["1","0","e","e − 1"],a:0,exp:"ln e − ln 1"},
    {q:"∫ de 0 à π de sin x dx = …",c:["0","2","π","1"],a:1,exp:"[−cos x] de 0 à π = 1 + 1"},
    {q:"∫ de 0 à 2 de (3x² + 1) dx = …",c:["8","6","14","10"],a:3,exp:"[x³ + x] de 0 à 2"},
    {q:"Si f est paire et continue, ∫ de −a à a de f = …",c:["∫ de 0 à a de f","2 ∫ de 0 à a de f","0","−2 ∫ de 0 à a de f"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est impaire et continue, ∫ de −a à a de f = …",c:["a","0","2 ∫ de 0 à a de f","−a"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est continue et T-périodique, ∫ de a à a + T de f…",c:["ne dépend pas de a","est nulle","vaut T","dépend de a"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Intégration par parties : ∫ de a à b de f g' = …",c:["∫ f' g − [f g]","f g' − f' g","[f g] de a à b − ∫ de a à b de f' g","[f g] de a à b + ∫ de a à b de f' g"],a:2,exp:"Formule d'intégration par parties"},
    {q:"∫ de 0 à 1 de x eˣ dx = …",c:["0","e − 1","e","1"],a:3,exp:"[x eˣ − eˣ] de 0 à 1 = 0 − (−1)"},
    {q:"Si f ≥ g sur [a ; b], l'aire entre les courbes Cf et Cg est…",c:["∫ de a à b de (f + g)","∫ de a à b de f × g","∫ de a à b de (f − g)","∫ de a à b de (g − f)"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Le volume d'un solide compris entre les plans z = a et z = b est V = …",c:["∫ de a à b de S(t) dt, où S(t) est l'aire de la section","S(b) − S(a)","(S(a) + S(b))/2","S(a) × (b − a)"],a:0,exp:"Propriété admise"},
    {q:"Le volume de révolution engendré par un domaine sous la courbe d'une fonction positive f entre a et b, autour de (Ox), est…",c:["∫ de a à b de f(x)² dx","π ∫ de a à b de f(x)² dx","π ∫ de a à b de f(x) dx","2π ∫ de a à b de f(x) dx"],a:1,exp:"Solides de révolution"},
    {q:"Le volume d'une boule de rayon R est…",c:["4 π R²","(1/3) π R³","π R³","(4/3) π R³"],a:3,exp:"Solide de révolution : π ∫ de −R à R de (R² − x²) dx"},
    {q:"La fonction F(x) = ∫ de a à x de f(t) dt est…",c:["l'unique primitive de f qui s'annule en a","une primitive de f valant 1 en a","la dérivée de f","une constante"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La méthode des trapèzes permet de déterminer…",c:["un extremum","une valeur approchée d'une intégrale","une primitive","la valeur exacte de toute intégrale"],a:1,exp:"Méthode du guide"},
  ],
  "TleC — Équations différentielles": [
    {q:"Les solutions de y' = f(x) sont…",c:["les fonctions constantes","f²","les primitives de f","les dérivées de f"],a:2,exp:"Équation du type y' = f(x)"},
    {q:"Pour résoudre y'' = g(x), on…",c:["multiplie g par x²","primitive deux fois g","dérive deux fois g","résout une équation du second degré"],a:1,exp:"Deux primitivations successives"},
    {q:"Les solutions de a y' + b y = 0 (a ≠ 0) sont…",c:["y = −b/a","y = C x e^(−b/a)","y = C e^(−bx/a)","y = C e^(bx/a)"],a:2,exp:"Propriété du guide"},
    {q:"La solution de y' + 2y = 0 avec y(0) = 3 est…",c:["y = 3e^(2x)","y = −6x + 3","y = e^(−2x)","y = 3e^(−2x)"],a:3,exp:"y = C e^(−2x) avec C = 3"},
    {q:"Les solutions de y' = 3y sont…",c:["y = 3x","y = C e^(3x)","y = C + 3x","y = C e^(−3x)"],a:1,exp:"a = 1, b = −3"},
    {q:"L'équation caractéristique de a y'' + b y' + c y = 0 est…",c:["a r² + b r + c = 0","r² = a + b + c","a r + b = 0","a + b r + c r² = 0 avec r = 0"],a:0,exp:"Définition du guide"},
    {q:"Les solutions de y'' − 3y' + 2y = 0 sont…",c:["y = C₁ e^(−x) + C₂ e^(−2x)","y = C₁ cos x + C₂ sin x","y = (C₁ x + C₂) eˣ","y = C₁ eˣ + C₂ e^(2x)"],a:3,exp:"r² − 3r + 2 = 0 : r = 1 ou r = 2"},
    {q:"Les solutions de y'' + y = 0 sont…",c:["y = (C₁ x + C₂) e^(−x)","y = C₁ eˣ + C₂ e^(−x)","y = C e^x","y = C₁ cos x + C₂ sin x"],a:3,exp:"r² + 1 = 0 : r = ± i"},
    {q:"Les solutions de y'' + 2y' + y = 0 sont…",c:["y = C₁ cos x + C₂ sin x","y = (C₁ x + C₂) e^(−x)","y = C e^(−2x)","y = C₁ e^(−x) + C₂ e^(x)"],a:1,exp:"Racine double r = −1"},
    {q:"Si l'équation caractéristique a des racines α ± iβ, les solutions sont…",c:["y = C₁ e^(αx) + C₂ e^(βx)","y = e^(αx)(C₁ cos βx + C₂ sin βx)","y = (C₁ x + C₂) e^(αx)","y = C e^(iβx) seulement"],a:1,exp:"Cas Δ < 0"},
    {q:"Les solutions de y'' = 6x sont…",c:["y = 6","y = x³ + C₁ x + C₂","y = x³ + C","y = 3x² + C"],a:1,exp:"Deux primitivations"},
    {q:"Les solutions de y' + y = 1 sont…",c:["y = 1 − x","y = C e^(−x)","y = C e^x + 1","y = 1 + C e^(−x)"],a:3,exp:"y = 1 est solution particulière"},
    {q:"La solution de y' − y = 0 avec y(0) = 1 est…",c:["y = e^(−x)","y = eˣ","y = x + 1","y = 1"],a:1,exp:"C = 1"},
    {q:"La solution générale de a y' + b y = f(x) est la somme…",c:["de f et de sa primitive","d'une solution particulière et de la solution générale de a y' + b y = 0","de y' et de y","de deux solutions particulières"],a:1,exp:"Structure des solutions"},
  ],
  "TleC — Probabilités : événements & probabilité conditionnelle": [
    {q:"Une probabilité p sur un univers Ω vérifie p(Ω) = …",c:["le nombre d'éléments de Ω","1","0","1/2"],a:1,exp:"Définition du guide"},
    {q:"Si A et B sont incompatibles, p(A ∪ B) = …",c:["p(A) × p(B)","p(A) + p(B)","1","p(A) − p(B)"],a:1,exp:"Définition d'une probabilité"},
    {q:"p(A) + p(non A) = …",c:["1","2","0","p(Ω) − 1"],a:0,exp:"Propriété démontrée en classe"},
    {q:"p(A ∪ B) = …",c:["p(A) + p(B) + p(A ∩ B)","p(A) + p(B) − p(A ∩ B)","p(A) × p(B)","p(A) − p(B)"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si A ⊂ B, alors…",c:["p(A) ≥ p(B)","p(A) = p(B)","p(A) ≤ p(B)","p(A) + p(B) = 1"],a:2,exp:"Propriété démontrée en classe"},
    {q:"En situation d'équiprobabilité, p(A) = …",c:["nombre de cas favorables / nombre de cas possibles","p(non A)","nombre de cas possibles / nombre de cas favorables","1/2"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La probabilité conditionnelle de A sachant B (p(B) ≠ 0) est p_B(A) = …",c:["p(A ∩ B)/p(B)","p(A ∩ B)/p(A)","p(A ∪ B)/p(B)","p(A) × p(B)"],a:0,exp:"Définition du guide"},
    {q:"p(A ∩ B) = …",c:["p_A(B) + p(A)","p_A(B) × p(A)","p(A) + p(B)","p(A)/p_A(B)"],a:1,exp:"Formule des probabilités composées"},
    {q:"Si (B₁, …, Bₙ) est un système complet d'événements, alors p(A) = …",c:["p(B₁) + … + p(Bₙ)","p(A ∩ B₁) × … × p(A ∩ Bₙ)","p(A ∩ B₁) + p(A ∩ B₂) + … + p(A ∩ Bₙ)","1"],a:2,exp:"Formule des probabilités totales"},
    {q:"Un système complet d'événements est formé d'événements…",c:["de même probabilité","deux à deux incompatibles dont la réunion est Ω","tous de probabilité 1/2","tous contraires les uns des autres"],a:1,exp:"Définition"},
    {q:"A et B sont indépendants si et seulement si…",c:["p(A) = p(B)","p(A ∪ B) = 1","p(A ∩ B) = p(A) × p(B)","p(A ∩ B) = 0"],a:2,exp:"Définition du guide"},
    {q:"Si A et B sont indépendants (p(B) ≠ 0), alors p_B(A) = …",c:["1","p(A)","p(B)","0"],a:1,exp:"Propriété démontrée en classe"},
    {q:"A et B sont indépendants si et seulement si A et non B sont…",c:["contraires","incompatibles","indépendants","confondus"],a:2,exp:"Propriété démontrée en classe"},
    {q:"p(A) = 0,4 ; p(B) = 0,5 ; p(A ∩ B) = 0,2. Les événements A et B sont…",c:["incompatibles","indépendants","contraires","impossibles"],a:1,exp:"0,4 × 0,5 = 0,2"},
    {q:"p(A) = 0,3 ; p(B) = 0,6 ; p(A ∩ B) = 0,18. Alors p_B(A) = …",c:["0,5","0,18","0,6","0,3"],a:3,exp:"0,18/0,6"},
    {q:"On tire deux boules sans remise dans une urne de 3 rouges et 2 bleues. La probabilité de tirer deux rouges est…",c:["3/10","9/25","6/25","3/5"],a:0,exp:"3/5 × 2/4"},
    {q:"On lance deux dés équilibrés. La probabilité d'obtenir une somme égale à 7 est…",c:["1/7","7/36","1/6","1/12"],a:2,exp:"6 couples sur 36"},
    {q:"Deux événements sont incompatibles lorsque…",c:["A ∪ B = Ω","p(A ∩ B) = p(A) p(B)","A ∩ B = ∅","p(A) = p(B)"],a:2,exp:"Définition"},
  ],
  "TleC — Variables aléatoires & loi binomiale": [
    {q:"Une variable aléatoire réelle est…",c:["une application de l'univers Ω dans ℝ","un nombre fixé à l'avance","une probabilité","un événement"],a:0,exp:"Définition du guide"},
    {q:"L'espérance de X prenant les valeurs xᵢ avec les probabilités pᵢ est E(X) = …",c:["Σ pᵢ xᵢ","Σ xᵢ² / n","Σ pᵢ","Σ xᵢ"],a:0,exp:"Définition"},
    {q:"La variance de X est V(X) = …",c:["Σ pᵢ (xᵢ − E(X))","E(X)²","Σ pᵢ (xᵢ − E(X))²","Σ pᵢ xᵢ"],a:2,exp:"Définition"},
    {q:"L'écart-type de X est…",c:["la moitié de V(X)","le carré de V(X)","la racine carrée de V(X)","E(X)/V(X)"],a:2,exp:"σ(X) = √V(X)"},
    {q:"La fonction de répartition de X est définie par F(t) = …",c:["p(X ≤ t)","p(X ≥ t)","p(X = t)","p(X < t)"],a:0,exp:"Définition du guide"},
    {q:"X prend les valeurs 0, 1, 2 avec les probabilités 0,2 ; 0,5 ; 0,3. Alors E(X) = …",c:["0,5","1","1,1","1,3"],a:2,exp:"0 + 0,5 + 0,6"},
    {q:"X prend les valeurs 0, 1, 2 avec les probabilités 0,2 ; 0,5 ; 0,3. La variance de X vaut…",c:["1,7","0,49","1,21","0,7"],a:1,exp:"E(X²) = 0,5 + 1,2 = 1,7 ; V = 1,7 − 1,1²"},
    {q:"La fonction de répartition est…",c:["constante","décroissante","à valeurs dans [1 ; +∞[","croissante, à valeurs dans [0 ; 1]"],a:3,exp:"Propriété de F"},
    {q:"La somme des probabilités de la loi d'une variable aléatoire est…",c:["E(X)","0","le nombre de valeurs","1"],a:3,exp:"p(Ω) = 1"},
    {q:"Une épreuve de Bernoulli est…",c:["une expérience à deux issues : succès de probabilité p et échec","une expérience à trois issues","une expérience sans hasard","une expérience de probabilité 1/2 obligatoire"],a:0,exp:"Définition du guide"},
    {q:"Un schéma de Bernoulli est…",c:["un arbre à trois branches","la répétition de n épreuves de Bernoulli identiques et indépendantes","une seule épreuve","une suite d'épreuves dépendantes"],a:1,exp:"Définition du guide"},
    {q:"Si X suit la loi binomiale B(n ; p), alors p(X = k) = …",c:["n pᵏ","pᵏ (1 − p)ᵏ","C(n, k) pᵏ (1 − p)^(n − k)","C(n, k) pⁿ"],a:2,exp:"Propriété admise"},
    {q:"Si X suit la loi binomiale B(n ; p), alors E(X) = …",c:["n p (1 − p)","p/n","n(1 − p)","n p"],a:3,exp:"Propriété du guide"},
    {q:"Si X suit la loi binomiale B(n ; p), alors V(X) = …",c:["p (1 − p)","n p (1 − p)","n (1 − p)","n p"],a:1,exp:"Propriété du guide"},
    {q:"Si X suit B(3 ; 1/3), alors p(X = 1) = …",c:["4/9","1/3","2/9","8/27"],a:0,exp:"3 × (1/3) × (2/3)²"},
    {q:"Si X suit B(10 ; 0,3), alors V(X) = …",c:["7","3","2,1","0,21"],a:2,exp:"10 × 0,3 × 0,7"},
    {q:"Si X suit B(4 ; 1/2), alors p(X = 2) = …",c:["6/16 + 1","3/8","1/4","1/2"],a:1,exp:"6 × (1/2)⁴ = 6/16"},
  ],
  "TleC — Suites numériques": [
    {q:"Un raisonnement par récurrence comporte…",c:["deux initialisations","une initialisation puis une hérédité (P(n) ⟹ P(n + 1))","une hérédité seulement","une initialisation seulement"],a:1,exp:"Structure du raisonnement"},
    {q:"Toute suite croissante et majorée est…",c:["négative","constante","convergente","divergente"],a:2,exp:"Propriété admise"},
    {q:"Toute suite décroissante et minorée est…",c:["divergente","croissante","convergente","nulle"],a:2,exp:"Propriété admise"},
    {q:"Toute suite croissante et non majorée est…",c:["bornée","constante","divergente","convergente"],a:2,exp:"Propriété admise"},
    {q:"Théorème des gendarmes : Vₙ ≤ Uₙ ≤ Wₙ avec lim Vₙ = lim Wₙ = l ⟹",c:["(Uₙ) est croissante","lim Uₙ = l","(Uₙ) diverge","lim Uₙ = 0"],a:1,exp:"Propriété admise"},
    {q:"Si Uₙ ≥ Vₙ à partir d'un certain rang et lim Vₙ = +∞, alors…",c:["lim Uₙ = +∞","lim Uₙ = 0","(Uₙ) est bornée","lim Uₙ = −∞"],a:0,exp:"Propriété admise"},
    {q:"Si Uₙ ≤ Vₙ à partir d'un rang, lim Uₙ = l et lim Vₙ = l', alors…",c:["l ≥ l'","l < l'","l ≤ l'","l = l'"],a:2,exp:"Passage à la limite dans une inégalité large"},
    {q:"Si |Uₙ − l| ≤ Vₙ et lim Vₙ = 0, alors…",c:["lim Uₙ = +∞","lim Uₙ = 0","(Uₙ) diverge","lim Uₙ = l"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Pour a > 1, la limite de aⁿ est… ; pour 0 < a < 1, elle est…",c:["+∞ et 0","+∞ et +∞","1 et 1","0 et +∞"],a:0,exp:"Propriété admise"},
    {q:"Si Uₙ₊₁ = g(Uₙ) converge vers l (g continue), alors…",c:["g(l) = 0","l = 0","g'(l) = 1","g(l) = l"],a:3,exp:"Propriété admise"},
    {q:"Si (Uₙ) converge vers a et si f a pour limite b en a (f continue), alors la limite de f(Uₙ) est…",c:["a","0","f(a) + b","b"],a:3,exp:"Propriété admise"},
    {q:"La limite de n²/2ⁿ est…",c:["+∞","1","0","2"],a:2,exp:"Croissances comparées"},
    {q:"La limite de Uₙ = (2n + 1)/(n + 3) est…",c:["2","1","+∞","3"],a:0,exp:"2 + 1/n sur 1 + 3/n"},
    {q:"U₀ = 1 et Uₙ₊₁ = Uₙ/2 + 1. Si (Uₙ) converge, sa limite l vérifie…",c:["l = 1/2","l = 1","l = 0","l = l/2 + 1, donc l = 2"],a:3,exp:"Passage à la limite dans la relation de récurrence"},
    {q:"La suite Uₙ = (−1)ⁿ…",c:["converge vers −1","converge vers 0","diverge (elle n'a pas de limite)","converge vers 1"],a:2,exp:"Elle alterne entre 1 et −1"},
    {q:"La suite Uₙ = n² − 3n…",c:["converge vers −3","diverge vers +∞","converge vers 0","est décroissante"],a:1,exp:"n²(1 − 3/n) tend vers +∞"},
    {q:"Toute suite convergente est…",c:["monotone","positive","croissante","bornée"],a:3,exp:"Propriété vue en 1ère"},
    {q:"La limite de sin n / n est…",c:["n'existe pas","0","1","+∞"],a:1,exp:"|Uₙ| ≤ 1/n : théorème des gendarmes"},
    {q:"Une suite géométrique de raison q avec |q| < 1 converge vers…",c:["q","0","+∞","1"],a:1,exp:"qⁿ tend vers 0"},
  ],
  "TleC — Isométries du plan": [
    {q:"Une symétrie glissée d'axe (Δ) et de vecteur →u (directeur de (Δ)) est la composée…",c:["de la symétrie orthogonale d'axe (Δ) et de la translation de vecteur →u","de deux symétries orthogonales","d'une rotation et d'une translation","de deux translations"],a:0,exp:"Définition du guide"},
    {q:"Une symétrie glissée admet…",c:["tous les points invariants","une droite de points invariants","aucun point invariant","un seul point invariant"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si →u est normal à (Δ), alors t_u ∘ s_Δ est…",c:["une symétrie glissée","une translation","une rotation","une symétrie orthogonale"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si →u n'est pas normal à (Δ), alors t_u ∘ s_Δ est…",c:["une rotation","une symétrie orthogonale","l'identité","une symétrie glissée"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une isométrie du plan qui laisse invariants trois points non alignés est…",c:["une rotation","une translation","une symétrie orthogonale","l'identité"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une isométrie non identique qui laisse invariants deux points distincts A et B est…",c:["une rotation de centre A","une symétrie glissée","la symétrie orthogonale d'axe (AB)","une translation"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Une isométrie qui laisse invariant un seul point A est…",c:["une symétrie glissée","une rotation de centre A","une translation","une symétrie orthogonale"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Toute isométrie du plan est…",c:["une translation, une rotation, une symétrie orthogonale ou une symétrie glissée","une rotation seulement","une translation ou une homothétie","une symétrie centrale seulement"],a:0,exp:"Classification des isométries"},
    {q:"Un déplacement est une isométrie qui…",c:["change les longueurs","n'a aucun point invariant","conserve les angles orientés","transforme tout angle orienté en son opposé"],a:2,exp:"Définition du guide"},
    {q:"Un antidéplacement est une isométrie qui…",c:["fixe tous les points","conserve l'aire seulement","conserve les angles orientés","transforme tout angle orienté en son opposé"],a:3,exp:"Définition du guide"},
    {q:"Les déplacements sont…",c:["les translations et les rotations","les symétries orthogonales et glissées","les affinités","les homothéties"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Les antidéplacements sont…",c:["les symétries orthogonales et les symétries glissées","les homothéties","les rotations","les translations et les rotations"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Soient A ≠ B et A' ≠ B' avec AB = A'B'. Il existe…",c:["une unique homothétie","une infinité de déplacements","aucun antidéplacement","un unique déplacement et un unique antidéplacement transformant A en A' et B en B'"],a:3,exp:"Propriétés démontrées en classe"},
    {q:"Toute isométrie f s'écrit f = t ∘ g avec g(A) = A et t…",c:["une projection","une affinité","une translation","une homothétie"],a:2,exp:"Propriété démontrée en classe"},
  ],
  "TleC — Applications affines & affinités": [
    {q:"Une application affine du plan est une application qui conserve…",c:["seulement les angles","seulement les longueurs","les aires","le barycentre de deux points"],a:3,exp:"Définition du guide"},
    {q:"Une application affine bijective s'appelle…",c:["une isométrie","une projection","une similitude","une transformation affine"],a:3,exp:"Définition du guide"},
    {q:"La composée de deux applications affines est…",c:["une projection","une isométrie","une application affine","une homothétie"],a:2,exp:"Propriété démontrée en classe"},
    {q:"L'application vectorielle F associée à une application affine f est définie par…",c:["F(→AB) = →BA","F(→AB) = →AB","F(→AB) = f(→AB) + A","F(→AB) = →f(A)f(B)"],a:3,exp:"Définition du guide"},
    {q:"L'application vectorielle associée est…",c:["constante","une translation","linéaire : F(u + v) = F(u) + F(v) et F(αu) = αF(u)","bijective toujours"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Toute application affine conserve…",c:["les angles","le barycentre de n points pondérés","les aires","les longueurs"],a:1,exp:"Propriété du guide"},
    {q:"Une application affine du plan est déterminée par…",c:["un seul point et son image","trois points non alignés et leurs images","deux points et leurs images","le centre et l'angle"],a:1,exp:"Propriété démontrée en classe"},
    {q:"L'ensemble des points invariants d'une application affine est…",c:["vide, un point, une droite ou le plan","un cercle","toujours un point","une parabole"],a:0,exp:"Propriété du guide"},
    {q:"Si A' = B' pour f affine, l'image de la droite (AB) est…",c:["le singleton {A'}","un segment","la droite (A'B')","un cercle"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Si A' ≠ B', l'image de (AB) par f est…",c:["la droite (A'B')","le point A'","un segment","un cercle"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Une application affine transforme deux droites parallèles en…",c:["deux cercles","deux droites parallèles (si l'image est une droite)","deux droites sécantes","deux droites perpendiculaires"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Si f est bijective, l'image du plan f(P) est…",c:["le plan entier","une droite","un point","une conique"],a:0,exp:"Propriété du guide"},
    {q:"Si f n'est pas bijective, f(P) est…",c:["le plan entier","un point ou une droite","un cercle","une parabole"],a:1,exp:"Propriété du guide"},
    {q:"L'expression analytique d'une application affine est de la forme…",c:["x' = ax² + by ; y' = cx + dy²","x' = ax + by + c ; y' = a'x + b'y + c'","x' = ax + by ; y' = a'x + b'y seulement","x' = a/x ; y' = b/y"],a:1,exp:"Propriété du guide"},
    {q:"L'affinité d'axe (D), de direction δ et de rapport k associe à M le point M' tel que…",c:["→HM' = →HM + k","→MM' = k →HM","→HM' = k →HM, où H est le projeté de M sur (D) suivant δ","M' = H"],a:2,exp:"Définition du guide"},
    {q:"Si g(x) = a f(x), Cg est l'image de Cf par l'affinité d'axe…",c:["(Oy), de direction (Ox) et de rapport a","(Oy) et de rapport 1/a","(Ox), de direction (Oy) et de rapport a","(Ox) et de rapport 1/a"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Si g(x) = f(ax) (a ≠ 0, a ≠ 1), Cg est l'image de Cf par l'affinité d'axe…",c:["(Oy), de direction (Ox) et de rapport 1/a","(Ox), de direction (Oy) et de rapport a","(Ox) et de rapport 1/a","(Oy) et de rapport a"],a:0,exp:"Propriété démontrée en classe"},
  ],
  "TleC — Coniques : définition & parabole": [
    {q:"Une conique de foyer F, de directrice (D) et d'excentricité e est l'ensemble des points M tels que…",c:["MF = e MH²","MF + MH = e","MF × MH = e","MF/MH = e, où H est le projeté orthogonal de M sur (D)"],a:3,exp:"Définition du guide"},
    {q:"Si e = 1, la conique est…",c:["une hyperbole","un cercle","une ellipse","une parabole"],a:3,exp:"Définition"},
    {q:"Si 0 < e < 1, la conique est…",c:["une ellipse","une parabole","une droite","une hyperbole"],a:0,exp:"Définition"},
    {q:"Si e > 1, la conique est…",c:["une parabole","une ellipse","une hyperbole","un cercle"],a:2,exp:"Définition"},
    {q:"La droite passant par F et perpendiculaire à (D) est…",c:["une tangente","un axe de symétrie de la conique (axe focal)","une asymptote","une directrice"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Une parabole coupe son axe focal en…",c:["une infinité de points","deux points","aucun point","un seul point, son sommet"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Une conique d'excentricité e ≠ 1 coupe son axe focal en…",c:["aucun point","deux points (ses sommets)","un seul point","trois points"],a:1,exp:"Propriété démontrée en classe"},
    {q:"Dans un repère orthonormé (S, →i, →j) avec →i = →SF, la parabole a pour équation…",c:["y² = px²","x² = 2py","y² = 2px, où p est la distance de F à (D)","y = px²"],a:2,exp:"Équation réduite"},
    {q:"La parabole d'équation y² = 8x a pour foyer…",c:["(2 ; 0)","(8 ; 0)","(4 ; 0)","(1 ; 0)"],a:0,exp:"y² = 2px avec p = 4 ; foyer (p/2 ; 0)"},
    {q:"La parabole d'équation y² = 8x a pour directrice…",c:["y = −2","x = −4","x = −2","x = 2"],a:2,exp:"Directrice : x = −p/2"},
    {q:"La tangente à y² = 2ax en M₀(x₀ ; y₀) a pour équation…",c:["y y₀ = a(x + x₀)","y y₀ = 2a(x − x₀)","y − y₀ = a","y = a x₀"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La tangente à y² = 8x au point M₀(2 ; 4) a pour équation…",c:["y = x + 2","y = x − 2","y = 4","y = 2x"],a:0,exp:"4y = 4(x + 2)"},
    {q:"Le paramètre p de la parabole est…",c:["le rayon du cercle principal","la distance de S à F","l'excentricité","la distance du foyer à la directrice"],a:3,exp:"Définition du guide"},
  ],
  "TleC — Ellipse & hyperbole": [
    {q:"L'ellipse de foyers F et F' et de grand axe 2a est l'ensemble des points M tels que…",c:["MF − MF' = 2a","MF × MF' = 2a","MF = MF'","MF + MF' = 2a"],a:3,exp:"Définition bifocale (FF' < 2a)"},
    {q:"La définition bifocale de l'hyperbole est |MF − MF'| = 2a avec…",c:["FF' > 2a","FF' < 2a","FF' = a","FF' = 2a"],a:0,exp:"Propriété du guide"},
    {q:"L'équation réduite d'une ellipse est…",c:["x²/a² − y²/b² = 1","xy = k","y² = 2px","x²/a² + y²/b² = 1 (a > b > 0)"],a:3,exp:"Propriété démontrée en classe"},
    {q:"L'équation réduite d'une hyperbole est…",c:["x² + y² = 1","x²/a² + y²/b² = 1","y² = 2px","x²/a² − y²/b² = 1"],a:3,exp:"Propriété du guide"},
    {q:"Pour l'ellipse x²/25 + y²/9 = 1, la demi-distance focale c vaut…",c:["4","5","√34","16"],a:0,exp:"c² = a² − b² = 25 − 9"},
    {q:"Pour l'ellipse x²/25 + y²/9 = 1, l'excentricité est…",c:["3/5","5/4","4/3","4/5"],a:3,exp:"e = c/a"},
    {q:"Les foyers de x²/25 + y²/9 = 1 sont…",c:["(4 ; 0) et (−4 ; 0)","(5 ; 0) et (−5 ; 0)","(0 ; 4) et (0 ; −4)","(3 ; 0) et (−3 ; 0)"],a:0,exp:"Sur l'axe focal (Ox)"},
    {q:"La tangente à l'ellipse x²/a² + y²/b² = 1 en M₀(x₀ ; y₀) a pour équation…",c:["x x₀/a² − y y₀/b² = 1","x₀/a² + y₀/b² = 1","x x₀ + y y₀ = 1","x x₀/a² + y y₀/b² = 1"],a:3,exp:"Propriété admise"},
    {q:"Une représentation paramétrique de x²/a² + y²/b² = 1 est…",c:["x = cos t ; y = sin t","x = a t ; y = b t²","x = a sin t ; y = b sin t","x = a cos t ; y = b sin t"],a:3,exp:"Propriété démontrée en classe"},
    {q:"L'ellipse est l'image du cercle de diamètre [AA'] par l'affinité orthogonale d'axe (AA') et de rapport…",c:["1","a × b","a/b","b/a"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Pour l'hyperbole x²/9 − y²/16 = 1, la demi-distance focale c vaut…",c:["√7","5","25","7"],a:1,exp:"c² = a² + b² = 9 + 16"},
    {q:"Les asymptotes de l'hyperbole x²/9 − y²/16 = 1 sont…",c:["y = ± x","y = ± (16/9) x","y = ± (4/3) x","y = ± (3/4) x"],a:2,exp:"y = ± (b/a) x"},
    {q:"L'excentricité de x²/9 − y²/16 = 1 est…",c:["4/3","5/3","9/16","3/5"],a:1,exp:"e = c/a"},
    {q:"La tangente à l'hyperbole x²/a² − y²/b² = 1 en M₀(x₀ ; y₀) a pour équation…",c:["x x₀/a² − y y₀/b² = 1","x x₀ − y y₀ = 1","x₀/a² − y₀/b² = 1","x x₀/a² + y y₀/b² = 1"],a:0,exp:"Propriété admise"},
    {q:"Une conique à centre (e ≠ 1) admet pour centre de symétrie…",c:["le sommet A","le foyer F","aucun point","le milieu de [AA'] entre ses deux sommets de l'axe focal"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Le régionnement du plan par une ellipse permet de distinguer…",c:["seulement l'intérieur","quatre régions égales","l'intérieur, l'extérieur et l'ellipse (MF + MF' < 2a, > 2a, = 2a)","deux demi-plans"],a:2,exp:"Régionnement du plan"},
  ],
  "TleC — Similitudes planes directes & indirectes": [
    {q:"Toute similitude plane directe a une écriture complexe…",c:["z' = a/z","z' = a conj(z) + b","z' = az²","z' = az + b avec a ∈ ℂ*"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Si a = 1, la similitude z' = az + b est…",c:["une homothétie","l'identité","la translation de vecteur d'affixe b","une rotation"],a:2,exp:"Propriété du guide"},
    {q:"Si a ≠ 1, la similitude z' = az + b admet…",c:["une droite de points invariants","tous les points invariants","aucun point invariant","un seul point invariant Ω"],a:3,exp:"Propriété du guide"},
    {q:"Le point invariant d'affixe ω de z' = az + b (a ≠ 1) vérifie…",c:["ω = b/(1 − a)","ω = −b","ω = a + b","ω = b/a"],a:0,exp:"Résolution de z = az + b"},
    {q:"Une similitude directe de centre Ω s'écrit comme composée…",c:["d'une projection et d'une rotation","de deux réflexions","d'une rotation et d'une homothétie de même centre Ω","de deux translations"],a:2,exp:"Forme réduite s = r ∘ h = h ∘ r"},
    {q:"Les éléments caractéristiques d'une similitude directe (a ≠ 1) sont…",c:["le foyer et l'excentricité","le centre Ω, le rapport |a| et l'angle arg(a)","l'axe et la direction","le rapport a et le vecteur b"],a:1,exp:"Propriété du guide"},
    {q:"Si |a| = 1 et a ≠ 1, la similitude est…",c:["une rotation","une homothétie","une translation","une symétrie axiale"],a:0,exp:"Propriété du guide"},
    {q:"La composée de deux similitudes directes de rapports k, k' et d'angles θ, θ' est…",c:["une similitude directe de rapport kk' et d'angle θ + θ'","de rapport k + k' et d'angle θθ'","une isométrie","de rapport kk' et d'angle θθ'"],a:0,exp:"Propriété démontrée en classe"},
    {q:"La réciproque d'une similitude directe de rapport k et d'angle θ est de rapport… et d'angle…",c:["1/k et θ","−k et −θ","1/k et −θ","k et θ"],a:2,exp:"Propriété démontrée en classe"},
    {q:"Une similitude directe de rapport k multiplie les aires par…",c:["2k","k²","k","|k|³"],a:1,exp:"Propriété du guide"},
    {q:"Une similitude directe conserve…",c:["l'alignement, le parallélisme, l'orthogonalité, les angles orientés et le barycentre","les longueurs","aucune de ces propriétés","les aires"],a:0,exp:"Propriétés énoncées dans le guide"},
    {q:"Pour la similitude directe de centre A, rapport k et angle a, on a AM' = … et mes(→AM, →AM') = …",c:["k AM et a (à 2π près)","k AM et 2a","AM/k et a","AM et a"],a:0,exp:"Propriété démontrée en classe"},
    {q:"Il existe une unique similitude directe transformant A en A' et B en B' lorsque…",c:["AB = A'B'","A = B","A' = B'","A ≠ B et A' ≠ B'"],a:3,exp:"Propriété démontrée en classe"},
    {q:"Dans un repère orthonormé direct, toute similitude plane indirecte a une écriture complexe…",c:["z' = a/z + b","z' = a conj(z) + b","z' = az + b","z' = a z² + b"],a:1,exp:"Propriété énoncée dans le guide"},
    {q:"Une similitude indirecte z' = a conj(z) + b avec |a| = 1 est…",c:["un déplacement","un antidéplacement","une translation","une homothétie de rapport |a|"],a:1,exp:"Propriété du guide"},
    {q:"Un tel antidéplacement est une réflexion si et seulement si…",c:["a = 1","a conj(b) + b = 0","a b + conj(b) = 0","b = 0 seulement"],a:1,exp:"Propriété du guide"},
    {q:"La transformation z' = conj(z) + 2i est…",c:["une translation","la réflexion d'axe la droite d'équation y = 1","la réflexion d'axe (Ox)","une rotation"],a:1,exp:"a = 1, b = 2i : a conj(b) + b = −2i + 2i = 0 ; points invariants y = 1"},
    {q:"Si |a| ≠ 1, la similitude indirecte z' = a conj(z) + b se décompose en…",c:["une réflexion d'axe D et une homothétie de centre M₀ et de rapport |a|","une rotation et une translation","une projection et une affinité","deux symétries orthogonales"],a:0,exp:"Propriété du guide"},
  ],
  "TleC — Prop. & Déf.": [
    {q:"Définition : la fonction vectorielle de Leibniz associée aux (Aᵢ, αᵢ) est…",c:["M ↦ →OM","M ↦ Σ MAᵢ","M ↦ Σ αᵢ →MAᵢ","M ↦ Σ αᵢ MAᵢ²"],a:2,exp:"Leibniz"},
    {q:"Propriété : si Σ αᵢ ≠ 0, la fonction scalaire de Leibniz vérifie φ(M) = …",c:["Σ αᵢ MG","(Σ αᵢ) MG + φ(G)","(Σ αᵢ) MG² + φ(G)","φ(G) − MG²"],a:2,exp:"Leibniz"},
    {q:"Propriété : l'ensemble des points équidistants de A et B est…",c:["le plan médiateur de [AB]","la droite (AB)","la sphère de diamètre [AB]","le milieu de [AB]"],a:0,exp:"Plan médiateur"},
    {q:"Propriété : une homothétie de rapport k multiplie les volumes par…",c:["3k","k²","|k|³","k"],a:2,exp:"Homothétie de l'espace"},
    {q:"Propriété : la composée de deux réflexions de plans perpendiculaires suivant (Δ) est…",c:["l'identité","le demi-tour d'axe (Δ)","une homothétie","une translation"],a:1,exp:"Réflexions"},
    {q:"Propriété : la composée d'un demi-tour d'axe (Δ) et d'une réflexion de plan orthogonal à (Δ) en A est…",c:["la symétrie centrale de centre A","l'identité","un demi-tour","une translation"],a:0,exp:"Demi-tour"},
    {q:"Propriété : →u ∧ →v = →0 si et seulement si…",c:["→u et →v sont orthogonaux","→u = →v","‖→u‖ = ‖→v‖","→u et →v sont colinéaires"],a:3,exp:"Produit vectoriel"},
    {q:"Théorème : division euclidienne dans ℤ : (a, b) avec b ≠ 0 ⟹ il existe un unique couple (q, r) tel que…",c:["r > |b|","a = bq + r avec 0 ≤ r < |b|","a = b + qr","a = bq seulement"],a:1,exp:"Division euclidienne"},
    {q:"Définition : x ≡ y [n] si et seulement si…",c:["x = y","n divise x − y","x et y sont premiers entre eux","n divise x + y"],a:1,exp:"Congruence"},
    {q:"Théorème de Bézout : a et b sont premiers entre eux si et seulement si…",c:["a divise b","PGCD(a, b) = 0","il existe u, v tels que au + bv = 1","a + b = 1"],a:2,exp:"Bézout"},
    {q:"Théorème de Gauss : si a divise bc et PGCD(a, b) = 1, alors…",c:["b divise c","a divise c","a = b","a divise b"],a:1,exp:"Gauss"},
    {q:"Propriété : δ μ = …",c:["a − b","a + b","a × b","a/b"],a:2,exp:"PGCD × PPCM"},
    {q:"Propriété : ax + by = c a des solutions dans ℤ² si et seulement si…",c:["PGCD(a, b) divise c","a divise c","a et b sont premiers","c = 0"],a:0,exp:"Équation diophantienne"},
    {q:"Théorème : tout entier n ≥ 2 admet une unique décomposition en…",c:["puissance de 2","produit de facteurs premiers","produit de deux premiers","somme de carrés"],a:1,exp:"Décomposition en facteurs premiers"},
    {q:"Propriété : ℤ/pℤ est un corps si et seulement si…",c:["p est pair","p = 2","p est premier","p est impair"],a:2,exp:"ℤ/pℤ"},
    {q:"Propriété : une isométrie du plan qui laisse invariant un seul point A est…",c:["l'identité","une symétrie orthogonale","une translation","une rotation de centre A"],a:3,exp:"Isométries"},
    {q:"Définition : un déplacement est une isométrie qui…",c:["change les longueurs","transforme tout angle orienté en son opposé","n'a pas de point invariant","conserve les angles orientés"],a:3,exp:"Déplacements"},
    {q:"Définition : une application affine du plan est une application qui conserve…",c:["le barycentre de deux points","les aires","les angles","les longueurs"],a:0,exp:"Application affine"},
    {q:"Définition : une conique de foyer F, directrice (D) et excentricité e est l'ensemble des points M tels que…",c:["MF + MH = e","MF = e","MF × MH = e","MF/MH = e"],a:3,exp:"Conique"},
    {q:"Propriété : e = 1 ⟹ … ; 0 < e < 1 ⟹ … ; e > 1 ⟹ …",c:["hyperbole ; parabole ; ellipse","cercle ; ellipse ; parabole","ellipse ; parabole ; hyperbole","parabole ; ellipse ; hyperbole"],a:3,exp:"Nature d'une conique"},
    {q:"Propriété : la parabole de foyer F et de directrice (D) a pour équation réduite…",c:["x²/a² − y²/b² = 1","x²/a² + y²/b² = 1","y² = 2px","y = px"],a:2,exp:"Parabole"},
    {q:"Propriété : l'ellipse de foyers F et F' est l'ensemble des points tels que…",c:["MF + MF' = 2a","MF × MF' = 2a","MF = MF'","|MF − MF'| = 2a"],a:0,exp:"Définition bifocale"},
    {q:"Propriété : l'hyperbole de foyers F et F' est l'ensemble des points tels que…",c:["MF × MF' = 2a","MF + MF' = 2a","MF = MF'","|MF − MF'| = 2a"],a:3,exp:"Définition bifocale"},
    {q:"Propriété : l'ellipse x²/a² + y²/b² = 1 admet la représentation paramétrique…",c:["x = a t ; y = b t","x = a cos t ; y = b sin t","x = cos t ; y = sin t","x = a sin t ; y = a cos t"],a:1,exp:"Ellipse"},
    {q:"Propriété : toute similitude plane directe a pour écriture complexe…",c:["z' = az + b (a ≠ 0)","z' = az²","z' = a/z","z' = a conj(z) + b"],a:0,exp:"Similitude directe"},
    {q:"Propriété : la composée de deux similitudes directes (k, θ) et (k', θ') est…",c:["une translation","une similitude directe (k + k', θθ')","une isométrie","une similitude directe (kk', θ + θ')"],a:3,exp:"Composée"},
    {q:"Propriété : la similitude z' = az + b (a ≠ 1) a pour point invariant…",c:["le point d'affixe b/(1 − a)","l'origine","aucun point","le point d'affixe b"],a:0,exp:"Point invariant"},
    {q:"Propriété : une similitude indirecte z' = a conj(z) + b (|a| = 1) est une réflexion si et seulement si…",c:["b = 0","a b + conj(b) = 0","a conj(b) + b = 0","a = 1"],a:2,exp:"Similitude indirecte"},
  ],
});
